spesmilo/electrum

electrum/commands.py

`deserialize_proxy()` from `network.py` supports `none` value for `--proxy`.
It is worth documenting since it is a useful feature.

Document how to disable proxy

---

README.rst

`README.rst` lists the `apt-get` requirements for `pull_locale` (which is good) but neglects to do the same for `make_libsecp256k1.sh`.  This PR adds the relevant info for the latter.

Readme: Clarify dependencies of make_libsecp256k1.sh

---

electrum/gui/qt/utxo_list.py

Makes it easier to subclass UTXOList without code duplication.

UTXOList: Split stretch_column out of __init__

---

electrum/commands.py

The previous description of `getservers` made it sound like it returned the list of currently connected servers; this clarifies that it's only a list of candidate servers to connect to (no guarantee that they are all currently connected).

Commands: clarify description of getservers

---

contrib/requirements/requirements-hw.txt
electrum/plugins/trezor/__init__.py
electrum/plugins/trezor/clientbase.py
electrum/plugins/trezor/cmdline.py
electrum/plugins/trezor/qt.py
electrum/plugins/trezor/trezor.py

In upcoming Trezor T firmware, we moved the decision where the passphrase is entered from the device to the host.
IOW, in firmware < 2.3.0, when using a passphrase, the Trezor screen would ask: "enter passphrase on host / device?"
Depending on the choice, either Trezor would ask for a passphrase, or indicate to Electrum that the passphrase dialog should be displayed.
In firmware >= 2.3.0, the passphrase dialog should be shown by default, with an additional option to "Enter Passphrase on Device", which would indicate to Trezor that it should prompt for passphrase.
See [this doc](https://github.com/trezor/trezor-firmware/blob/master/docs/common/communication/passphrase-redesign-migration.md) for details.
Practical effect is that users with new firmware and old trezorlib/Electrum will only …

trezor: bump lib version, implement new passphrase-on-device UI

---

electrum/network.py

Resolves https://github.com/spesmilo/electrum/issues/6085
I just copied the same print then exit fail style from here:
https://github.com/spesmilo/electrum/blob/da8b24d61af00109d480fe4ee5b73d130a7c1f25/electrum/gui/stdio.py#L26-L27
However this doesn't seem to actually exit the process for me, in the terminal I see the "Failed to parse server-string." text but the python process just hangs. Am I doing something wrong?

Hard fail on bad server-string

---

.gitignore

This allows you to simply run `./run_electrum --portable` during development to get a development only wallet without worrying about accidentally committing it.

Add electrum_data to .gitignore

---

contrib/build-linux/appimage/Dockerfile
contrib/build-wine/Dockerfile

It seems there was update.
https://launchpad.net/ubuntu/+source/git/1:2.7.4-0ubuntu1.9
https://launchpad.net/ubuntu/+source/git/1:2.17.1-1ubuntu0.7
I think this is probably the effect.
https://usn.ubuntu.com/4334-1/

build: update git in dockerfiles

---

electrum/gui/qt/main_window.py

When you export private keys to a file (electrum-private-keys.csv or .json), it's created with default file permissions (644 on my system), which is not very secure for private keys I think. Let's use 600 instead.

set more restrictive file permissions for exported private keys

---

electrum/commands.py
electrum/gui/qt/main_window.py
electrum/interface.py

Resolves #6084 
Needs a bit more work but it's fully functional and testable now.
If you want to test against my server you can run:
```
$ ./run_electrum --oneserver --server bitcoin.lukechilds.co:50002:s --serverfingerprint ED1FE28B21A5943A8810747B2A6DDFC0E3089115D6205125E5C4D3EE8E126F80
```
This should connect as normal.
If you run:
```
$ ./run_electrum --oneserver --server bitcoin.lukechilds.co:50002:s --serverfingerprint DEADBEEF
```
Then an `ErrorSSLCertFingerprintMismatch` error should be thrown.
Two questions:
1. `ErrorSSLCertFingerprintMismatch` is being caught somewhere so it doesn't kill the app, the connection keeps being retried. It's not entirely clear to me where this is getting handled. Instead I want the error handler to exit the application if it encounters an …

Add --serverfingerprint option

---

run_electrum

The RPC client was returning an exit code of 0 (success) if the server returned an error; this was confusing to tools that expect an error to be reflected in the exit code.  (If you prefer a different nonzero exit code, let me know; it just definitely shouldn't be 0.)

RPC client: exit code 1 if RPC server returned error

---

electrum/gui/qt/transaction_dialog.py
electrum/wallet.py

related: #6127
This PR makes it explicit that funding txns cannot be fee-bumped.
It also closes the add inputs/outputs flow described in https://github.com/spesmilo/electrum/issues/6127#issuecomment-622070937. i.e. we disallow joining a partial tx that we know is a funding tx of ours
It does not seem possible to completely close down all footguns re changing the txid of a funding tx via adding inputs/outputs, as e.g. the user could
- create tx1 in wallet1, which is a funding tx for a channel open
- create tx2 in wallet2
- join them together in wallet2, through e.g. the "Load transaction" menu
- and then broadcast; resulting in most likely losing the coins intended for the channel open

wallet: disallow fee-bumping/coinjoining ln funding tx

---

contrib/build-linux/appimage/Dockerfile

E: Version '1.0.2g-1ubuntu4.15' for 'libssl-dev' was not found
E: Version '1.0.2g-1ubuntu4.15' for 'libssl1.0.0' was not found
E: Version '1.0.2g-1ubuntu4.15' for 'openssl' was not found
Now version is 1.0.2g-1ubuntu4.16
https://packages.ubuntu.com/xenial/openssl

appimage: update openssl

---

electrum/plugins/trezor/trezor.py
electrum/transaction.py
electrum/wallet.py

A security issue* in the design of BIP-143 allows an attacker to lie about segwit input amounts and get the user to pay an unexpectedly high transaction fee. The problem affects all HWW vendors.
We are fixing this by making Trezor require the full UTXO for all types of inputs, so we can validate that the input amount is correct.
To facilitate that, we need Electrum to provide full UTXOs for all input types. (This goes against the recommendation in BIP-174, saying that `NON_WITNESS_UTXO` should not be provided for SegWit inputs. Nevertheless, the resulting PSBT is still valid AFAICT.)
This PR enables that for Trezor, modifications for other HWW vendors will most likely also be required. Also I'm not sure whether this is a complete PR, perhaps my modifications to the data model are breaking …

enable streaming full UTXOs for all types of inputs

---

electrum/crypto.py
electrum/gui/kivy/main_window.py
electrum/gui/kivy/uix/dialogs/lightning_channels.py
electrum/gui/qt/channels_list.py
electrum/gui/qt/main_window.py
electrum/lnutil.py
electrum/lnworker.py

Channel backup version

---

electrum/lnwatcher.py
electrum/lnworker.py
electrum/synchronizer.py
electrum/util.py

Before this, we were subscribing to our addresses in their bip32 order,
leaking this information to servers. While this leak seems mostly harmless,
it is trivial to fix.

network: randomise the order of address subscriptions

---

electrum/gui/qt/network_dialog.py

Resolves #6242 
Nested if to check count of connected nodes. Fixes language if connected to only 1 node.

Fixes network status "node" vs "nodes" count

---

contrib/requirements/requirements-hw.txt
electrum/plugins/bitbox02/bitbox02.py

It would be great if this made it into the next beta release (or real release :crossed_fingers:).
Edit: since the bb02 plugin is now released with Electrum, we will be careful to preserve backwards compatibility as best as we can going forward. Thanks and congrats on Electrum 4! :rocket:

plugins/bitbox02: fix compatibility with bitbox02-4.0.0

---

electrum/interface.py
electrum/network.py
electrum/synchronizer.py
electrum/util.py

some basic sanity checks
Previously if the server sent back a malformed response, it could partially corrupt a wallet file.
(as sometimes the response would get persisted, and issues would only arise later when the values were used)

interface: check server response for some methods

---

contrib/android/buildozer.spec

For https://github.com/spesmilo/electrum/issues/6321

remove QDarkStyle from packages before building for android

---

electrum/plugins/bitbox02/bitbox02.py

Without it, if you have say a 1-of-2 multisig with two BitBox02s, you
would run into trouble if the first keystore would try to match to the
wrong inserted BitBox02 (wrong order, or the first one is not
inserted, etc. ).
With the soft device id, the device manager can figure it on its own
which keystore belongs to which connected bb02.

bitbox02: implement get_soft_device_id so multisig runs more smoothly

---

electrum/gui/qt/console.py

Ctrl+L should clear the whole console except the current line like
a standard Python console.

Keep current input when clearing Python console

---

electrum/gui/kivy/uix/dialogs/installwizard.py

Fixes a UI issue in kivy Install Wizzard.
The Choices UI was displayed in a small vertical line for a split second, before being resized to correct size.
This fixes that by ensuring resizing is done before next frame is displayed https://kivy.org/doc/stable/api-kivy.clock.html#schedule-before-frame .

Re-size the wizard before next frame is displayed.

---

electrum/currencies.json
electrum/exchange_rate.py

Added [Bitragem](https://bitragem.com/) and [Biscoint](https://biscoint.io/buy/btc/brl?amount=1000&isQuote=true) for BRL.
I chose to remove the NEGOCIECOINS exchange as it stole many users, evidence below.
https://cointelegraph.com.br/news/folha-de-sao-paulo-states-that-negociecoins-has-millionaire-debt
https://canaltech.com.br/criptomoedas/clientes-processam-empresa-paranaense-de-bitcoins-por-sumico-de-dinheiro-146475/
https://etopsaber.com/o-caso-da-negociecoins/

Feature: more price sources for BRL and remove scam broker

---

electrum/currencies.json
electrum/exchange_rate.py

Added Brazilian Bitcoin Index from Cointrader Monitor (https://cointradermonitor.com/api/pbb/v1/ticker) as a "BRL" Fiat source.
The index is calculated from the last price and volume from 30 brazilian exchanges. It is a well-known price index used by bitcoin brazilian users.
More information at https://cointradermonitor.com/

Brazilian Bitcoin index source included.

---

electrum/gui/qt/console.py

- Change >> to >>> as in a normal Python console.
- Avoid printing an empty string which is why the console looked like:
```
>>
Network banner
>>
```
Instead of:
```
Network banner
>>>
```
- Remove **welcome_message** from console.py
It is not used anymore.
The console prints **network.banner** instead.

Remove empty startup message from console

---

electrum/plugins/coldcard/coldcard.py

For the multi-sig wallet On Coldcard, there is a function called "show address on ColdCard" 
which will show the address into on ColdCard device to verify. but there is a bug on this function which will raise Error like
this is because on `show_p2sh_address`  function,  items in `xfp_paths` should have the same order as `pubkeys` on the script. this fix is to make they have the same order

fix the coldcard multi-sig show address issue

---

electrum/base_wizard.py
electrum/bip39_recovery.py
electrum/bip39_wallet_formats.json
electrum/constants.py
electrum/gui/kivy/uix/dialogs/installwizard.py
electrum/gui/qt/bip39_recovery_dialog.py
electrum/gui/qt/installwizard.py
electrum/scripts/bip39_recovery.py

Resolves #6155 
Implements automated scanning of all known BIP32 chains that can be imported into Electrum.
I'm opening this PR for review, it's not ready to be merged yet. Account discovery is functional but still needs to be integrated in to the GUI.
Currently it's implemented as a script for easy testing, you can quickly test it out by running the `electrum/scripts/bip39_recovery.py` script with a `mnemonic` parameter and also an optional second `passphrase` parameter. It will return a list of any previously used accounts it can find. You can use this mnemonic that I've created a few test accounts in:
```
much bottom such hurt hunt welcome cushion erosion pulse admit name deer
```
e.g:
```
$ ./bip39_recovery.py "much bottom such hurt hunt welcome cushion erosion pulse admit name deer" …
```

Automated BIP39 Recovery

---

electrum/plugins/trezor/clientbase.py

fixes #6457
Trezor T does not allow `Ping` message without unlocking the device. There's a matching bug in `trezorctl` which makes this worse: `client.ping()` should cleanly handle the situation but it doesn't.
The easiest and most user-friendly solution in Electrum is to use `init_device()` call instead; it's guaranteed to not require user interaction, which is what we want in `has_usable_connection`.

trezor: use `init_device` instead of `ping` to check connection

---

electrum/gui/qt/console.py

**set_history()**, **get_history()** and **register_command()** were never used.

Remove unused methods from Console

---

electrum/commands.py

When using the `add_request` command I realized that the returned address will be reused in the next payment request after I restart my electrum daemon (if no other operation which saves the walletDB has been performed in the meantime).
It seems that the `add_request`, `add_lightning_request` and `rmrequest` commands change the wallet DB (_by adding or removing payment requests_), but do not flush the changes down to the disk.
If any other operation later on changes the wallet DB, then the changes of the 3 commands will also be flushed. If not, then the changes (payment requests) might get lost.
(`clear_requests` is not affected as `self.save_db()` is called in `wallet.py` in `clear_requests(self)`.)
- adds `wallet.save_db()` to RPC commands which change the Wallet DB but didn't save them

Save wallet DB after adding or removing payment requests

---

electrum/commands.py

This PR is a fix discussed in #6529
`for_broadcast` argument added is to determine whether to also call `addtransaction` or not.
@SomberNight

Added for_broadcast argument to payto/paytomany

---

electrum/gui/qt/console.py

- Replace "...." by "... " in multiline constructs.
- Execute constructs after one empty line and not two or three. It
was more or less random before.
Before:
```
>>> for i in range(0, 3):
....    print(i)
....
....
0
1
2
>>> 
```
After:
```
>>> for i in range(0, 3):
...     print(i)
...
0
1
2
>>>
```

Fix handling of constructs in console

---

electrum/gui/stdio.py
electrum/gui/text.py

Hi,
e1ce3aace7e3143da24115890d9bae78a9f5bca updated the qt and kivy guis, but not stdio or text one, so trying to use the text gui gives an error `missing 1 required positional argument: 'storage'`, coming from the line
```
self.wallet = Wallet(storage, config=config)
```
and `electrum --gui stdio` just closes without any output.
With this patch electrum starts as it should for both guis again.

gui: update stdio and text after db and storage separation

---

electrum/lnchannel.py
electrum/lnworker.py
electrum/tests/test_lnchannel.py
electrum/tests/test_lnpeer.py

Previously if we coop-closed multiple channels in the same session, they would reuse the wallet address.

LN cooperative close: avoid address-reuse

---

electrum/gui/qt/console.py

Syntax errors emerged when running multiline scripts in the console
when using the run() command.
Example `file.py`:
```
print(1)
print(2)
```
Before:
```
>>> run('file.py')
File "/***/electrum/gui/qt/console.py", line 84, in run_script
result = eval(script, self.namespace, self.namespace)
File "<string>", line 2
print(2)
^
SyntaxError: invalid syntax
During handling of the above exception, another exception occurred:
File "/***/electrum/gui/qt/console.py", line 250, in runCommand
exec(command, self.namespace, self.namespace)
File "<string>", line 1, in <module>
File "/***/electrum/gui/qt/console.py", line 84, in run_script
result = eval(script, self.namespace, self.namespace)
File "<string>", line 2
print(2)
^ …
```

Fix multiline script error

---

electrum/gui/qt/console.py

Console input was being replaced by an empty line every time the server used changed.
Before:
```
>>> for i in range(0, 3):
...     print(i)
Welcome to electrum.blockstream.info - no logs and Tor support - Please learn about running your own server!
... 
```
After:
```
>>> for i in range(0, 3):
...     print(i)
Welcome to electrum.blockstream.info - no logs and Tor support - Please learn about running your own server!
...     print(i)
... 
0
1
2
>>> 
```

Keep console input when switching server

---

electrum/daemon.py
electrum/gui/kivy/main_window.py
electrum/gui/qt/main_window.py
electrum/lnworker.py
electrum/wallet.py

This PR returns passing wallet to `request_status` (and `invoice_status` for symmetry) events.
It is useful to track which wallet changed request/invoice refers to in event handler (useful for payment processing, complex event forwarding, etc.)
One question: should I change `self.wallet` to `wallet` in some event handlers?

Pass wallet to invoice_status/request_status

---

electrum/gui/qt/console.py

Mimic the behavior of the standard Python console by storing indented lines in history.

Save indented lines in console history

---

electrum/channel_db.py
electrum/commands.py
electrum/util.py

The `dumpgraph` command is broken at the moment, which is fixed by this PR.
This PR adds channels to the output to have a complete view of the whole graph
(excluding one own's node) in terms of a dict, which is json encodeable.
Tested with the Qr-console and with the command line interface.
The `ShortChannelID` is currently encoded to a hex string, as it came from [bytes](https://github.com/spesmilo/electrum/blob/52bd0eb1a656bdd0eb32340350fb4bf82af5c690/electrum/util.py#L258). Should we
print out a more human readable form, we could use the x notation or the int version that lnd uses?
As a side note, I observe that channels seem have no capacity assigned (tested on LN testnet).

Fix dumpgraph command: give out json encoded nodes and channels

---

electrum/commands.py
electrum/daemon.py

Before commit 46ffab0b5547050881eab5622dac07bb41769793 all of these used to work:
```
./run_electrum -o signmessage tb1qeh090ruc3cs5hry90tev4fsvrnegulw8xssdzx "asdasd" -w ~/.electrum/testnet/wallets/test_segwit_2 --testnet
./run_electrum -o signmessage -w ~/.electrum/testnet/wallets/test_segwit_2 tb1qeh090ruc3cs5hry90tev4fsvrnegulw8xssdzx "asdasd" --testnet
./run_electrum -w ~/.electrum/testnet/wallets/test_segwit_2 -o signmessage tb1qeh090ruc3cs5hry90tev4fsvrnegulw8xssdzx "asdasd" --testnet
```
Since then, the last one no longer works.
Related: 9d2ede8796f4b9c460d50cd7dfc0a85a0de50b6d

CLI: allow specifying --wallet at any arg position, as before

---

electrum/servers.json

Server turned rogue after dyn DNS expired as was re-registered by scammers.

Remove rogue phishing server enode.duckdns.org

---

contrib/build-wine/deterministic.spec

The "setup" Windows binary we distribute allows users to "install" Electrum
on their system. The distributable is created by NSIS. During
installation a bunch of files will get unpacked in %programfiles(x86)%/Electrum,
including an "inner" exe that will be the entrypoint for the user to start
the application. A shortcut is also created for the inner exe.
With this change, there will now be two inner EXEs. One the same as before,
the other with a "-debug" suffix in its name. The debug exe is built as a
"console" application (as opposed to a "windowed" application), so when
launched via double-click a black console window would appear; and also
importantly stdin/stdout are handled properly for it (unlike for "windowed"
programs). (see #2592)
There will not be a shortcut or similar for the …

windows build: for the "setup" exe, put another "-debug" exe inside

---

electrum/gui/qt/console.py

Use Ctrl+C to raise a KeyboardInterrupt.
This is especially useful to escape constructs.
Example:
```
>>> for i in range(0, 3):
...
KeyboardInterrupt
>>>
```

Handle KeyboardInterrupt in Python Console

---

electrum/gui/qt/network_dialog.py
electrum/interface.py

Fixes #6576.
When a server address is entered without the protocol (`t`/`s`), we guess the preferred protocol to use (`s`) and configure it.
It is also possible to give the string `host:port:protocol` as a connection string as the server. On update of the server field,
only the server address and port are written back into the server field.
In #6576, a server is entered to use the plain protocol. Focus loss of the field triggers a config update (working correctly) and the field is updated, removing the protocol part. Because the protocol was missing due to autofill, the protocol guessing gets active and wrongly selects again the `s` protocol and configures it. Thanks to @SomberNight for the hints.
In this PR, the full connection string is written back to the server field, which fixes the …

network dialog: include protocol in server address field

---

electrum/gui/qt/console.py

sys.ps1 and sys.ps2 define the strings used as primary and secondary prompts in the Python interpreter.
Also fix a rare bug introduced by myself in 7772af6 (#6607) where spaces at the end of the current line would not be remembered when switching server.

Use default sys.ps1 and ps2 as console prompts

---

electrum/servers.json

Currentlane.lovebitco.in is being actively used in the phishing attack against Electrum users.
This can be confirmed by looking at https://ra.pe or https://hodlister.co/server-verification.txt,
the server points directly to an ip in the /24 range being used by phishing ElectrumX servers (46.148.231.31) (https://check-host.net/ip-info?host=currentlane.lovebitco.in)
You can also confirm this by connecting directly to the node using versions 3.3.2 and below and attempt to broadcast a transaction.

Remove phishing server

---

electrum/bitcoin.py
electrum/coinchooser.py
electrum/gui/qt/paytoedit.py
electrum/lnsweep.py
electrum/lnutil.py
electrum/plugins/keepkey/keepkey.py
electrum/plugins/ledger/ledger.py
electrum/plugins/safe_t/safe_t.py
electrum/submarine_swaps.py
electrum/tests/test_transaction.py
electrum/transaction.py
electrum/wallet.py

Mainly just cleanups and small API changes for transaction.py and bitcoin.py.
This is, in part, to accommodate feedback from [this reddit post](https://www.reddit.com/r/Electrum/comments/jghvig/the_power_of_import_electrum_as_a_python_bitcoin/), both explicit and implicit (looking at the linked code).

bitcoin/transaction: construct_script, and clean-ups

---

run_electrum

Previously an unhandled exception in the main script could cause the main thread to die
but the process to hang, as the event loop thread would keep running.
example:
```
$ ./run_electrum -o signmessage tb1qeh090ruc3cs5hry90tev4fsvrnegulw8xssdzx "mymsg" -w ~/.electrum/testnet/wallets/test_segwit_2
File "./run_electrum", line 424, in <module>
init_cmdline(config_options, wallet_path, False)
File "./run_electrum", line 146, in init_cmdline
db = WalletDB(storage.read(), manual_upgrades=False)
File "/home/user/wspace/electrum/electrum/wallet_db.py", line 72, in __init__
self.load_data(raw)
File "/home/user/wspace/electrum/electrum/wallet_db.py", line 103, in load_data
self._after_upgrade_tasks()
File "/home/user/wspace/electrum/electrum/wallet_db.py", line …
```

fix main script hanging (not exiting after exception) in some cases

---

electrum/gui/qt/invoice_list.py
electrum/gui/qt/main_window.py

Based on repeated anecdotal evidence ISTM some users are afraid to click "Pay".
Notably, these are typically users looking for fee settings (and who are not familiar with the architecture: the client cannot sign without prompting for the password ofc).
These users then go on and open thread on reddit/bitcointalk or ask on IRC -- support load that we could do without.
I was pondering how we could change the button text from "Pay" to something else that suggests that there is still a dialog before sign/broadcast, and "Pay..." is my best idea atm.
Ellipsis ("...") is sometimes used in UIs to suggest there will be an additional modal dialog before executing the action. see https://stackoverflow.com/q/637683
Note that I am cheating as the referenced UI guides are talking about menu items, not …

qt gui: send tab: change "Pay" button text to "Pay..."

---

electrum/channel_db.py
electrum/lnrater.py

Add comment on node score and return copies of channel db dicts as per comment in #6705 @SomberNight.

lnrater: follow-up for save channel db attribute accesses

---

electrum/gui/qt/main_window.py

`daemon` was improperly turned into a function in the Python console.
Point `daemon` to `window.gui_object.daemon` instead.
```
Before:
>>> window.gui_object.daemon
<electrum.daemon.Daemon object at 0xffff8d116970>
>>> daemon
'daemon' is a function. Type 'daemon()' to use it in the Python console.
>>> daemon()
File "***/electrum/electrum/gui/qt/main_window.py", line 2141, in <lambda>
return lambda *args, **kwargs: f(method,
File "***/electrum/electrum/commands.py", line 161, in _run
cmd = known_commands[method]
KeyError: 'daemon'
After:
>>> window.gui_object.daemon
<electrum.daemon.Daemon object at 0xffffb1eff730>
>>> daemon
<electrum.daemon.Daemon object at 0xffffb1eff730>
```

Fix daemon being treated as a function

---

electrum/plugins/bitbox02/bitbox02.py

In multisig, we plan to allow other kinds of keypaths that are not
exactly 4 elements long. This change allows parsing the account
keypath for any kind of keypath, assuming the last two element are /change/address.

bitbox02: more robust account keypath

---

electrum/lnrater.py

Fixes a KeyError #6781 when an analyzed node's pubkey is not present in node infos.

lnrater: fix KeyError for unknown node

---

electrum/gui/qt/swap_dialog.py

Fixes #6770 a crash happening when clicking the max button in the swap dialog.

[wip] swaps: fix infinite recursion for max button

---

electrum/gui/qt/util.py

On Linux, when Electrum is executed from Appimage file, to prevent system library
inconsistence for Electrum and web browser and all issues involving that,
Electrum starts web browser and opens web page upon clicking on
'View on block explorer' by fork()'ing the process, unsetting
its custom LD_LIBRARY_PATH environment variable in the child process,
and calling webbrowser.open().
Due to incorrect usage of sys.exit() instead of os._exit() for child process,
Electrum (parent) can't be terminated and endlessly waits for child process upon
exit, while child process does nothing but still exists.
Fix this issue by using os._exit function, which should be used for
child processes (not only in Python).

Use os._exit() for FORKed child browser opener process. Fixes #6404.

---

electrum/gui/qt/main_window.py
electrum/gui/qt/stylesheet_patcher.py
electrum/gui/qt/util.py

see: #6299
I think in general it would look better with this change;
except on macOS with the light theme :( There the status bar buttons have an outline/background, which makes it ugly...
-----
Pics before:
<details>
<summary>Ubuntu GNOME</summary>
</details>
<details>
<summary>Windows</summary>
</details>
<details>
<summary>macOS</summary>
</details>
-----
Pics after:
<details>
<summary>Ubuntu GNOME</summary>
</details>
<details>
<summary>Windows</summary>
</details>
<details>
<summary>macOS</summary>
</details>

qt StatusBarButton: use QToolButton instead of QPushButton

---

electrum/gui/kivy/__init__.py
electrum/gui/kivy/main.kv
electrum/gui/kivy/main_window.py
electrum/gui/kivy/uix/dialogs/installwizard.py
electrum/gui/kivy/uix/dialogs/invoice_dialog.py
electrum/gui/kivy/uix/dialogs/label_dialog.py
electrum/gui/kivy/uix/dialogs/lightning_open_channel.py
electrum/gui/kivy/uix/dialogs/password_dialog.py
electrum/gui/kivy/uix/dialogs/qr_dialog.py
electrum/gui/kivy/uix/dialogs/qr_scanner.py
electrum/gui/kivy/uix/dialogs/request_dialog.py
electrum/gui/kivy/uix/dialogs/settings.py
electrum/gui/kivy/uix/dialogs/tx_dialog.py
electrum/gui/kivy/uix/screens.py
electrum/gui/kivy/uix/ui_screens/history.kv
electrum/gui/kivy/uix/ui_screens/receive.kv
electrum/gui/kivy/uix/ui_screens/send.kv
run_electrum

When running kivy on Linux desktop,
running from git clone, `./run_electrum -g kivy` worked,
but `pip install -e . ; electrum -g kivy` did not.
This was due to the relative paths using cwd as base.
see #6835
note: I have also tried using [kivy.resources.resource_add_path](https://kivy.org/doc/stable/api-kivy.resources.html#kivy.resources.resource_add_path) as an alternative, but could not get that to work.

kivy: fix some resource path issues

---

contrib/build-linux/appimage/build.sh
contrib/build-linux/sdist/build.sh
contrib/build-wine/prepare-wine.sh
contrib/build_tools_util.sh
contrib/osx/make_osx
setup.cfg

see https://pip.pypa.io/en/stable/reference/pip_install/#controlling-setup-requires
> Setuptools offers the `setup_requires` `setup()` keyword for specifying
> dependencies that need to be present in order for the `setup.py`
> script to run. Internally, Setuptools uses easy_install to
> fulfill these dependencies.
> pip has no way to control how these dependencies are located.
> None of the package index options have an effect.
With these changes, we will now instead hard fail if this were to happen.
related: https://github.com/spesmilo/electrum/issues/5859#issuecomment-743621898

build: don't allow setuptools to sneakily install build-time deps

---

electrum/gui/qt/channels_list.py
electrum/gui/qt/swap_dialog.py
electrum/submarine_swaps.py

This PR fixes some issues with the swaps:
* We disable the swap button if no channels are present. It is enabled when channels are open.
* In the case when we have more onchain funds than we can receive on the Lightning wallet, the max button didn't take into account the amount receivable by the Lightning wallet, which led to an empty "you receive" field. The max amount in the normal swap is now limited to the receivable amount on Lightning.
* In case of a forward swap, the swap amount calculation was previously not using a formula that led to the exact expected amount requested by the server, which led to a slight overpayment, depending on the overall swap amount. Using the formula given in the commit message, our estimated amount is now the expected amount from the server.

Swap improvements

---

electrum/invoices.py
electrum/wallet_db.py

The 'height' field was added in https://github.com/spesmilo/electrum/commit/cdfaaa260942b807f809c2c0414fb242a03e945a
At the time we thought we could just add it with a default value without a db upgrade;
however the issue is that if old code tries to open a new db, it will fail (due to unexpected new field).
Hence it is better to do an explicit conversion where old code *knows* it cannot open the new db.
```
E | gui.qt.ElectrumGui |
File "...\electrum\electrum\gui\qt\__init__.py", line 257, in start_new_window
wallet = self.daemon.load_wallet(path, None)
File "...\electrum\electrum\daemon.py", line 488, in load_wallet
db = WalletDB(storage.read(), manual_upgrades=manual_upgrades)
File "...\electrum\electrum\wallet_db.py", line 72, in __init__ …
```

wallet_db: impl convert_version_33: put 'height' field into invoices

---

electrum/lnchannel.py
electrum/lnworker.py

in the num_sats_can_send/receive methods of the lnwallet. Fixes #6855.

lnchannel: reflect frozen amounts and disconnected peers

---

electrum/plugins/coldcard/README.md
electrum/plugins/coldcard/coldcard.py

Latest version of Coldcard firmware (3.2.1) requires derivation paths to be known for all co-signers during multisig signing. This change adds that information, which was previously shown as comment in the same spot. With a multisig wallet open, go to _Wallet > Information > Export for Coldcard_ to exercise this change.
Also updates plugin README, removing historical junk.
[v3.2.1 firmware release notes](https://blog.coinkite.com/version-3.2.1-released/)

Export full derivation paths for Coldcard v3.2.1

---

electrum/commands.py

Ideally the commands `deserialize` and `serialize` should reverse each other.  This will provide the minimum amount of correction to allow `serialize(deserialize(pbst))` to complete without error
* Fixed 'locktime' typo that had it incorrectly camel-cased
* Made 'value' and 'value_sats' synonyms so either can be used
It is assumed that the field "value" is a already in SATs.  If "value" is assumed to be in BTC or mBTC, a correction will be needed.

Correct errors in command 'serialize(deserialize(pbst))'

---

electrum/base_wizard.py
electrum/commands.py
electrum/plugins/trustedcoin/trustedcoin.py

segwit addresses are widely supported today.

Wizard: do not ask seed type, default to segwit

---

electrum/gui/kivy/main_window.py
electrum/gui/kivy/uix/dialogs/installwizard.py
electrum/gui/kivy/uix/dialogs/password_dialog.py
electrum/gui/kivy/uix/dialogs/settings.py
electrum/gui/kivy/uix/dialogs/wallets.py
electrum/wallet.py
run_electrum

When a wallet password is updated, check the password for all
wallets in directory. If that check passes, update password for
all wallets. If it fails, update only the current wallet.

Kivy: use the same password for all wallets

---

electrum/gui/qt/settings_dialog.py
electrum/util.py

We now allow setting a custom URL for the block explorer setting (previously user could only choose from hardcoded list).
The QLineEdit expects values such as (one per line):
```
https://blockstream.info/testnet/
https://192.168.0.38:3021/
("https://blockstream.info/testnet/", {'tx': 'tx/', 'addr': 'address/'})
```
closes #4831
-----
<details>
<summary>pics</summary>
</details>

qt block explorer: allow custom URL

---

electrum/gui/qt/main_window.py

on git master d7515b936e32efc02f6b4b0dd97b8520b5c447a7
```
E | gui.qt.exception_window.Exception_Hook | exception caught by crash reporter
File "/home/wakiyamap/electrum/electrum/network.py", line 857, in wrapper
return await func(self, *args, **kwargs)
File "/home/wakiyamap/electrum/electrum/network.py", line 1042, in get_transaction
return await self.interface.get_transaction(tx_hash=tx_hash, timeout=timeout)
File "/home/wakiyamap/electrum/electrum/interface.py", line 918, in get_transaction
raw = await self.session.send_request('blockchain.transaction.get', [tx_hash], timeout=timeout)
File "/home/wakiyamap/electrum/electrum/interface.py", line 173, in send_request
timeout)
File "/usr/lib/python3.6/asyncio/tasks.py", line 339, in wait_for
return (yield …
```

Fix error of showing bitcoin paper(testnet)

---

electrum/lnchannel.py
electrum/lnhtlc.py
electrum/lnpeer.py
electrum/lnworker.py
electrum/tests/test_lnpeer.py

This PR adds a unit test which showcases that on current master we might fulfill an HTLC before it is irrecovably committed;
and fixes that behaviour.
Note that this makes two of the four fields stored in `hm.log['unfulfilled_htlcs']` useless, so we could rm those. This would need a wallet upgrade. Shall we do that?

fix htlc switch fulfilling htlc too soon (in case of race)

---

.travis.yml

Using Docker-ce(18.x) will cause windows build to fail.
I change to use the latest stable.
build log https://gist.github.com/wakiyamap/dcb638a6df1aeeffd3a61d94cb1a9488
ref. https://www.docker.com/blog/multi-arch-build-what-about-travis/

Fix windows build(travis)

---

electrum/transaction.py

Currently it's only possible to set the script-type for the inputs in a psbt for wallet owned inputs. For other imported inputs(payjoin) they stay 'unknown'. 
This PR adds a function to determine the inputs-types by checking if a script(in scriptpubkey or redeem-script) matches a scripts pattern.
I wanna use this function in this PR: https://github.com/spesmilo/electrum/pull/6804 to validate equality of input-types in the payjoin.
---
general question:
Why is the naming of the script-types different than in most other application/BIPs? If I'm right, in Electrum composed names are in the form: [inner/encapsulated-type]-outer (p2wpkh-p2sh), but in the BIP's the naming is p2sh-p2wpkh. Do I understand it correctly?

add function to determine script-type for all inputs in a psbt

---

electrum/paymentrequest.py

Outputs is passed in PR data as output script, so there is possibility to pay PR on different network.
Next commit fix this.
- paymentrequest: check network on PaymentRequest parse

paymentrequest: check network on PaymentRequest parse

---

electrum/lnpeer.py

Fix to correcly instantiate OnionRoutingFailureMessage, otherwise this can lead to an endless reconnection when a multipart payment times out.

lnpeer: fix timed out mpp

---

electrum/plugins/ledger/ledger.py

This PR is fixing the issue with invalid signatures for "small" r & s values when signing the message with Ledger wallet.
The issue lies in the signed message format, the format expects 32 bytes for r and 32 bytes for s values if the value starts with 2 or more zeros for either r or s it will create invalid base64 signature.
The one example I stumbled upon is this:
hash to sign: `cfd24a369db6159bdf9c96e8e00bae3f9042eb029e88fae9196f56f9daee8014`
address: `bc1quprwg497w2p6up7upqscfedz6crepz9fvcr3qs` aka `1MSsHdMg7oFUDx7FhNj2vh9SRRjqZcWAD4`
> {
>   "v": 0,
>   "r": "0ec5cacf09793857d6daf65783b0c3b1d08bf6fd6af404e8896ef73a680678",
>   "s": "5ec8f943682c0bd5b0147f8f320ea141bd98c863f3b157323a9dff4a2dc26a6f"
> }
current Electrum implementation spits: …

Fix ledger sign message

---

electrum/paymentrequest.py

Set PaymentDetails.network for testnet. Related to #6993.
- make_unsigned_request: set network for testnet

make_unsigned_request: set network for testnet

---

contrib/build-wine/Dockerfile

```
The following packages have unmet dependencies:
dirmngr : Depends: gpgconf (= 2.2.19-3ubuntu2)
Recommends: gnupg (= 2.2.19-3ubuntu2) but it is not going to be installed
gnupg2 : Depends: gnupg (>= 2.2.19-3ubuntu2) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
Current version is `2.2.19-3ubuntu2.1`.
https://packages.ubuntu.com/en/focal-updates/gnupg2
https://packages.ubuntu.com/en/focal-updates/utils/dirmngr

windows build: update gnupg(2.2.19-3ubuntu2.1)

---

electrum/daemon.py
electrum/gui/kivy/main_window.py
electrum/gui/kivy/uix/dialogs/lightning_channels.py
electrum/gui/kivy/uix/dialogs/lightning_open_channel.py
electrum/gui/kivy/uix/dialogs/settings.py
electrum/gui/qt/channels_list.py
electrum/gui/qt/main_window.py
electrum/gui/qt/settings_dialog.py
electrum/lnaddr.py
electrum/lnchannel.py
electrum/lnonion.py
electrum/lnpeer.py
electrum/lnrouter.py
electrum/lnutil.py
electrum/lnwire/onion_wire.csv
electrum/lnworker.py
electrum/network.py
electrum/sql_db.py
electrum/tests/regtest/regtest.sh

- trampoline is enabled by default in config, to prevent download of `gossip_db`.
(if disabled, `gossip_db` will be downloaded, regardless of the existence of channels)
- if trampoline is enabled:
- the wallet can only open channels with trampoline nodes
- already-existing channels with non-trampoline nodes are frozen for sending.
- there are two types of trampoline payments: legacy and end-to-end (e2e).
- we decide to perform legacy or e2e based on the invoice:
- we use `trampoline_routing_opt` in features to detect Eclair and Phoenix invoices
- we use `trampoline_routing_hints` to detect Electrum invoices
- when trying a legacy payment, we add a second trampoline to the path to preserve privacy.
(we fall back to a single trampoline if the payment fails for all trampolines)
- the …

Trampoline

---

electrum/gui/kivy/main_window.py

Add Kivy `app.scan_qr_non_android` to simplify debugging on other platforms.

kivy: add app.scan_qr_non_android

---

electrum/mpp_split.py
electrum/tests/test_mpp_split.py

Optimizes split parameters and leaves tests in a proper state by undoing side effects in tearDown.

mpp_split: optimize split parameters

---

electrum/lnchannel.py
electrum/lnpeer.py
electrum/lnworker.py

when receiving htlcs as part of MPP
- it is not the invoice_amount the htlc set sum should be tested against but `total_msat`,
i.e. htlc set sum and `total_msat` should be compared
- specifically, BOLT-04 seems to suggest testing equality of htlc set sum and `total_msat` (instead of `>=`)
> if the total `amount_msat` of this HTLC set equals `total_msat`
- re zero amount invoices, they too might be MPP, so the same tests still need to be done
- (the FIXME in `lnchannel.py` is pre-existing brokenness)
https://github.com/lightningnetwork/lightning-rfc/blob/90468030d5c374ced568c91df5d37699fe020010/04-onion-routing.md#basic-multi-part-payments

lnpeer: MPP recv: only fulfill htlc if amt sum exact-matches total_msat

---

electrum/coinchooser.py
electrum/gui/qt/main_window.py
electrum/gui/qt/rbf_dialog.py
electrum/tests/test_transaction.py
electrum/tests/test_wallet_vertical.py
electrum/transaction.py
electrum/wallet.py

- wallet: refactor `bump_fee` strategies so that `bump_fee` can use any subset of them in any permutation
- wallet: add a new `bump_fee` strategy which decreases the payment outputs (instead of change)
(this would close https://github.com/spesmilo/electrum/issues/6783)
- qt: move RBF dialog out of `main_window.py` into its own file
- qt: add "Advanced" button to RBF dialogs; expose "strategy" selection to bump_fee dialog
- qt: rename "Final" checkbox to "Keep Replace-By-Fee enabled"
-----
Re UI changes:
<details>
<summary>Before PR</summary>
</details>
<details>
<summary>After PR</summary>
</details>

wallet: refactor bump_fee; add new strategy; change Qt dialog to have "advanced" button

---

electrum/lnhtlc.py
electrum/lnpeer.py
electrum/lnworker.py
electrum/tests/test_lnpeer.py

We now try to fail pending HTLCs when shutting down.
This is most useful when receiving MPP where there is a non-trivial chance
that we have received some HTLCs for a payment but not all, and the user
closes the program. We try to fail them and wait for the fails to get
ACKed, with a timeout of course.

fail pending htlcs on shutdown

---

electrum/gui/qt/main_window.py

This updates the help text to remove outdated info and answer common questions.
The added "(?)" suffix to the label itself intends to make the help text more discoverable.

qt receive tab: change "Expires after" label and help text

---

electrum/lnworker.py
electrum/mpp_split.py
electrum/tests/test_lnpeer.py
electrum/tests/test_mpp_split.py

Adds the node id as an input to mpp_split (extending the `short_channel_id` key), to be able to filter out split configurations that pay via several nodes. We need to do this in case of trampoline multipart payments, see https://github.com/ACINQ/eclair/issues/1723. Related: #7087.
TestPeer now inherits from `TestCaseForTestnet` instead of `ElectrumTestCase` to disable filtering of single nodes in tests, to not break `test_multipart_payment_with_trampoline`, which we want to keep in its current form (as intended for the future without the above mentioned bug). Let me know if there's a better way to do this.

mpp_split: use single nodes for mpp payments over trampoline

---

electrum/lnpeer.py
electrum/tests/test_lnpeer.py

When forwarding an HTLC and the outgoing channel doesn't have enough funds or other transient issues, we are failing the HTLC with a temporary channel failure.
From BOLT # 04:
* if during forwarding to its receiving peer, an otherwise unspecified,
transient error occurs in the outgoing channel (e.g. channel capacity
reached, too many in-flight HTLCs, etc.):
-> return a temporary_channel_failure error.

forwarding: temp chan fail on insufficient funds

---

electrum/base_wizard.py
electrum/bitcoin.py
electrum/channel_db.py
electrum/commands.py
electrum/gui/kivy/main.kv
electrum/gui/kivy/main_window.py
electrum/gui/kivy/uix/dialogs/lightning_channels.py
electrum/gui/kivy/uix/dialogs/lightning_open_channel.py
electrum/gui/kivy/uix/dialogs/settings.py
electrum/gui/kivy/uix/ui_screens/status.kv
electrum/gui/messages.py
electrum/gui/qt/channels_list.py
electrum/gui/qt/main_window.py
electrum/gui/qt/settings_dialog.py
electrum/keystore.py
electrum/lnchannel.py
electrum/lnpeer.py
electrum/lnutil.py
electrum/lnworker.py
electrum/tests/regtest/regtest.sh
electrum/tests/test_wallet.py
electrum/wallet.py
electrum/wallet_db.py

Deterministic NodeID:
- lightning_xprv is derived from seed at wallet creation
- only for standard wallets with a 'segwit' seed_type
- other wallets still use 'lightning_privkey2'
Recoverable channels:
- channel recovery data is added funding tx using an OP_RETURN
- recovery data = 4 magic bytes + node id[0:16]
- recovery data is chacha20 encrypted using funding_address as nonce.
(this will allow to fund multiple channels in the same tx)
GUI:
- whether channels are recoverable is shown in wallet info dialog.
- if the wallet can have recoverable channels but has an old node_id,
users are told to close their channels and restore from seed
to have that feature.

Deterministic node

---

electrum/bitcoin.py

Fixing the poor design of address_to_scripthash.
closes #7141

Issue #7141 RE #fixing poor_design_fix_address_to_scripthash

---

electrum/commands.py
electrum/gui/kivy/uix/dialogs/lightning_channels.py
electrum/gui/qt/swap_dialog.py
electrum/submarine_swaps.py

First commit:
- document `SwapManager._get_recv_amount` and `SwapManager._get_send_amount`
- change calculations so that they match the boltz-backend
- note that in the reverse swap case, the server does not care about the on-chain claim tx the client
needs to pay for. This introduced some implicit hacks and inconsistencies in the code in the past,
it is still a bit ugly but at least this is now explicit.
- `SwapManager._get_recv_amount` and `SwapManager._get_send_amount` are now proper inverses of each other
Second commit:
- swaps: (fix) for forward swaps, correctly consider `num_sats_can_receive`
- Previously the `min()` was passed lightning amounts and on-chain amounts mixed;
which is conceptually a type error. It is now only passed on-chain amounts.
Due to the bug, we did not allow a …

swaps: revise send/recv amount calculation

---

setup.py

This makes pip install copy ~all files from the tar.gz to site-packages.
(well, not everything, only files in `electrum/` (so e.g. not `contrib`))
See comment in `setup.py`.
E.g. we have been including the www/ folder in the tar.gz but have not been installing it to site-packages. Now we do.
Or we have been including the kivy GUI files in the tar.gz but not installing them. Now we do.
I like this because it simplifies setup.py and should be easier to reason about too.
should fix #7089 (at least when using the tar.gz)
-----
related:
https://github.com/pypa/sampleproject/issues/30#issuecomment-143947944
https://github.com/pypa/sampleproject/issues/30#issuecomment-597944718
(most of that thread really)

sdist build: let pip install put ~everything from tar.gz to site-packages

---

electrum/address_synchronizer.py
electrum/wallet.py

This allows looking up what UTXOs the wallet had at a specific time in the past.

wallet: implement get_utxos at specific block height

---

electrum/base_wizard.py
electrum/gui/kivy/main_window.py
electrum/gui/qt/main_window.py
electrum/keystore.py
electrum/wallet.py
electrum/wallet_db.py

- implement `Deterministic_KeyStore.get_seed_type()`, to be able to tell the seed type without prompting the user for password
- wallet_db upgrade: put 'seed_type' into existing keystores
- keystore: encapsulate "can_have_deterministic_lightning_xprv" logic
- change `wallet.init_lightning()` to be able to either deterministic or random LN keys, preferring deterministic ones if available
- expose some of this to GUI logic to adapt messages

keystore to store seed_type; wallet.init_lightning() to sometimes create deterministic LN keys

---

contrib/osx/make_osx

In some places in the script if some directory name had spaces it could cause issues. 
I also added quotes around a few other directory names that currently are hardcoded with names without spaces as a way to prevent any future mishap

Prevent spaces from causing issues in make_osx

---

electrum/gui/qt/qrcodewidget.py

In some situations, if a QR code's data and help_text were too long, the QR code was unscannable.
Before:
https://ipfs.io/ipfs/Qmc6Sa39BWnPbwuzpj8fXJ82U51Tf9cQGCYpoCFpMxXabi?filename=qr_before.png
After:
https://ipfs.io/ipfs/QmRAUufgXZB8we1WXBGB1Dbb2UYkHZhbMTQBti4CFd3XuT?filename=qr_after.png
Quick way to test it in the console:
```
>>> from electrum.i18n import _
>>> from electrum.gui import messages
>>> window.show_qrcode('channel_backup:AShYky6ADIEoGkWQy12/sJKj7cLg+wlo+IZzi4w8FjYz6RpjrEHi9752qL5XNZFHWJiqMaqZ1jzOCrCZuA57jj4CHaWA8jG+nzi567No9IUdkfXzDMgqrPsOnGbflPHSD+9UV3t+krbT1Hb+75aQAS9KLMWvMmY53vCGP9qVACYVH1gstqaDyLQ6y0tcNZBwbTnMS3GsYplL1SEMEhGBtAceMgUFYg4UybmWWhqx2kXlWLuvtpJuZGJsvuJBIBfFMaso2vybFOxT68BVBvMFPd2RPC8hD3Zz7ToDXoTCqSxABP4+yWCgQ3nF5Y6ukOMeIMAUwFvF3Q3oFvRDr+kKl5fcFQRfqMBm3a3S …
```

Avoid hiding QR codes with help_text

---

electrum/gui/stdio.py
electrum/gui/text.py
electrum/logging.py
electrum/tests/__init__.py
run_electrum

Previously, during early-startup (until configure_logging(config) is
called in run_electrum),
- the stderr log handler lost all log messages below warning level (irrespective of `-v`), and
- the file log handler lost all log messages regardless of log level
We now instead start buffering log messages in memory as soon as
electrum.logging is imported. The buffer is dumped into the
stderr and file log handlers when they are fully set up, and then
the buffer is discarded (and the temporary log handler is removed).
Note that messages are not logged until configure_logging() is called.
Previously WARNING/ERROR messages would get logged immediately to stderr,
but not anymore. This was changed so that the order of the log messages
can be kept intact. (if we log WARNINGs immediately, but need to …

logging: don't lose log messages during early startup

---

electrum/address_synchronizer.py
electrum/blockchain.py
electrum/commands.py
electrum/lnhtlc.py
electrum/lnrouter.py
electrum/lnutil.py
electrum/lnworker.py
electrum/network.py
electrum/tests/test_lnpeer.py
electrum/tests/test_lnrouter.py
electrum/util.py

Implements liquidity hints for pathfinding, i.e., take information of successful and failed routing attempts to improve pathfinding, similar to the strategy LND employs.
We interpret temporary channel failures such that a node couldn't forward a payment as the channel (or node pair) didn't have enough balance on its side of the channel. Based on this assumption, we can keep a record of the previous part of the route (which was successful) and the failing channel. For each channel we record the `can_send` and cannot_send values upon which we build a new penalty for edge weights in pathfinding. Likewise, when a payment succeeds, we record `can_send` amounts for the channels involved (the assumption is that we can send the same amount again, even if we changed the balances by sending). …

Liquidity hints for pathfinding

---

electrum/submarine_swaps.py

In #7186  it is reported that the inverse `send_amount` is not the `send_amount` that we gave.
I tried to run through some explicit sample values and I see that
`recv_amount == SwapManager._get_recv_amount(SwapManager._get_send_amount(recv_amount))`
but
`send_amount != SwapManager._get_send_amount_get(SwapManager._recv_amount(send_amount))`
for some `send_amount` values, see the test cases. The probability of the occurrence of these errors is the same as the swap fee percentage, but it shows up when the swap slider in kivy is moved many times or continuously.
Both methods internally use `math.floor` and `math.ceil` which are non-invertible, which probably leads to these off-by-one errors. I suggest to relax the cross check regarding off-by-ones. I don't think those methods can be made …

swaps: fix swap sanity check

---

electrum/commands.py
electrum/lnworker.py
electrum/network.py

Fixes #7242. I went through all occurrences of `network.path_finder` and added checks for `path_finder` initialization, in scopes that do not apply the `if not self.channeldb` check previously. Right now I'm unsure whether we should check explicitly for `network.path_finder` or to use `lnworker.channel_db` as a check, i.e. check on the per wallet or per network basis.
I also think we could make the code more readable by converting `if not self.channeldb` to something more explicit, `network.uses_gossip`/`network.uses_trampoline`, perhaps.

lnworker: fix path_finder access

---

electrum/gui/kivy/uix/dialogs/lightning_open_channel.py

Fixes #7219, where the issue is that it is still possible to paste node connection strings into the open channel dialog in the Android GUI, but we allow only to open channels with preselected nodes for now. This PR disables the paste and QR scan buttons and prevents crashing when unparseable connection strings are pasted (for the gossiping case). I hope the latter pattern is OK (re #7234).

kivy: improve openchannel dialog for trampoline

---

electrum/gui/kivy/uix/screens.py
electrum/gui/qt/main_window.py
electrum/invoices.py
electrum/lnaddr.py
electrum/util.py

Fixes #7184, where upon user input Electrum crashes after amount validation for very high amounts (for receiving and sending input). I suggest to handle the error more gracefully, however I have no idea why this happens all of a sudden. It could be that some service pushes out wrong bitcoin URIs as the user feedback in the issue indicates.

invoice: fail gracefully with large amount

---

contrib/build-linux/appimage/Dockerfile

Fix for the current docker file that breaks with: `E: Version '2.23-0ubuntu11.2' for 'libc6-dev' was not found`

Appimage: update libc6-dev package

---

electrum/gui/kivy/main_window.py

This change fixes the storage access behavior for the wallet backup for android. Ref: https://github.com/spesmilo/electrum/issues/6774
The permission for accessing storage has to be granted in runtime. This is already implemented, but in the wrong order when it comes to creating the back up dir.

Android: Fix wallet backup 

---

electrum/commands.py
electrum/tests/test_commands.py
run_electrum

I saw a new `TODO` was introduced in https://github.com/spesmilo/electrum/commit/638d4f747238f1255b58d40035366903a832dfb4 on the `signtransaction` command and tried to address the `TODO` by separating the command to two new commands: `signtransaction_with_privkey` and `signtransaction_with_wallet`.
Also did a tweak to the `signtransaction_with_privkey` logic to accept list of private keys and sign with many private keys instead of only one.

cmd: add sign with privkey and wallet

---

electrum/lnrouter.py
electrum/lnworker.py
electrum/tests/test_lnpeer.py
electrum/tests/test_lnrouter.py

When making a multipart payment, the payment in principle can have overlapping paths for individual parts.
The [spec](https://github.com/lightningnetwork/lightning-rfc/blob/master/04-onion-routing.md#basic-multi-part-payments) states that we `SHOULD try to use diverse paths to the recipient for each HTLC`.
Here, the inflight HTLCs are tracked in the liquidity hints system, just by counting the active HTLCs per channel. The penalty for channels gets additional penalties proportional to the number of HTLCs in the channel.
I needed to make `create_routes_for_payment` an async generator, such that inflight HTLCs can be asynchronously added and removed.
This PR also solves an issue with #7202, where when sending an MPP over our single channel with equal split sizes, we avoid probing the same …

lnrouter: add inflight htlcs to liquidity hints

---

electrum/gui/kivy/uix/dialogs/addresses.py
electrum/gui/qt/address_list.py

I've noticed that old used addresses can make an address list unwieldy over time. I would like a filter for "Funded & Unused" that filters out old zero balance addresses.

Qt address list: add "funded or unused" filter option

---

electrum/commands.py
electrum/constants.py
electrum/gui/qt/main_window.py
electrum/lnaddr.py
electrum/servers_signet.json
electrum/simple_config.py
electrum/trampoline.py
electrum/util.py
run_electrum

rebase https://github.com/spesmilo/electrum/pull/7267
Please let me know if you have any problems.

add signet support

---

electrum/gui/qt/amountedit.py
electrum/gui/qt/main_window.py
electrum/gui/qt/transaction_dialog.py

The current window minimum sizing makes electrum a bit cumbersome on smaller screens (640x480 in my case).
Simply making the central widget of the main window a QScrollArea fixes the main window.
Reducing the minimum size on the BaseTxDialog and setting the width explicitly both allows for it to be resized smaller and still retains the original size.  They both work perfectly on 640x480 after this modification.

Friendlier minimum sizing for small screens for air-gapped signing

---

electrum/daemon.py

If `listen_jsonrpc` is `False`, lockfile is not used, so if doing cleanup gracefully, error occurs:
`FileNotFoundError: [Errno 2] No such file or directory: '/home/alex/.electrum/testnet/daemon`

Don't cleanup lockfile if listen_jsonrpc is False

---

electrum/commands.py

This pull request adds a new tag for commands decorator to mark command as requiring lightning. It allows for better error messages and identification of lightning commands in cases where it is unsupported. For example, instead of errors about `wallet.lnworker` being `None`, it would say `Lightning not supported in this wallet type`
Few questions:
1) Should commands not requiring wallet be marked as lightning (i.e. `decode_invoice`, `clear_ln_blacklist`)? They seem to not use lightning keys
2) Is it safe to assume that if `wallet.lnworker is None`, then lightning is not supported in a wallet, or a better check should be used?
3) (for understanding 4.1 changes) when restoring a wallet, init_lightning() would always be called for supported wallets, so in my code there is no need to manually …

Add lightning tag for commands

---

electrum/address_synchronizer.py
electrum/wallet.py

Previously the `request_status` event was only called when a tx touching the receive request was added to the wallet (typically while unconfirmed). Notably, it will now also fire when the tx gets its first confirmation. Subsequent confirmation number changes for the receive request can be tracked by listening to the `blockchain_updated` event.
After either event, the status of the request can be checked via `wallet.get_onchain_request_status(req)`.

wallet: fire "request_status" event also when conf number changes

---

contrib/build-wine/build-electrum-git.sh
contrib/osx/make_osx

The .pyc files would get created when a .py module is imported,
which is done during the build for some source files by pyinstaller
(when it analyses imports).
I considered setting PYTHONDONTWRITEBYTECODE=1 in build_tools_util.sh,
to apply to all builds, but am not sure how it would affect the Android build,
where we actually want .pyc files included in the apk.
see https://docs.python.org/3/using/cmdline.html#envvar-PYTHONDONTWRITEBYTECODE
@ecdsa

mac build: don't create __pycache__ folders

---

electrum/lnrater.py
electrum/network.py
electrum/util.py

This PR removes `_mythread` checks and uses native asyncio APIs instead.
Why it works:
If there is no event loop in current thread, `_get_running_loop()` returns None, which is not equal to self.asyncio_loop. Network thread has self.asyncio_loop running. Otherwise loop objects won't be equal
I have tested scripts/quick_start, works as expected, also tried using `run_from_another_thread` in `async def _start` method running in network thread, assert is working.
It creates `get_running_loop` utility
This can be changed of course
All tests pass (tested locally, remotely travis hates me)

Improve _mythread checks

---

.gitignore
contrib/osx/make_osx

related: https://github.com/spesmilo/electrum/issues/7266
We are trying to make the macOS builds reproducible...
Compiling python from source on OSX seems to be very difficult in a reproducible way.
As a workaround, we make the same tradeoff the Windows binaries already have: we trust the python binaries distributed by `python.org`.

mac build: download python from python.org instead of using pyenv

---

contrib/osx/README.md
contrib/osx/apply_sigs.sh
contrib/osx/compare_dmg
contrib/osx/extract_sigs.sh

- added notes about reproducibility requirements
- adapted build scripts from Bitcoin Core that can
- extract signatures from a signed .app
- apply previously extracted signatures to an unsigned .app
closes https://github.com/spesmilo/electrum/issues/7266

mac build: attempt at "reproducible" codesigned builds

---

electrum/channel_db.py
electrum/lnrouter.py

Previously pathfinding returned `NoPathFound` exceptions for circular pathfinding, mainly because `nodeA` and `nodeB` were not considered to potentially be equal.
Note that I removed the `is_mine` checks and added an alternative code block, as in the meantime the meaning of `my_channels` has changed within the `create_routes_for_payment` scope. Right now it is interpreted like "these are the channels over which I want payments to go out because they are active and can send something", so they will not include receiving-only channels.
The effect of the removal of `is_mine` checks is less reliability on the receiving side, but it decouples concerns (we have liquidity hints which take care of this), but alternatively we could also restore the old `my_channels` meaning, which is an open …

lnrouter: fix self-payments

---

electrum/gui/qt/installwizard.py

Currently, in the multisig page of the wizard, the tab order is "bottom slider, top slider, back/next, and nothing (the entire scroll area)". This makes the scroll area non-focusable (on all pages) so the focus rectangle won't disappear once per Tab-key cycle, and (on the multisig page) constructs the top slider before the bottom slider so it comes first in the tab order.

Fix tab order in Qt setup wizard

---

electrum/trampoline.py

I forked eclair and handled supporting signet for electrum.
https://github.com/wakiyamap/eclair/commits/bitcoin-signet
https://github.com/wakiyamap/bitcoin-lib/commits/bitcoin-signet
Please teach me know if you have any problems.
eclair.conf
```
eclair.chain=signet
eclair.bitcoind.rpcport=38332
eclair.bitcoind.rpcuser=********
eclair.bitcoind.rpcpassword=********
eclair.bitcoind.zmqblock="tcp://127.0.0.1:29000"
eclair.bitcoind.zmqtx="tcp://127.0.0.1:29001"
eclair.api.password=********
eclair.api.enabled=true
eclair.trampoline-payments-enable=true
eclair.node-alias="eclair@wakiyamap"
eclair.server.public-ips=[signet-eclair.wakiyamap.dev]
eclair.server.port=9735
eclair.max-funding-satoshis=500000000
```

Change lightning node(signet)

---

run_electrum

No longer prompts for new password if `--new_password` parameter is used
fixes https://github.com/spesmilo/electrum/issues/7475

Fix bug with new password prompt

---

electrum/i18n.py

The option "brasilian" is inaccurate since we brazilians do speak Portuguese.
We don't consider "brasilian" as a language, so I believe this change I've made is a more accurate option for this public.

Removes inaccurate "brasilian" language

---

.cirrus.yml
.dockerignore
contrib/android/Dockerfile
contrib/android/build.sh
electrum/tests/regtest.py
electrum/tests/regtest/run_bitcoind.sh
electrum/tests/regtest/run_electrumx.sh
electrum/tests/regtest/start_electrumx.sh

As discussed on IRC, this PR adds Cirrus CI.
To see what the Cirrus results look like, see https://github.com/JeremyRand/electrum-nmc/runs/3155036786
Some random notes:
1. A few of the Lightning unit tests fail nondeterministically.  I haven't looked at this too closely, but I don't think this is caused by the Cirrus environment.
2. The functional regtests fail to break out of the "wait until Alice sees channel open" loop.  Again, I didn't look at this very closely.
3. I had to refactor the scripts that launch Bitcoin Core and ElectrumX for the functional tests.  One benefit of the refactor is that Cirrus shows the logs for each in a separate log section, which is helpful for debugging when the functional tests fail.
4. I had to slightly tweak the `docker build` command for the Android …

Add Cirrus CI

---

electrum/daemon.py
electrum/lnwatcher.py
electrum/sql_db.py
electrum/tests/regtest/regtest.sh

From my testing I saw that the watchtower isn't actually tested for publication of the punishment transaction. That test fails, which is fixed by the watchtower polling the sweepstore. Maybe there's a more efficient way using events?

watchtower: continuously check for added channels

---

electrum/commands.py
electrum/daemon.py
electrum/tests/regtest.py
electrum/tests/regtest/regtest.sh

This patch adds support for Unix domain sockets to Electrum. To use, spawn the daemon with `-u` or `--unixdomain`, e.g.:
`electrum daemon -du`
You can also specify a path for the domain socket manually with the `--sockpath` argument, e.g.:
`electrum daemon -du --sockpath=$(mktemp --dry-run)`
An integration test is included under `electrum/tests/test_unixsocket.sh`. I am not at all sure if this would meet your standards for tests, because it's a shell script. I would thus be happy to receive feedback on this point.
Closes #4955.

Add support for Unix domain sockets

---

electrum/lnpeer.py

`drop_to_remote` can be False and at the same time the to_remote output
is not present, because it is below dust. Therefore, we have to explicitly
check if to_remote is present when checking for the allowed script types and
dust limits. This affects channels which have sent only dust values, they
can't be closed unilaterally without this fix.
Fixes a regression introduced by 947693c90d6579ca52281ea7228a91fd59a81c81.

lnpeer: fix possibly nonexistant to_remote check

---

contrib/requirements/requirements-hw.txt
electrum/plugins/trezor/clientbase.py
electrum/plugins/trezor/trezor.py

minor compatibility tweaks, plus Taproot support (looking to the future)
summary of changes:
* trezorlib now recognizes protobuf required fields, and so some values are needed at construction time. So there's a reorganization of how `TxInputType` and `TxOutputType` instances are created.
* `trezorlib.btc.sign_tx` accepts kwargs instead of `details`
* the signature of `button_request` is changed, it now accepts the full `ButtonRequest` object instead of just code
tested for normal and multisig wallets, seems to work fine.
Draft because trezorlib 0.13 is not out yet.

trezorlib 0.13 compatibility

---

electrum/lnworker.py
electrum/mpp_split.py
electrum/tests/test_lnpeer.py
electrum/tests/test_mpp_split.py
electrum/trampoline.py

Changes the splitting algorithm to an easier approach and allows for split amounts in individual channels.
Fixes #7180. I redesigned the splitting algorithm, which is in my view easier to understand and maintain. The main change is how the split configurations are created. Here, I'm using a more top-down probabilistic approach to fill up the channels. I think it doesn't really matter how the configurations are created as long as it samples the solution space relatively well. Rating of the solutions stays the same (except for adapting to individual amounts in a channel) and one can also see from the tests that the algo doesn't significantly change things.
I think this in combination with #7152 will significantly improve mpp sending. In the edge case of a single channel, it was previously …

MPP splitting algorithm: redesign and split within channels

---

.cirrus.yml

Electrum seems to encounter bizarre network connectivity errors (in the form of failed syscalls) when run in a Docker container on Cirrus.  This was causing the functional tests on Cirrus to fail, presumably because some of Electrum's Lightning-related socket syscalls were failing.  Switching that task to run in a VM instead of a Docker container fixes the failure.
I am not sure whether this is a Cirrus-specific issue or if Electrum has these issues in Docker in general.  There is also some nondeterministic behavior in the functional tests that can cause them to sometimes hang; that is out of scope for this PR, but the easy workaround is to restart the affected Cirrus task.
I also fixed the ElectrumX version at v1.15.0, since Electrum master is using the BSV ElectrumX repo (which …

Cirrus: Use VM instead of Docker for functional tests

---

electrum/lnpeer.py
electrum/tests/test_lnpeer.py
electrum/trampoline.py

~~Based on #7202 (first three commits).~~
- Implements a way to define arbitrary test graphs
- Adds tests for legacy and end-to-end single-part trampoline payments
- When a (trampoline) payer computes a trampoline route based on route hints of a trampoline receiver, we need to use typical trampoline forwarder fees instead of the normal fee policy (they would be too low)
- Fixes a bug, where an Electrum trampoline forwarder doesn't include the correct payment secret when forwarding to a legacy receiver

flexible lnpeer test graphs and spp trampoline tests

---

.cirrus.yml
README.rst
contrib/deterministic-build/requirements.txt
contrib/freeze_packages.sh
contrib/requirements/requirements.txt
electrum/address_synchronizer.py
electrum/bip39_recovery.py
electrum/daemon.py
electrum/exchange_rate.py
electrum/interface.py
electrum/lnpeer.py
electrum/lntransport.py
electrum/lnworker.py
electrum/network.py
electrum/synchronizer.py
electrum/tests/test_lnpeer.py
electrum/tests/test_lntransport.py
electrum/util.py
electrum/wallet.py
run_electrum
setup.py
tox.ini

This PR
- bumps the min required python version from 3.6.1 to 3.8, including some minor clean-up due to dropping older versions (closes https://github.com/spesmilo/electrum/issues/7486)
- migrates from aiorpcx 0.18.7 to 0.22.1 (closes https://github.com/spesmilo/electrum/issues/7446)
Re the aiorpcx changes, note that the external API of that [library changed](https://github.com/kyuupichan/aiorpcX/blob/e55950fed903b63e82b87c7b6ca93ab50e18ce08/docs/changelog.rst#version-0201-06-mar-2021).
- Most notable is that when using a TaskGroup in an `async with` statement, exceptions encountered by enclosed tasks are not re-raised in `__aexit__`. Instead, it is now the caller's responsibility to inspect the results and exceptions of the tasks. 
For old code that looks like this:
```python
async with …
```

bump min python to 3.8, and migrate to aiorpcx 0.22

---

electrum/lnpeer.py
electrum/lnworker.py
electrum/tests/test_lnpeer.py
electrum/trampoline.py

~~Based on #7426 (first four commits) and~~ partially fixes #7604, related to #7648.
* Refactored `create_trampoline_route`.
* Enables end-to-end multi-trampoline multipart payments. Trampoline-to-legacy payments are still not enabled, as this is currently not supported by Eclair.
* Reintroduces a global trampoline fee level.

Multi-trampoline multipart payments

---

electrum/ecc.py
electrum/plugins/digitalbitbox/digitalbitbox.py
electrum/tests/test_bitcoin.py

see https://github.com/spesmilo/electrum/issues/3861:
> there is no clear consensus how to sign messages with segwit addresses (txin type of `p2wpkh-p2sh` and `p2wpkh`)
> We do one thing, and Trezor does something else. Bitcoin Core has this disabled.
This PR only changes the signature verification we do:
- the signatures we create are unchanged,
- but we now also accept signatures created by Trezor and others.
closes https://github.com/spesmilo/electrum/issues/3861
closes https://github.com/spesmilo/electrum/issues/7660

signmessage: also accept Trezor-type sigs for p2wpkh and p2wpkh-p2sh addrs

---

electrum/interface.py

This value can be also negative because of an unconfirmed spending transaction.
References:
- https://electrumx-spesmilo.readthedocs.io/en/latest/protocol-methods.html#blockchain-scripthash-get-balance
- https://github.com/spesmilo/electrumx/blob/c8d2cc0d5cf9e549a90ca876d85fed9a90b8c4ed/electrumx/server/session.py#L1133
- https://github.com/spesmilo/electrumx/blob/c8d2cc0d5cf9e549a90ca876d85fed9a90b8c4ed/electrumx/server/mempool.py#L371
- https://github.com/spesmilo/electrum/blob/master/electrum/interface.py#L1023

docs-compliant get_balance method

---

electrum/plugin.py

This is a BUG which causes electrum to load incorrect client for keystores with identical xpub.
Steps to reproduce:
1. create multisig/singlesig wallet with some of your hardware devices
2. create same multisig/singlesig wallet with at least one device different (but with same wallet loaded, in my case I used same seed and derivation path loaded on ledger and coldcard)
3. open 1. in electrum
4. open 2. in electrum but with device from one connected
5. get Attribute error back from specific plugin (depends on which you used, in my case opened wallet with ledger with coldcard connected)
`  AttributeError: 'CKCCClient' object has no attribute 'checkDevice'` --> tried to use LedgerClient methods on CKCCClient
After above error is thrown, your Ledger device, that is not connected will appear …

BUGFIX: invalid client loaded for identical wallet with different HW type

---

contrib/android/Dockerfile
contrib/android/Readme.md
contrib/android/build.sh
contrib/build-linux/appimage/Dockerfile
contrib/build-linux/appimage/README.md
contrib/build-linux/appimage/build.sh
contrib/build-linux/sdist/Dockerfile
contrib/build-linux/sdist/README.md
contrib/build-linux/sdist/build.sh
contrib/build-wine/Dockerfile
contrib/build-wine/README.md
contrib/build-wine/build-electrum-git.sh
contrib/build-wine/build.sh
contrib/build-wine/make_win.sh
contrib/docker_notes.md
contrib/make_libusb.sh

This includes two logically separate changes:
- on the host, try not to require sudo when running the build scripts
- namely when interacting with the docker daemon, this requires the unix user on the host to be part of the `docker` group
- this solves part of https://github.com/spesmilo/electrum/issues/7602
- while running inside the docker containers, do not run as root
- this means that e.g. files created in mounted folders should no longer be owned by root on the host
- there is some code duplication involved here - not sure how it could be deduped.

build: rm need for sudo in most places; and do not run as root

---

electrum/lnpeer.py
electrum/lnwire/peer_wire.csv
electrum/tests/regtest.py
electrum/tests/regtest/regtest.sh
electrum/tests/test_lnpeer.py

This replaces  #7586
I refactored the code in `_shutdown`:
- the fee negotiation is split into smaller functions, reducing the scope of variables.
- the `while` loop logic is condensed in a few lines, so it is easier to understand termination conditions.
- removed code that was never executed

Modern fee negotiation

---

electrum/gui/qt/main_window.py
electrum/lnpeer.py

- rm the `_get_channel_ids` abstraction as each of its usages needs subtle differences.
Some code duplication is preferable in this case.
- raise exceptions in `wait_for_message`, so that callers such as the GUI can show user-feedback
- on_error/on_warning were dropping messages with temp_chan_ids if they were not stored in
`temp_id_to_id` - which was only done once the mapping was known (so the normal chan_id was known).
To fix this, we now store temp_chan_ids into `temp_id_to_id` early.
- `schedule_force_closing` only works if the chan_id is already in `channels`
related:
https://github.com/spesmilo/electrum/pull/7645 (and related commits)
-----
example before commit:
```
D/P | lnpeer.Peer.[LNWallet, 03933884aa-3b53e4ab] | Sending OPEN_CHANNEL
D/P | lnpeer.Peer.[LNWallet, …
```

lnpeer: some rework of error/warning message handling

---

electrum/gui/qt/__init__.py

see https://github.com/spesmilo/electrum/issues/7725
related https://github.com/Electron-Cash/Electron-Cash/pull/1545

qt gui: (maybe fix) opening "Preferences" segfaults on macOS for some

---

electrum/address_synchronizer.py
electrum/submarine_swaps.py
electrum/transaction.py
electrum/wallet.py

Note: this is somewhat inefficient, because we loop over swaps.
This PR adds a new field to PartialTxOutput
set_label has been commented out because it would create dangling labels.

bump fee of swap claim transactions

---

electrum/address_synchronizer.py
electrum/gui/stdio.py
electrum/gui/text.py
electrum/synchronizer.py
electrum/util.py
electrum/verifier.py
electrum/wallet.py

This PR changes `wallet.is_up_to_date()` to consider both the Synchronizer and the Verifier (SPV).
Without this, currently, `wallet.is_up_to_date()` only considers the Synchronizer.
IIRC historically this choice was made to show the wallet balance as early as possible when restoring from seed. At the time, the Synchronizer did not depend on the Verifier at all, so this was reasonable. (obviously the Verifier does depend on the Synchronizer: that's how it gets txs to verify)
However, this is no longer the case, since https://github.com/spesmilo/electrum/commit/9c31c1f970d9bc371ed2dcba26354c71c6ec8756, the wallet only generates new addresses and rolls the gap limit forward after existing addresses have spv-verified confirmed history. That is, the Synchronizer too depends on the Verifier. …

wallet: "up_to_date" to wait for SPV/Verifier

---

electrum/gui/qt/bip39_recovery_dialog.py
electrum/gui/qt/main_window.py
electrum/gui/qt/util.py
electrum/lnworker.py

fixes https://github.com/spesmilo/electrum/issues/7750
`window.run_coroutine_from_thread` no longer uses `wallet.thread`, hence the underlying coroutines are not serialised anymore (they can now run concurrently). Note that this means e.g. the GUI now allows trying to pay multiple LN invoices concurrently.
Also, each task we schedule on `TaskThread` (`wallet.thread`) can provide an optional `cancel` method.
When stopping `TaskThread`, we call this `cancel` method on all tasks in the queue. If the currently running task does not implement `cancel`, `TaskThread.stop` will block until that task finishes.

qt taskthread cleaner shutdown

---

electrum/gui/kivy/main_window.py
electrum/gui/qt/main_window.py

fix typo in warning message shown when enabling lightning

---

contrib/build-linux/appimage/Dockerfile

https://launchpad.net/ubuntu/+source/git/1:2.17.1-1ubuntu0.11
* SECURITY REGRESSION: Previous update was incomplete causing regressions
and not correctly fixing the issue.
- debian/patches/CVE-2022-24765-5.patch: fix safe.directory
key not being checked in setup.c.
- debian/patches/CVE-2022-24765-6.patch:
opt-out of check with safe.directory=* in setup.c. (LP: [#1970260](https://launchpad.net/bugs/1970260))

git update to 2.17.1-1ubuntu0.11 for appimage

---

contrib/build-linux/appimage/make_appimage.sh

should fix https://github.com/spesmilo/electrum/issues/7784
by including commit https://github.com/AppImage/pkg2appimage/commit/1e3ecde6b92ef198405463415b8090a4435d0cb0

build appimage: bump pkg2appimage version

---

electrum/__init__.py
electrum/commands.py
electrum/crypto.py
electrum/daemon.py
electrum/ecc_fast.py
electrum/gui/__init__.py
electrum/gui/kivy/__init__.py
electrum/gui/qt/__init__.py
electrum/plugin.py
electrum/qrscanner.py

This adds a `version_info` CLI/RPC command that returns a dict of versions/paths of dependencies.
This is mostly for debugging purposes. The main motivation is to be able to instruct users who run from source (and encounter issues / report a bug) to run this and provide us with the output.
example:
```
$ ./run_electrum -o version_info
{
"aiohttp.version": "3.8.1",
"aiorpcx.version": "0.22.1",
"certifi.version": "2021.10.08",
"cryptodome.version": null,
"cryptography.path": "/home/user/.local/lib/python3.8/site-packages/cryptography",
"cryptography.version": "3.4.6",
"dnspython.version": "2.2.0",
"electrum.path": "/home/user/wspace/electrum/electrum",
"electrum.version": "4.2.1",
"hidapi.version": "0.11.0.post2",
"libsecp256k1.path": "/home/user/wspace/electrum/electrum/libsecp256k1.so.0", …
```

add `version_info` command

---

electrum/lnutil.py
electrum/lnwatcher.py
electrum/transaction.py

This stops the recursion in `inspect_tx_candidate` at `n==1` if the transaction does not look like a first-level HTLC
fixes #7781

lnwatcher: match witness scripts against HTLC script templates

---

electrum/gui/kivy/main_window.py
electrum/gui/qt/main_window.py
electrum/invoices.py
electrum/paymentrequest.py
electrum/wallet.py
electrum/wallet_db.py

I think this should fix https://github.com/spesmilo/electrum/issues/7777
- the key of outgoing on-chain invoices is redefined to avoid using `TxOutput.__repr__()`
- a wallet_db upgrade is included that rekeys the (outgoing) `invoices` dict accordingly
- `PaymentRequest.get_id()` is removed

wallet_db upgrade: recalc keys of outgoing on-chain invoices

---

electrum/commands.py
electrum/daemon.py
electrum/exchange_rate.py
electrum/gui/kivy/main_window.py
electrum/lnworker.py
electrum/network.py
electrum/sql_db.py
electrum/tests/__init__.py
electrum/tests/test_commands.py
electrum/tests/test_lnpeer.py
electrum/tests/test_lnrouter.py
electrum/tests/test_lntransport.py
electrum/tests/test_network.py
electrum/tests/test_storage_upgrade.py
electrum/tests/test_wallet.py
electrum/tests/test_wallet_vertical.py
electrum/util.py

`asyncio.get_event_loop()` became deprecated in python3.10. (see https://github.com/python/cpython/issues/83710)
```
.../electrum/electrum/daemon.py:470: DeprecationWarning: There is no current event loop
self.asyncio_loop = asyncio.get_event_loop()
.../electrum/electrum/network.py:276: DeprecationWarning: There is no current event loop
self.asyncio_loop = asyncio.get_event_loop()
```
Also, according to that thread, "set_event_loop() [... is] not deprecated by oversight".
So, we stop using `get_event_loop()` and `set_event_loop()` in our own code.
Note that libraries we use (such as the stdlib for python <3.10), might call `get_event_loop`,
which then relies on us having called `set_event_loop` e.g. for the GUI thread. To work around
this, a custom event loop policy providing a …

asyncio: stop using get_event_loop(). introduce ~singleton loop.

---

electrum/_vendor/distutils/LICENSE
electrum/_vendor/distutils/__init__.py
electrum/_vendor/distutils/version.py
electrum/gui/qt/update_checker.py

[`distutils`](https://github.com/python/cpython/tree/9d38120e335357a3b294277fd5eff0a10e46e043/Lib/distutils) (a module in the python standard library that we use) got deprecated in python 3.10,
and is [planned to be removed](https://github.com/python/cpython/blob/9d38120e335357a3b294277fd5eff0a10e46e043/Lib/distutils/__init__.py#L16) from the stdlib in python 3.12.
We only use it in the Qt `update_checker` (for signed version notifications), to compare version numbers.
That is, we only use a very small part of it (only `distutils.version.StrictVersion`).
```
.../electrum/electrum/gui/qt/update_checker.py:7: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
from distutils.version import …
```

vendor a part of `distutils`, to be removed from stdlib in py3.12

---

electrum/address_synchronizer.py
electrum/wallet.py

It does not make sense to count change outputs in our unconfirmed balance,
because our balance will not be negatively affected if the transaction does
not get confirmed.
It is also incorrect to add signed values of get_addr_balance in order to compute
the balance over a domain. For example, this leads to incoming and outgoing
transactions cancelling out in our total unconfirmed balance.
This commit looks at the coins that are spent by a transaction. If those
coins belong to us and are confirmed, we do not count the transaction outputs
in our unconfirmed balance.
As a result, get_balance always returns positive values for unconfirmed balance.

Change the semantics of get_balance:

---

electrum/gui/qt/main_window.py

Added a simple button to allow the user to get a message signature just by scanning a QR code and not copying it by hand to another device.

Show message signature as QR code

---

electrum/lnworker.py
electrum/tests/test_lnpeer.py

follow-up to https://github.com/spesmilo/electrum/pull/7818
- note it matters whether a sender pays us end-to-end-trampoline or just via legacy
- consider: Alice has 0.1 BTC recv cap in chan1 and 1 BTC recv cap in chan2, both with border-node T1
- if sender is paying e2e trampoline, it can realistically pay even ~1.1 BTC, as T1 can resplit the HTLCs
- if sender is paying legacy, it will have a hard time trying to pay more than 1 BTC, in practice
- although note if T1 has implemented non-strict-forwarding (see BOLT-04), achieving 1 BTC is easy,
as T1 can redirect HTLCs (but cannot split them, in this case)
- to make num_sats_can_receive realistic, it assumes the legacy case
- To calc num_sats_can_receive, we sort our channels in decreasing order of receive-capacities, iterate over them
and …

lnworker: rework num_sats_can_receive and routing_hints_for_invoice

---

electrum/gui/kivy/uix/dialogs/lightning_channels.py
electrum/gui/qt/channels_list.py
electrum/lnchannel.py
electrum/lnpeer.py
electrum/lnworker.py

The `WE_ARE_TOXIC` state is added as a sanity check to ensure that if
the remote has proven that we have lost state we do not accidentally
do a local force-close. E.g. if we receive an "error" message for the
channel, we might normally do an automatic force-close. Manually
force-closing in such a state is not offered anymore by the GUI.
The `REQUESTED_FCLOSE` state is added as it is quite likely that
we receive an error message from the remote after requesting a fclose,
e.g. during a later chan-reestablish. In such a scenario, we should
not do an auto-local-fclose, however the manual option of a local-fclose
should still be offered.

lnchannel: add new states: `WE_ARE_TOXIC`, `REQUESTED_FCLOSE`

---

electrum/address_synchronizer.py
electrum/daemon.py
electrum/exchange_rate.py
electrum/gui/kivy/main_window.py
electrum/gui/qt/__init__.py
electrum/gui/qt/channel_details.py
electrum/gui/qt/lightning_dialog.py
electrum/gui/qt/main_window.py
electrum/gui/qt/network_dialog.py
electrum/gui/qt/settings_dialog.py
electrum/gui/qt/util.py
electrum/gui/stdio.py
electrum/gui/text.py
electrum/lnwatcher.py
electrum/lnworker.py
electrum/tests/test_lnpeer.py
electrum/util.py
electrum/wallet.py

This is a refactoring of callbacks in `util.py.` Event listeners must be methods of the EventListener class, and named `'on_event_' + event_name`
It is still a draft, a few things need to be decided:
1. We could add a `@event_listener` decorator to all event listeners, that does nothing but asserts their name starts with `on_event_`, for pedagogic purposes.
2. Alternatively, we could allow arbitrary names, and add a decorator that takes the event's name as parameter.
3. We could try to add a filtering option to the decorator (to avoid starting methods with `if self.wallet != wallet: return`). Not sure if it can be done in a way that removes the current quadratic complexity ("everyone listens to everyone")
4. I am not sure to understand how `QNetworkUpdatedSignalObject` worked before this …

EventListener class to handle callbacks

---

electrum/gui/qt/__init__.py
electrum/gui/qt/confirm_tx_dialog.py
electrum/gui/qt/invoice_list.py
electrum/gui/qt/main_window.py
electrum/gui/qt/paytoedit.py
electrum/gui/qt/send_tab.py
electrum/gui/qt/transaction_dialog.py

Re the Qt GUI, this splits the "Send tab" out from main_window.py,
in hope of better encapsulation and to make main_window.py shorter.
It is mostly move-only.
@ecdsa feel free to check which methods are moved, but no need to review for functional correctness.

qt: (refactor) split "send tab" out from main_window.py

---

electrum/lnutil.py
electrum/trampoline.py

This PR uses the same temporary bits as Eclair (148/149).
The reason why we did not use the same bits as Eclair last time (50/51) was to prevent ACINQ attempting pay-to-open with Electrum clients. I suppose it is fine now.

update trampoline feature bits. fixes #7801

---

electrum/wallet.py

There is some duplication between `wallet.get_onchain_request_status` and `wallet.is_onchain_invoice_paid`
(both in terms of code, and conceptually). `get_onchain_request_status` is used for incoming invoices (receive requests),
and `is_onchain_invoice_paid` is used for outgoing invoices. I think `get_onchain_request_status` existed first,
but as it uses txi/txo, it only works for ismine addresses, so `is_onchain_invoice_paid` was added later
(along with a `get_prevouts_by_scripthash` and corresponding new persisted data structure) to handle the non-ismine
addresses corresponding to outgoing invoices.
I think we could just merge the two functions together... (?)
and this PR does that.

wallet: rm get_onchain_request_status; just use is_onchain_invoice_paid

---

contrib/build-linux/appimage/Dockerfile
contrib/build-wine/Dockerfile

appimage: update libssl-dev libssl1.1 openssl
https://launchpad.net/ubuntu/+source/openssl/1.1.1-1ubuntu2.1~18.04.20
Windows image: update gnupg2 dirmngr
https://packages.ubuntu.com/en/focal-updates/utils/dirmngr
https://packages.ubuntu.com/en/focal-updates/gnupg2

Update windows and appimage

---

electrum/lnworker.py

- for an onchain backups, if the channel is with a
hardcoded trampoline, try first without gossip DB.
- for imported backups, fallback to gossip DB if we
fail to connect with the provided network address.

Improve request_force_close_from_backup

---

electrum/network.py

Fixes: https://github.com/spesmilo/electrum/issues/5815 (_No connection error message could be more clear_)
This has been a topic in Bitcointalk and some users think that the message should be more understandable for the end-users.
Reference: [https://bitcointalk.org/index.php?topic=5129190.msg60586747#msg60586747](url)

Update "No Connection" error to be user-friendly

---

electrum/gui/qt/receive_tab.py
electrum/gui/qt/util.py

QTabWidget with "West" tab pos and horizontal text looks completely broken on macOS
(despite looking good on e.g. Ubuntu GNOME and Windows).
The alternative here looks ok on all three OSes.
Instead of using QTabWidget with "west" tabs, and hacking the tab text to be horizontal;
this is using QTabWidget with default "north" tabs, but with the north tabs hidden and instead with our own vertical-box of push-buttons added on the left. 
fixes https://github.com/spesmilo/electrum/issues/7908
-----
<details>
<summary>macOS pics</summary>
</details>
<details>
<summary>Ubuntu GNOME pics</summary>
</details>
<details>
<summary>Windows pics</summary>
</details>

Qt receive_tab: fix receive_tabs widget on macOS

---

contrib/build-linux/appimage/make_appimage.sh
contrib/build-wine/build-electrum-git.sh
contrib/build-wine/prepare-wine.sh
contrib/osx/make_osx

When running `pip install` for packages that will get downloaded from PyPI, pip by default prefers wheels, in fact binary wheels.
Obviously it would be better for us not to rely on pre-built binaries from PyPI.
- mac build: force using source dists for most of our python dependencies
- we compile from those ourselves when needed
- windows build: there is no C compiler available in the wine environment atm, so not a lot can be done
- but for `requirements.txt` at least, we enforce getting the sdists, as that list only contains "pure python" deps
- (though aiohttp and friends have optional C extensions, we now opt-out of them)

mac/win build: `pip install --no-binary :all:` in more places

---

electrum/lnworker.py

Previously lnworker called LNWatcher.add_channel() on these, and then LNWatcher itself decided to unwatch them.
-----
note: motivation related to https://github.com/spesmilo/electrum/pull/7932#discussion_r945755584 ,
where I have legacy (pre-staticremotekey) redeemed channels in a wallet.

lnwatcher: don't add `REDEEMED` channels

---

.cirrus.yml
contrib/build-linux/sdist/build.sh
contrib/build-linux/sdist/make_sdist.sh
contrib/build_locale.sh
contrib/generate_payreqpb2.sh
contrib/release.sh
electrum/paymentrequest.py

This PR adds a series of changes that are necessary to produce "clean" tarballs, without generated files, dependencies, etc.
To `make_sdist.sh`, three options (passed by environment variable) are added:
* `NO_INSTALL_PACKAGES` (do not run the scripts for installation of packages)
* `NO_BUILD_LOCALE` (omit the compiled locale files)
* `OMIT_PB2_GENERATED` (omit the file `paymentrequest_pb2.py`)
By default, nothing changes. If the options are unset, `make_sdist.sh` behaves exactly as before. This is all opt-in.
There is also a slight refactor of the same script, where some locale generation code moves into `contrib/build_locale.sh`. This is necessary to be able to invoke this script separately, e.g. after unpacking a tarball.
Finally, a script is added to generate the file …

Produce packager-friendly tarballs

---

electrum/exchange_rate.py
electrum/tests/test_wallet.py

We poll the fx rate provider every 2.5 minutes (unchanged).
Previously if there was any error during a tick, there would be no fx rate
available in the client until the next tick.
Now, instead, we keep the last rates received with a 10 minute expiry.
One potential drawback is that previously there was instant feedback
to the user when e.g. changing proxy settings, and this is no longer
the case. E.g. consider a provider that bans Tor exit nodes. If a user
enables using a Tor proxy in the network settings, the fxrate used to
disappear immediately - but now the cached rate would still be
available.

exchange_rate: more robust spot price against temporary network issues

---

electrum/commands.py
electrum/gui/kivy/uix/screens.py
electrum/gui/qml/qeinvoice.py
electrum/gui/qt/invoice_list.py
electrum/gui/qt/request_list.py
electrum/gui/qt/send_tab.py
electrum/gui/text.py
electrum/invoices.py
electrum/lnworker.py
electrum/wallet.py
electrum/wallet_db.py

Do not index requests by address.
Instead, use the same get_id method as for invoices.
wallet: in `create_request`, reuse use addresses of expired requests (fixes  #7927)
Separate `wallet.get_request` and `wallet.get_request_by_addr,` which takes an address
Note that expired requests in` wallet._requests_addr_to_key` get overwritten when a new one is added

Do not index request by receiving address

---

contrib/build-linux/appimage/make_appimage.sh
contrib/osx/README.md
contrib/osx/make_osx

Commit https://github.com/spesmilo/electrum/commit/0c2a885c66d6c8e6c7aff1b1822b27341d4946db from https://github.com/spesmilo/electrum/pull/7918 was reverted in https://github.com/spesmilo/electrum/commit/019d213325312badc55d95a6cabc6278dda47a8a.
I intend to re-add that commit -- this PR is here to experiment, and so that we don't forget.

mac build: `pip install --no-binary :all:` in more places (take 2)

---

contrib/build-wine/Dockerfile
contrib/build-wine/apt.preferences
contrib/build-wine/apt.sources.list
contrib/build-wine/make_win.sh
contrib/freeze_containers_distro.sh

This reverts commit b8240bec3ef531167c794e48453770fc9ac63e4e.
Looks like the win-iconv build is not deterministic...
Reverting this for now, will have to debug later.

 Revert "wine build: build win-iconv-mingw, instead of using debian sid"

---

electrum/gui/kivy/main_window.py
electrum/gui/qml/qeinvoicelistmodel.py
electrum/gui/qml/qewallet.py
electrum/gui/qt/main_window.py
electrum/lnworker.py

This patch adds the invoice status to the `invoice_status` callback;
1) analog to `request_status` callback
2) all consumers of the callback do the `wallet.get_invoice_status(wallet.get_invoice(key))` dance anyway
There's some commented lines in this patch, and some logging, to makes this patch easier to review (will clean up after review).
Also, I've made one assumption here, the `PR_INFLIGHT` status in the `lnworker.pay_to_node()` route loop. As far as I can see, there's no code path that sets a different status while in this loop. If this assumption is incorrrect, we can retrieve the current status from `self.get_invoice_status()` at this point.

add invoice status to invoice_status callback

---

electrum/simple_config.py

Change the logging message displayed when the config file can't be
parsed: include the underlying exception text, so that a user who is
attepting to edit the config manually can find and fix any errors.

make it easier to troubleshoot config parse errors

---

.gitattributes

This should prevent accidentally committing files with CRLF line endings to the repo.
related: https://github.com/spesmilo/electrum/issues/8025
see https://git-scm.com/docs/gitattributes#_end_of_line_conversion :
> If you want to ensure that text files that any contributor introduces to the repository have their line endings normalized, you can set the text attribute to "auto" for all files.
> ```
> * text=auto
> ```
>
> From a clean working directory:
> ```
> $ echo "* text=auto" >.gitattributes
> $ git add --renormalize .
> $ git status    # Show files that will be normalized
> $ git commit -m "Introduce end-of-line normalization"
> ```
-----
I have tried to find some large cross-platform projects that use git for EOL normalisation. Notably the golang/go project recommends against it, …

add .gitattributes file for end-of-line normalisation

---

electrum/commands.py

$ ./run_electrum --testnet getinfo
{
"auto_connect": true,
"blockchain_height": 2378672,
"connected": true,
"default_wallet": "/home/user/.electrum/testnet/wallets/default_wallet",
"fee_per_kb": 1000,
"network": "testnet",
"path": "/home/user/.electrum/testnet",
"server": "testnet.server.org",
"server_height": 2378672,
"spv_nodes": 7,
"version": "4.3.2"
}

add network name to getinfo()

---

contrib/build-wine/Dockerfile
contrib/build-wine/build-electrum-git.sh
contrib/build-wine/electrum.nsi
contrib/build-wine/prepare-wine.sh

closes #8051 
executables are built in CI, but cannot test a.t.m.

use debian makensis instead of windows makensis executable through wine

---

electrum/plugins/trezor/trezor.py

Since Electrum is not using TxRequestSerializedType.serialized_tx we might ask the device not to serialize transactions by setting SignTx.serialize=False
The trezorlib requirement is bumped to 0.13.4, since that's the version when SignTx.serialize field appeared for the first time.

trezor: optimize signing speed by not serializing transaction in trezor

---

electrum/wallet.py

This pull request adds a new field, `tx_hashes` to payment requests output
This is useful to know which transactions were used to pay an invoice.
It should work as it relies on existing logic, the only question is: are payments via lightning network to be included here too somehow?
P.S. Failing LN tests in CI are obviously flaky and not caused by this PR

Add `tx_hashes` to exported payment requests

---

electrum/gui/qt/qrcodewidget.py
electrum/gui/qt/receive_tab.py

fixes https://github.com/spesmilo/electrum/issues/8071
This was a regression from 2a31f80d0962197780a2f45c279c83236051e4de, before which, when using the default `QRCodeWidget()` constructor, there had been a min size set on the widget. I like that old behaviour: reasonable size should be set by default, and if you want to set the size manually, opt-in to that.

qt wizard: (fix) during 2fa wallet creation, shared QR to be drawn

---

electrum/servers.json

I migrated from bitcoin.lukechilds.co to bitcoin.lu.ke. I'll keep the old domain up so old versions of electrum still work but it would be great if newer releases use this address.

Update @lukechilds server address

---

.cirrus.yml
contrib/build_tools_util.sh

"AppImage build" on the CI is failing with "Container errored with 'OOMKilled'" since 65ae2811809315c48ecc1eb9ae2fa52d9a72a252:
- https://cirrus-ci.com/task/6506466559918080
- https://cirrus-ci.com/task/6518283422662656
Apparently, when running in a Cirrus CI container, `nproc` returns the number of host CPUs, instead of the number of cpus available to the container. Opened upstream issue: https://github.com/cirruslabs/cirrus-ci-docs/issues/1115

CI: AppImage build is failing with `Container errored with 'OOMKilled'`

---

electrum/commands.py
electrum/exchange_rate.py

This adds command convert_currency which allows command line and RPC users to access the currency conversions already existing in Electrum.

Add command for currency conversions

---

electrum/logging.py

In the past we decided not to put a timestamp into the stderr logs
to have shorter log lines (to save column width in a terminal).
However over time I at least have found that it would be valuable
to have timestamps also in the stderr - e.g. when users provide logs.
Often I am only interested in the time taken between logged events,
so as a compromise to still save some length, I propose adding relative
timestamps (relative to process startup time).
Compare these log lines from the file logger:
```
20220816T120601.882003Z |     INFO | gui.qt.ElectrumGui | starting Qt main loop
20220816T120601.905619Z |     INFO | gui.qt.history_list.HistoryModel | refreshing... reason: update_tabs
20220816T120601.911908Z |    DEBUG | util.profiler | Abstract_Wallet.get_full_history 0.0059 sec …
```

logging: add a relative timestamp to stderr console logs

---

electrum/gui/qt/main_window.py

Same change like it was for this line: electrum/gui/qt/main_window.py:343 (see commit 019566b383cf3852897010ddce3e110f4f45e571).

use placeholder for better translation

---

electrum/gui/qt/settings_dialog.py

This updates the balance in the status bar when the preference "Zeros after decimal point" is changed.

Update status bar when preference "Zeros after decimal point" is changed

---

electrum/wallet.py

Before the PR, if you paid an invoice partially, it would return status unpaid and an empty list of `tx_hashes`
Now it allows to inspect the list of tx hashes even for partial payments

Return list of tx hashes for partially paid invoices too

---

org.electrum.electrum.metainfo.xml

AppStream metainfo.xml files are like extended .desktop files used to populate app stores with information about GUI applications.  Debian and Ubunto and other major Linux distributions are starting to push for their inclusions.  This is a fairly minimal example that just covers the required entries.  The text for the description is a slightly modified version of text taken from Electrum's FAQ.
Metainfo files can contain links to screenshots.  I have not included any here, but that might be something someone would like to add in the future.

Add an AppStream metainfo.xml file

---

electrum/gui/qt/address_list.py
electrum/gui/qt/utxo_list.py

This RP attempts to fix #8155 by replacing "Spend from" context menu option with "Add to coin control"/"Remove from coin control" options, similar to how it is done in UTXO list.

fix adding coins to coincontrol from address list (fixes #8155)

---

.cirrus.yml

Tasks recently started spuriously getting killed with "Container errored with 'OOMKilled'". Not sure what changed, but this seems like the easiest fix.

CI: bump available memory for unit tests (1G->2G)

---

electrum/gui/qt/confirm_tx_dialog.py
electrum/gui/qt/fee_slider.py
electrum/gui/qt/locktimeedit.py
electrum/gui/qt/main_window.py
electrum/gui/qt/rbf_dialog.py
electrum/gui/qt/send_tab.py
electrum/gui/qt/settings_dialog.py
electrum/gui/qt/transaction_dialog.py
electrum/wallet.py

- transaction_dialog is read-only
- ConfirmTxDialog and RBF dialogs inherit from TxEditor
- TxEditors are configurable

Qt: new onchain tx creation flow:

---

electrum/address_synchronizer.py
electrum/gui/qt/main_window.py
electrum/gui/qt/utxo_dialog.py
electrum/gui/qt/utxo_list.py
electrum/wallet.py

I have decided not to display the list of parent labels in the `utxo` tab, because it was getting too crowded. 
Only the direct parent tx label is displayed, as it was the case before (note that I dropped the `get_label_for_address` fallback).
The number of parents is displayed in a new column of the `utxo` tab, and it already a good indicator of privacy.
For now, `get_tx_parents` only does what its name says: it returns parents, and it does not consider address reuse.
The reason is that results need to be cached, and caching becomes complicated if we include address reuse to the analysis.
After a reverse swap, the number of parents is displayed 2, then it goes down to 1 once the swap funding address is dropped by `lnwatcher`. This is weird, and should probably be addressed. I suppose the …

Privacy analysis

---

electrum/address_synchronizer.py
electrum/commands.py
electrum/gui/kivy/uix/dialogs/tx_dialog.py
electrum/gui/qml/qetransactionlistmodel.py
electrum/gui/qml/qetxdetails.py
electrum/gui/qml/qetxfinalizer.py
electrum/gui/qt/main_window.py
electrum/gui/qt/rate_limiter.py
electrum/gui/qt/transaction_dialog.py
electrum/tests/test_wallet_vertical.py
electrum/transaction.py
electrum/wallet.py

See commit messages for the individual commits.
-----
Re the Qt tx dialog, here are some pics for tx `eec306392190ddf956c3a233c764ef17fa4ded81540de9e3e8565ab7edd755df`:
<details>
<summary>pics</summary>
</details>

split out network reqs from `wallet.add_input_info`, and add "Download input data" cb in qt tx dlg

---

electrum/gui/qt/main_window.py
electrum/wallet_db.py

Store the electrum version used to create a wallet file and a timestamp, in the file itself. This can be useful for debugging.

Store file creation date and version in db

---

electrum/lnutil.py

In the binary serialised format, replace all instances of int16 with uint16. In particular, this allows port>32767.
Fixes https://github.com/spesmilo/electrum/issues/8264
I think this is backwards compatible, as in, any existing channel backup already out there, should be properly parsed with the new code. (new code however can serialise cbs that old code deserialises incorrectly)
```
>>> struct.pack('<h', 258)
b'\x02\x01'
>>> struct.pack('<H', 258)
b'\x02\x01'
```

lnutil.ImportedChannelBackupStorage: change ser format: int16->uint16

---

.gitignore
contrib/android/Dockerfile
contrib/android/build.sh
contrib/build-linux/appimage/.dockerignore
contrib/build-linux/appimage/Dockerfile
contrib/build-linux/appimage/build.sh
contrib/build-linux/sdist/.dockerignore
contrib/build-linux/sdist/Dockerfile
contrib/build-linux/sdist/build.sh
contrib/build-wine/.dockerignore
contrib/build-wine/Dockerfile
contrib/build-wine/build.sh

closes https://github.com/spesmilo/electrum/issues/8261
See commit messages for individual commits.
In short, we distinguish "local dev builds" and "reproducible builds":
- local dev builds use the host userid inside the container, directly operate on the project dir
- do not need sudo
- repro builds create a fresh git clone, chown it to 1000, and use userid=1000 inside the container
- if the host userid is 1000, do not need sudo
- otherwise, need sudo

build: docker scripts to work even if host user id != 1000

---

electrum/gui/qml/components/Pin.qml
electrum/gui/qml/components/controls/ElDialog.qml
electrum/gui/qml/components/main.qml

Pressing "Esc" on kivy when testing on desktop closes the active popup/dialog/window/application, similar to what pressing the hw/OS "back" button on Android would do.
I want the same behaviour on qml, as it makes testing more convenient.
This change seems to work; and it seems not to break Android either.
The `Popup.CloseOnEscape` modifiers need to be removed as they are catching the signal before it could get to the application-level `Shortcut`, and if I leave them in, one needs to press Esc multiple times to trigger.

qml: pressing "Esc" on desktop to ~simulate "back" button

---

electrum/ecc_fast.py

FreeBSD installs libsecp256k1 as:
```
/usr/local/lib/libsecp256k1.so.2.0.1
/usr/local/lib/libsecp256k1.so -> libsecp256k1.so.2.0.1
/usr/local/lib/libsecp256k1.so.2 -> libsecp256k1.so.2.0.1
```

fix: Fix libsecp256k1 loader on FreeBSD

---

electrum/gui/qt/rbf_dialog.py

`wallet.bump_fee()` only allows targeting a feerate.
Prior to this commit, `_BaseRBFDialog(TxEditor)` allowed setting either a feerate or an abs fee. When setting an abs fee, `TxEditor.update_fee_fields()` tries to adjust the feerate accordingly, and then via side-effecting, `wallet.bump_fee()` will get called with the derived feerate. This seems really buggy[0] atm. I think it is best to disable setting abs fees, and if we want to enable it later, targeting needs to be implemented in `wallet.bump_fee()` - just like how it works in `ConfirmTxDialog(TxEditor)` and `wallet.make_unsigned_transaction()`.
[0]: due to how the side-effecting works, changing the abs fee only affects the actual tx created one tick later.
Errors are sticky: try setting the abs fee to zero and then to something …

qt bump fee: disallow targeting an abs fee. only allow setting feerate

---

README.md

We don't actually need the development headers, instead using this as a hack to be agnostic to the version scheme and pull in the latest.
related:
https://github.com/spesmilo/electrum/issues/8328#issuecomment-1518061250
https://github.com/spesmilo/electrum/pull/8185
https://github.com/spesmilo/electrum/pull/8320
- debian 11 (stable) only has `libsecp256k1-0`
- debian 12 (testing) atm only has `libsecp256k1-1`
- ubuntu 23.04 only has `libsecp256k1-1`
- I expect `libsecp256k1-2` might soon get packaged too, now that upstream libsecp256k1 [released v0.3.0](https://github.com/bitcoin-core/secp256k1/blob/1f33bb2b1c5e65cab5720a174b15c499d99b1cfc/CHANGELOG.md).
So what do we tell users to install? well, turns out most distros have `libsecp256k1-dev`, which just pulls in the latest secp.
Caveat: …

README: refer to `libsecp256k1-dev` instead of `libsecp256k1-0`

---

electrum/gui/qml/qewallet.py
electrum/gui/qml/qewalletdb.py

This is hugely hackish -- it uses the kivy approach, which uses this same hack...
I am not really content with it but it should be relatively easy to review, and if ok, should hotfix the linked issue.
fixes https://github.com/spesmilo/electrum/issues/8374
related https://github.com/spesmilo/electrum/pull/8382

qml: always ask for the password on wallet-open, even for ks-enc-only wallets

---

electrum/gui/qml/components/main.qml
electrum/gui/qml/qedaemon.py
electrum/gui/qml/qewalletdb.py
electrum/gui/qt/__init__.py
electrum/util.py
electrum/wallet.py
electrum/wallet_db.py

- case 1: in version 4.4.1, 4.4.2, the qml GUI wizard allowed creating multisig wallets with an old_mpk as cosigner.
- case 2: in version 4.4.0, 4.4.1, 4.4.2, the qml GUI wizard allowed creating multisig wallets with mixed xpub/Ypub/Zpub.
The corresponding missing input validation was a bug in the wizard, it was unintended behaviour. Validation was added in d2cf21fc2bcf79f07b7e41178cd3e4ca9e3d9f68. Note however that there might be users who created such wallet files.
Re case 1 wallet files: there is no version of Electrum that allows spending from such a wallet. Coins received at addresses are not burned, however it is technically challenging to spend them. (unless the multisig can spend without needing the old_mpk cosigner in the quorum).
Re case 2 wallet files: it is possible to create …

wallet_db version 52: break non-homogeneous multisig wallets

---

electrum/util.py

[3xpl](https://3xpl.com/bitcoin) is fast, private, its core is open-source (MIT license), and, most importantly, there are no ads.
It also supports Omni Layer.

Add 3xpl.com to the list of explorers

---

electrum/gui/qt/address_list.py

As reported in #8469, in v4.4.4, sorting on the FIAT_BALANCE column of the Address list window is done with amounts considered as text.
This PR  `setData` on the FIAT_BALANCE column with the numerical value so that sorting works as expected

:bug: fix #8469 - fiat balance sorting in address list window

---

electrum/gui/qt/main_window.py
electrum/gui/qt/my_treeview.py
electrum/gui/qt/transaction_dialog.py
electrum/simple_config.py

I've been frustrated when copying btc/fiat values from the different windows into other software. Copied amounts contain _thousand separator spaces_ (if the option is set in config) and most other software do not cope well with this format.
From contextual menus, when copying data from a numerical column, spaces are removed.
Let me know if this should be handled in a different manner

:sparkles: remove thousand separator when copying numbers to clipboard

---

electrum/gui/kivy/uix/dialogs/fx_dialog.py

Kivy fiat rates are broken after merging these 2 commits:
https://github.com/spesmilo/electrum/commit/503776c0dee2a544c0d746e9b853f29fe0b54279
https://github.com/spesmilo/electrum/commit/24980feab71957df05b1e55f72fbb7dc8cf34036

kivy: fix fx history rates

---

electrum/gui/qml/components/AddressDetails.qml
electrum/gui/qml/qeaddressdetails.py

Only single private key still, no multiple private keys when multiple keystores with secrets present.

qml: initial show private key in address details

---

electrum/plugins/hw_wallet/qt.py

Error message:
```
Aucun périphérique matériel détecté.
Pour déclencher un nouveau scan, pressez 'Suivant'.
Sur Linux, vous pouvez avoir à ajouter une nouvelle permission à vos règles udev.
Message de débogage
bitbox02: (error during plugin init)
Vous avez peut-être une bibliothèque incompatible.
Error loading bitbox02 plugin: ImportError("cannot import name 'parse_URI' from 'electrum.util' (/Users/satochip/Documents/github/electrum-satochip/dist/Electrum.app/Contents/MacOS/electrum/util.pyc)")
coldcard: (error during plugin init)
Vous avez peut-être une bibliothèque incompatible.
Error loading coldcard plugin: ImportError("cannot import name 'parse_URI' from 'electrum.util' (/Users/satochip/Documents/github/electrum-satochip/dist/Electrum.app/Contents/MacOS/electrum/util.pyc)") …
```

Patch error caused by the method "parse_URI()" being moved to bip21.py and renamed "parse_bip21_URI"

---

electrum/plugins/jade/jade.py
run_electrum

Allows use with DIY Jade + Camera based on common, low cost boards like those based on ESP32-Wrover and ESP32-CAM.

Add Vendor/Device IDs for CH340 based DIY Jade devices.

---

electrum/lnchannel.py
electrum/lnsweep.py
electrum/lnutil.py
electrum/lnworker.py
electrum/tests/regtest.py
electrum/tests/regtest/regtest.sh
electrum/tests/test_lnutil.py

scenario:
- user opens a lightning channel and exports an "imported channel backup"
- user closes channel via local-force-close
- local ctx is published, to_local output has user's funds and they are CSV-locked for days
- user restores wallet file from seed and imports channel backup
- new wallet file should be able to sweep coins from to_local output (after CSV expires)
This was not working previously, as the local_payment_basepoint was not included in the
imported channel backups, and the code was interpreting the lack of this as the channel not
having option_static_remotekey enabled. This resulted in lnutil.extract_ctn_from_tx
using an incorrect funder_payment_basepoint, and lnsweep not recognising the ctx due to
the garbage ctn value.
The imported channel backup serialisation format …

fix sweeping chan after local force-close using cb

---

contrib/requirements/requirements.txt
electrum/gui/kivy/uix/screens.py
electrum/gui/qml/qeinvoice.py
electrum/gui/text.py
electrum/invoices.py
electrum/payment_identifier.py
electrum/tests/test_invoices.py
electrum/wallet_db.py

- `@amount_msat.validator` prevents the creation of invoices with e.g. too large amounts
- however the qml gui is mutating invoices by directly setting the `amount_msat` field, and it looks like attrs validators only run during init. We can use `on_setattr` (introduced in attrs==20.1.0).
- a wallet db upgrade is added to rm existing insane invoices
btw the qml gui was already doing its own input validation on the textedit (see qeconfig.btcAmountRegex). However that only limits the input to not have more chars than what is needed to represent 21M BTC (e.g. you can still enter 99M BTC, which the invoice logic does not tolerate later on - but is normally caught).
fixes https://github.com/spesmilo/electrum/issues/8582

invoices: also run amount-validator on setter

---

electrum/bitcoin.py
electrum/gui/qml/qechannelopener.py
electrum/gui/qml/qeswaphelper.py
electrum/gui/qt/confirm_tx_dialog.py
electrum/gui/qt/main_window.py
electrum/gui/qt/send_tab.py
electrum/gui/qt/swap_dialog.py
electrum/gui/qt/transaction_dialog.py
electrum/lnpeer.py
electrum/lnworker.py
electrum/network.py
electrum/submarine_swaps.py
electrum/tests/test_wallet_vertical.py
electrum/transaction.py
electrum/util.py
electrum/wallet.py

Somewhat a follow-up to 649ce979abfeb18a285dec792d455ecf137c6382.
This adds some safety belts so we don't accidentally sign a tx that contains a dummy address. I strongly think we should have something along these lines, to guard against future programming errors.
Specifically we check that tx does not contain output for dummy addr:
- in wallet.sign_transaction
- in network.broadcast_transaction
The second one is perhaps redundant, but I think it does not hurt.

add sanity checks we don't sign tx including dummy addr

---

electrum/gui/messages.py
electrum/gui/qt/address_list.py
electrum/gui/qt/confirm_tx_dialog.py
electrum/gui/qt/history_list.py
electrum/gui/qt/my_treeview.py
electrum/gui/qt/new_channel_dialog.py
electrum/gui/qt/receive_tab.py
electrum/gui/qt/settings_dialog.py
electrum/gui/qt/swap_dialog.py
electrum/gui/qt/transaction_dialog.py
electrum/gui/qt/util.py
electrum/simple_config.py

related to https://github.com/spesmilo/electrum/issues/8542#issuecomment-1641780165 :
> We recently restructured config variables, and they are now listed in simple_config.py (they used to be scattered around in the code). Maybe we could pass a helpstring to ConfigVar, and make it visible from command line
This PR moves the tooltips into the ConfigVars - but they are not exposed to the CLI yet.
Note that many configvars are missing tooltips - I did not write new ones, only moved existing ones around.
This is because they are either only indirectly exposed to the GUI or not exposed at all.

config: move tooltips from Qt gui into configvars

---

electrum/bip39_wallet_formats.json

bip39: add likely script vs derivation path mistakes for BIP49 and BIP84 paths. See e.g.
https://bitcointalk.org/index.php?topic=5454270.0

bip39: add likely script vs derivation path mistakes

---

electrum/commands.py
electrum/daemon.py
electrum/gui/qml/qewalletdb.py
electrum/gui/qt/__init__.py
electrum/gui/qt/wizard/wallet.py
electrum/json_db.py
electrum/lnwatcher.py
electrum/tests/test_storage_upgrade.py
electrum/tests/test_wallet.py
electrum/tests/test_wallet_vertical.py
electrum/wallet.py
electrum/wallet_db.py
electrum/wizard.py
run_electrum

This separates the `WalletDB` class from the class doing database upgrades.
The main reason for this change is to fix the type of the `data` field in `WalletDB`: on master, it starts as a `dict` during init/upgrades, then becomes a `StoredDict`

Jsondb cleanup

---

contrib/requirements/requirements.txt
electrum/gui/qt/console.py
electrum/gui/qt/main_window.py
electrum/json_db.py
electrum/lnpeer.py
electrum/storage.py
electrum/wallet.py

- partial writes are append only.
- StoredDict objects will append partial writes to the wallet file when items are added, replaced, removed.
- Lists in the wallet file that have not been registered as StoredObject are converted to StoredList, which overloads append() and remove(). Those methods too will append partial writes to the wallet file.
- Unlike the old jsonpatch branch, this branch does not support file encryption. Encrypted files always fully rewritten, even if the change before encryption is a partial write.
related: https://github.com/spesmilo/electrum/issues/4823

partial-writes using jsonpatch

---

electrum/gui/text.py

Today the text GUI crashes when you create an invoice (Receive tab): 
```
$ ./build/electrum gui -g text
/tmp/electrum/./build/electrum:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
__import__('pkg_resources').require('Electrum==4.4.6')
Password:
14.19 | E | daemon.Daemon | GUI raised exception: AttributeError("'Request' object has no attribute 'lightning_invoice'"). shutting down.
15.03 | E | __main__ | daemon.run_gui errored
File "/tmp/electrum/electrum/electrum", line 456, in handle_cmd
d.run_gui()
File "/tmp/electrum/electrum/daemon.py", line 625, in run_gui
self.gui_object.main()
File "/tmp/electrum/electrum/gui/text.py", line 528, in main
self.run_tab(2, …
```

fix recv for text gui

---

.cirrus.yml

These linter warnings were all fixed in 312f2641e7284dc9ed7bde99a61060b4d9e35dd9, so making CI enforce them will reduce the risk of regressions.

Cirrus: Mark E722 linter as mandatory

---

electrum/blockchain.py

There is no reason why the hash function for identifying a block and the hash function used to instantiate Hashcash must be the same; it's only a coincidence that Bitcoin happens to use the same hash for both use cases.  Reflecting this fact by adding this abstraction makes the code more flexible.
(As discussed on IRC, this is particularly desirable for downstream projects that use different PoW functions, such as Namecoin.)

Add pow_hash_header abstraction

---

electrum/gui/qml/components/About.qml
electrum/gui/qml/qeapp.py

APK version was basically unused

qml: remove APK version, add Qt and PyQt version strings to About page

---

electrum/commands.py
electrum/lnchannel.py
electrum/lnpeer.py
electrum/lnutil.py
electrum/lnwire/peer_wire.csv
electrum/lnworker.py
electrum/simple_config.py
electrum/tests/regtest.py
electrum/tests/regtest/regtest.sh

The first commit add support for zeroconf channels (follows the BOLTs). 
It requires a trusted node to be set in the config.
The second commit adds support for just-in-time channels. 
It differs significantly from LSPS2:
- the scid alias is derived for the node ID.
- a channel opening fee field is added to `open_channel`
- the server requires htlc settlement before broadcasting (server does not trust client)
This is not activated for the moment (and not ready to be activated), but I think we can merge it to the code now.
One issue that bothers me is that tests are performed using `regtest`. It would be better to be able to test this with python.

Just in time channels

---

electrum/gui/qml/components/WalletMainView.qml
electrum/gui/qml/qeinvoice.py

add support for ln address and openalias, fix lnurl finalize step, avoid overloading invoiceParser with new payment identifiers while potentially long-running resolve/finalize steps are ongoing, show errors inresolve/finalize steps to user.
Note: Lightning address and Openalias might benefit from a manual entry dialog instead of just paste and qr scan options currently implemented. This is not part of this PR.

qml: add support for ln address and openalias

---

contrib/android/buildozer_qml.spec

ThomasV reported contrib/release.sh generating .aab artifacts.
aabs are shady business... best to avoid handing privkeys to big G (or any 3rd party!).
This must be a consequence of the recent p4a rebase, e.g. https://github.com/kivy/buildozer/commit/04bb63bbf05302a5eb6f24016aa42aadd49c6470
(untested)

android build: we always want apks, as we want to use our own privkey

---

electrum/gui/qml/components/ReceiveDialog.qml
electrum/gui/qt/receive_tab.py

Be more compatible, uppercase is a QR optimization

qt, qml: use lowercase bolt11 when copying or sharing

---

electrum/gui/qml/qewallet.py
electrum/gui/qt/wallet_info_dialog.py
electrum/wallet.py
electrum/wallet_db.py
electrum/wizard.py

In the db, the 'seed_type' field could be present both at the top-level and inside keystores.
Note:
- both fields had usages
- the top-level field was added in 2.8 re "initial segwit support" (3a64ec0f2ed9c845b5c01daa07fafcbfa26c3cb7)
- there was no db upgrade for it, so older files are missing it
- if present, valid values can be electrum types but also other types supported by the wizard, e.g. "bip39"
- the keystore-level field was added in 4.1 (7b7bba22992eca4536a91249758f178b4a7e044a)
- there was a db upgrade when it was introduced, so old files also have it
- if present, valid values can only be electrum types
- there is not much value in the top-level one having a non-electrum value, and those values were never used by other parts of the code
- note that when creating a standard …

wallet db: deduplicate "seed_type" field

---

contrib/osx/README.md
contrib/osx/make_osx.sh
contrib/osx/notarize_app.sh

See individual commits.
In short, Apple removed support for `altool`, which we were using for notarisation, and to be able to use their new tool (`notarytool`), the build machine needs at least macOS 11.

mac build: migrate to new VM (macOS 10.14 -> 11)

---

electrum/gui/qml/components/TxDetails.qml
electrum/gui/qml/qetxdetails.py
electrum/gui/qt/transaction_dialog.py
electrum/tests/test_wallet_vertical.py
electrum/wallet.py

This continues https://github.com/spesmilo/electrum/pull/8699
- risk_of_burning_coins_as_fees is turned into a private (helper) method, only called by check_sighash. UIs should only care about check_sighash.
- check_sighash returns instance of new class "TxSighashDanger" instead of tuple
- made warning levels more fine-grained (FEE_WARNING_SKIPCONFIRM vs FEE_WARNING_NEEDCONFIRM)
- this became more complicated than I had hoped for but I think it is worth it to ~merge check_sighash and risk_of_burning_coins_as_fees into one.

wallet: refactor check_sighash/risk_of_burning_coins_as_fees

---

electrum/gui/qml/components/wizard/WCServerConfig.qml

if the user entered the server select screen and immediately clicked next, a random server would get set but with auto_connect disabled.

qml: WCServerConfig.qml: only disable autoconnect if given server

---

contrib/android/p4a_recipes/certifi/__init__.py
contrib/android/p4a_recipes/hostpython3/__init__.py
contrib/android/p4a_recipes/openssl/__init__.py
contrib/android/p4a_recipes/python3/__init__.py
contrib/build-linux/appimage/make_appimage.sh

- just a conservative bump of patch version deps only
- let's see the CI build
---
- not included:
- we will have to do a large bump of python3 for win and mac, to at least 3.11.x, as 3.10 is now in source-release only mode
- also, android is stuck in the past atm, maybe we should bump all to 3.11.x

build: bump some security-sensitive packages (py3, ssl)

---

electrum/commands.py
electrum/tests/test_daemon.py

Hello! This pull request restore the ability to pass wallet directly, avoiding loading it in daemon beforehand. This is used with e.g. custom daemons, or in this case specifically when implementing a diskless mode, which does not load the wallet anywhere except memory. As wallet doesn't have storage associated with it, it can't be added to daemon. Before I was able to pass it just fine, but due to added check here: 4e80ef818df0295fa46ee50bbe695b7e6eab1eda I no longer can
When passing wallet object directly as before, I now get that wallet object is not defined. When passing a wallet path it works, but it defeats the purpose of passing wallet object directly and breaks this special in-memory mode

Restore ability to pass wallet in-memory

---

electrum/gui/qt/channels_list.py
electrum/lnchannel.py
electrum/lnpeer.py
electrum/lnworker.py
electrum/tests/test_lnpeer.py

see individual commits
- fix some timing issues for `lnpeer.reestablish_channel`
- this resolves one of the failing tests in https://github.com/spesmilo/electrum/pull/8778
- gui: allow request-force-close chan close option if chan is already in WE_ARE_TOXIC state
- should help https://github.com/spesmilo/electrum/issues/8770

lnpeer.reestablish_channel: fix some timing issues for dataloss case

---

.cirrus.yml

The android+windows+appimage build tasks make up around 2/3 of our CI time usage currently.
(in particular the android build is using a lot of credits: the build caching for it seems to have broken around the qt6 changes. I guess the ~6 GBs we are trying to store in the cache is just too much...)
I think we could de-prioritise these binary builds to only be done once per day, instead of on every commit.
---
(untested)
related https://github.com/cirruslabs/cirrus-ci-docs/discussions/949

ci: only run build tasks once per day (or on manual trigger)

---

electrum/json_db.py
electrum/tests/test_wallet.py
electrum/wallet_db.py

fixes https://github.com/spesmilo/electrum/issues/8842
- tests: walletdb: add failing test case for persistence with jsonpatch
- add reproducer for https://github.com/spesmilo/electrum/issues/8842
- walletdb: change structure of prevouts_by_scripthash, and db upgrade
- this fixes the test case added in prev
- jsondb: raise when trying to store sets in the db
- Some generic protection to prevent bugs similar to what was just fixed in prev commits.

walletdb: change structure of prevouts_by_scripthash, and db upgrade

---

electrum/gui/qml/components/wizard/Wizard.qml

If there is an `accept` handler in the wizard navmap, we need that to run even for the `last` view.
For example, see
https://github.com/spesmilo/electrum/blob/061c8211281d6c0b50166e4075656ce0fb2c89f5/electrum/plugins/trustedcoin/trustedcoin.py#L623-L626
Even if `navmap[view]['last']` is True, we still want the `navmap[view]['accept']` handler to run.
fixes https://github.com/spesmilo/electrum/issues/8861
---
Note that an analogous issue does not exist for the desktop qt gui, see https://github.com/spesmilo/electrum/blob/061c8211281d6c0b50166e4075656ce0fb2c89f5/electrum/gui/qt/wizard/wizard.py#L205-L212
There, `wizard.resolve_next` is called regardless of `is_last`.
---
Or we could do something like this:
```diff
diff --git a/electrum/gui/qml/components/wizard/Wizard.qml …
```

qml wizard: run navmap[view]['accept'] handler a final time on finish

---

electrum/gui/qt/wizard/wizard.py

qt: wizard: move page.on_ready() to just after construction to avoid triggering signal/slots that might assume on_ready() has run.
A number of reports that Shouldn't Happen™ are triggered in similar ways, after `on_next_button_clicked`/`load_next_component`.
Interestingly, these all happen on Windows and MacOS, not on Linux.
- https://github.com/spesmilo/electrum/issues/8834
- https://github.com/spesmilo/electrum/issues/8856
- https://github.com/spesmilo/electrum/issues/8848
- https://github.com/spesmilo/electrum/issues/8815
- https://github.com/spesmilo/electrum/issues/8809
I suspect the event queue handling in Qt is implemented slightly differently on each platform, leading to triggered signals earlier than expected.

qt: wizard: move page.on_ready() to just after construction

---

electrum/gui/qml/qedaemon.py

qml: tighten self._loading guard to encompass whole loadWallet func + success slot, not just task thread.
Also make sure QEWallet is never instantiated within the task thread.
Note: intentionally not initializing QEWallet.password attribute in the constructor, as I want to see bad derefs, as it indicates these parallellism bugs exist.

qml: tighten self._loading guard to encompass whole loadWallet fn

---

electrum/lnpeer.py

This allows making any message handler async in lnpeer.
Note: `process_message` is only called from `_message_loop`.
There are(would be) basically three types of message handlers:
1. "traditional blocking msg handlers". non-async ones. When these handlers are called, `process_message` naturally blocks until the handler returns, which means `_message_loop` also blocks until the message is fully processed before starting the next iteration.
2. "async blocking msg handlers". async ones where we want the previous property, i.e. we want the `_message_loop` to wait until the handler finishes. We await the handler inside `process_message`, and `_message_loop` awaits `process_message`.
3. "async non-blocking msg handlers". async message handlers that can be spawned e.g. onto `Peer.taskgroup` and …

lnpeer: make `process_message` async

---

electrum/commands.py
electrum/daemon.py
electrum/util.py
electrum/wallet.py
run_electrum

Previously, generally, in case of any error, commands would raise a generic "Exception()" and the CLI/RPC would convert that and return it as `str(e)`.
With this change, we now distinguish "user-facing exceptions" (e.g. "Password required" or "wallet not loaded") and "internal errors" (e.g. bugs).
- for "user-facing exceptions", the behaviour is unchanged
- for "internal errors", we now pass around the traceback (e.g. from daemon server to rpc client) and show it to the user (previously, assuming there was a daemon running, the user could only retrieve the exception from the log of that daemon). These errors use a new jsonrpc error code int (code 2).
As the logic only changes for "internal errors", I deem this change not to be compatibility-breaking.
----------
Examples follow.
Consider …

cli/rpc: nicer error messages and error-passing

---

electrum/_vendor/pyperclip/LICENSE.txt
electrum/_vendor/pyperclip/README.md
electrum/_vendor/pyperclip/__init__.py
electrum/gui/text.py

commit 43ab4a779afa339c5295aa1bab61c3915d2df2b9 introduced "pyperclip" as a dependency for the prototype "text" gui.
pyperclip is small enough for us to vendor it, and looks mature/stable enough so that it would ~never need updating. This makes it easier to try out the text gui when running from source, or using the AppImage.
would close https://github.com/spesmilo/electrum/issues/8844
---
note: I don't feel strongly about this PR at all, I mostly wrote it to test an appimage build and to see how the diff would look.

dependencies: vendor "pyperclip" pkg, used by text gui

---

electrum/lnchannel.py
electrum/lnpeer.py
electrum/wallet_db.py
tests/test_lnchannel.py

- "fail_htlc_reasons" was removed in 9b1c40e3964ba7036600cbb0f8bd5938cb3edb22
- "unfulfilled_htlcs": rm 2 dead items from the 4-tuple, and convert False value of forwarding_key

walletdb: chan dict: small clean-up (incl db upgrade)

---

electrum/currencies.json
electrum/exchange_rate.py

This historical exchange went out of business last year and its API hasn't been active for many months..

Removed TRT

---

electrum/gui/qml/qetxdetails.py

I think this logic should be encapsulated in the wallet.
Looks like the extra guards were added in https://github.com/spesmilo/electrum/commit/84cb210e7eed547f28bbd4e948500547fd01213e
(except for `can_save_as_local` -- added in https://github.com/spesmilo/electrum/commit/9cb8dea3435e6a5cdb16a08fc6523198d027031c)
I don't really see a reason why this logic should be GUI-specific.
Also, note that it can make sense to allow bump_fee on a local tx, and so wallet.get_tx_info() allows it (and hence so does the qt gui). For example, if your tx falls out of the mempool, you might want to bump it. (though it could also make sense to allow dscancel in the same scenario but we don't allow that)
For cpfp, as long as there is no package relay, it does not make sense to allow it for a local tx.
I don't …

qml: QETxDetails: defer to wallet.get_tx_info() for rbf/cpfp

---

electrum/plugins/revealer/qt.py

Now that I am an official Debian Developer (previously I was a Debian Maintainer) I would like to use my Debian email address for contributions to upstream projects.

Change copyright email address to soren@debian.org.

---

contrib/deterministic-build/requirements-hw.txt
contrib/requirements/requirements-hw.txt
electrum/plugins/jade/jadepy/README.md
electrum/plugins/jade/jadepy/jade.py
electrum/plugins/jade/jadepy/jade_serial.py
electrum/plugins/jade/jadepy/jade_tcp.py

Updates cbor dependency to cbor2, required for modern linux/python versions.
(Also some new calls (unused in electrum), improvements to logging, better scanning for usb-connected hw)

jade: update Jade api to 1.0.29

---

contrib/deterministic-build/requirements.txt
contrib/requirements/requirements.txt
electrum/lnaddr.py
electrum/segwit_addr.py
electrum/trampoline.py
tests/test_bolt11.py

- `bitstring` started depending on `bitarray` [in version 4.1](https://github.com/scott-griffiths/bitstring/blob/95ee533ee4040b4480da1ead548eab2459e8e573/release_notes.txt#L108)
- that would mean one additional dependency for us (from yet another maintainer), which is not even pure python
- we only use bitstring for bolt11-parsing
- hence this PR rewrites the bolt11-parsing and removes `bitstring` as dependency
- note: I benchmarked lndecode [using this](https://github.com/spesmilo/electrum/commit/d7597d96d0c336838adb32e3e175d3ea6f9763e8), and the new code performs better,
taking around 80% time needed for old code (when using bitstring 3.1.9, pure python).
Though the variance is quite large in both cases.

dependencies: remove bitstring

---

electrum/gui/qt/settings_dialog.py
electrum/lnrouter.py
electrum/lnutil.py
electrum/lnworker.py
electrum/simple_config.py
electrum/trampoline.py
tests/test_lnpeer.py

See individual commit messages.
closes https://github.com/spesmilo/electrum/issues/9033

trampoline: use exponential search for fees, capped by configurable budget

---

electrum/slip39.py
tests/slip39-vectors.json
tests/test_mnemonic.py
tests/test_wallet_vertical.py

This pull request implements a [recent revision](https://github.com/satoshilabs/slips/commit/8d060706b549af6443e04f55605b71f65c981663) of the [SLIP-39 specification](https://github.com/satoshilabs/slips/blob/master/slip-0039.md). The highest bit of the iteration exponent has been repurposed for a new "extendable backup flag". Setting the flag indicates that the random identifier is not used as salt in the encryption of the master secret. This makes it possible to create multiple sets of shares, such that each set of shares uses a different identifier and each set of shares leads to the same master secret for every passphrase. This is a desirable property, which unfortunately was not considered in the initial specification. It allows users to start working with their wallet by creating a …

slip39: Implement extendable backups

---

electrum/ecc.py
tests/test_bitcoin.py
tests/test_ecc.py

This is mainly an API change, which I think makes behaviour simpler to reason about.
-----
The low-S rule for ecdsa signatures is mandated by Bitcoin Core policy/standardness (though not by consensus). If we get signatures from untrusted sources, we should mandate they obey the policy rules. (e.g. from LN peers)
Note that we normalize the signatures in the sig format conversion methods (DER <-> (r,s) <-> sig64).
The BOLTs treat high-S signatures as invalid, and this changes our behaviour to that.
(previously we would silently normalize the `s` value)
Note that `$ bitcoin-cli verifymessage` does NOT enforce the low-S rule for ecdsa sigs, and we make sure to do the same. (so no change for that)
see https://github.com/bitcoin/bitcoin/pull/6769
see https://github.com/lightning/bolts/pull/807

ecc: ecdsa_verify to enforce low-S rule

---

.cirrus.yml
contrib/android/p4a_recipes/libsecp256k1/__init__.py
contrib/make_libsecp256k1.sh

- bump libsecp version for build scripts
- have CI run tests with this version, instead of using apt

bump libsecp256k1 version (0.4.1->0.5.0)

---

electrum/gui/qml/components/main.qml
electrum/gui/qml/qeconfig.py

qml: don't rely on wallet when deactivating PIN and no wallet loaded (fixes #8366)

---

electrum/gui/qml/components/main.qml
electrum/gui/qml/qeqrscanner.py

don't unbind/unregister the ActivityResultListener from within the ActivityResultListener handler func. instead, schedule a queued finished signal to unregister the listener after the handler has finished. See PythonActivity.java in P4A for why this probably causes the most often occurring crash we see on the Play Store:
```
Exception java.lang.RuntimeException:
at android.app.ActivityThread.deliverResults (ActivityThread.java:5164)
at android.app.ActivityThread.handleSendResult (ActivityThread.java:5205)
at android.app.servertransaction.ActivityResultItem.execute (ActivityResultItem.java:51)
at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
at …
```

qml: don't unbind/unregister the ActivityResultListener from within the ActivityResultListener handler func

---

electrum/gui/qml/components/main.qml

The config PIN is a global, while the wallet passwords are per wallet (unless the passwords have been unified).
Knowing the per-wallet password should not be sufficient to change the global config PIN.
related https://github.com/spesmilo/electrum/pull/9074

qml: "wallet_else_pin" auth should only use the wallet pw if is unified

---

electrum/gui/qml/components/SendDialog.qml
electrum/gui/qml/components/WalletMainView.qml

importing a channel backup to a second bip39/xprv wallet with lightning disabled now shows proper message instead of exception text.
We could also provide the option to the user here to enable lightning?

qml: fix handling of channel backup import on lightning-disabled wallets

---

electrum/bitcoin.py
electrum/descriptor.py
electrum/ecc.py
electrum/keystore.py
electrum/lnutil.py
electrum/transaction.py
tests/bip-0341/wallet-test-vectors.json
tests/test_bitcoin.py
tests/test_descriptor.py
tests/test_psbt.py
tests/test_transaction.py

Add support for key-path-spending taproot utxos into transaction.py.
- no wallet support yet
- add some related bits to psbt and descriptors
- preliminary work towards script-path spends

transaction.py: impl taproot key-spends

---

electrum/gui/qml/components/controls/QRImage.qml
electrum/gui/qml/qeapp.py

When displaying a QR code on Android, this sets the screen brightness to max. In some cases this makes it much easier to successfully scan it.
I was trying to scan a PSBT using a laptop camera from my phone screen for 2 minutes, until I realised the screen brightness was the issue.  o.O

qml/android: set max screen brightness when displaying QR codes

---

electrum/plugins/jade/jade.py
electrum/plugins/jade/jadepy/README.md
electrum/plugins/jade/jadepy/__init__.py
electrum/plugins/jade/jadepy/jade.py
electrum/plugins/jade/jadepy/jade_serial.py

1.  latest jade api to recognise more recently added hw
2.  remove code which walked psbt/tx data and mapped it into Jade's legacy 'sign_tx' json format - instead pass PSBT directly to Jade for signing, since this has been supported in fw now for well over a year and seems to be working well.

Jade native psbt

---

electrum/gui/qml/components/WalletDetails.qml
electrum/gui/qml/qewallet.py

qml: add seed passphrase property to QEWallet, show in WalletDetails

---

electrum/gui/qml/qeswaphelper.py

I am not able to test this commit because the qml gui is broken for me on master:
```
1.82 | W | gui.qml.qeapp | file:///opt/electrum/electrum/gui/qml/components/WalletMainView.qml:332:9: Unable to assign QEWallet to QEWallet
1.82 | W | gui.qml.qeapp | file:///opt/electrum/electrum/gui/qml/components/WalletMainView.qml:327:9: Unable to assign QEWallet to QEWallet
```
not sure what causes that issue.

qml: do not display success if swap failed..

---

contrib/add_cosigner
contrib/android/Dockerfile
contrib/android/buildozer_qml.spec
contrib/android/get_apk_versioncode.py
contrib/android/make_apk.sh
contrib/make_download
contrib/print_electrum_version.py
contrib/release.sh
electrum/version.py

This drops the trailing .0 from the version number of android apks. It is a historical thing that we don't need/utilise anymore. (Some years ago, prior to reproducible builds at least, sometimes we had .1 and .2 releases just for android-specific bugs.)
Related https://github.com/spesmilo/electrum/issues/9210#issuecomment-2376572832
Also, the android `versionCode` calculation is changed to accommodate the changed version string, but also to have the architecture part in the least significant digits, as requested in https://github.com/spesmilo/electrum/issues/9210#issuecomment-2380559324
@thecockatiel Could you check if this looks good to you? (re version string and int version code construction)

android: rm APK_VERSION, and change versionCode calculation

---

.cirrus.yml

follow-up https://github.com/spesmilo/electrum/commit/fcc4e1d38773da0484910cacc80c16117b9c15c5
error msg was:
```
SHA for cache folders (/opt/wine64/drive_c/electrum/contrib/build-wine/.cache/win32/wine_pip_cache, /opt/wine64/drive_c/electrum/contrib/build-wine/.cache/win64/wine_pip_cache) is 'be33ad1b0598b1733992e36659bb71406f8fcfaa3a442166ecbe26e2db9a65c2'
Failed to tar caches for Upload 'pip' cache with error walking folder /opt/wine64/drive_c/electrum/contrib/build-wine/.cache/win32/wine_pip_cache: lstat /opt/wine64/drive_c/electrum/contrib/build-wine/.cache/win32/wine_pip_cache: no such file or directory!
```

ci: fix windows build caching

---

contrib/android/get_apk_versioncode.py
contrib/release_www.sh

This updates the `version` file hosted at `https://electrum.org/version` to also include the android `versionCode` (or rather, a closely related value, as that would depend on the target architecture).
This can be used by the F-Droid buildserver to detect new versions and release updates automatically.
ref:
https://github.com/spesmilo/electrum/pull/9221#issuecomment-2386549086
https://f-droid.org/en/docs/Build_Metadata_Reference/#UpdateCheckMode
@thecockatiel does this look good? AFAICT UpdateCheckMode/HTTP cannot parse json files, but I think a regex should be sufficient to extract the version number from this structure.
Example file:
```
{
"version": "4.5.5",
"signatures": {"13xjmVAB1EATPP8RshTE8S8sNwwSUM9p1P": "H29AgDpgA0jFGPq6AiL8DAZsyq0TSyzmbHGxT7dwimRTeF28qc93agiG+oR6K+81gNVqNxvDRO2r …
```

contrib/release_www.sh: put android versionCode in "version" file

---

electrum/commands.py

commands: require wallet password for lnpay command

---

electrum/gui/qt/confirm_tx_dialog.py
electrum/gui/qt/main_window.py
electrum/gui/qt/swap_dialog.py
electrum/gui/qt/transaction_dialog.py
electrum/gui/qt/util.py

RunCoroutineDialog has a run() method that blocks the thread without blocking the GUI (using exec), and a Cancel button that cancels the coroutine.
main_window.run_coroutine_dialog() is a wrapper that returns the coroutine result and may raise exceptions.
BlockingWaitingDialog was removed is transaction_dialog, where it was not particularly useful.

qt: replace BlockingWaitingDialog with RunCoroutineDialog

---

electrum/interface.py

The `ssl.VERIFY_X509_STRICT` flag for openssl verification has been enabled by default in python 3.13+ (it was disabled before that). see https://github.com/python/cpython/issues/107361 and https://discuss.python.org/t/ssl-changing-the-default-sslcontext-verify-flags/30230/16
We explicitly disable it for self-signed certs, thereby restoring the pre-3.13 defaults, as it seems to break lots of servers.
For example, using python 3.13 (or setting `sslc.verify_flags |= ssl.VERIFY_X509_STRICT`),
- I can connect to `btc.electroncash.dk:60002:s`
- but not to `electrum.emzy.de:50002:s`
despite both using self-signed certs.
We should investigate more why exactly "strict" verification fails for some self-signed certs and not for others, and make sure that at least newly generated certs adhere to the …

interface: disable ssl.VERIFY_X509_STRICT for self-signed certs

---

electrum/channel_db.py
electrum/commands.py
electrum/crypto.py
electrum/gui/qml/qechannelopener.py
electrum/gui/qt/main_window.py
electrum/lnchannel.py
electrum/lnonion.py
electrum/lnpeer.py
electrum/lnsweep.py
electrum/lntransport.py
electrum/lnutil.py
electrum/lnworker.py
electrum/trampoline.py
tests/test_lnchannel.py
tests/test_lnpeer.py
tests/test_lntransport.py
tests/test_lnutil.py

This will be useful if we decide to ship lntransport as a separate package. It is also a conceptual cleanup.
Notes:
- lntransport still requires crypto.py
- parsing node id from a bolt11 invoice is not supported.

Make lntransport not require lnutil.

---

electrum/lnpeer.py
electrum/lnsweep.py
electrum/lnwatcher.py
electrum/lnworker.py
tests/regtest.py
tests/regtest/regtest.sh
tests/test_lnpeer.py

If we accept a MPP and we forward the payment (trampoline or swap), we need to persist the payment accepted status, or we might wrongly release htlcs on the next restart.
lnworker.received_mpp_htlcs used to be cleaned up in maybe_cleanup_forwarding, which only applies to forwarded payments. However, since we now persist this dict, we need to clean it up also in the case of payments received by us. This part of maybe_cleanup_forwarding has been migrated to lnworker.maybe_cleanup_mpp

Persist MPP resolution status in wallet file.

---

electrum/interface.py
electrum/lntransport.py
electrum/lnworker.py
electrum/network.py
electrum/util.py
tests/test_lntransport.py
tests/test_network.py

also refactor, for proxy instantiation, use Network instance, not a proxy dict.

network: use TOR stream isolation

---

electrum/daemon.py
electrum/gui/qt/main_window.py

this also removes alpha-sort of the wallet list in favor of placing most recently opened on top

qt: keep list of recently used wallets in sync across windows

---

electrum/gui/qt/wizard/wallet.py
electrum/gui/qt/wizard/wizard.py

This allows control over which control to focus. If undefined, the Next button is focused by default

qt: add WizardComponent.initialFocus() 

---

contrib/requirements/requirements.txt
electrum/commands.py
electrum/gui/qt/main_window.py
electrum/gui/qt/rbf_dialog.py
electrum/gui/qt/send_tab.py
electrum/gui/qt/settings_dialog.py
electrum/gui/qt/swap_dialog.py
electrum/lnutil.py
electrum/lnworker.py
electrum/plugins/swapserver/server.py
electrum/plugins/swapserver/swapserver.py
electrum/simple_config.py
electrum/submarine_swaps.py
electrum/wallet.py
run_electrum
tests/regtest.py
tests/test_simple_config.py

Swaps over Nostr:
- Separation between SwapManager and its transport: Legacy transpport uses http, Nostr uses websockets
- The transport uses a context to open/close connections. This context is not async, because it needs to be called from the GUI
- Initialize swapserver fees values to None instead of 0 (so that they cannot be used before swap manager is initialized)
- Remove swapserver fees disk caching (swap_pairs file)
- Regtests set config 'nostr_relays' to an empty string, so that the swap manager falls back to using the http transport

Swaps over nostr

---

electrum.desktop

The `Keywords` field in .desktop files provides additional key words beyond those in the `Name` and `GenericName` fields that can be used to search for a program.  Debian likes to have this field populated.  This patch adds a few words, but there are probably others that I haven't thought of.

Add .desktop file keywords entry.

---

electrum/lnchannel.py
electrum/lnworker.py
electrum/wallet.py

We were already reserving wallet addresses for full channels. Now we also do the same for imported channel backups. (but not for onchain, as we don't have enough info for that)
Without this, if the same seed is used on multiple devices (with each device having its own set of LN channels), the wallet instances will reuse keys (specifically the payment_basepoint, which for static_remotekey chans is used as the to_remote output so it is trivially visible onchain). Now with this change, at least if the wallet instances have imported channel backups of each other, this reuse is avoided.

lnworker: reserve wallet addresses also for chan backups

---

electrum/lnsweep.py

this was rebased in july 2024 from #7509
I guess it needs to be rebased again :-) 
Here are my personal notes regarding this rebase:
- <s> some tests are broken (`REDEEMED` state reached too early in test_breach)</s>
- <s> we should use password in memory (daemon `unlock` command) </s>
- if no password in memory (non-android GUI): maybe warn user?
- stop LN support for watching-only and hardware wallets

Anchor commitments 2024

---

electrum/paymentrequest.proto

The previous link has expired and has been replaced with the latest address.

chore: fix 404 status URL

---

electrum/gui/qt/main_window.py

Fixes the following traceback in case a user cancels a reverse swap before the coordinator answered:
```bash
File "/home/user/code/electrum/electrum/gui/qt/channels_list.py", line 366, in <lambda>
menu.addAction(read_QIcon('update.png'), _('Submarine swap'), lambda: self.main_window.run_swap_dialog())
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
File "/home/user/code/electrum/electrum/gui/qt/main_window.py", line 1189, in run_swap_dialog
return d.run(transport)
~~~~~^^^^^^^^^^^
File "/home/user/code/electrum/electrum/gui/qt/swap_dialog.py", line 263, in run
funding_txid = self.window.run_coroutine_dialog(coro, _('Initiating swap...'))
File "/home/user/code/electrum/electrum/gui/qt/main_window.py", line 308, in run_coroutine_dialog
return d.run()
~~~~~^^
File …
```

Catch UserCancelled exception in main window on user swap cancellation

---

electrum/gui/qt/plugins_dialog.py
electrum/gui/qt/util.py
electrum/plugin.py

This PR adds the sha256 hash of the zipfile of external plugins to the PluginDialog so users can see it when enabling a plugin. 
The hash is calculated when searching for plugins and split with a whitespace every 16 chars to allow for line wrapping and easier readability.

Add filehash of external plugins to PluginDialog 

---

electrum/trampoline.py

LND doesn't support trampoline payments so this node doesn't work here.

Remove wakiyamap lnd node from signet trampoline nodes

---

electrum/lnworker.py

This PR sets the payment retry limit to 20 if the client is using trampoline to prevent excessive retries until the timeout.

Limit payment attempts if client uses trampoline

---

electrum/lnpeer.py

This changes the OnionFailureCode returned from ```maybe_forward_trampoline()``` on ```PaymentFailure``` to ```TRAMPOLINE_FEE_INSUFFICIENT``` so the client will retry the payment with higher trampoline fee instead of giving up.

Change OnionFailureCode returned when failing trampoline forwarding

---

electrum/lnpeer.py

Currently forwarding trampoline payments is only done in one attempt. The attempts have to be increased to make forwarding more reliable.

Increase attempts when forwarding trampoline payment

---

electrum/lnworker.py

This PR adds a fallback list of signet lightning nodes and uses it in ```lnworker._get_next_peers_to_try()``` in case there are no previous peers in the ChannelDB. 
As peers only get added to the ChannelDB on connection if trampoline is already disabled this will help to directly find peers when disabling trampoline payments (enabling gossip) as the ChannelDB doesn't contain any previous peers yet (they would be added on restart when reconnecting with loaded ChannelDB).

Add fallback list of signet nodes and use it for ln peer discovery

---

electrum/lnchannel.py
electrum/lnpeer.py
electrum/lnsweep.py
electrum/lnutil.py
electrum/lnwatcher.py
electrum/lnworker.py
electrum/wallet.py
electrum/wallet_db.py
tests/regtest/regtest.sh
tests/test_lnutil.py

Ideally, given an on-chain backup, after the remote force-closes, we should be able to spend our anchor output, to CPFP the remote commitment tx (assuming the channel used OPTION_ANCHORS). To spend the anchor output, we need to be able to sign with the local funding_privkey.
Previously we derived the funding_key from the channel_seed (which comes from os.urandom). Prior to anchors, there was no use case for signing with the funding_key given a channel backup. Now with anchors, we should make its derivation deterministic somehow, in a way so that it can be derived given just an on-chain backup.
- one way would be to put some more data into the existing OP_RETURN
- uses block space
- the OP_RETURNs can be disabled via "use_recoverable_channels"
- only the initiator can use OP_RETURNs (so …

lightning: change derivation of funding_pubkey

---

electrum/channel_db.py
electrum/lnpeer.py
tests/test_lnmsg.py

Adds function ```to_addresses_field()``` to serialize hostname and port for node announcement gossip ```addresses``` field according to bolt7.
Adds parsing of address type 5 (dns hostname) to ```parse_addresses_field()``` (for receiving gossip).
Removes parsing of onion v2 hostnames as they are not functional anymore anyways. 
Adds tests for both parsing and serializing.

Add gossip address field serialization, parsing and tests

---

electrum/commands.py
electrum/simple_config.py

This adds commands to view the list of config variables

cmdline: add listconfig/helpconfig

---

contrib/requirements/requirements.txt
run_electrum

Increase the allowed version of [aiorpcx](https://github.com/kyuupichan/aiorpcX) to the new 0.24 version, which uses the new websockets version, so it's possible to get rid of the websockets deprecation warning when starting electrum.
Changelog of aiorpcX 0.24: [Changelog](https://github.com/kyuupichan/aiorpcX/blob/master/docs/changelog.rst#version-024-16-jan-2024)

Bump allowed aiorpcx version to 0.24

---

electrum/gui/qt/swap_dialog.py

Currently when we raise an exception on creation of a reverse swap it pops up to the GUI. This PR handles exceptions as we do in ```do_normal_swap()```., it shows the user an error dialog with the exception. 
Example exception now caught:
```
3602.51 | E | gui.qt.exception_window.Exception_Hook | exception caught by crash reporter
File "/home/user/code/electrum-fork/electrum/gui/qt/channels_list.py", line 366, in <lambda>
menu.addAction(read_QIcon('update.png'), _('Submarine swap'), lambda: self.main_window.run_swap_dialog())
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
File "/home/user/code/electrum-fork/electrum/gui/qt/main_window.py", line 1190, in run_swap_dialog
return d.run(transport)
~~~~~^^^^^^^^^^^
File …
```

Handle reverse swap exception more gracefully

---

electrum/lnpeer.py

We send the query_short_channel_ids gossip message with zlib compression encoding enabled by default. However this was removed/forbidden in the bolt spec in this PR https://github.com/lightning/bolts/pull/981 and must not be done anymore, see https://github.com/lightning/bolts/blob/master/07-routing-gossip.md#query-messages. I removed the compression part completely as i see no case where it could be used anymore.

Remove query_short_channel_ids zlib compression

---

electrum/base_crash_reporter.py

Changes usage of the depreciated [```locale.getdefaultlocale()```](https://docs.python.org/3/library/locale.html#locale.getdefaultlocale) to the new [```locale.getlocale()```](https://docs.python.org/3/library/locale.html#locale.getlocale) to fix the following depreciation warning:
```
../electrum/base_crash_reporter.py:127: DeprecationWarning: 'locale.getdefaultlocale' is deprecated and slated for removal in Python 3.15. Use setlocale(), getencoding() and getlocale() instead.
"locale": locale.getdefaultlocale()[0] or "?",
```

Use getlocale() instead of getdefaultlocale() in crash reporter

---

electrum/lnpeer.py
electrum/lnutil.py
electrum/lnworker.py
electrum/trampoline.py

Related to https://github.com/spesmilo/electrum/pull/9433#issuecomment-2592754899. Adds a bool flag to ```NoPathFound``` exception that can be used to determine if the exception could be caused by a too low fee or if it has another cause when catching it. This information is then be used to send either ```OnionFailureCode.TRAMPOLINE_FEE_INSUFFICIENT``` or ```OnionFailureCode.UNKNOWN_NEXT_PEER``` when failing to forward a trampoline payment, so we don't always return ```TRAMPOLINE_FEE_INSUFFICIENT``` even if maybe there is no channel available at all (so raising fees would be useless). 
The flag could also be used client side, for example to show the user that a payment maybe failed because of a too low fee instead of just showing that it failed without reason as we use the …

Separate between fee related NoPathFound and other causes when doing lightning payments/forwards

---

electrum/plugins/coldcard/coldcard.py

* this is bug where electrum showed correct address (i.e `p2wpkh` or `p2sh-p2wpkh`) but Coldcard was always showing `p2pkh` address. Msg verifies OK (sig correct) as all the address types for specific path have same public key, but address verification on device is not possible

fix Coldcard msg signing for segwit v0 address types

---

electrum/gui/qt/main_window.py
electrum/simple_config.py
electrum/submarine_swaps.py
electrum/util.py

* Changes the event type for nostr swap announcements to 30315 (NIP38 user status), we now also filter directly for the chain hash and add an expiry tag.
Example event:
```json
{
"id": "49ca58b57fda5dc384a6b2f3d1dcf83ec33160670e439ccd95701135d06f171e",
"pubkey": "c70d7bc9de7e98280c039e6b741c075b66f3f56e4798e3d9c3b4c93dc0511f27",
"created_at": 1739351024,
"kind": 30315,
"tags": [
[
"d",
"electrum-swapserver-2"
],
[
"r",
"net:signet"
],
[
"expiration",
"1739351634"
]
],
"content": "{\"percentage_fee\": 0.5, \"normal_mining_fee\": 952, \"reverse_mining_fee\": 1071, \"claim_mining_fee\": 952, \"min_amount\": 20000, \"max_amount\": 10000000, \"relays\": \"wss://nos.lol,wss://relay.damus.io,wss://brb.io,wss://nostr.mom,wss://relay.primal.net,wss://ftp.halifax.rwth-aachen.de/nostr,wss://eu.purple …
```

Change nostr swap event type, add PoW, rebroadcast events

---

electrum/lnutil.py
tests/test_lnutil.py

We use `list_enabled_bits()` to get the features we signal in ln/gossip messages. Bolt 9 specifies: 
> MUST NOT set both the optional and mandatory bits.
We however set both, optional and required features in messages because `list_enabled_bits()` returns them both if they are set in a LnFeatures instance. This caused the invalid announcement signature warning by eclair because eclair correctly reserialized our message which was different from what we signed, so the signature didn't match anymore.
Example for LnFeatures(175922003768259):
This is what we sent before:
```
['OPTION_DATA_LOSS_PROTECT_REQ', 'OPTION_DATA_LOSS_PROTECT_OPT', 'GOSSIP_QUERIES_REQ', 'GOSSIP_QUERIES_OPT', 'VAR_ONION_REQ', 'VAR_ONION_OPT', 'OPTION_STATIC_REMOTEKEY_REQ', 'OPTION_STATIC_REMOTEKEY_OPT', …
```

Ignore odd bits if even bit is set too in list_enabled_bits

---

electrum/gui/qml/components/NostrSwapServersDialog.qml

Shows flat mining fee of the swap provider in the qml gui. See `+ 150 sat` below:

Show flat fee in qml swap provider selection

---

electrum/commands.py
electrum/gui/qml/components/ReceiveDetailsDialog.qml
electrum/gui/qml/components/ReceiveDialog.qml
electrum/gui/qml/components/WalletMainView.qml
electrum/gui/qml/qewallet.py
electrum/gui/qt/receive_tab.py
electrum/gui/qt/request_list.py
electrum/gui/qt/send_tab.py
electrum/gui/text.py
electrum/invoices.py
electrum/plugins/payserver/payserver.py
electrum/simple_config.py
electrum/wallet.py
tests/regtest/regtest.sh
tests/test_invoices.py

This PR removes on-chain fallback addresses in bolt11 invoices, and removes gap limit restrictions on the number of lightning invoices that can be created. In the GUI, it reintroduces the previous design with two buttons in the receive tab, which is simpler.
The QML component `ReceiveDialog.qml` needs further simplification.
The payserver plugin needs to be adapted too.

reintroduce separate request types for lightning and onchain

---

electrum/gui/common_qt/util.py
electrum/gui/qml/qeapp.py

`get_font_id` also saves the trouble of specifying the entire path of the fonts.

Cache font-ids that were already loaded

---

electrum/channel_db.py
electrum/lnpeer.py
electrum/lntransport.py
electrum/lnutil.py
electrum/lnworker.py
tests/test_lnpeer.py

This PR implements handling the [query messages](https://github.com/lightning/bolts/blob/master/07-routing-gossip.md#query-messages) defined in BOLT-7.
Only `LNWallet` peers forward gossip messages and handle queries. This allows peers to find us (`LNWallet` publishes `node_announcement`), and prevents peers from querying both `LNGossip` and `LNWallet` for the same data. All this functionality will only be active if payment forwarding is enabled too.
Queries are handled directly in the `Peer`, when receiving a query the Peer will fetch the requested messages from `ChannelDB` and forward them. Simultaneous queries are disallowed and dropped with warning.
When receiving a `gossip_timestamp_filter` message it is stored as non-persisted variable of the `Peer`. 
When we receive gossip it is …

Introduce incoming gossip query handling and forwarding

---

electrum/lnpeer.py
electrum/lnworker.py

Considers the available inbound liquidity when deciding if the client requires a just-in-time channel to receive the requested amount. Also disables the MPP feature flags in the invoice if client requests a jit channel to prevent the LSP from opening multiple channels to it (one for each htlc). 
Also makes the difference between the static scid alias we create if there is no existing channel and the "regular" scid aliases more clear by renaming two functions, so we don't call two different things 'scid alias'.
Required for https://github.com/spesmilo/electrum/pull/9584

Disable mpp flags in invoice creation if jit channel is required and consider available liquidity 

---

electrum/lnpeer.py

Allows the client to accept an incoming channel even if recoverable channels are enabled if the originator is a trusted zeroconf node. This way the client doesn't have to completely disable recoverable channels to get incoming JIT channels and as the trusted nodes are supposed to be hardcoded the client is able to recover them. 
If we want to move away from hardcoding the providers we could look into opening recoverable jit channels.
Required for https://github.com/spesmilo/electrum/pull/9584

Refector on_channel_open to accept incoming channels if the source is a trusted zeroconf node

---

electrum/base_crash_reporter.py
electrum/gui/qml/components/NetworkOverview.qml
electrum/gui/qml/components/ProxyConfigDialog.qml
electrum/gui/qml/components/controls/OnchainNetworkStatusIndicator.qml
electrum/gui/qml/components/controls/ProxyConfig.qml
electrum/gui/qml/qenetwork.py
electrum/gui/qt/__init__.py
electrum/gui/qt/main_window.py
electrum/gui/qt/network_dialog.py
electrum/gui/qt/send_tab.py
electrum/gui/qt/util.py
electrum/gui/qt/wizard/server_connect.py
electrum/gui/text.py
electrum/network.py
electrum/simple_config.py
electrum/util.py
electrum/wizard.py
tests/test_wizard.py

The wizard was already using `ProxyWidget` and `ServerWidget`, which are a refactor of `NetworkChoiceLayout`.
This commit refactors the 'regular' network settings dialog to the same components.
Proxy settings are refactored to `ProxySettings` class, replacing the dict and encapsulating most proxy settings related code.
The Tor checkbox is removed, as it was somewhat confusing and not kept in UI-sync with actual Tor use. It is replaced with a 'detect tor proxy' button. Tor probing is moved to backend code in `electrum/network.py`. QML now also gained Tor probe functionality.

qt: refactor NetworkChoiceLayout to ProxyWidget+ServerWidget

---

electrum/network.py
electrum/util.py
tests/test_util.py

see https://docs.python.org/3.13/library/asyncio-task.html#asyncio.create_task :
> Important
> Save a reference to the result of this function, to avoid a task
> disappearing mid-execution. The event loop only keeps weak references
> to tasks. A task that isn’t referenced elsewhere may get garbage
> collected at any time, even before it’s done. For reliable
> “fire-and-forget” background tasks, gather them in a collection
ref https://github.com/python/cpython/issues/91887

asyncio: hold our own strong refs for tasks and futures

---

electrum/lnpeer.py
electrum/lnworker.py
tests/test_lnpeer.py

Required for https://github.com/spesmilo/electrum/pull/9584
Adds a persisted dictionary of htlc keys (= result of `serialize_htlc_key()`) to lnworker to allow adding htlcs which should not be settled back even if we got the required preimage to do so. 
Currently if we open a JIT channel and get the preimage from the client we concurrently settle the incoming htlc to us, however we may still want to fail it in the process of opening the JIT channel which is not finished yet, for example if we were unable to broadcast the funding tx. With this change we can block the settling until the forwarding callback has returned.
<s>Also fixes a key error exception that happened if the incoming htlc got settled before the callback returned, `wrapped_callback` then tried to access …

Add mechanism to block htlcs from settling back

---

electrum/lnchannel.py
electrum/lnpeer.py
electrum/lnutil.py
electrum/wallet.py

This adds handling of zeroconf channels with funding tx height `TX_HEIGHT_LOCAL`. This way the client removes channels if the LSP fails to broadcast the funding transaction instead of trying to continue using it. It also allows the LSP to remove the channel on client side by sending shutdown instead of broadcasting the funding tx, the client will then remove the channel as it is in `CLOSING` state, this is useful if the LSP wants to abort the opening procedure, e.g. if the client fails to provide the preimage.
Required for https://github.com/spesmilo/electrum/pull/9584

Handle unfunded zeroconf channels in update_unfunded_state

---

electrum/lnchannel.py
electrum/lnwatcher.py
electrum/lnworker.py
tests/regtest.py
tests/regtest/regtest.sh

call lnworker.htlc_failed once the htlc_tx is deeply mined.
In the case of a forwarding, this will fail incoming htlcs. (fixes #8547)

Fail incoming htlcs if we forwarded and chan was force-closed (fix #8547)

---

electrum/gui/qt/receive_tab.py
electrum/wallet.py

Adds handling of zeroconf payment requests to qt gui by checking if user can receive through zeroconf channel. If possible it shows a warning that has to be accepted first before the invoice is shown. Prefers swaps over zeroconf channels as they require less trust and are more capital efficient.
https://github.com/user-attachments/assets/0a37b82c-8e42-4ce7-85d9-51ed1e8687f0

Handle zeroconf lightning requests in QT gui

---

electrum/gui/qml/components/ReceiveDetailsDialog.qml
electrum/gui/qml/qerequestdetails.py
electrum/gui/qml/qewallet.py
electrum/lnworker.py

Allows to create invoices in QML gui if client has configured trusted zeroconf channels. Shows according warning when a channel is going to get opened or when the amount is too low to receive the payment.

Handle just in time channels in qml request creation

---

electrum/address_synchronizer.py
electrum/gui/qt/confirm_tx_dialog.py
electrum/simple_config.py
electrum/wallet.py

Adds a new config option: `WALLET_FREEZE_REUSED_ADDRESS_UTXOS`. This is based on [Bitcoin Core's "avoid_reuse"](https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-0.19.0.1.md#wallet) wallet flag.
This opt-in feature, if enabled:
> Automatically freeze coins received to already used addresses.
> This can eliminate a serious privacy issue where a malicious user can track your spends by sending small payments
> to a previously-paid address of yours that would then be included with unrelated inputs in your future payments.
Note that currently we only have a single coinchooser policy, `CoinChooserPrivacy`, which interacts well with this option, as it spends all coins from any selected address. However, if we later add a different coinchooser policy, which allowed …

wallet: add new config option "FREEZE_REUSED_ADDRESS_UTXOS"

---

electrum/coinchooser.py
electrum/wallet.py
tests/test_coinchooser.py
tests/test_txbatcher.py

This fixes two bugs with anchor output sweeping, `make_tx` is not called with multiple change addresses if the option `Use multiple change addresses` is enabled when there are no outputs specified. 
Also in `sufficient_funds` it doesn`t consider a bucket value <= 0 sufficient anymore, even if total input amount seems sufficient if there are no outputs, so that inputs will be added and a change output created, to prevent creating an invalid transaction with no outputs.

Fix anchor output sweeping bug creating invalid sweeping tx

---

electrum/commands.py
electrum/daemon.py
electrum/plugin.py
electrum/plugins/labels/commands.py
electrum/plugins/labels/labels.py
run_electrum

This PR adds functionality which allows plugins to register cli commands. 
CLI commands can be registered from within a `commands.py` file at the plugins root by decorating them with the `@plugin_command(requirements, plugin_name)` decorator.
Example:
```python
file: plugins/demo_plugin/commands.py
from electrum.commands import plugin_command
plugin_name = "demo_plugin"
@plugin_command("", plugin_name=plugin_name)
async def plugin_demo_command(self: 'Commands'):
plugin: 'DemoPlugin' = self.daemon._plugins.get_plugin(plugin_name)
plugin.do_something()
return "plugin did something (this is the cli output)"
```
This works for internal and external plugins. Plugin commands have to begin with `plugin_` and are not allowed to overwrite other commands. 
Here is a external demo plugin which …

Allow plugins to register CLI commands 

---

electrum/gui/qt/send_tab.py

base_tx in make_unsigned_transaction
is expected to be of type
Optional[Transaction], not boolean.

fix base_tx type

---

.gitmodules
contrib/build-wine/deterministic.spec
contrib/deterministic-build/requirements-hw.txt
contrib/osx/osx.spec
contrib/requirements/requirements-hw.txt
contrib/requirements/requirements.txt
electrum/plugins/keepkey/client.py
electrum/plugins/keepkey/keepkey.py

replaces https://github.com/spesmilo/electrum/pull/9581
The difference is that this PR adds our fork of keepkeylib as a git submodule, instead of including it directly into the git tree. This avoids polluting the tree.
[Our fork of keepkeylib](https://github.com/spesmilo/electrum-keepkeylib) has the protobuf-generated code regenerated with more modern protoc, and a lot of altcoin stuff is removed.
Also see description of prev PR:
> This adds keepkeylib into our git tree. We will vendor it that way from now, instead of declaring it as an external dependency.
> 
> Upstream keepkeylib is effectively unmaintained -- but the only problem with it is that it requires an old version of `protobuf`. (see https://github.com/keepkey/python-keepkey/issues/146)
> By vendoring it, we can fix that …

plugins: keepkey: vendor our fork of keepkeylib (as git submodule)

---

electrum/commands.py
electrum/gui/qml/qeinvoice.py
electrum/gui/qml/qewallet.py
electrum/gui/qt/send_tab.py
electrum/gui/text.py
electrum/lnworker.py
electrum/submarine_swaps.py
tests/test_lnpeer.py

generalization needed in preparation for other invoice types, e.g. bolt12

refactor lnworker.pay_invoice to accept Invoice object instead of bolt11 string

---

electrum/plugin.py
electrum/plugins/payserver/__init__.py
electrum/plugins/swapserver/__init__.py
electrum/plugins/watchtower/__init__.py
electrum/simple_config.py
tests/regtest.py

- probably needs a better way to pass default value and type
- needs to set `SimpleConfig._init_done`:  we are currently passing the config object to the constructor of Plugins(). That might be easier if we passed Plugins to the constructor of SimpleConfig

config vars for plugins

---

electrum/submarine_swaps.py
electrum/util.py

This PR relies on https://github.com/spesmilo/electrum-aionostr/pull/5
Passes the electrum proxy configuration to the aionostr library so the websocket connections go through the proxy.
Can be tested by configuring tor as proxy and using these onion nostr relays in the config:
`ws://oxtrdevav64z64yb7x6rjg4ntzqjhedm5b5zjqulugknhzr46ny2qbad.onion,ws://bitcoinr6de5lkvx4tpwdmzrdfdpla5sya2afwpcabjup2xpi5dulbad.onion,ws://nostrland2gdw7g3y77ctftovvil76vquipymo7tsctlxpiwknevzfid.onion`

Pass proxy settings to aionostr manager for submarine swaps

---

electrum/plugin.py
electrum/plugins/payserver/__init__.py
electrum/plugins/swapserver/__init__.py
electrum/plugins/watchtower/__init__.py
electrum/simple_config.py

- define vars less dynamically
- enforce "key" starts with name of plugin
- this depends on https://github.com/spesmilo/electrum/pull/9655 to work properly

plugin ConfigVars: define vars less dynamically

---

electrum/lnpeer.py
electrum/lnworker.py
tests/test_lnpeer.py

Stops using a fallback feerate for lightning fee estimation function (`current_target_feerate_per_kw()`) and prevents trying channel reestablishment before we have fee estimates available and are fully synced to prevent errors like this and resulting causing force closes:
```
INFO | lnpeer.Peer.[LNWallet, ...] | remote peer sent error [DO NOT TRUST THIS MESSAGE]: 'local/remote feerates are too different: remoteFeeratePerKw=37500 localFeeratePerKw=788'. chan_id=.... is_known_chan_id=True
```

lightning: don't use fallback feerates for lightning fee estimation

---

electrum/lnworker.py

channels in DISCONNECTED state are incorrectly considered as usable receiving capacity

lnworker: take peer_state into account in get_channels_for_receiving

---

electrum/lnpeer.py

If public channels are opened without setting `LIGHTNING_LISTEN` to some listening address `LNPeer.send_node_announcement()` will raise an exception as the default value of `LIGHTNING_LISTEN` is `None`. However it should be possible to have public channels without announcing a listening address.
Exception:
```
File "/home/user/code/electrum-fork/electrum/lnpeer.py", line 553, in _send_own_gossip
self.send_node_announcement(alias)
~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
File "/home/user/code/electrum-fork/electrum/lnpeer.py", line 1738, in send_node_announcement
hostname, port = addr.split(':')
^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
```

lightning: fix exception if LIGHTNING_LISTEN is not set on public node

---

electrum/gui/qml/qeswaphelper.py
electrum/gui/qt/swap_dialog.py
electrum/gui/qt/utxo_list.py
electrum/lnworker.py
electrum/plugins/swapserver/server.py
electrum/submarine_swaps.py
electrum/wallet.py

Makes swap provider announce the actual available liquidity for forward and reverse swaps instead of a static hardcoded max value. This should increase reliability of swaps as clients will know upfront if the provider even has enough liquidity to fulfill their request.
Depends on https://github.com/spesmilo/electrum/pull/9647

swaps: Announce available liquidity instead of static maximum value

---

electrum/gui/qml/qechannelopener.py

Calls `QEChannelOpener.validate()` after setting the max amount slider in the channel open dialog so that the `Open Channel...` button gets activated when max amount was set. 
Right now if max amount gets set and no other value gets changed the `Open Channel...` button stays deactivated.

qml: call QEChannelOpener.validate() on updateMaxAmount

---

electrum/gui/qml/qechannelopener.py
electrum/gui/qml/qetxfinalizer.py

The fee slider in the qml lightning channel tx dialog didn't work because the fee policy passed to `mktx_for_open_channel` was not updated when the slider position changed.

qml: pass updated fee policy to make_tx function when opening channel

---

electrum/gui/qt/main_window.py
electrum/submarine_swaps.py

Swap provider discovery using nostr was sometimes unreliable (in the sense of showing that no providers could be found, even though the logs showed successful connections) because the timeout in `initialize_swap_manager()` was independent of the connection timeout used for the relay manager. So the relay manager tried to connect to (unreachable) relays longer than the timeout in `initialize_swap_manager()` causing  `initialize_swap_manager()` to close the NostrTransport again before the connect call even returned. The solution is to just use a shared timeout value (+ some buffer in `initialize_swap_manager()`)

swaps: make swap transport use shared timeout value

---

electrum/submarine_swaps.py

Set log level of the logger passed into the aionostr.Manager to INFO because the debug log output of Manager is very verbose (showing single websocket messages etc.). This still provides enough useful information for debugging purposes.

swaps: Reduce logging verbosity of aionostr.Manager in swap transport

---

electrum/submarine_swaps.py

If the user tries to send change to lightning in an onchain payment and the swap amount is below the supported amount by the provider it will send `invoiceAmount` None to the server, this causes the swapserver taskgroup to stop due to an exception and the client will be stuck in the 'Requesting swap invoice...' dialog waiting for a response. 
This pr adds a error response to the swapserver so the client is able to handle errors of the server and checks if `invoiceAmount` is not none before even trying to request a swap.

swaps: improve send change to lightning and swapserver error handling

---

electrum/gui/qml/__init__.py
electrum/gui/qml/qeapp.py
electrum/gui/qml/qedaemon.py
electrum/gui/qml/qenetwork.py
electrum/plugins/trustedcoin/qml.py

force QEDaemon singleton, and refer to QEDaemon.instance where possible In cases where we would run into circular dependencies, pass the instance
also refer to singleton QEConfig instead of passing instance in qeapp.py

qml: simplify QEConfig and QEDaemon use.

---

electrum/gui/common_qt/util.py
electrum/lnpeer.py
electrum/lnworker.py
electrum/plugins/nwc/__init__.py
electrum/plugins/nwc/cmdline.py
electrum/plugins/nwc/manifest.json
electrum/plugins/nwc/nwcserver.py
electrum/plugins/nwc/qt.py
electrum/plugins/revealer/qt.py
electrum/simple_config.py
electrum/util.py
electrum/wallet.py

Implements https://github.com/nostr-protocol/nips/blob/75f246ed987c23c99d77bfa6aeeb1afb669e23f7/47.md as plugin.
Supports CLI and QT gui.
This allows remote control of an Electrum lightning wallet via Nostr, so Electrum can be used as funding source for nwc clients like [Amethyst](https://github.com/vitorpamplona/amethyst), [lnbits](https://github.com/lnbits/lnbits), [Bitbanana](https://github.com/michaelWuensch/BitBanana), [AlbyGo](https://github.com/getAlby/go/), the [Alby Browser Extension](https://github.com/getAlby/lightning-browser-extension) and more stuff.
It allows to set a 24h budget and an expiry date for the connection. 
I tested with Amethyst, Alby Go, Alby browser extension and bitbanana, most things work but the spec leaves room for interpretation, so in some clients some …

plugin: implement Nostr Wallet Connect (NIP47) plugin

---

electrum/lnworker.py

When a channel with outgoing htlc is force closed and there is no preimage released by the recipient `LNWallet.htlc_failed()` will indirectly get called on each startup and new block until the channel is not being watched anymore. 
This triggers the `payment_failed` callback every time which will trigger a UI reaction in qt and qml, which is annoying and misleading.
This PR adds a check `if self.get_payment_status(payment_hash) != PR_UNPAID` so that the callback will get triggered only once (when the payment status hasn't already been set to `PR_UNPAID`).

lightning: trigger payment_failed only once in LNWallet.htlc_failed().

---

electrum/gui/qt/settings_dialog.py
electrum/lnworker.py
electrum/simple_config.py

The config option (`LIGHTNING_LEGACY_ADD_TRAMPOLINE`) to add a 2nd trampoline hop to legacy trampoline payments requires too much space in the trampoline onion. Because the trampoline onion has only limited space of 400b and the payload with 2nd t hop and no r_tags already requires 392b it is practically unusable for payments that require routing hints to be included in the onion (e.g. because the receiver has no direct channel to the 2nd trampoline node) as there is no space left to include even a single routing hint (1r_tag == ~52b).
As discussed, this pr removes the config option from SimpleConfig and the GUI, however it keeps the logic of use_second_trampoline so we could in theory enable it again if the conditions (available space?) change. I also added a TODO to completely remove …

lightning: remove LIGHTNING_LEGACY_ADD_TRAMPOLINE config option

---

electrum/gui/qt/__init__.py
electrum/gui/qt/main_window.py
electrum/gui/qt/plugins_dialog.py
electrum/gui/qt/wizard/wallet.py
electrum/plugin.py
electrum/plugins/jade/manifest.json
electrum/plugins/labels/qt.py
electrum/plugins/nwc/qt.py
electrum/plugins/psbt_nostr/qt.py
electrum/plugins/revealer/manifest.json
electrum/plugins/revealer/qt.py
electrum/simple_config.py
electrum/wizard.py

- both internal and external plugins require GUI install (except internal HW plugins, which are 'auto-loaded' and hidden)
- remove init_qt hook
- in Qt, reload wallet windows if plugin enabled/disabled
- add 'uninstall' button to PluginDialog
- add 'add plugins' button to wizard hw screen
- add icons to the plugin list

Add/remove plugins from GUI

---

electrum/gui/qt/seed_dialog.py

This is only used when displaying wallet xpub in wizard for multisig setup.

qt: SeedWidget: for xpubs, show copy button next to QR button.

---

electrum/gui/qml/components/ExportTxDialog.qml
electrum/gui/qml/components/TxDetails.qml
electrum/gui/qml/components/controls/ButtonContainer.qml
electrum/gui/qml/components/main.qml
electrum/gui/qml/qeapp.py
electrum/gui/qt/transaction_dialog.py
electrum/gui/qt/util.py
electrum/plugins/psbt_nostr/manifest.json
electrum/plugins/psbt_nostr/psbt_nostr.py
electrum/plugins/psbt_nostr/qml.py
electrum/plugins/psbt_nostr/qml/main.qml
electrum/plugins/psbt_nostr/qt.py

also some boilerplate for plugins extending QML GUI

psbt_nostr: split generic and UI parts, implement for qml

---

electrum/commands.py

The eval type of the `new_password` argument to the `password` command should be `str`, currently the command is not usable as it tries to eval `new_password` as bool.

cmd: fix password command eval type

---

electrum/plugins/psbt_nostr/psbt_nostr.py
electrum/plugins/psbt_nostr/qml.py
electrum/plugins/psbt_nostr/qml/main.qml
electrum/plugins/psbt_nostr/qt.py

also don't break the receive loop when an invalid tx is received, fix qml wallet switch, move can_send_psbt logic to backend, exclude 2FA wallets.

plugins: psbt_nostr: start processing PSBTs after wallet is_up_to_date

---

electrum/gui/qt/util.py

fixes #9761
There was a type error in `add_menu_button` as it got passed a QIcon but expected a string icon name, now it can handle both. Can be reproduced by opening the Sign/Verify Message dialog.

qt: fix OverlayControlMixin.add_menu_button type error, fix type hints

---

electrum/submarine_swaps.py

In `SwapManager.pay_invoice()` we pass attempts=10 to `lnworker.pay_invoice()`.
The comment says it's only supposed for unit tests:
```
async def pay_invoice(
self, invoice: Invoice, *,
amount_msat: int = None,
attempts: int = None,  # used only in unit tests
```
Without attempts it will be limited to 30 if the payer uses trampoline, otherwise it uses a timeout of 120 sec.

swaps: don't limit attempts when paying swap invoice

---

electrum/plugins/psbt_nostr/psbt_nostr.py

Reading the relays directly from the config has the benefit that user changes to the config are used directly when sharing a new psbt, instead of requiring a restart to use the new relays.

plugin: psbt_nostr: read psbt cosigning relays directly from config

---

electrum/harden_memory_linux.py
run_electrum

This module tries to restrict the ability of other processes to access the memory of our process. This is Linux-specific.
The immediate motivation is that, when having LN channels with anchor outputs, we need to be able to spend onchain utxos to bring fees to e.g. second-stage htlc transactions or to spend anchors, and for this the current idea is to keep the wallet password in memory.
-----
Traditionally, on Linux, one process can access the memory of another arbitrary process if both are running as the same user (uid). (Root can ofc access the memory of ~any process)
Programs can opt-out from this by setting `prctl(PR_SET_DUMPABLE, 0);`
- see longer comment at the top of the new module
- see https://man.archlinux.org/man/PR_SET_DUMPABLE.2const.en
-----
Also, from …

add harden_memory_linux: harder for other processes to read our memory

---

electrum/gui/qt/plugins_dialog.py
electrum/plugin.py

Fixes 3 issues:
1.
If the plugin zip got already deleted while being in the `PluginDialog` of another installation of the same plugin, 
trying to delete it again will raise an exception, and closing the installing `PluginDialog` tries to delete the file if the user doesn't click on `Install...`.
This is fixed by catching the `FileNotFound` exception in `download_plugin_dialog()` and `add_plugin_dialog()` .
Related to this, if the user tries to install an external plugin that is already installed, and then closes the PluginDialog, the PluginsDialog will get into a bad state, throwing an exeption on future instantiations as `add_plugin_dialog()` will remove the required zipfile when cancelling the dialog, but the metadata will stay in `Plugins`.
This is fixed by checking if the plugin is …

fix: PluginsDialog bugs causing exceptions

---

electrum/gui/qt/transaction_dialog.py

Fixes the following exception:
```
26.46 | E | gui.qt.exception_window.Exception_Hook | exception caught by crash reporter
File "/home/user/code/electrum-fork/electrum/gui/qt/main_window.py", line 2300, in do_process_from_text
self.show_transaction(tx)
~~~~~~~~~~~~~~~~~~~~~^^^^
File "/home/user/code/electrum-fork/electrum/gui/qt/main_window.py", line 1127, in show_transaction
show_transaction(
~~~~~~~~~~~~~~~~^
tx,
^^^
...<4 lines>...
show_broadcast_button=show_broadcast_button,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
)
^
File "/home/user/code/electrum-fork/electrum/gui/qt/transaction_dialog.py", line 418, in show_transaction
d = TxDialog(
tx,
...<4 lines>...
on_closed=on_closed,
)
File "/home/user/code/electrum-fork/electrum/gui/qt/transaction_dialo …
```

fix: type error when loading psbt with lnworker enabled

---

electrum/gui/qt/plugins_dialog.py
electrum/plugin.py

Currently there is no way to update a plugin with a new version in the plugin manager. The user first has to uninstall the old version, then install the new version. This PR adds an "Update..." button that will show if the user loads a plugin of the same (manifest) name but a different hash, allowing for updates/downgrades.

plugins: handle updating plugins from plugin manager

---

electrum/gui/qt/exception_window.py

If a dialog is open while an exception was raised in the dialog, the input of `Exception_Window` is blocked and the user cannot click the button to submit the issue report. Only if the other dialog is closed `Exception_Window` starts responding. By setting the modality of `Exception_Windows` to `ApplicationModal` the `Exception_Window` will get the 'highest priority' and accepts input even if other dialogs are open.
Can be tested by applying this diff and then checking the Trampoline checkbox in settings dialog:
```diff
diff --git a/electrum/gui/qt/settings_dialog.py b/electrum/gui/qt/settings_dialog.py
index aadd04b71..6f8218963 100644
--- a/electrum/gui/qt/settings_dialog.py
+++ b/electrum/gui/qt/settings_dialog.py
@@ -115,6 +115,7 @@ class SettingsDialog(QDialog, QtEventListener): …
```

fix: blocked Exception_Window by setting modality

---

electrum/channel_db.py
electrum/lnrater.py

`suggest_node_channel_open()` did suggest peers with onion hostname, even if the caller has no proxy enabled. This causes channel openings in the gui to sometimes just not work and show a `CancelledError()` becaues it wasn't able to connect to the peer.
Now only clearnet peers will get recommended, as these will always work.
The change in channel_db.py is just a fixed linting error.

fix: don't suggest onion peers for channel opening

---

electrum/payment_identifier.py

When paying a 0 amount invoice, after clicking pay the entered amount will get saved in
`PaymentIdentifier.boltPaymentIdentifier.bolt11.amount_msat`. However if the user clicks cancel instead of pay, and then changes the amount, amount_msat will not get updated, as it is not None anymore. If the user clicks pay again, it will pay the previously entered wrong amount. 
This change instead checks the `LnAddr` amount instead of the `Invoice` amount, which will always stay `None` for 0 amount invoices.

fix: SendTab not updating amount after text input change

---

electrum/daemon.py
electrum/gui/qt/__init__.py
electrum/gui/qt/main_window.py
electrum/lnchannel.py
electrum/transaction.py
electrum/txbatcher.py
electrum/wallet.py

This makes it possible to use `txbatcher` without unlocking the wallet.
- if a password is required, send a signal to the GUI, unless the wallet is unlocked.
- if a transaction is verified, cancel the password future; the next iteration might not require a password anymore (for example, after a commitment tx has been mined we do not need to sweep anchor outputs anymore)

Txbatcher without password in memory

---

electrum/json_db.py
electrum/plugin.py
electrum/plugins/nwc/nwcserver.py
electrum/plugins/psbt_nostr/psbt_nostr.py
electrum/plugins/psbt_nostr/qml.py
electrum/plugins/psbt_nostr/qt.py
electrum/simple_config.py
electrum/wallet.py
electrum/wallet_db.py

Adds a method `get_plugin_dict()` to `WalletDB` to be used by plugins with their manifest name if they have to store data in the db. If the wallet is closed, data of plugins that are not registered in the config (-> not installed) will then get deleted from the db.

plugins: structure plugin storage in wallet db and prune uninstalled plugins data

---

electrum/gui/qt/wizard/server_connect.py
electrum/gui/qt/wizard/terms_of_use.py

Moves the 2nd sentence in network tab below the checkboxes and adds a bit of spacing below the electrum logo in the Terms of Use tab.

followup: qt terms of use, move label in network tab

---

electrum/plugins/psbt_nostr/psbt_nostr.py

Checks if the pubkey of the author sending the psbt cosigning request is in our list of cosigner pubkeys to prevent accepting "fake" requests from other pubkeys. 
I don't (additionally) request the cosigner pubkeys in the relay query filter, as this would let the relays know the cosigner pubkeys without obvious benefit.

fix: verify author pubkey of psbt nostr events

---

electrum/lnworker.py
electrum/mpp_split.py
tests/test_lnpeer.py

I noticed certain ln payments become very unreliable. These payments are ~21k sat, from gossip sender, with direct channel.
Due to the recent fix https://github.com/spesmilo/electrum/pull/9723 `LNPathFinder.get_shortest_path_hops()` will not use channels for the last hop of a route anymore that aren't also passed to it in `my_sending_channels`:
```python
if edge_startnode == nodeA and my_sending_channels:  # payment outgoing, on our channel
if edge_channel_id not in my_sending_channels:
continue
```
Conceptually this makes sense as we only want to send through `my_sending_channels`, however if the only channel between us and the receiver is a direct channel that it got from the r_tag and it's not passed in `my_sending_channel` it's not able to construct a route now.
Previously this type …

ln: don't exclude single part configs for too small payments

---

electrum/lnchannel.py
electrum/lnworker.py
tests/test_lnchannel.py

lightning: verify single payment limits for swaps and invoices

---

electrum/gui/qt/wizard/terms_of_use.py

adds some delay before detecting the scrollbar in the terms of use dialog. This prevents it from falsely detecting a scrollbar and disabling the "I Agree" button even if there is no scrollbar. I noticed this issue on windows, the order in which the window is created seems to be slightly different from linux/wayland there.

fix: make ToU scrollbar detection more reliable

---

electrum/gui/qt/plugins_dialog.py
electrum/plugin.py

Adds functionality that allows the user to store the plugin authorization pubkey without having to edit files/registry manually. On Linux systems it spawns the commands in a subprocess with polkits pkexec which will trigger an OS prompt to execute the commands as root. The user sees the executed commands and can either authorize with the root password or decline.
On windows it uses the windows `ShellExecuteExW` api to execute reg.exe with elevated permissions to edit the registry, this also triggers an OS dialog the user can accept or decline (UAC dialog).
There is also functionality to reset the key again, which works in the same way.
I tested this from source on both plattforms and as AppImage and Windows installer.
On macos it wraps the shell command in applescript and runs the …

plugins: add functionality to allow setting plugin pubkey from gui

---

electrum/gui/qt/channel_details.py
electrum/lnchannel.py
electrum/lnpeer.py

If a force-close happens due to e.g. a feerate disagreement or an invalid signature, etc, and the remote peer sends us an error, it can be useful if users can provide us with this error. If the user does not have logging enabled when the error is sent, without this persistence it will likely get lost.

lnchannel: persist error sent by remote peer into db

---

electrum/submarine_swaps.py

Changes the attempt to liquidity updates in the swapserver to a simple loop which regularly (30 sec) checks if the liquidity has changed, and broadcasts a new swapserver announcement if so.
This is simpler and more reliable than trying to trigger an update on each change of liquidity.

swaps: Improve accuracy of swapserver liquidity announcement.

---

electrum/gui/qml/qeswaphelper.py
electrum/gui/qt/main_window.py
electrum/gui/qt/swap_dialog.py
electrum/submarine_swaps.py

introduces a class SwapOffer which is used instead of passing around offers in dicts.
Also fixes incorrect variable naming of swapserver npubs / public keys by assigning the npub instead of the hex pubkey to config.SWAPSERVER_NPUB
updates qt swap dialog after changing the swap provider so the shown values get updated when switching swapservers.

swaps: replace offers dict with class, fix incorrect naming

---

electrum/commands.py
electrum/contacts.py
electrum/dns_hacks.py
electrum/dnssec.py
electrum/gui/qml/qeinvoice.py
electrum/gui/qt/main_window.py
electrum/lnworker.py
electrum/payment_identifier.py
electrum/paymentrequest.py
electrum/util.py

dnspython has [added](https://github.com/rthalley/dnspython/commit/7f197681162b420c8b3fd5b5339628378cf80d62) an async interface in version 2.0 which we already require in our requirements. 
The api is the same as the sync version and is stable between 2.0 and the current 2.7. 
So i switched the dnspython calls in dnssec (used for openalias resolving) and the lightning dns seed fetching to use the async interface instead of threads.

dns: use async dnspython interface 

---

electrum/lnurl.py
electrum/payment_identifier.py

Makes the lookup of openalias and lightning addresses concurrent and prefers the result of the lightning address if both are available on the same address. 
Technically it doesn't depend on https://github.com/spesmilo/electrum/pull/9833 (async dns) but without it this wouldn't provide a benefit.

make openalias and lnaddress lookup concurrent

---

electrum/mpp_split.py
tests/test_mpp_split.py

passing `exclude_single_channel_splits` to `suggest_splits` did not reliably remove single channel splits from configurations if the same configuration also contained a valid split on another channel
This [comment](https://github.com/spesmilo/electrum/blob/f908a34b0b100a9b81ed9a5c76e128eb73776bdc/electrum/lnworker.py#L1942C47-L1942C51) explains `exclude_single_channel_splits` as:
> we don't split within a channel when sending to a trampoline node, 
the trampoline node will split for us

fix: suggest_splits exclude single channel splits

---

README.md

To help users to find the translations add the link to Crowdin in addition to a bagde on top of the README

chore: README.md add link to Crowdin translations

---

fastlane/metadata/android/en-US/full_description.txt

Added "libre" to help users from PlayStore to understand that this is FOSS app.
Links moved to bottom so a user will see features first.
Used allowed HTML tags: `<b>`, `<a>` for links and `<ul>` instead of bullets.
Added a link to Crowdin translations to attract more translators.
See about formatting https://f-droid.org/docs/All_About_Descriptions_Graphics_and_Screenshots
I also will create a Wikipedia page https://en.wikipedia.org/wiki/Electrum_Bitcoin_Wallet based on https://en.bitcoin.it/wiki/Electrum and it's German translation https://de.wikipedia.org/wiki/Electrum_Bitcoin_Wallet.
Please review it too.

chore: improve Fastlane full_description.txt

---

electrum/lnutil.py

This is so we don't error out when GUI hinted minimum 2mBTC channel size is used for peers that constrain max-htlc-in-flight to 45% of channel capacity. (see #8712)

lnutil: lower minimum max-htlc-in-flight for new channels from 100_000_000 to 90_000_000

---

electrum/address_synchronizer.py
electrum/txbatcher.py

get_tx_height previously did not consider whether the walletDB has the full tx for the corresponding txid, and could consider a tx even "mined" and spv-ed, even if we were missing the raw tx.
Now if the full tx is missing or the tx in the db is partial, get_tx_height considers it to be LOCAL.
In particular the txbatcher, in `run_iteration`,
- first saves a tx as local *unsigned* (to reserve UTXOs),
- then signs it and tries to broadcast it.
The history tx will later transition to local and signed, after we get back the broadcasted tx via the Synchronizer dance. In the meantime there is a race where we have an unsigned tx in the history, but the txid could already transition to mempool or even to mined, before we download the full raw tx from the server. During that time window, it makes …

adb.get_tx_height: return "LOCAL" height if missing full signed tx

---

electrum/gui/qml/components/controls/ServerConfig.qml
electrum/gui/qml/qeconfig.py
electrum/gui/qt/network_dialog.py
electrum/simple_config.py

some cosmetic followups to https://github.com/spesmilo/electrum/pull/9243
I think the checkbox text needs to be more descriptive.
I also added a longer explanation for the option.  However TBH to properly explain the tradeoffs it would need an even longer explanation, which would also touch on auto-connect. 
-----
In general I think the auto-connect and oneserver options are inherently intertwined (already showcased by the fact that the `auto_connect and oneserver` combination is disallowed).  Maybe we could have a slider instead of two checkboxes. The slider of "trust" :D
```
(A1. auto_connect) --> (A2. no auto_connect) --> (A3. oneserver)
```
Also consider https://github.com/spesmilo/electrum/issues/9528, which also kind of fits into the slider.  Then we could have:
```
(B1. …
```

gui: oneserver option: make text more verbose

---

electrum/gui/messages.py
electrum/gui/qt/network_dialog.py

If oneserver is enabled, display 'Fork detection disabled' in the split_label

network dialog: replace checkboxes with tri-state connect_mode ComboBox

---

electrum/commands.py
electrum/constants.py
electrum/simple_config.py
run_electrum

- constants.py: add `datadir_subdir`, `cli_flag`, `config_key` methods
- use these to generalise recurring "switch-like" ifs
- this effectively also adds a `--mainnet` CLI option
- closes https://github.com/spesmilo/electrum/issues/9790

constants.py: add datadir_subdir, cli_flag, config_key methods

---

electrum/plugins/digitalbitbox/digitalbitbox.py
electrum/plugins/ledger/ledger.py
electrum/transaction.py
tests/test_transaction.py

This new `Transaction.verify_sig_for_txin` function is an instance method of `Transaction` instead of `PartialTransaction`.
It takes a complete txin, a pubkey and a signature, and verifies the signature.
- `get_preimage_script` is renamed to `get_scriptcode_for_sighash` and now effectively has two implementations:
- the old impl became `PartialTxInput.get_scriptcode_for_sighash`
- this assumes we are the ones constructing a spending txin and can have knowledge beyond what will be revealed onchain
- the new impl is in the base class, `TxInput.get_scriptcode_for_sighash`
- this assumes the txin is already "complete", and mimics a consensus-verifier by extracting the required fields
from the already complete witness/scriptSig and the scriptpubkey of the funding utxo
- `serialize_preimage` …

transaction: add method verify_sig_for_txin

---

electrum/commands.py
electrum/lnworker.py
tests/test_commands.py
tests/test_lnpeer.py

Adds four new commands to the CLI which allow handling hold invoices
* add_hold_invoice
* cancel_hold_invoice
* check_hold_invoice
* settle_hold_invoice
Users have to bring their own preimage.

cli: add hold invoice cli functionality

---

electrum/commands.py
electrum/daemon.py
electrum/gui/qml/qedaemon.py
electrum/gui/qt/__init__.py
electrum/gui/stdio.py
electrum/gui/text.py
electrum/simple_config.py
run_electrum
tests/regtest/regtest.sh

- CURRENT_WALLET is set when a single wallet is loaded in memory.
- if several wallets are loaded, RPCs must specify which wallet they apply to, using the --wallet option.
- the fallback to 'default_wallet' essentially only applies when creating a new wallet file

Replace config GUI_LAST_WALLET with CURRENT_WALLET

---

electrum/gui/qt/new_channel_dialog.py
electrum/lnrater.py

the `while True:` loop in `suggest_node_channel_open()` of lnrater would not break if there are only peers that are not "good" and continue the loop. This can likely happen for example on testnet. As a result the gui blocks and electrum has to be killed. 
This change removes the tested candidates from the avaliable list of candidates so each node gets tested only once and the loop terminates if no valid peers are available.

fix: prevent lnrater from blocking if no good peers

---

RELEASE-NOTES

* adds link to swapserver setup docs
* add lightning address contacts
* hint that anchor channels are the default
* fixes some typos

additions to 4.6.0 changelog

---

electrum/gui/qml/components/NostrSwapServersDialog.qml
electrum/gui/qml/components/SwapDialog.qml
electrum/gui/qml/components/main.qml
electrum/gui/qml/qeswaphelper.py
electrum/submarine_swaps.py

changes qeswaphelper to share a single, long lived transport instance instead of opening new transports to do swaps and fetch offers. 
This allows to continuosly fetch offers, so events which get returned later by slow relays don't get lost and the fee values stay updated. 
Also fixes a race causing the list to miss swap servers sometimes, as the current implementation fetches only until `swap_manager.is_initialized()` is set, which will get set as soon as an event of the configured swap server is received. So if the event of the configured swap server is received as first, all server events coming in after it would get ignored.
Also replaces the threads with asyncio coroutines.

fix: use single long lived swap transport in qeswaphelper

---

electrum/commands.py
electrum/gui/qml/qeswaphelper.py
electrum/gui/qt/swap_dialog.py
electrum/submarine_swaps.py

QML:
now uses the `eta:2` fee policy for the funding tx of forward swaps as using the config fee policy could lead to issues (maybe too high or low), not configurable in the qml swap dialog.
Qt:
disables the `SwapDialog` fee slider on reverse swaps as the its value is not used anyways (txbatcher uses the swap fee policy for the claim transaction), and setting the claim tx fee could be dangerous (too low fee could allow server to refund itself after getting the preimage if the claim tx doesn't confirm in time).
Swaps:
remove `SwapManager.get_swap_tx_fee()` as it used the config fee policy and was used to calculate the claim tx fee amount, which is incorrect as the claim tx fee is not estimated with the user configurated fee policy in txbatcher, but the separate swap fee policy.
Replaced …

swaps: use eta:2 instead of config fee policy in qml, disable qt fee slider on reverse swaps

---

electrum/gui/qt/plugins_dialog.py

this changes PluginsDialog to disable the "Enable" button of plugins that are missing dependencies (e.g. amodem) instead of not showing them at all. A tooltip is shown explaining the user why the plugin is disabled.

plugins: disable "Enable" button of unavailable plugins in PluginsDialog

---

electrum/gui/qt/send_tab.py

Fixes #9940 exception ocurring when entering a '!' amount with a payment identifier that is not allowed to send max (e.g. bolt11).
Fixes #8947 exception when "Max" is still set from previous PI and the PI gets replaced by one that doesn't allow max sending.

fix: handle ! amount for payment identifiers more gracefully

---

electrum/gui/qt/__init__.py

Explicitly sets the `AA_DontShowIconsInMenus` attribute to false as it defaults to true on some Qt versions / environments which causes icons to not show up in the menus (e.g. MacOS).
see https://forum.qt.io/post/813228
The attribute has to be set on `self.app` after the` QApplication` has been instantiated (https://doc.qt.io/qt-6/qt.html#ApplicationAttribute-enum)

qt: fix: set ApplicationAttribute.AA_DontShowIconsInMenus False

---

run_electrum

```
$ ./run_electrum
Error: No module named 'dns'. Try 'sudo python3 -m pip install <module-name>' $ pip install dns
ERROR: Could not find a version that satisfies the requirement dns (from versions: none) ERROR: No matching distribution found for dns
$ pip install dnspython
Collecting dnspython
Downloading dnspython-2.7.0-py3-none-any.whl (313 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 313.6/313.6 kB 3.4 MB/s eta 0:00:00
Installing collected packages: dnspython
Successfully installed dnspython-2.7.0
$ ./run_electrum
Error: No module named 'certifi'. Try 'sudo python3 -m pip install <module-name>'
$ ./run_electrum
Error: No module named 'google'. Try 'sudo python3 -m pip install <module-name>' $ pip install google
Collecting google
Downloading google-3.0.0-py2.py3-none-any.whl (45 kB) …
```

run_electrum: improve check_imports()

---

electrum/gui/qml/components/controls/BtcField.qml
electrum/gui/qml/qeinvoice.py

textAsSats was being set to 0 initially, regardless of actual text, only healing after onTextChanged.
fixes https://github.com/spesmilo/electrum/issues/9974
-----
@accumulator could you review if this looks ok?
- not sure exactly what https://github.com/spesmilo/electrum/commit/376d88115445c918935d43ae92e0a52bfe3da42b was fixing
- e.g. do we need to explicitly initialise the `text` field to `""` or similar?

qml: set BtcField.textAsSats initial value to match its text

---

electrum/gui/qt/paytoedit.py
electrum/gui/qt/qrtextedit.py
electrum/gui/qt/send_tab.py
electrum/gui/qt/util.py

There was too much code duplication - there still is a bit...
- in some places buttons had text "Read QR code with camera", in others it was "Read QR code from camera"
- https://github.com/spesmilo/electrum/commit/63c224cb53739c5b4b5630e3a0bfb8208d785879 added a "on_qr_from_file_input_btn" input method, which was not added everywhere.
- was missing in add_qr_input_combined_button and in editor_contextMenuEvent

qt: qrtextedit: rm some duplication

---

electrum/commands.py
electrum/lnpeer.py
tests/test_commands.py

Allowing to create hold invoices just by providing a payment hash instead of the preimage right from the beginning allows for additional use cases where the recipient doesn't have access to the preimage when creating the invoice. 
As a side effect invoices won't automatically get settled when the channel holding the htlcs gets force closed as there is no preimage available to do so.

cli: use payment hash for hold invoice creation

---

electrum/gui/qt/history_list.py

The endInsertRows() call triggers the main calls to get_data_for_role(): in the current order, the try/except goes to the exception every time
In the updated order, it doesn't do it ever
We have full control over what's in the cache, and we always fully populate it, so we can get rid of the fallback

Populate tx_status_cache before it's used, not after. Only compute short_id when requested 

---

contrib/osx/README.md
contrib/osx/extract_sigs.sh

Adds docs to osc README on how to create a self-signed certificate and use it to sign the dmg. Also adds a check in `extract_sig.sh` to exclude the notarization files from the comparison if `IS_NOTARIZED` is explicitly set `false`.

build-osx: add docs for testing with self-signed certificate

---

electrum/plugins/revealer/qt.py

Fixes #10007
The `create_noise_file()` function in the revealer plugin did catch exceptions, preventing them from triggering the `CrashReporter`, this caused an incorrect German translation with missing closing bracket to break the functionality silently for the last 7 years the translation existed.
Also fixed the translation on crowdin and downvoted the incorrect one, so hopefully the correct locale will make it into the next build.

plugin: revealer: stop catching exceptions on noise file creation

---

electrum/i18n.py
tests/test_i18n.py

We often call str.format() on translated strings.
E.g. `_("time left: {} seconds").format(t1)`
If the translated string has a different format syntax, this can raise at runtime.
This PR adds some runtime checks that try to ensure the source string and the translated string have a similar format syntax. If the checks fail, `_()` will "reject" the translation by returning the source string.
fixes https://github.com/spesmilo/electrum/issues/10010
ref https://github.com/spesmilo/electrum/issues/10007#issue-3203378250

i18n: syntax-check translations at runtime

---

electrum/commands.py

Only try to get wallet from daemon in the `command` decorator if the wallet_path is available to prevent raising `TypeError` when `daemon.get_wallet(path=None)` gets called.
Fixes https://github.com/spesmilo/electrum/issues/10012

commands: fix: only try to get wallet if wallet_path

---

electrum/gui/qml/components/WalletMainView.qml

when setting a transaction label in the qml `LightningPaymentDetails` or `TxDetails` dialogs which get opened directly by the `ReceiveDialog` (through the `onRequestPaid` callback) the label is not shown in the main transaction list as no callback for `detailsChanged` is registered which gets called when the label changes. As a result the label is only visible after the main list gets reloaded (e.g. restart). This commit adds callbacks for `detailsChanged` so the labels are shown directly when changing them after receiving the payment.
Can be tested by: Creating a lightning invoice -> paying it while keeping the QR code dialog open -> setting a label when it switches to the payment details after the payment arrived -> going back to the main menu -> label is not visible.

fix: qml: update tx label on detailsChanged signal

---

electrum/gui/qml/components/wizard/WCWalletType.qml

Deletes the `seed_type` key from `wizard_data` in `WCWalletType` if it is not explicitly set to prevent a stale value from a previous wizard flow if the user goes back in the wizard and selects a different wallet type instead of completing the wizard with the previously selected wallet type.
This happens as the `apply()` function gets called with the previously set radio button, e.g. 2fa, if the user goes back. If he then selects multisig the `2fa_segwit` `seed_type` won't get cleared and cause the exception later.
Example exception when first selecting 2fa, then going back and creating a multisig wallet:
```
32.77 | E | gui.qml.qeapp.Exception_Hook | exception caught by crash reporter
File "/home/vagrant/electrum/electrum/gui/qml/qewizard.py", line 40, …
```

fix: qml: wizard: delete seed_type from wizard_data if not set explicitly

---

electrum/gui/qt/__init__.py
electrum/gui/qt/confirm_tx_dialog.py
electrum/gui/qt/main_window.py
electrum/gui/qt/swap_dialog.py

When closing Electrum with open `ConfirmTxDialog` the following exception is raised:
```
1319.20 | E | gui.qt.exception_window.Exception_Hook | exception caught by crash reporter
File "/home/user/code/electrum-fork/electrum/gui/qt/send_tab.py", line 575, in do_pay_or_get_invoice
self.do_pay_invoice(self.pending_invoice)
~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
File "/home/user/code/electrum-fork/electrum/gui/qt/send_tab.py", line 602, in do_pay_invoice
self.pay_onchain_dialog(invoice.outputs, invoice=invoice)
~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/user/code/electrum-fork/electrum/gui/qt/send_tab.py", line 328, in pay_onchain_dialog
tx, is_preview = self.window.confirm_tx_dialog(make_tx, output_value, …
```

fix: qt: handle main_window.gui_object.timer being None

---

electrum/base_crash_reporter.py
electrum/gui/qml/components/ExceptionDialog.qml
electrum/gui/qml/qeapp.py
electrum/gui/qt/exception_window.py
electrum/simple_config.py

This changes the crash reporter in the Qt/QML guis a bit.
- on clicking "Send", there is now an additional small confirmation popup
- this makes it harder to accidentally send a report
- the "Never" button and the corresponding `config.SHOW_CRASH_REPORTER` option is removed
-  we now always hook into `sys.excepthook` to show the crash reporter
- don't show crash reporter multiple times for the "same" exception
- at least until the user restarts the program (there is no persistence)
- exceptions are grouped the same way the crash reporter server is grouping them (I think)
- in case there's e.g. a thread with timer spamming an exception erroneously,
we won't spam the user with the crash reporter window
The motivation is https://github.com/spesmilo/electrum/pull/10049#issuecomment-3089278083 …

crash reporter: rm `Never`, add confirm to `Send`, and only show window once per exc group

---

.cirrus.yml

It seems like the OS version of the CI image has been bumped, the regtest of PR https://github.com/spesmilo/electrum/pull/10073 fails for me with this error:
```
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 111702 files and directories currently installed.)
Preparing to unpack .../jq_1.7.1-3ubuntu0.24.04.1_amd64.deb ...
Unpacking jq (1.7.1-3ubuntu0.24.04.1) over (1.7.1-3build1) ...
Preparing to unpack .../libjq1_1.7.1-3ubuntu0.24.04.1_amd64.deb ...
Unpacking libjq1:amd64 (1.7.1-3ubuntu0.24.04.1) over (1.7.1-3build1) ...
Setting up libjq1:amd64 …
```

fix failing pip installs in regtest CI

---

electrum/gui/qml/java_classes/org/electrum/qr/SimpleScannerActivity.java

When putting app to background with qr scanner active, then moved to foreground again, `SimpleScannerActivity` instance is not destroyed, but the local `mScannerView` was re-initialized with a new instance (through `startCamera()`) regardless of pre-existing instance, and added to the `contentFrame`. This leaves the previous `mScannerView` instance in limbo, potentially getting garbage collected at unpredictable times.

android: don't keep adding BarcodeScannerView instances to contentFrame when starting camera

---

electrum/gui/qt/__init__.py

Removes the '.desktop' suffix from the
`QGuiApplication.setDesktopFileName` argument to prevent the following warning on startup of Electrum:
```
QGuiApplication::setDesktopFileName: the specified desktop file name ends with .desktop.
For compatibility reasons, the .desktop suffix will be removed.
Please specify a desktop file name without .desktop suffix
```
The [qt docs](https://doc.qt.io/qtforpython-6/PySide6/QtGui/QGuiApplication.html#PySide6.QtGui.QGuiApplication.desktopFileName) say that `desktopFileName` is "... is the file name, without the full path or the trailing “.desktop” extension of the desktop entry that represents this application according to the freedesktop desktop entry specification."
In QML we do the same:
https://github.com/spesmilo/electrum/blob/da18c975a2f2ac690276 …

fix: remove .desktop from setDesktopFileName argument

---

electrum/gui/qml/qetxfinalizer.py
electrum/gui/qt/confirm_tx_dialog.py
electrum/wallet.py
tests/test_wallet_vertical.py

Right now if a lightning reserve utxo is required and there is already a reserve sized utxo available, `make_unsigned_transaction()` will still add the reserve as input to a 'spend max' transaction and add a reserve change
output. This seems wasteful, this patch instead just removes the input from the tx so it is not spent at all.
The `PartialTxOutput.is_utxo_reserve` flag is kept as it is also used in the qml gui.

wallet: don't spend reserve utxo to create new reserve utxo

---

electrum/gui/qml/components/ImportAddressesKeysDialog.qml
electrum/gui/qml/components/ImportChannelBackupDialog.qml
electrum/gui/qml/components/OpenChannelDialog.qml
electrum/gui/qml/components/ScanDialog.qml
electrum/gui/qml/components/SendDialog.qml
electrum/gui/qml/components/SweepDialog.qml
electrum/gui/qml/components/WalletMainView.qml
electrum/gui/qml/components/controls/QRScan.qml
electrum/gui/qml/components/wizard/WCHaveMasterKey.qml
electrum/gui/qml/components/wizard/WCImport.qml
electrum/gui/qml/java_classes/org/electrum/qr/SimpleScannerActivity.java
electrum/gui/qml/qeapp.py
electrum/gui/qml/qeqrscanner.py
electrum/gui/qml/qetypes.py

android: pass on QR binary scan result data as well
qml: add signals for QEQRScanner and fallbacks, add QEBytes container type so we can pass along byte arrays between QML and python, port qr scan occurrences to new signals.

simplify QR scanner QML interface, remove properties, add results to signals

---

electrum/constants.py

Currently running the help command lists the supported chains in random order. This patch changes the ordering to be lexicographical.
```
$ ./run_electrum --help
usage: run_electrum [-h] [--version] [-v VERBOSITY] [-D ELECTRUM_PATH] [-w WALLET_PATH] [-P]
[--testnet] [--signet] [--mainnet] [--simnet] [--regtest] [--testnet4] [-o]
[--rpcuser RPCUSER] [--rpcpassword RPCPASSWORD] [--forgetconfig]
<command> ...
[...]
global options:
-v VERBOSITY          Set verbosity (log levels)
-D ELECTRUM_PATH, --dir ELECTRUM_PATH
electrum directory
-w WALLET_PATH, --wallet WALLET_PATH
wallet path
-P, --portable        Use local 'electrum_data' directory
--testnet             Use testnet chain
--signet              Use signet chain
--mainnet             Use mainnet chain
--simnet              Use simnet …
```

constants: NETS_LIST to have deterministic ordering

---

electrum/commands.py
electrum/lnutil.py
electrum/lnworker.py
tests/test_lnpeer.py

Adds `max_cltv`, `max_fee_millionths` and `fee_cutoff_msat` parameters to the `lnpay` cli command which allow to specify a custom `PaymentFeeBudget` for the lnpay payment. Allowing to specify a these parameters can be useful for usecases like https://github.com/spesmilo/electrum/issues/10056.
Closes #10056

cli: add max_cltv, max_fee_msat parameters to lnpay

---

electrum/i18n.py
electrum/logging.py

adds very basic form of opt-in rate-limiting of log spam
related https://github.com/spesmilo/electrum/pull/10011#discussion_r2190209204

logging: add "only_once=False" param to logger.info/warning/etc calls

---

electrum/interface.py
electrum/lrucache.py
electrum/network.py
tests/__init__.py
tests/test_interface.py
tests/test_lntransport.py

Often when the wallet creates a tx, the flow is:
- create unsigned tx
- sign tx
- broadcast tx, but don't save it in wallet history
- server sends notification that status of a subscribed address changed
- client calls scripthash.get_history
- client sees txid in scripthash.get_history response
- client calls blockchain.transaction.get to request missing tx
Instead, now when we broadcast a tx on an interface, we cache that tx *for that interface*,
and just before calling blockchain.transaction.get, we lookup in the cache.
Hence this will often save a network request.
-----
In addition to the above:
- some code needed to be moved around (hence review commit-by-commit)
- adds a small new unit test framework into `test_interface.py`, including a toy electrum server implementation
- adds a …

interface: don't request same tx from server that we just broadcast to it

---

electrum/bitcoin.py
electrum/fee_policy.py
electrum/gui/qml/qetxfinalizer.py
electrum/gui/qt/confirm_tx_dialog.py
electrum/gui/qt/main_window.py

Review should be done commit-by-commit. First few commits are conceptual clean-up.
- split dust_threshold from minrelayfee, make it hardcoded instead
- the dust threshold in bitcoin core is calculated with a 3 sat/vbyte feerate,
which we were interpreting as 3*minrelayfee
- and now bitcoin core is considering changing the minrelayfee (1->0.1 s/b),
independently from the dust threshold
- fee_policy: lower min relay fee from 1 sat/byte to 0.1 s/b
- minrelayfee is still server-reported, but the clamps are changed from [1, 50] to [0.1, 50] sat/vbyte
- dynamic feerates coming from the estimator are still clamped to [1, 1500] sat/vbyte
- ~~util: increase feerate quanta from 0.1 sat/vbyte to 0.01 sat/vbyte~~
closes https://github.com/spesmilo/electrum/issues/10030
ref …

change minrelayfee clamps from `[1, 50]` to `[0.1, 50]` sat/vbyte

---

electrum/gui/qml/qetransactionlistmodel.py
tests/test_qml_qetransactionlistmodel.py

Reduces the precision of the date field in the qml transaction history
list to minutes. Seconds don't seem very useful in practice and add
clutter to the UI. This adapts the behavior to the Qt GUI.

qml: reduce tx history timestamp precision

---

electrum/bip32.py
electrum/gui/common_qt/plugins.py
electrum/gui/qt/wallet_info_dialog.py
electrum/keystore.py
electrum/plugins/trustedcoin/trustedcoin.py
electrum/wallet.py
tests/test_wizard.py

- fixes:
- disable `enable_keystore()`/`disable_keystore()` for 2fa wallets
- `disable_keystore()` should not destroy `root_fingerprint`/`derivation_prefix` information
- tests:
- add test case for old seed
- also test `disable_keystore()`
- add test for adding an unrelated seed to a watchonly wallet

wallet: enable/disable_keystore: some more fixes and tests

---

electrum/keystore.py
tests/test_wallet.py

check_password(None) should raise InvalidPassword when called on a keystore that has a password.
regression from https://github.com/spesmilo/electrum/commit/f86bdc86a2f2cc78f12e072b1eb5ae06f40d2178
fixes https://github.com/spesmilo/electrum/issues/10142

keystore: Old_KeyStore: fix check_password(None) if ks has password

---

electrum/submarine_swaps.py

limits the swapserver to process at most one request every 5 seconds and drops incoming requests if a queue size of 5 is reached

swaps: rate limit swapserver requests

---

electrum/commands.py
electrum/util.py
tests/test_commands.py

old behaviour:
```
>>> from electrum.commands import format_satoshis
>>> format_satoshis(1)
'1E-8'
```

commands: use format_satoshis consistently. don't use sci-notation

---

electrum/lnworker.py
electrum/submarine_swaps.py

Removes the persisted payment info from lnworker once a swap got failed. 
Stops persisting the OnionRoutingFailure as it is sufficient to delete the payment info to fail potential incoming htlcs. 
Deletes stored swap leftovers in lnworker and SwapManager

swaps: cleanup data after swap gets failed

---

contrib/android/buildozer_qml.spec
electrum/gui/qml/components/BIP39RecoveryDialog.qml
electrum/gui/qml/components/ExceptionDialog.qml
electrum/gui/qml/components/LnurlPayRequestDialog.qml
electrum/gui/qml/components/LoadingWalletDialog.qml
electrum/gui/qml/components/MessageDialog.qml
electrum/gui/qml/components/NostrSwapServersDialog.qml
electrum/gui/qml/components/OpenWalletDialog.qml
electrum/gui/qml/components/PasswordDialog.qml
electrum/gui/qml/components/Pin.qml
electrum/gui/qml/components/ReceiveDetailsDialog.qml
electrum/gui/qml/components/controls/ElDialog.qml
electrum/gui/qml/components/controls/HelpDialog.qml
electrum/gui/qml/components/main.qml
electrum/gui/qml/java_classes/org/electrum/qr/SimpleScannerActivity.java
electrum/gui/qml/qeapp.py
electrum/plugins/psbt_nostr/qml/PsbtReceiveDialog.qml

This PR makes the QML gui and the java android barcode scanner view compatible with the android edge-to-edge layout which is enforced from sdk version 35. The first commit also bumps the sdk version to 35.
It works by fetching the size of the status- and navigation bar from the android API and applying padding to the gui elements so that nothing is overlapped by the system bars.
I tested on Pixel 9, Android 16; Pixel 9 XL Android 16 emulator; Pixel 4a Android 13 emulator and Galaxy Tab A (2016) Android 8.1 (armv7).
Also tested with the 16kb patch commit of https://github.com/spesmilo/electrum/pull/10148.
If the edge-to-edge layout is not enforced (Android < 15) it doesn't opt-in and the UI stays as before.
Fixes #10139
Part of #9899

android: make app compatible with edge-to-edge layout

---

electrum/daemon.py
electrum/gui/qml/qedaemon.py

I think `_wallet_key_from_path` should not raise.
This is probably the sane way to deal with this.
Though all this is assuming that os.path.realpath can be treated as consistent/stateless.
closes https://github.com/spesmilo/electrum/issues/10182

daemon: get_wallet: handle OSError for weiiird paths

---

electrum/commands.py
electrum/gui/qt/main_window.py
electrum/lnpeer.py
electrum/util.py

Replace calls to deprecated asyncio.iscoroutinefunction with calls to [inspect.iscoroutinefunction](https://docs.python.org/3/library/inspect.html#inspect.iscoroutinefunction) to prevent the following deprecation warnings from showing up if running with Python 3.14:
```
/home/user/code/electrum-fork/electrum/util.py:1225: DeprecationWarning: 'asyncio.iscoroutinefunction' is deprecated and slated for removal in Python 3.16; use inspect.iscoroutinefunction() instead
assert asyncio.iscoroutinefunction(func), 'func needs to be a coroutine'
/home/user/code/electrum-fork/electrum/util.py:507: DeprecationWarning: 'asyncio.iscoroutinefunction' is deprecated and slated for removal in Python 3.16; use inspect.iscoroutinefunction() instead
if asyncio.iscoroutinefunction(func): …
```

chore: replace calls to asyncio.iscoroutinefunction

---

electrum/lnwatcher.py

Catch exceptions happening in lnwatcher callbacks to continue calling the remaining callbacks. Otherwise if one callback throws an exception it prevents execution of the following callbacks.

lnwatcher: catch callback exceptions

---

electrum/gui/qt/send_tab.py
electrum/wallet.py
tests/test_wallet_vertical.py

I don't understand what the "coins not used" comment meant here, @ecdsa. It was added in the change away from the old config.WALLET_BATCH_RBF option (https://github.com/spesmilo/electrum/commit/ab14c3e1382c1af48baff73b790aecfbd069eb8a).
The `coins` param *is used* in wallet.get_candidates_for_batching. Without setting that, the returned set of candidates was restricted to only base txs that had a large enough change output to cover *all* the newly added outputs. Instead, it is desirable to allow adding new inputs.
-----
closes https://github.com/spesmilo/electrum/issues/10201

qt confirm_tx_dialog: fix wallet.get_candidates_for_batching

---

electrum/wallet.py

Fixes AttributeError when calling `num_sats_can_receive()` while getting a request help text in wallets without lnworker. Fixes https://github.com/spesmilo/electrum/issues/8100#issuecomment-3294556043.
```
File "/usr/lib/python3.13/site-packages/electrum/gui/qt/request_list.py", line 103, in selection_changed
self.receive_tab.update_current_request()
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
File "/usr/lib/python3.13/site-packages/electrum/gui/qt/receive_tab.py", line 237, in update_current_request
help_texts = self.wallet.get_help_texts_for_receive_request(req)
File "/usr/lib/python3.13/site-packages/electrum/wallet.py", line 3446, in get_help_texts_for_receive_request
can_receive = self.lnworker.num_sats_can_receive()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
```

wallet: fix AttributeError when getting help text

---

contrib/build-linux/appimage/build.sh
contrib/build-linux/appimage/make_appimage.sh
contrib/build-wine/prepare-wine.sh
contrib/osx/make_osx.sh

We should avoid using this `(...) || ...` construct as it behaves completely un-intuitively.
This exits as expected:
```
$ cat s1.sh
#!/bin/bash
set -e
(
echo "a"
false
echo "b"
)
$ ./s1.sh
a
```
This does NOT exit, seemingly because of the outer context?!
```
$ cat s2.sh
#!/bin/bash
set -e
(
echo "a"
false
echo "b"
) || echo "c"
$ ./s2.sh
a
b
```
ref https://unix.stackexchange.com/questions/65532/why-does-set-e-not-work-inside-subshells-with-parenthesis-followed-by-an-or

contrib: "set -e" behaves weird in subshells followed by OR. don't use.

---

.cirrus.yml

coveralls has been quite flaky recently -- let's try to lower the number of CI tasks where it spreads the flakiness.

ci: only run coveralls on one of the unittest tasks

---

electrum/util.py
tests/__init__.py
tests/test_lnpeer.py

`util.callback_mgr.callbacks` was not getting properly cleared between tests. Every time an `Abstract_Wallet` or an `LNWorker` (or many other subclasses of `EventListener`) is instantiated, `self.register_callbacks()` is called in `__init__`, which puts callbacks into `util.callback_mgr.callbacks`. These are only cleaned up if we explicitly call `Abstract_Wallet.stop()` or `LNWorker.stop()` later, which we usually do not do in the tests.
As a result, when running multiple unit tests in a row, lots of objects created in a given testcase are never GC-ed and leak into subsequent tests. This is not only a memory leak, but wastes compute too: when events are triggered and cbs get called, these old objects also have their cbs called.
After running all (~1061) unit tests, I observe …

tests: clear util.callback_mgr between test cases

---

electrum/gui/qml/components/LnurlWithdrawRequestDialog.qml
electrum/gui/qml/components/SendDialog.qml
electrum/gui/qml/components/WalletMainView.qml
electrum/gui/qml/qeapp.py
electrum/gui/qml/qeinvoice.py
electrum/gui/qml/qepiresolver.py
electrum/gui/qml/qerequestdetails.py
electrum/gui/qt/send_tab.py
electrum/lnurl.py
electrum/lnworker.py
electrum/payment_identifier.py
tests/test_lnurl.py
tests/test_payment_identifier.py

lnurl-withdraw is used by lightning bitcoin atms, vouchers (e.g. azteco), and web services allowing users to withdraw funds without having to copy-paste invoices (esp. between desktop <-> smartphone).
https://github.com/lnurl/luds/blob/227f850b701e9ba893c080103c683273e2feb521/03.md
Can be tested with https://demo.lnbits.com and the `Withdraw Links` (LNURLW) and `Pay Links` (LNURLP) extensions.

lightning: implement lnurl-withdraw (LUD-03)
