spesmilo/electrum

lib/daemon.py

- added localhost
- sys.executable to get around python2 / python3 issues
- close_fds cannot be combined with stderr and stdout on windows. see python doc.

Fix Daemon on Windows

---

plugins/trezor.py

This pull request adds 'Show on TREZOR' item in address context menu for Trezor wallets.

Confirm address on TREZOR

---

electrum

fix help message

---

.travis.yml

http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/

travis: use container-based infrastructure for faster tests

---

plugins/btchipwallet.py

Prepare upcoming firmware integration

New firmware integration

---

gui/qt/main_window.py
lib/commands.py
lib/transaction.py
plugins/cosigner_pool.py
scripts/authenticator.py

It seems that https://github.com/spesmilo/electrum/commit/e3de121be9a56c84ec80ce79a84f7ce1ae6b9b20 changed the API for Transaction class, but not several files are still using the old API.

Fix a few issues with transaction serialization and deserialization

---

electrum

Googling reveals this code is likely a remnant of prior code
and no longer needed.  It appears to have no effect on my system.

Remove apparenlty dead import and __builtin__ assignment.

---

gui/qt/main_window.py
lib/wallet.py

Well spotted Thomas.  How about this, keeping the localization bit in main_window.py?
Tested on watch-only and not watch-only wallet, after confirming your predicted failure with a watch-only wallet.

Tray tip wallet

---

lib/wallet.py

This is preparation to hopefully fix #1163

Make it 3-step instead of four. Avoid quadratic insertions.

---

lib/interface.py

First step in cleaning up the run() function.
Calls stop() rather than setting is_connected to False on
case of timeout, which cleanly closes the socket.

Move ping functionality into its own function.

---

lib/interface.py

Currently requests are sent from the requestor's thread.  The lock is
not properly held where necessary so this is not thread-safe.  For example
it can race with the thread stopping and closing the socket the
requestor is trying to use to send with.
Resolve such races by having send_request() simply queue the requests,
which are asynchronously sent from the interface thread itself.

Send requests only from the interface thread.

---

lib/interface.py

This makes the operation of run() more clear.
No essential change in functionality.

Move response getting to its own function.

---

lib/interface.py

First, close the socket from the thread itself rather than from
the stop() function.  This prevents another thread closing the
socket that the interface thread is simultaneously using.
Second, it occasionally would happen that the parent thread such as
network.py start() an interface, do a send_request() and timeout
waiting for a response (timeouts are 0.1s).  It would check
is_connected(), get False, and assume the connection has failed.
In fact the thread hadn't even been scheduled or gotten around to
completing the socket connection.  Fix by having self.connected
start out True.  If the connection fails or times out, we set
connected to False soon enough.
Finally for correctness we need to deepcopy a send_request() rather
than take a reference to it.

Fix two races in interface.py.

---

lib/wallet.py

This restores a working offline mode.

Don't use self.network to get the local height.

---

lib/network.py

Handle requests in the main loop.
Remove unused lock.
interface.py was reworked and send_request() no longer throws.

No need for thread to handle requests

---

lib/network.py

Simply moves code to a new function; no logic change

Put interface notification handling in its own function.

---

lib/network.py

Prefer to use safer self.is_connected() as it checks interface
is not None.
Using common code gives small observable changes in behaviour:
- slightly different print_error() messages
- network restarts now enter status 'connecting' which they
didn't before, which seems correct
- status 'connecting' is done with set_status() rather than
simply assigning the status, which seems more correct.  Now
that the response_queue is available in the constructor this
works; it used to fail with 'response_queue is not defined'

Put common network start and stop code in one place.

---

lib/network.py

(note this depends on / includes PR #1224)
switch_to_interface() becomes the common place where
self.interface is set; therefore self.interface is not None
precisely when self.default_server is connected.  Previously some
places required it to be connected and some didn't.  Also an
interface change now sends the 'updated' notification
consistently - previously some did and some didn't.
Have network_start() call start_interfaces() - this also means
network restarts now do this.
Fix apparent off-by-one in start_interfaces()

Consistency in handling of self.interface

---

lib/util.py

Tested in Spanish locale, where scanning a 0.25 BTC send failed before and now works.
Fixes #1226

Plain number formatting for URIs.

---

lib/network.py

They are now only called from the same place; it's simpler
and clearer to put them inline.

Absorb add_interface and remove_interface

---

lib/wallet.py

This speeds up save_transactions by 2 to 3 times for me.

Flush wallet storage once for a sequence of puts.

---

lib/network.py

1) For new proxy or protocol, restart the network and default to
the requested server.
2) Otherwise if we aren't using the requested server, switch to it
3) Otherwise choose a random server if the requested server is
stale and auto_connect is True
As switch_to_interface() now has another user, move the logic
there whereby we close the old interface in order to terminate
subscriptions, in order to have it in one place.

Improve logic in network.py's set_parameters()

---

electrum
gui/gtk.py
gui/qt/network_dialog.py
lib/network.py
scripts/servers

call sites.
Remove unused imports and redundant random pick of server

Clean up pick_random_server() and filter_protocol() and their

---

gui/qt/amountedit.py
lib/util.py

str() can convert amounts to scientific notation

Fix nasty bug in amount editors

---

gui/qt/qrcodewidget.py

Probably speeds it up by about a factor of two.
Unfortunately it needs to be another 5x faster
for sluggishness to disappear in the GUI when
typing a description in the receive tab.
Note the old code was off-by-one.

Speed up painting of qr codes.

---

gui/android.py
gui/gtk.py
gui/qt/lite_window.py
gui/qt/main_window.py
gui/stdio.py
gui/text.py
lib/bitcoin.py
lib/commands.py
lib/util.py
plugins/exchange_rate.py

Use same name as is in bitcoind.
Note that one of the constants in text.py had the wrong number
of zeroes previously...

Create a constant for 100000000 and use it

---

lib/network.py

Handle local requests immediately.
Defer those requiring connectivity until we have an interface.

Fix request handling.

---

lib/commands.py

Fix typo in param_descriptions

---

.travis.yml

Please see https://travis-ci.org/romanz/electrum for `py.test` typical execution.

travis: use pytest (due to better test discovery)

---

lib/transaction.py
lib/util.py
lib/verifier.py

Fix few small issues.

---

lib/transaction.py
lib/wallet.py

This implements BIP-LI01, see https://github.com/kristovatlas/rfc/blob/master/bips/bip-li01.mediawiki.  The idea is to improve privacy and reduce information leakage.
This should wait until after the upcoming release.

Implement BIP-LI01.

---

plugins/btchipwallet.py

* Fix Windows support 
* Support Ledger 2FA
* Prepare for upcoming Ledger firmware transaction encoding
To be bundled with https://github.com/LedgerHQ/btchip-python/tree/v0.1.15

HW.1 fix pack

---

gui/qt/main_window.py

View contact address on block explorer menu item

---

gui/qt/main_window.py
gui/qt/transaction_dialog.py

Show-before-send currently asks for the password
and creates a signed tx before showing anything.
This is a little unnerving as you can't see what
you're being asked to sign.
This patch does a few things:
- Adds a description label to the TX dialog
- You see the tx before being asked for password;
that is only requested on pressing Sign
- in show-before-broadcast mode, the Send button
text is instead "Show...".  Hook up this button
text change to the prefs dialog too.
- Remove many redundant imports.  In particular
PyQ4 is checked in main_window.py so no need
in tx_dialog too.
Note I had to remove disabling of the Sign button,
because if the user presses "cancel" nothing will
re-enable it.

Have show-before-broadcast defer password request

---

plugins/btchipwallet.py

Ledger fixes for 2.3.3 - fixes #1311

Ledger fixed 2.3.2

---

gui/qt/transaction_dialog.py
plugins/cosigner_pool.py
plugins/greenaddress_instant.py

The "actions" (sign, broadcast, send to cosigner, verify GA instant)
go on the RHS next to the "Cancel" button.
Copy, QR code and save go on the left.

Split tx dialog buttons

---

lib/wallet.py

I noticed this whilst debugging the daemon issue.

Remove apparently dead code.

---

lib/daemon.py

Caused by unicode vs non-unicode strings.

Avoid string representation issues, fix #1338

---

lib/network.py

Makes auto_connect a class member variable rather than function.

Suggested auto_connect daemon mode fix for #1336

---

plugins/__init__.py
plugins/btchipwallet.py

Closes #1326 and add command line support
Still needs a fix in lib/transaction.py (update, suggested self.inputs = None before deserialize call)

Rework UI, fix missing hooks

---

lib/tests/test_util.py
lib/util.py

This should also fix the errors at Travis CI build: 
https://travis-ci.org/spesmilo/electrum/builds/72459771

util: fix small typo at parse_URI() and update its unittests

---

plugins/btchipwallet.py

Update installwizard init

---

plugins/__init__.py
plugins/btchipwallet.py

Rename BTChip -> Ledger

---

lib/tests/test_interface.py

It was broken at: https://travis-ci.org/spesmilo/electrum/builds/76762981

test_interface: fix check_host_name test

---

lib/tests/test_account.py

This should improve code coverage for account management code.

Add test_account for testing lib.account module

---

gui/qt/installwizard.py

Fixed GroupBox layout in installwizard

---

plugins/keepkey.py
plugins/trezor.py

Made the change to Trezor too.

fixed attempt to access account derivation before it is created

---

gui/qt/main_window.py

Fixes expiration value bug

---

lib/interface.py

Fix a small typo in Connection docstring.

Fix typo in Connection docstring

---

contrib/make_packages
gui/kivy/tools/buildozer.spec

use `pip install -t` in make_packages to aggregate packages & comment android.branch=master(allows it to run with latest bulldozer)

use `pip install -t` in make_packages to aggregate packages.

---

plugins/exchange_rate.py

Exchange rate fixes

---

plugins/exchange_rate/exchange_rate.py

Coinsecure exchange added

---

lib/blockchain.py

Improve get_target

---

lib/blockchain.py

I make changes that describe in #1558 and something else.
@ecdsa not sure about project code style.. such as extra spaces for math operators */-+, if-else line..

Small blockchain.py changes

---

setup.py

BUG: allow non-root installation on linux

---

RELEASE-NOTES
contrib/build-wine/README
plugins/trezor/__init__.py
plugins/trezor/plugin.py
plugins/trezor/qt_generic.py
plugins/trezor/trezor.py

correct capitalization of letters

fix spelling of TREZOR and SatoshiLabs

---

plugins/ledger/ledger.py
plugins/ledger/qt.py

Redesign Ledger plugin around the generic components

Ledger plugin redesign

---

setup.py

Fix installation when --root is specified

---

lib/coinchooser.py

Probably a copy pasta from the development process.

Remove penalty_func from CoinChooserPrivacy that is later redefined

---

lib/util.py

https://github.com/bitcoin/bips/blob/master/bip-0122.mediawiki

Added Blockchain URI (BIP 122) to block explorers list.

---

plugins/ledger/ledger.py

Make the firewall happy for older versions + free cleanup

Fix setup for Nano S firmware version < 1.2

---

lib/wallet.py
lib/www/index.html

Up to now, websockets configuration was possible for the daemon only,
this patch passes that information to the client via json file
produced with the payment request.

Adding possibility of websockets configuration

---

lib/paymentrequest.py

Otherwise the client would simply hang when receiving an invalid URL dumping a hard-to-read exception to the terminal.
While this is an improvement over the previous situation (and therefor should be merged), it doesn't actually address the underlying that caused this situation in the first place: Coinbase uses payment request URLs for their processing, but also Cloudflare for their webservers. Considering how easy was to enable TOR in my Electrum instance I'd definitely call this a series of unfortunate circumstances. I'm not sure what to do about that through…

Properly handle invalid payment request URLs

---

lib/util.py

I fixed this issue [link](https://github.com/spesmilo/electrum/issues/2091)

changed false Identification of windows as linux

---

lib/exchange_rate.py

Could you please add this pull request, we added three new exchanges in the BRL market and updated the MercadoBitcoin link that was not working.
Sincerely,
Marcdnd

Added BRL exchanges: Bitvalor, Foxbit, NegocieCoins

---

plugins/ledger/ledger.py

Output stream requires btchip-python version 0.1.19 and BTC application 1.1.4+ (currently experimental version available at https://github.com/ledgerhq/blue-app-btc on the stream-output branch)

Ledger : Testnet support, APDU verbosity aligned with Electrum, Nano S / Blue output streaming

---

gui/qt/address_list.py
gui/qt/contact_list.py
gui/qt/history_list.py
gui/qt/invoice_list.py
gui/qt/main_window.py
gui/qt/request_list.py
gui/qt/util.py

This pull request:
* Transfers the filter columns definition from ElectrumWindow to the list
* Saves the filter string in the list that is being filtered
* Re-filters the list when the data is updated
Closes #2165

Keep filter after updating the list

---

gui/qt/network_dialog.py

Also: Don't use the proxy to connect to the proxy

Use a checkbox instead of a button

---

lib/wallet.py

Remove newlines from transaction labels

---

gui/qt/network_dialog.py
lib/network.py

It looks like this:
Closes #2073

Allow using a SOCKS5 proxy with authentication

---

lib/util.py

Since it's imported as 
from decimal import Decimal

Fix decimal usage

---

lib/network.py

similar to how relayfee is logged

report fee_estimates to verbose log

---

plugins/trezor/qt_generic.py

https://github.com/spesmilo/electrum/commit/45f25586ef586c998ae3e24d731a7c3f651d90f2#diff-0ff6b1ec17ee386204c01b266d788c45L206
/cc @prusnak

TREZOR: Update qt_generic for new InstallWizard

---

plugins/digitalbitbox/digitalbitbox.py

Due to constrained memory sources in embedded microcontrollers, large transactions cannot fit without being chunked and streamed to the microcontroller in multiple parts.
The previous plugin ~would~ should have returned an error if the transaction is too big. This PR allows streaming large transactions of any number of inputs to be signed (for example if sweeping a wallet).
EDIT - applies to the Digital Bitbox plugin

stream signing for tx with large number of inputs

---

lib/tests/test_transaction.py

This should fix the currently broken Travis [build](https://travis-ci.org/spesmilo/electrum/builds/221364926#L202).

tests: fix TestTransaction.test_tx_signed testcase

---

lib/util.py

Add BlockCypher.com as a block explorer

---

lib/commands.py

Add input and output addresses to CLI history

---

plugins/trezor/plugin.py

Trezor plugin: Sort multisig pubkeys before signing

---

gui/qt/main_window.py

The console tab isn't useful for most users and might even be confusing to some. This change hides the console tab by default and adds a menu action to show/hide the tab. In order to improve the menu organization, tab toggling menu items are grouped in a new "View" menu.
Summary
===
- Hide console tab by default
- Hide contacts tab by default
- Move tab toggling menu items to new "View" menu
- Refactoring
- Remove shortcut Ctrl+A for toggling the addresses tab
Screenshots
===

Hide console tab by default

---

lib/commands.py

This resolves issue #2588. Adds a 5 second timeout on the request.

Added a timeout on the urllib2 request during a notify event.

---

gui/qt/main_window.py

Add shortcuts to toggle actions in view menu

---

lib/commands.py

This simply exposes tx locktime as a --locktime option for payto command. This may be useful after a fork to allow splitting coins using locktime method. 
Currently only supports by block number. It wouldn't be hard to add date support but not sure what date format it should accept. If that can be decided I could change the arg type to support a date value and convert it.
I tested this only by creating an unsigned tx and then decoding it on http://coin.bin to verify. It gave correct locktime value. I don't currently have a wallet with enough funds to sign and send a test locktime tx. hopefully, someone who sees value in this cmd option can test.
If a ledger wallet then this PR requires the ledger fix PR #2625 just submitted. The ledger cmdline module cannot load with spelling mistake.

Add locktime cmdline support

---

contrib/build-wine/build-electrum-git.sh
contrib/build-wine/deterministic.spec
contrib/build-wine/prepare-wine.sh
electrum

- `console` is only enabled for debugging, it should be disabled later
- Setting `PYTHONHASHSEED` to a known value should enable deterministic builds but that's not tested yet

Fix pyinstaller3 build

---

gui/qt/network_dialog.py

bugfix: [GUI-QT/Network] Save proxy setting when toggling Tor checkbox

---

plugins/ledger/auth2fa.py

Simple one word chg. That's all.

Fix Ledger plugin help text grammar

---

plugins/digitalbitbox/digitalbitbox.py

The digital bitbox plugin didn't work anymore, mostly due to str/bytes
issues.
This patch fixes message and tx signing. Backup restore is also
tested.
Untested: firmware <= v2.1.1 and wallet initialization.

fix digital bitbox plugin, port to Python 3

---

plugins/ledger/auth2fa.py
plugins/ledger/ledger.py

Assorted set of micro fixes (HW.1 should work now) + use BIP 49 to trigger Segwit wallets

Ledger - Python 3 and Segwit fixes

---

lib/transaction.py

Needed these changes to get Segwit working on testnet.

Python 3 fixes for Segwit

---

lib/util.py

urllib.quote no more being, replace by new urrlib.parse.quote

fix urllib.quote py2 to py3

---

lib/transaction.py

fix: set scriptSig when spending from coinbase

---

lib/bitcoin.py
lib/tests/test_bitcoin.py

fix bech32 scriptPubKeys (OP_n), and tests

---

lib/exchange_rate.py

Removed BTCe and added WEX to exchange_rate.py

---

plugins/ledger/ledger.py

Check firmware version for Segwit related transactions, add native segwit support in upcoming Bitcoin application 1.1.10

Ledger : native segwit support

---

contrib/build-wine/deterministic.spec

"lib/locale/*" directory is not including now.
So I pull a request.

include locale for windows binary

---

contrib/build-wine/deterministic.spec

include plugins in windows builds

---

plugins/trustedcoin/trustedcoin.py

fix json error when resetting 2fa

---

lib/bitcoin.py
lib/keystore.py
lib/tests/test_bitcoin.py

This would have caught the bug fixed in #2941

tests: message signing

---

gui/qt/contact_list.py

fix: contact name editing

---

gui/text.py

Had experienced crashes such as
```
File "/home/user/wspace/electrum/gui/text.py", line 302, in main
self.run_tab(0, self.print_history, self.run_history_tab)
File "/home/user/wspace/electrum/gui/text.py", line 245, in run_tab
if c: exec_func(c)
File "/home/user/wspace/electrum/gui/text.py", line 250, in run_history_tab
out = self.run_popup('',["blah","foo"])
File "/home/user/wspace/electrum/gui/text.py", line 373, in run_popup
return self.run_dialog(title, map(lambda x: {'type':'button','label':x}, items), interval=1, y_pos = self.pos+3)
File "/home/user/wspace/electrum/gui/text.py", line 419, in run_dialog
self.w = curses.newwin( 5 + len(items)*interval + (2 if buttons else 0), 50, y_pos, 5)
TypeError: object of type 'map' has no len()
```
See …

fixes in text UI (mainly py3)

---

gui/qt/main_window.py
lib/paymentrequest.py

fix: saving payment request as bip70 file

---

lib/tests/test_bitcoin.py

re commit 0f4b5abc158d46ac25fc2a976154004a2c705f2d

fix tests: message signing

---

plugins/labels/labels.py

fix trace for LabelSync with Imported_Wallet

---

plugins/audio_modem/qt.py

(following the migration to Python 3)

amodem: fix str/bytes handling

---

lib/storage.py

See #3003.
This code converts the "test_privkey_315135_v13" wallet included in the above issue to the following "test_privkey_315135_v14":
<details>
<summary>test_privkey_315135_v14</summary>
```
{
"addr_history": {
"16MrxVEhhhJR5TyygpSBQmsT9Q4fakrqpL": [],
"17i37FFyPV5YgMJo9Wx3kHnxa692xDUPRE": [],
"1APJi7stpPAyQyzCxLjFpFJ3USizeZUGLS": [],
"1BZ7zxHCVp8D5GvdSqSPHDHctTwSYhFMAf": [],
"1DkuqKzepHVApuahpH29UmxFJ2bEL6AEti": [],
"1G2qu99yuax7C2tf4cZd1Jbk6b1sDGF6Bc": [],
"1HfeZFsMxP65oV8VRBJaFvy8Szvqy6Z2L": [],
"1NdWKCQQQmCmE8JyS5VUeEg9AvF6Etse4f": [],
"1PXb9PmexHmQ3TgFvmsu864rCfQpQXKcQe": []
},
"addresses": {
"16MrxVEhhhJR5TyygpSBQmsT9Q4fakrqpL": {
"pubkey": "038b8454a739c1d34f83ba101c2af1f7ae2f7ff4ef6701620ae93b9e1541809673",
"type": "p2pkh"
},
"17i37FFyPV5YgMJo9Wx3kHnxa692xDUPRE": {
"pubkey": …
```

fix: v13 to v14 wallet (with Imported_KeyStore) conversion

---

gui/qt/network_dialog.py

Following 2a80f6877808181d27cc5a80d31458b88f3b4d17
- `Use Tor proxy...` button was broken
- proxy on/off setting did not get restored after application close-reopen

network dialog fixes

---

lib/network.py

Unstuck GUI from "synchronizing..."

---

plugins/digitalbitbox/digitalbitbox.py
plugins/digitalbitbox/qt.py

- menu option to verify addresses securely
- p2pkh transaction verification
Next steps: p2sh tx verification and full 2FA.

digitalbitbox: import mobile pairing config

---

lib/bitcoin.py

Only one branch of these methods is tested... Unit tests should be written that reach both program paths.

fix: py3 in bitcoin.py: aes_encrypt_with_iv() and aes_decrypt_with_iv()

---

plugins/cosigner_pool/qt.py

I have tested this with a local instance of the server script, and it worked.
-----
However, it does not work with the remote 'official' server... is there a problem with that server?
When calling `server.put()`:
```
File "/home/user/wspace/electrum/plugins/cosigner_pool/qt.py", line 182, in do_send
server.put(_hash, message)
File "/usr/lib/python3.5/xmlrpc/client.py", line 1092, in __call__
return self.__send(self.__name, args)
File "/usr/lib/python3.5/xmlrpc/client.py", line 1432, in __request
verbose=self.__verbose
File "/usr/lib/python3.5/xmlrpc/client.py", line 1134, in request
return self.single_request(host, handler, request_body, verbose)
File "/usr/lib/python3.5/xmlrpc/client.py", line 1146, in single_request
http_conn = self.send_request(host, …
```

py3: cosigner_pool

---

contrib/build-wine/prepare-wine.sh

Now there is no more user interaction required to prepare the Wine environment.

Install NSIS silently

---

gui/qt/contact_list.py
lib/contacts.py

fixes #3086 
Also, `_validate()` needs this change as py3 introduced:
```
File "/home/user/wspace/electrum/lib/contacts.py", line 63, in import_file
d = self._validate(json.loads(f.read()))
File "/home/user/wspace/electrum/lib/contacts.py", line 129, in _validate
for k,v in data.items():
RuntimeError: dictionary changed size during iteration
```

fix: contacts import

---

lib/plugins.py

Return loaded plugin from plugins.load_plugin()

---

plugins/trustedcoin/trustedcoin.py

fix: set wallet_type attr for 2fa wallets

---

lib/transaction.py

fix: transaction.parse_witness() for coinbase

---

gui/qt/network_dialog.py

See #3127 
This PR tries to handle the "proxy" part of that issue.

(QT network dialog) don't keep resetting proxy settings

---

gui/qt/main_window.py

Payment request: "pay now" allow multiple attempts

---

plugins/ledger/ledger.py

fix xtype for ledger native segwit

---

gui/qt/address_list.py

fix #3155 
I've actually tried to transition to using [Enums](https://docs.python.org/3/library/enum.html) but it turned out to be more complicated than it's worth (here).

fix AddressList: indices of address states

---

lib/network.py
lib/simple_config.py

See #2878
It is not obvious to me whether introducing fee-specific lock(s) would be needed, I can't see any harmful race conditions at the moment.

Periodically poll fee estimates from server

---

lib/storage.py

storage upgrade v16: fix flawed v14 upgrade for imported addresses

---

gui/qt/main_window.py

fix: exporting privkeys multiple times

---

gui/qt/main_window.py
lib/tests/test_transaction.py
lib/transaction.py

See #3222
This should catch more ill-formed transactions... but it's still not perfect.
Can we just catch all Exceptions thrown by `deserialize()` and rethrow as `SerializationError `s? Or maybe all `TypeError`s?
<details>
<summary>Valid Tx</summary>
```
010000000001090c079384933aa5b98eec6744ffc57a590ed1ac524bdefcb1dd97e2675f86f9c10100000023220020d6cd39e665a7882f8443eb1812c6001be4d1fa2646f79de94e97dbee77153a23ffffffff6f6aee0f65ac1dc93d466678f5830a3ab1c084a972ae51d369bbfa389c12799f0100000023220020e5cdc48f017d819c83d78da3e0b0b6a96aed41e8679a44af9006f53397e13a6dffffffff438a77fbe2c334ef525e08f9ac13d891f1f5d6eccbb967d0211a1660aa5c713908000000232200209ce6732d8f8551862638b351ca912008909f6f292c0f013b3ead813505cfc72affffffffaa64653185a1535ed54d5d9e31ae48c8d5afbe67f7fdfc90fce6498aed1e160f08000000232 …
```

make tx deserialization more robust to ill-formed tx

---

lib/commands.py

Just a couple of problems from missing imports or Python 3 migration. Signing issues discovered in #bitcoin conversation with user frankocan this morning.

Fixes to signing, notify commands and command exception handling.

---

contrib/build-wine/deterministic.spec

windows binaries were missing servers_testnet.json

---

plugins/digitalbitbox/digitalbitbox.py

digitalbitbox: delegate clear_dialog() calls to GUI thread

---

lib/interface.py

fix #1463
Not sure if complete IPv6 support still requires more changes but this specific issue is solved.

fix parsing of ipv6 addresses in interface

---

plugins/digitalbitbox/digitalbitbox.py
plugins/digitalbitbox/qt.py

Also, since it touched on mobile verification, I added some checks to disable it for non-p2pkh transactions.

digitalbitbox: add support for segwit

---

lib/coinchooser.py
lib/transaction.py

better segwit tx size estimation

---

gui/qt/main_window.py

follow-up #3361 (notifications for incoming transactions)

---

lib/transaction.py

See https://github.com/spesmilo/electrum/issues/3363#issuecomment-346722837
I do not think this fully solves referenced issue.

tx size estimation: handle uncompressed pubkeys

---

contrib/build-wine/build-electrum-git.sh
contrib/build-wine/build.sh

Make build timezone independent

---

plugins/trezor/plugin.py

Make trezor code specific to trezor

---

plugins/trezor/plugin.py

fixes (parts of ???) https://github.com/spesmilo/electrum/issues/3072
see https://github.com/spesmilo/electrum/issues/3072#issuecomment-347751703
This PR reverts https://github.com/spesmilo/electrum/commit/020f0637d7d8ec412df3762cfa9485a36574d274

fix: keepkey sending to p2sh output

---

contrib/build-wine/README.md

Add instruction to install dirmngr to Wine README

---

gui/qt/main_window.py

Add "Testnet" to main window title in testnet mode

---

gui/qt/main_window.py
lib/wallet.py
plugins/trustedcoin/trustedcoin.py

https://github.com/spesmilo/electrum/pull/3380 broke sweeping for 2fa wallets
I could not yet test this properly because I don't have testnet working for 2fa atm.

fix sweeping for 2fa wallets

---

plugins/ledger/ledger.py

Closes https://github.com/spesmilo/electrum/issues/3532

ledger: mention "bitcoin" app when update is needed

---

lib/wallet.py

@ecdsa 
We talked about this at some point but then I forgot to actually do it.

RBF/sweep: use BIP_LI01_sort()

---

gui/qt/installwizard.py
lib/base_wizard.py

Closes https://github.com/spesmilo/electrum/issues/3373

wizard: add derivation presets for bip44/49

---

gui/qt/__init__.py

fixes #3217 
See https://github.com/spesmilo/electrum/issues/3217#issuecomment-354520203

fix #3217: make sure qt quits

---

lib/wallet.py

Not sure why this is 5000 atm.
https://github.com/bitcoin/bitcoin/blob/v0.15.1/src/policy/policy.h#L32

change default relay fee to 1000 sat/kbyte

---

gui/kivy/uix/dialogs/installwizard.py
gui/qt/installwizard.py
gui/qt/main_window.py
gui/qt/qrtextedit.py
gui/qt/seed_dialog.py
gui/qt/util.py
lib/base_wizard.py

ScanQRTextEdit optionally allows to concat data

---

lib/daemon.py

make daemon lockfile not executable

---

.travis.yml
requirements_travis.txt

Add [caching](https://docs.travis-ci.com/user/caching/) to `.travis.yml`

Cache pip installs in travis

---

gui/qt/main_window.py

I think we should add a warning along these lines.

qt privkey export: if multisig wallet, warn users re backup

---

plugins/ledger/ledger.py

Currently the ledger version comparison is a bit lacking. If the bitcoin ledger app was updated to 1.2.0, electrum would assume incompatibility with multi-output, segwit and native segwit.
Instead of adding any new dependencies for this simple task (ie. semver), I simply compare the versions as tuples.
Let me know if I should change anything.

Better ledger version comparison

---

plugins/ledger/ledger.py

fixes https://github.com/spesmilo/electrum/issues/3304

ledger: handle pin-locked state better

---

gui/qt/network_dialog.py
lib/commands.py
lib/network.py

remove the --nossl option that was introduced in https://github.com/spesmilo/electrum/commit/dc388d4c7c541fadb9869727e359edace4c9f6f0
supersedes https://github.com/spesmilo/electrum/pull/3731

remove --nossl option

---

lib/network.py
lib/websockets.py

fixes https://github.com/spesmilo/electrum/issues/3670

websocket: migrate to scripthashes

---

contrib/make_packages

Follow-up #3751

---

lib/wallet.py

wallet.add_unverified_tx: test if self.verifier exists

---

lib/util.py

Sorry for the horrible diff, but blockonomics.co structures their URLs differently... :/

add block explorer: blockonomics.co

---

gui/kivy/main_window.py
gui/kivy/uix/dialogs/installwizard.py
gui/kivy/uix/dialogs/tx_dialog.py
gui/kivy/uix/ui_screens/network.kv
gui/qt/address_list.py
gui/qt/console.py
gui/qt/contact_list.py
gui/qt/history_list.py
gui/qt/installwizard.py
gui/qt/invoice_list.py
gui/qt/request_list.py
gui/qt/transaction_dialog.py
lib/base_wizard.py
lib/commands.py
lib/plugins.py
lib/wallet.py
plugins/digitalbitbox/digitalbitbox.py
plugins/digitalbitbox/qt.py
plugins/greenaddress_instant/qt.py
plugins/hw_wallet/qt.py
plugins/keepkey/clientbase.py
plugins/keepkey/plugin.py
plugins/keepkey/qt_generic.py
plugins/ledger/auth2fa.py
plugins/ledger/ledger.py
plugins/trezor/clientbase.py
plugins/trezor/plugin.py
plugins/trezor/qt_generic.py
plugins/trustedcoin/qt.py
plugins/trustedcoin/trustedcoin.py

Found more translated strings using % formatting.

use string.format instead of old style (%) formatting

---

lib/base_wizard.py
lib/plugins.py
plugins/ledger/ledger.py

attempt at fixing ledger 'read error'

---

gui/qt/address_list.py
lib/wallet.py

address filter: (qt gui) add "all" filter option besides "receiving" and "change"
@shsmith asked for this on IRC
Closes #3356

address filter: add "all" filter option besides "receiving" and "change"

---

lib/util.py
plugins/hw_wallet/qt.py
plugins/ledger/ledger.py
plugins/trezor/trezor.py

Addresses https://github.com/spesmilo/electrum/pull/3621#issuecomment-354497699

check trezorlib version

---

lib/wallet.py

fix #3890 
see https://github.com/spesmilo/electrum/issues/3890#issuecomment-365080449
I believe this should solve that issue.

locking in wallet.create_new_address

---

gui/qt/exception_window.py

closes https://github.com/spesmilo/electrum/issues/3933

crash reporting: catch exceptions from requests.post

---

lib/wallet.py

fixes https://github.com/spesmilo/electrum/issues/3935
- wallet.add_transaction should not return if tx has already been added
- reverts https://github.com/spesmilo/electrum/commit/76bf53b2624813a4b4e95d1b59bdc2b19673d3d9
- only track spent_outpoints for is_mine inputs

fix: wallet.add_transaction

---

gui/kivy/uix/dialogs/bump_fee_dialog.py
gui/kivy/uix/dialogs/fee_dialog.py
gui/kivy/uix/dialogs/settings.py
gui/qt/main_window.py
gui/qt/transaction_dialog.py
lib/bitcoin.py
lib/simple_config.py
lib/util.py
lib/wallet.py

- fix kivy bump_fee_dialog
- add warning of "high fees" into qt transaction dialog
- impose hard limits on dynamic fees
- list fee related constants in simple_config

clean up fees a bit

---

gui/qt/contact_list.py
gui/qt/invoice_list.py
gui/qt/main_window.py
gui/qt/util.py
lib/contacts.py
lib/paymentrequest.py
lib/util.py

This merges https://github.com/spesmilo/electrum/pull/3910
and includes some clean-up.

File import-export unification

---

contrib/build-wine/README.md

While trying to build Windows executables I ran into quite a few problems related to Wine that could have been helped with this documentation. I imagine this could help someone in the future if they have issues similar to mine.

Update build-wine's README.md

---

lib/tests/test_wallet_vertical.py
plugins/trustedcoin/trustedcoin.py

Closes https://github.com/spesmilo/electrum/issues/3445
The tpub <-> xpub conversions are a bit messy... :/

make 2fa wallets work on testnet

---

contrib/build-wine/prepare-wine.sh

After having problems with Sourceforge being down/slow a few days ago I decided to modify this script to allow for caching of the files that would have otherwise been downloaded every time this script runs. This way we can still generate binaries even if Sourceforge is down.

Create file caching system

---

plugins/trezor/clientbase.py

fix https://github.com/spesmilo/electrum/issues/3996
Note that you need python-trezor master for this, 0.9.0 is not enough.
I think probably https://github.com/trezor/python-trezor/commit/bccd61cb23a5259e02d6606ac320093d6637d203 is needed specifically; but in any case I've been testing on https://github.com/trezor/python-trezor/commit/e37e9bfebda2c2c5c6bc2bf60aafe6dc65cc6546

trezorT: fix/implement passphrases

---

lib/currencies.json
lib/exchange_rate.py

I added three major Japanese exchanges.
BitFlyer https://bitflyer.jp/
BitBank https://bitbank.cc/
Zaif https://zaif.jp/

Add JPY exchange rate

---

electrum
gui/kivy/main_window.py
gui/qt/exception_window.py
gui/qt/main_window.py
gui/qt/network_dialog.py
lib/bitcoin.py
lib/blockchain.py
lib/constants.py
lib/keystore.py
lib/network.py
lib/tests/test_bitcoin.py
lib/util.py
plugins/digitalbitbox/digitalbitbox.py
plugins/keepkey/plugin.py
plugins/trezor/trezor.py
plugins/trustedcoin/trustedcoin.py

fixes https://github.com/spesmilo/electrum/issues/4004

refactor network constants

---

lib/base_wizard.py

closes https://github.com/spesmilo/electrum/issues/3804

wizard: rename option to "use a master key"

---

MANIFEST.in
setup.py

Move dependency to MANIFEST.in
@SomberNight

Prevent requirements.txt from being installed to /usr after installation

---

gui/qt/__init__.py
lib/bitcoin.py
lib/keystore.py
lib/storage.py
lib/util.py
lib/wallet.py
plugins/trustedcoin/trustedcoin.py

closes https://github.com/spesmilo/electrum/issues/4142
closes https://github.com/spesmilo/electrum/issues/4135
closes https://github.com/spesmilo/electrum/issues/4120
closes https://github.com/spesmilo/electrum/issues/4119
closes https://github.com/spesmilo/electrum/issues/4118
closes https://github.com/spesmilo/electrum/issues/4087

Catch wallet file related exceptions in Qt wizard

---

contrib/build-osx/README.md

Avoids the confusion that I just had..

Update doc for OSX build

---

electrum.desktop

Easy way to start testnet version from linux DE

Add testnet mode to .desktop file

---

gui/kivy/uix/screens.py
lib/wallet.py

related: https://github.com/spesmilo/electrum/issues/4098
this will be caught in Qt too:
https://github.com/spesmilo/electrum/blob/87aee100470be979bb324d186559441e5c914b6a/gui/qt/main_window.py#L918-L922

disallow adding receive requests without valid is_mine addresses

---

gui/qt/paytoedit.py
lib/transaction.py

for the opcode changes, see
https://github.com/bitcoin/bitcoin/blob/0277173b1defb63216d40a8d8805ae6d5d563c26/src/script/script.h#L170-L191

fix paying to script

---

plugins/labels/labels.py
plugins/labels/qt.py

labels plugin: better exception handling

---

gui/qt/main_window.py

A small detail :)
Thanks for your work!

Use HTTPS for weblinks

---

lib/commands.py

closes https://github.com/spesmilo/electrum/issues/4213

payto: get RBF setting from config

---

lib/servers.json

The owner of the domain asked me to remove it.

Remove cryptohead.de

---

plugins/trezor/clientbase.py
plugins/trezor/qt.py
plugins/trezor/trezor.py

This supersedes https://github.com/spesmilo/electrum/pull/2132
and includes most of the "TODO" items from it; except for the dialog having the same width

Trezor: Matrix recovery support

---

lib/tests/test_transaction.py
lib/transaction.py

fix https://github.com/spesmilo/electrum/issues/4333
fix https://github.com/spesmilo/electrum/issues/4335

transaction.py: (txin guess) fix some false positive matches of p2sh-segwit

---

gui/qt/amountedit.py
gui/qt/main_window.py
lib/simple_config.py
lib/util.py

closes https://github.com/spesmilo/electrum/issues/4259

allow fractional feerates

---

lib/commands.py
lib/network.py
lib/websockets.py

I'm endeavoring to understand the code base. Ultimately I would like to see if the backend (electrumX) could be loosely coupled with the rest.
In order to achieve this I'm hoping to push all explicit mentions of the protocol strings into the network module. This PR is a tiny step into that direction.

Remove explicit protocol mentions

---

gui/qt/main_window.py
lib/commands.py
plugins/trustedcoin/cmdline.py
plugins/trustedcoin/qt.py
plugins/trustedcoin/trustedcoin.py

fix https://github.com/spesmilo/electrum/issues/3429

trustedcoin: sign first, then prompt for OTP

---

plugins/trezor/trezor.py

electrum has its own xpub parsing method; use that in favor of Trezor's which is now considered private and moved away

trezor: do not rely on deprecated ckd_public

---

gui/kivy/main.kv
gui/kivy/main_window.py
gui/kivy/uix/dialogs/__init__.py
gui/kivy/uix/ui_screens/status.kv

kivy: show all xpubs

---

lib/network.py

socket.getaddrinfo on win32: do our own dns resolution outside the lock

---

lib/blockchain.py
lib/network.py
lib/verifier.py

Removing some wildcard imports.
Superseeds merge request #4367, that is now too outdated

Improving imports

---

gui/qt/installwizard.py
gui/qt/main_window.py
gui/qt/seed_dialog.py
gui/qt/util.py
lib/base_wizard.py

Our custom prefix types, and their existence, is word of mouth on e.g. reddit atm.
Related: https://github.com/spesmilo/electrum/issues/4406

Qt: show WIF help in import(x2) and sweep dialogs

---

lib/network.py

there are many races in network.py..
this aims to:
fix https://github.com/spesmilo/electrum/issues/3037
fix https://github.com/spesmilo/electrum/issues/4029
fix https://github.com/spesmilo/electrum/issues/4127
fix https://github.com/spesmilo/electrum/issues/4217
@haarts I know I said I would not do this now -- but the Android app crashed for me today due to this and I just had to do it >.<

locks in network.py

---

electrum
lib/commands.py
lib/constants.py
lib/simple_config.py

Using the default servers configuration file shared with regtest.

add simnet support

---

lib/network.py
lib/verifier.py
lib/wallet.py

Some minor clean ups. This was part of the infamous #4427 PR.

Preliminaries

---

electrum/base_wizard.py
electrum/gui/qt/installwizard.py
electrum/tests/test_wallet_vertical.py

fix #4566 
as in https://github.com/spesmilo/electrum/issues/4566#issuecomment-405995572

bip39 passphrases with multiple spaces

---

electrum/wallet.py

fixes https://github.com/spesmilo/electrum/issues/3859
Sometimes there are legitimate reasons for creating new change addresses / increasing the change gap limit. (such as verifying/identifying change addresses when offline signing)
If the user does that, current master will tend to leave a gap of unused change addresses when making new transactions, which can lead to not discovering funds when restoring. [0]
The gap limit for change is hardcoded at 6.
The gap is due to the wallet always choosing change addresses from the last 6.
This PR keeps a list of unused change addresses, and use it such that the wallet will always prefer choosing the first unused one (or more in case of the multiple change outputs preference).
-----
[0] This has been irking me for some time, as whenever a user asks …

wallet: try to plug gap limit for change addresses

---

electrum/__init__.py
electrum/interface.py
electrum/network.py

One ugly aspect is the need to use the hidden _sslobj to extract the certificate from a session. I don't know how to do this cleaner.

aiorpcx: pin certificates

---

electrum/gui/qt/__init__.py

try fixing rare Qt crash when closing window

---

electrum/commands.py
electrum/daemon.py
electrum/keystore.py
electrum/mnemonic.py
electrum/tests/test_commands.py
run_electrum

supersedes https://github.com/spesmilo/electrum/pull/4600
note: not clear if I should raise Exceptions or return dicts with error keys
note: no clear way to communicate messages to user (how to replace `print_msg`?)

cli/rpc: 'restore' and 'create' commands are now available via RPC

---

electrum/util.py

Adding Bitupper Explorer to the list

Add block explorer: Bitupper.com

---

electrum/gui/qt/__init__.py

keep qt app alive after wizard closes

---

electrum/blockchain.py
electrum/gui/kivy/main_window.py
electrum/gui/qt/network_dialog.py
electrum/interface.py
electrum/network.py
electrum/storage.py
electrum/tests/test_blockchain.py
electrum/tests/test_network.py
electrum/tests/test_wallet.py

- id forks by first blockhash instead of forkpoint height
- swap child fork with parent based on work instead of length

blockchain: generalise fork handling and follow most work chain

---

contrib/make_apk
electrum/gui/kivy/Makefile
electrum/gui/kivy/Readme.md
electrum/gui/kivy/tools/Dockerfile
electrum/gui/kivy/tools/build.sh
electrum/gui/kivy/tools/buildozer.spec

build android apk in docker
I also intend to have travis run this build script, though not necessarily as part of this PR.

android docker build

---

RELEASE-NOTES
electrum/daemon.py
electrum/gui/qt/__init__.py
electrum/gui/qt/address_dialog.py
electrum/gui/qt/contact_list.py
electrum/gui/qt/history_list.py
electrum/gui/qt/main_window.py
electrum/gui/qt/util.py
electrum/gui/qt/utxo_list.py
electrum/util.py
electrum/wallet.py

fix https://github.com/spesmilo/electrum/issues/4911

use QAbstractItemModel in History tab

---

electrum/base_wizard.py
electrum/bitcoin.py
electrum/plugins/trustedcoin/qt.py
electrum/plugins/trustedcoin/trustedcoin.py
electrum/storage.py
electrum/tests/test_wallet_vertical.py
electrum/version.py

2fa segwit (from ghost43's PR)

---

electrum/gui/qt/main_window.py
electrum/gui/qt/seed_dialog.py
electrum/plugins/revealer/__init__.py
electrum/plugins/revealer/qt.py

new interface
ref. #4540 
fix #4676

 new interface ref. #4540 fix #4676

---

electrum/interface.py
electrum/network.py

based on https://github.com/spesmilo/electrum/pull/4944

network: put NetworkTimeout constants together

---

electrum/blockchain.py
electrum/tests/test_wallet_vertical.py
electrum/wallet.py

more complex logic for setting locktime of new transactions
- check if chain tip is stale
see https://github.com/bitcoin/bitcoin/pull/15039
- randomise locktime occasionally
see https://github.com/bitcoin/bitcoin/blob/df73c23f5fac031cc9b2ec06a74275db5ea322e3/src/wallet/wallet.cpp#L2595-L2600

wallet: randomise locktime of transactions a bit. also check if stale.

---

README.rst

Correct filename paths under Creating Binaries.

Update: README.rst

---

electrum/gui/qt/utxo_list.py

Similarly to https://github.com/spesmilo/electrum/pull/5026 , this refactor makes UTXOList somewhat easier to subclass.

Refactor for loop in UTXOList

---

electrum/exchange_rate.py
electrum/gui/kivy/uix/dialogs/fx_dialog.py

I inserted history checkbox option for all currencies in android.

android all currencies with history checkbox

---

electrum/gui/qt/address_list.py
electrum/gui/qt/history_list.py
electrum/gui/qt/invoice_list.py
electrum/gui/qt/request_list.py
electrum/gui/qt/utxo_list.py

Fix bug in request list where address was copied instead of column specific data

Strip whitespace from amounts when copying. 

---

electrum/servers.json

Spreading malware

---

electrum/keystore.py
electrum/tests/test_transaction.py

keystore/transactions: fix overflow of derivation path indices

---

electrum/transaction.py

As in title, segwit input signing was doing quadratic hashing.
Performance improvements are negligible for typical transactions.
Only looked into this as I was playing on testnet with transactions that had 1000+ inputs.
I think the mental overhead introduced as a result of the changes is also negligible though :)
Some measurements of wall clock time for `Transaction.sign` (with libsecp256k1):
```
0.11 sec -> 0.08 sec    (  61 p2wpkh-p2sh inputs, 1 output)
2.48 sec -> 0.75 sec    ( 522 p2wpkh-p2sh inputs, 1 output)
13.2  sec -> 1.8  sec    (1445 p2wpkh inputs, 1 output)
176.4  sec -> 7.6  sec    (5542 p2wpkh inputs, 1 output)
```

transaction: segwit input signing was doing quadratic hashing

---

electrum/currencies.json
electrum/exchange_rate.py

Bitmarket does not exist anymore.

Exchange fix

---

electrum/gui/kivy/uix/dialogs/installwizard.py

fix android back button behavior in gui/kivy/uix/dialogs/installwizard.py
As in https://github.com/akhavr/electrum-dash/issues/88

gui/kivy: fix installwizard back button behaviour

---

electrum/tests/test_lnrouter.py

This makes the code more maintainable.

test_lnrouter: Pull in chain_hash from constants

---

electrum/gui/qt/history_list.py

Update utxo list when label is changed on history list

---

electrum/gui/qt/main_window.py

fix typo: wallet.requests -> wallet.receive_requests

---

electrum/channel_db.py
electrum/lnworker.py

fix expected returned peer address values when opening channel.

---

electrum/segwit_addr.py

segwit_addr: Use normal comparison for tuple literal

---

electrum/plugins/coldcard/qt.py

Fix needed after recent API change in: 5c1340b7bd8bab9a5beb8e15b7b15ea26a334695

plugins/coldcard/qt.py: bugfix for API change on main_window.show_transaction

---

electrum/gui/qt/transaction_dialog.py

In the Qt "Transaction dialog", maybe we could aggregate the "Copy"/"QR code"/"Export" buttons into a single "Export" dropdown.
<details>
<summary>Picture, before</summary>
</details>
<details>
<summary>Pictures, after</summary>
</details>

qt tx dialog: show dropdown for "export", instead of separate buttons

---

electrum/daemon.py

When no (supported) authentication is passed to the JSON-RPC server, return a 401 HTTP error code instead of 403.  This indicates to the client that authentication is required, and also requests that to be sent using the "basic" method.  The previously-returned code 403 is now only returned if authentication is passed but not valid.
There are some JSON-RPC clients out there that only send authentication after a 401 code requested it.  Those fail to connect to the Electrum RPC interface even if the correct password is configured.  Those same clients can e.g. connect to Bitcoin Core successfully, which already implements logic matching this change.
See also https://stackoverflow.com/questions/3297048/403-forbidden-vs-401-unauthorized-http-responses.

Return 401 from RPC server for missing auth

---

electrum/gui/qt/address_list.py
electrum/gui/qt/main_window.py
electrum/gui/qt/request_list.py
electrum/plugins/hw_wallet/qt.py

fixes https://github.com/spesmilo/electrum/issues/5710
<details>
<summary>More pics</summary>
</details>
@gits7r @ecdsa

qt receive tab: show plain bitcoin address

---

contrib/requirements/requirements-hw.txt
electrum/plugins/trezor/clientbase.py
electrum/plugins/trezor/qt.py
electrum/plugins/trezor/trezor.py

implements #5418
please let me know if there's a code style tool I should be using?

Trezor: support for Shamir backup and recovery

---

electrum/servers.json

Remove phishing server icarus.tetradrachm.net

---

electrum/gui/qt/util.py
electrum/gui/qt/utxo_list.py

This fixes the issue described at #5878

Restoring old behavior of the outpoint copy to clipboard feature

---

electrum/dns_hacks.py
electrum/network.py

closes https://github.com/spesmilo/electrum/issues/5337
related: https://github.com/spesmilo/electrum/issues/4421

windows dns hacks: resolve in parallel, and split into own module

---

electrum/util.py

Simple way for allowing users to change localization of Electrum directory from ~/.electrum to somewhere else

Added ELECTRUMDIR env variable

---

electrum/tests/test_transaction.py
electrum/transaction.py

fix BCDataStream.read_bytes

---

electrum/tests/test_verifier.py
electrum/verifier.py

- fix SPV.hash_merkle_root, add tests/test_verifier.py

fix SPV.hash_merkle_root, add tests/test_verifier.py

---

electrum/lnchannel.py
electrum/lnhtlc.py
electrum/lnpeer.py
electrum/lnworker.py
electrum/tests/test_lnpeer.py

First implementation of htlc switch.

Htlc switch

---

electrum/gui/kivy/uix/dialogs/installwizard.py
electrum/gui/qt/installwizard.py

fixes https://github.com/spesmilo/electrum/issues/6043

wizard: add a warning to multisig wallet creation to backup xpubs

---

electrum/commands.py

Makes it easier for calling code to know what error happened.

Use specific Exception when chain isn't synced

---

electrum/commands.py
electrum/gui/kivy/main_window.py
electrum/gui/kivy/uix/dialogs/lightning_channels.py
electrum/gui/qt/__init__.py
electrum/gui/qt/channels_list.py
electrum/gui/qt/main_window.py
electrum/gui/qt/settings_dialog.py
electrum/lnchannel.py
electrum/lnpeer.py
electrum/lnsweep.py
electrum/lnutil.py
electrum/lnwatcher.py
electrum/lnworker.py
electrum/tests/test_lnpeer.py
electrum/transaction.py
electrum/wallet.py
electrum/wallet_db.py

- channels can be backed up individually
- backups are added to lnwatcher
- AbstractChannel ancestor class

Replace wallet backup with channel backups

---

electrum/gui/qt/network_dialog.py

qt network dialog: merge "Overview" and "Servers" tabs

---

electrum/lnchannel.py
electrum/lnhtlc.py
electrum/lnonion.py
electrum/lnpeer.py
electrum/lnutil.py
electrum/lnworker.py

- persist fail_htlc error messages
- do not rely on payment_hash in htlc_switch

fix htlc forwarding:

---

electrum/lnchannel.py
electrum/lnpeer.py
electrum/tests/test_lnpeer.py

add extra states to describe progress of closing negotiation. see #6182

---

electrum/gui/kivy/uix/dialogs/tx_dialog.py
electrum/gui/qt/transaction_dialog.py
electrum/transaction.py
electrum/wallet.py

closes #5749
These warning texts are really hard to write...

tx dialog: show various warnings if input amounts cannot be verified

---

contrib/build-wine/deterministic.spec
contrib/osx/osx.spec
contrib/requirements/requirements.txt
electrum/daemon.py
electrum/lnworker.py
electrum/util.py

we don't need to pull those dependencies, aiohttp makes it easy to write from scratch

Remove dependencies: jsonrpcserver, jsonrpcclient

---

electrum/commands.py
electrum/gui/kivy/uix/dialogs/invoice_dialog.py
electrum/gui/kivy/uix/dialogs/lightning_open_channel.py
electrum/gui/kivy/uix/dialogs/request_dialog.py
electrum/gui/kivy/uix/screens.py
electrum/gui/qt/amountedit.py
electrum/gui/qt/invoice_list.py
electrum/gui/qt/main_window.py
electrum/gui/qt/request_list.py
electrum/invoices.py
electrum/json_db.py
electrum/lnaddr.py
electrum/lnchannel.py
electrum/lnworker.py
electrum/paymentrequest.py
electrum/tests/test_lnpeer.py
electrum/util.py
electrum/wallet.py
electrum/wallet_db.py

WIP alternative to https://github.com/spesmilo/electrum/pull/6252

LN invoices: support msat precision (alt 2nd approach)

---

electrum/util.py

Add mempool.space option for mainnet block explorer

---

electrum/invoices.py
electrum/wallet.py
electrum/wallet_db.py

related:
https://github.com/spesmilo/electrum/issues/6284
https://github.com/spesmilo/electrum/issues/6203#issuecomment-649853732

invoices: make sure that OnchainInvoice .exp and .time are not None

---

electrum/gui/qt/installwizard.py
electrum/plugins/trezor/clientbase.py

These `raise UserCacnelled` calls looks like typos

fix raise UserCacnelled calls

---

contrib/android/Dockerfile
electrum/gui/kivy/main_window.py

fixes #6276
see
https://github.com/SomberNight/python-for-android/commit/710d923aee389085799ab8313df6b7c8336744fa
https://github.com/SomberNight/python-for-android/commit/0dd2ce87a8f380d20505ca5dc1e2d2357b4a08fc

android: fix back button not working (main surface loses focus)

---

electrum/gui/qt/main_window.py
electrum/lnworker.py

qt receive tab: fix creating new payreq with all used imported wallet

---

electrum/gui/qt/swap_dialog.py

This PR fixes the wording in the swap dialog so that the description on the top updates when the swap direction is changed.

gui swap: fix swap wording

---

electrum/util.py

*Fixed Blockchain.com Testnet-URL

Fix Blockchain.com Testnet-URL

---

electrum/gui/qt/console.py

Remove main function from console.py and fix a typo.
The Python console isn't meant to run as a standalone.

Clean console.py

---

electrum/plugin.py
electrum/plugins/bitbox02/bitbox02.py
electrum/plugins/coldcard/coldcard.py
electrum/plugins/digitalbitbox/digitalbitbox.py
electrum/plugins/hw_wallet/plugin.py
electrum/plugins/keepkey/clientbase.py
electrum/plugins/keepkey/keepkey.py
electrum/plugins/ledger/ledger.py
electrum/plugins/safe_t/clientbase.py
electrum/plugins/safe_t/safe_t.py
electrum/plugins/trezor/clientbase.py
electrum/plugins/trezor/trezor.py

hidapi/libusb etc are not thread-safe.
related: #6554

hardware devices: run all device communication on dedicated thread

---

contrib/build-wine/Dockerfile
contrib/build-wine/build.sh
contrib/build-wine/deterministic.spec
contrib/build-wine/prepare-wine.sh
contrib/make_libsecp256k1.sh
contrib/make_zbar.sh
electrum/qrscanner.py

This allows bundling much newer zbar that includes many fixes.
related: #6018
This is largely based on
https://github.com/Electron-Cash/Electron-Cash/pull/1362
https://github.com/Electron-Cash/Electron-Cash/pull/1363
https://github.com/Electron-Cash/Electron-Cash/pull/1365
https://github.com/Electron-Cash/Electron-Cash/commit/eda015908e9d6ea9a0adfbda9db55b929c0926ba
(note: tested that reproducible build still works: got same hashes for win binaries on an Ubuntu and a Manjaro host)

win binary: build zbar ourselves

---

contrib/android/Dockerfile

compare https://github.com/kivy/buildozer/blob/0.39/docs/source/installation.rst
and https://github.com/kivy/buildozer/blob/1.2.0/docs/source/installation.rst

android build: update list of apt deps for buildozer

---

electrum/util.py

Same software as mempool.space other operator.

add mempool.emzy.de explorer

---

electrum/lnrater.py

Fix https://github.com/spesmilo/electrum/issues/6764

Fix get_running_loop (python<3.7)

---

electrum/gui/qt/contact_list.py

Try to fix https://github.com/spesmilo/electrum/issues/6356

Fix Import/Export contacts issue

---

electrum/currencies.json
electrum/exchange_rate.py

I added new exchange rate for brazillians: Walltime.

Added new brazillian exchange to exchange rates plugin: Walltime.

---

electrum/gui/qt/swap_dialog.py

fixes #6831
related: https://github.com/spesmilo/electrum/pull/6795
should we maybe rename `self.tx`?
It is evidently confusing for everyone that it is only applicable for the forward swaps.

qt swap dialog: fix enabling OK button

---

electrum/mnemonic.py
electrum/plugins/trustedcoin/trustedcoin.py

fixes https://github.com/spesmilo/electrum/issues/4326

mnemonic: tighten seed_type check for old "2fa" type seeds

---

electrum/invoices.py
electrum/wallet.py

Save height in invoices, use it to determine invoice status

---

electrum/gui/kivy/uix/dialogs/tx_dialog.py
electrum/gui/qt/history_list.py
electrum/gui/qt/main_window.py
electrum/tests/test_wallet_vertical.py
electrum/transaction.py
electrum/wallet.py

we fetch the missing prev txs over network
fixes #6551
fixes #6864

wallet: fix bump_fee and dscancel for "not all inputs ismine" case

---

electrum/gui/kivy/main_window.py
electrum/gui/kivy/uix/screens.py
electrum/gui/kivy/uix/ui_screens/receive.kv
electrum/gui/kivy/uix/ui_screens/send.kv
electrum/gui/qt/invoice_list.py
electrum/gui/qt/main_window.py
electrum/gui/qt/request_list.py
electrum/wallet.py

- delay 3 seconds in GUI
- rename invoice lists to "send queue", "receive queue"
- kivy remove 'delete' buttons from send/receive screens

auto-remove paid invoices from GUI

---

electrum/gui/qt/paytoedit.py

- qt: fix PayToEdit.parse_amount

qt: fix PayToEdit.parse_amount

---

electrum/invoices.py
electrum/lnaddr.py
electrum/wallet_db.py

We should validate that invoices/payreqs have sane amount values to make sure we can do decimal arithmetic with them.
Fixes https://github.com/spesmilo/electrum/issues/5223
The included wallet db upgrade fixes the corruption issue (https://github.com/spesmilo/electrum/issues/5223#issuecomment-780982742) for affected wallets.
Note that this PR does not touch the GUI so it remains possible to *attempt to* create invoices/payreqs with absurd amounts but an exception will propagate out. The invalid invoices will not get saved to the wallet file anymore as we categorically forbid constructing the objects.

invoices: validate 'amount' not to be out-of-bounds

---

electrum/lnonion.py
electrum/lnpeer.py
electrum/lnutil.py
electrum/lnworker.py
electrum/mpp_split.py
electrum/tests/test_lnpeer.py
electrum/tests/test_mpp_split.py

Implements a strategy to split payments and adds some last ingredients to complete multipart payment support. Related to #6586.

Complete multipart payment sending support

---

electrum/tests/test_mpp_split.py

Tests should now pass also for versions 3.6 and 3.7.
I removed the specific numbers from the test as we are interested in the general splitting behavior. I couldn't figure out what is the exact difference between 3.8 and <3.8, but one thing I observe is that the tests have equal outcomes to the 3.8 version once the seeding is moved to the global scope instead of seeding during the test set up :fearful:.

mpp_split: fix tests for python versions < 3.8

---

electrum/gui/qt/main_window.py
electrum/gui/qt/transaction_dialog.py

Added fiat fee estimate to Advanced Preview

---

electrum/gui/kivy/uix/dialogs/addresses.py

Also expose "freeze address" functionality to kivy GUI.

kivy: implement freezing addresses

---

electrum/gui/qt/main_window.py

(re onchain payments)
Beginner users often ask why they cannot send their full balance.
Hence, this intends to reduce support load.
In terms of UI, maybe there is a better way to do this but this was
easy to do and still a good first step IMHO.

qt send tab: when clicking "Max", show tooltip explaining max amt

---

electrum/bip39_wallet_formats.json

Update bip39_wallet_formats.json, replace PR 7260

---

electrum/commands.py

swaps: fix satoshi conversion bug

---

electrum/wallet.py
electrum/wallet_db.py

fixes https://github.com/spesmilo/electrum/issues/7339

wallet: fix channels backups in .backup files

---

electrum/gui/kivy/main_window.py
electrum/gui/kivy/uix/screens.py

Added BTC and Fiat amount(as enabled by the user) on the confirmation screen for a Lightning Invoice in the Kivy GUI #7410

Added BTC and Fiat amount on the confirmation screen for Lightning Invoice

---

contrib/android/bitcoin_intent.xml
contrib/build-wine/electrum.nsi
contrib/osx/make_osx
electrum.desktop
electrum/gui/kivy/main_window.py
electrum/gui/kivy/uix/screens.py
electrum/gui/qt/main_window.py
electrum/gui/qt/paytoedit.py
electrum/lnaddr.py
electrum/tests/test_bolt11.py
run_electrum

Adds `lightning:` URI support for Android and Qt. I hope I found all the places where the mimetype is added to the system, but unsure about macOS. Related: #7253.

qt+android: add lightning URI support

---

electrum/gui/qt/main_window.py

fix ln payments: set payto_e ln invoice correctly

---

contrib/build-linux/appimage/Dockerfile

https://launchpad.net/ubuntu/+source/openssl/1.0.2g-1ubuntu4.20

appimage build: update libssl-dev libssl1.0.0 openssl

---

electrum/commands.py
electrum/gui/kivy/uix/screens.py
electrum/gui/qt/main_window.py
electrum/gui/qt/paytoedit.py
electrum/util.py
electrum/wallet.py

Multiple max spends functionality added

---

electrum/gui/kivy/uix/dialogs/cpfp_dialog.py
electrum/gui/kivy/uix/dialogs/tx_dialog.py

implements https://github.com/spesmilo/electrum/issues/5507

Added CPFP Feature for Kivy GUI

---

electrum/json_db.py
electrum/lnchannel.py
electrum/lnhtlc.py
electrum/lnpeer.py
electrum/tests/test_lnchannel.py
electrum/wallet_db.py

Do not convert StoredDict keys to str.
Instead, convert json keys to int when storage is read.

No convert key

---

electrum/channel_db.py

Python3.9 compat: sample from list

---

contrib/build-linux/appimage/Dockerfile

https://ubuntu.pkgs.org/18.04/ubuntu-main-amd64/libudev1_237-3ubuntu10_amd64.deb.html
https://ubuntu.pkgs.org/18.04/ubuntu-main-amd64/libudev-dev_237-3ubuntu10_amd64.deb.html

appimage build: update libudev-dev libudev1

---

electrum/daemon.py

The daemon by default listens for RPC over a socket.
Before this change, this socket was a TCP/IP network socket (over localhost),
but now we change it to be a unix domain socket by default (if available).
This socket is used not only when sending commands over JSON-RPC,
but also when using the CLI, and to a tiny extent even used when running the GUI.
The type of socket used (and hence this change) is invisible to CLI and GUI users.
JSON-RPC users might want to use either the --rpcsock CLI flag
or set the "rpcsock" config key (to "tcp") to switch back to using a TCP/IP socket.
In practice it seems unix domain sockets are available on
all mainstream OSes/platforms, except for Windows.
closes https://github.com/spesmilo/electrum/issues/7553

daemon: change `rpcsock` default to "unix" where available

---

electrum/wallet.py

Minor grammar fixes at lines 1403 and 1467.

Minor grammar fixes

---

electrum/lnpeer.py
electrum/lnworker.py
electrum/tests/test_lnpeer.py

all messages are sent in reestablish_channel
on_channel_reestablish will not be cancelled if the connection is closed
revert 57583c05cf0a4e083801e375421ded77f44e113f

Separate reestablish_channel and on_channel_reestablish.

---

contrib/android/p4a_recipes/libsecp256k1/__init__.py
contrib/make_libsecp256k1.sh

note: I just want the CI to attempt the binary builds

bump libsecp256k1 version

---

electrum/daemon.py

fix rpcsock

---

README.rst

It is helpful for contributors to discover how to run unit tests easily.
Closes #6534

README: docs on how to run unit tests

---

contrib/deterministic-build/README.md
contrib/requirements/requirements-build-android.txt

related https://github.com/spesmilo/electrum/pull/7703#discussion_r826140909

android build: add Qt/QML build-time dependencies

---

contrib/build-linux/appimage/Dockerfile

https://launchpad.net/ubuntu/+source/openssl/1.1.1-1ubuntu2.1~18.04.15

appimage: update libssl-dev libssl1.0.0 openssl

---

contrib/osx/notes_for_arm.md

Installation notes for building from source for Apple M1 (ARM) 
@SomberNight

Notes for Apple M1 build from source

---

electrum/address_synchronizer.py
electrum/gui/qt/settings_dialog.py
electrum/lnworker.py
electrum/submarine_swaps.py

Confirm reverse swaps

---

contrib/build-linux/appimage/Dockerfile

https://launchpad.net/ubuntu/+source/git/1:2.17.1-1ubuntu0.10

appimage: update git

---

electrum/exchange_rate.py

closes https://github.com/spesmilo/electrum/issues/7770

exchange_rate: normalise some internal types, saner Decimal conversion

---

electrum/plugins/bitbox02/bitbox02.py
electrum/plugins/coldcard/coldcard.py
electrum/rsakey.py
electrum/tests/test_bolt11.py

Credit to Zoltan Konder for pointing me to this issue.

Fix "== None" linter fails

---

electrum/address_synchronizer.py
electrum/commands.py
electrum/gui/kivy/main_window.py
electrum/gui/kivy/uix/dialogs/addresses.py
electrum/gui/kivy/uix/dialogs/request_dialog.py
electrum/gui/kivy/uix/dialogs/tx_dialog.py
electrum/gui/kivy/uix/screens.py
electrum/gui/qt/address_list.py
electrum/gui/qt/channels_list.py
electrum/gui/qt/history_list.py
electrum/gui/qt/main_window.py
electrum/gui/qt/transaction_dialog.py
electrum/lnchannel.py
electrum/lnpeer.py
electrum/lnwatcher.py
electrum/lnworker.py
electrum/network.py
electrum/submarine_swaps.py
electrum/synchronizer.py
electrum/tests/test_commands.py
electrum/tests/test_lnpeer.py
electrum/tests/test_wallet.py
electrum/tests/test_wallet_vertical.py
electrum/wallet.py

The issues I mentioned yesterday (unwanted notifications and is_mine) are fixed.
There might still be instances of `wallet.method` calls that need to be changed to `wallet.adb.method`

Persist lnwatcher

---

contrib/build-linux/appimage/Dockerfile

https://launchpad.net/ubuntu/+source/openssl/1.1.1-1ubuntu2.1~18.04.19

appimage: update libssl-dev libssl1.1 openssl

---

contrib/build-linux/appimage/Dockerfile

https://launchpad.net/ubuntu/+source/git/1:2.17.1-1ubuntu0.12

appimage: Bump git

---

electrum/servers.json

Remove ca.poiuty.com as duplicate.
```
ca.poiuty.com 176.9.63.51
de.poiuty.com 176.9.63.51
```

remove ca.poiuty.com

---

electrum/gui/qt/history_list.py
electrum/wallet.py

This is an alternative to https://github.com/spesmilo/electrum/pull/7932
The first three commits are taken from that branch.

wallet: rm `maybe_set_tx_label_based_on_invoices`, just use `get_default_label`

---

electrum/plugins/jade/jadepy/README.md
electrum/plugins/jade/jadepy/__init__.py
electrum/plugins/jade/jadepy/jade.py

Update jade client library, thanks.

jade: update Jade api to 0.1.37

---

.cirrus.yml

Trying to get the CI to build the qml apk on every commit...
Let's see the CI.

CI: try to cache android apk builds

---

electrum/commands.py

Minor fixes. Noticed that requested_amount is not used, it could be cleaned from there.

commands: Remove unused requested_amount and fix a typo

---

contrib/build-linux/appimage/make_appimage.sh
contrib/build-wine/deterministic.spec
contrib/build-wine/make_win.sh
contrib/build-wine/prepare-wine.sh
contrib/osx/make_osx.sh
contrib/osx/osx.spec

follow-up 7d83335e34d7ea4752145b47e086a9fbe45742ad

libsecp256k1: update hardcoded .so lib name in binaries

---

electrum/gui/qml/qeinvoicelistmodel.py
electrum/gui/qml/qerequestdetails.py
electrum/gui/qt/receive_tab.py
electrum/gui/qt/request_list.py
electrum/invoices.py
electrum/lnworker.py
electrum/submarine_swaps.py
electrum/tests/test_invoices.py
electrum/tests/test_lnpeer.py
electrum/wallet.py
electrum/wallet_db.py

- wallet_db update: separate Invoices and Requests.
- do not store bolt11 invoice in Request
fixes #8213

Refresh bolt11 routing hints when channel liquidity changes:

---

electrum/gui/qml/components/LnurlPayRequestDialog.qml
electrum/gui/qml/qeinvoice.py

@accumulator can you have a look please ?
note: the signal `lnurlError` does not seem to be caught anywhere

qml: let user enter lnurl6 amount

---

electrum.desktop

remove PATH manipulation from .desktop file

---

electrum/gui/qml/__init__.py
electrum/gui/qml/components/controls/SeedKeyboard.qml
electrum/gui/qml/components/controls/SeedKeyboardKey.qml
electrum/gui/qml/components/controls/SeedTextArea.qml
electrum/gui/qml/components/main.qml
electrum/gui/qml/components/wizard/WCConfirmSeed.qml
electrum/gui/qml/components/wizard/WCHaveSeed.qml

This adds a custom qwerty keyboard to SeedTextArea, so we can use the system keyboard for the rest of the GUI.

custom keyboard for seed entry

---

electrum/gui/qml/components/ConfirmTxDialog.qml
electrum/gui/qml/components/CpfpBumpFeeDialog.qml
electrum/gui/qml/components/RbfBumpFeeDialog.qml
electrum/gui/qml/components/RbfCancelDialog.qml
electrum/gui/qml/components/TxDetails.qml
electrum/gui/qml/components/controls/TxOutput.qml
electrum/gui/qml/qetxfinalizer.py

We could add this too for ConfirmTxDialog, but not convinced it is useful there.

qml: add share toolbutton for outputs in TxDetails

---

contrib/make_download

see https://github.com/spesmilo/electrum-web/pull/20

contrib/make_download: adapt to downloads being merged into index.html

---

electrum/gui/qml/components/ChannelDetails.qml
electrum/gui/qml/components/Constants.qml
electrum/gui/qml/components/controls/ChannelBar.qml
electrum/gui/qml/components/controls/ChannelDelegate.qml
electrum/gui/qml/qechanneldetails.py
electrum/gui/qml/qechannellistmodel.py

Would this be sufficient to have some indication of #8411 ?

qml: render reserved channel capacity in a darker tone, take frozen into account

---

electrum/commands.py
electrum/lnworker.py
electrum/plugins/swapserver/__init__.py
electrum/plugins/swapserver/cmdline.py
electrum/plugins/swapserver/qt.py
electrum/plugins/swapserver/server.py
electrum/plugins/swapserver/swapserver.py
electrum/simple_config.py
electrum/submarine_swaps.py
electrum/tests/regtest.py
electrum/tests/regtest/regtest.sh

todo: 
- fix the hash returned in get_pairs
- fix GUI grouping for forward swaps with prepay
(continued from https://github.com/spesmilo/electrum/pull/8467)

Swapserver plugin

---

AUTHORS
electrum/plugins/revealer/qt.py

This fixes the layout problem discussed at #8586.

Fix Revealer Qt layout

---

electrum/bitcoin.py
electrum/coinchooser.py
electrum/gui/qml/qechannelopener.py
electrum/gui/qml/qeswaphelper.py
electrum/gui/qt/confirm_tx_dialog.py
electrum/gui/qt/main_window.py
electrum/gui/qt/send_tab.py
electrum/gui/qt/swap_dialog.py
electrum/gui/qt/transaction_dialog.py
electrum/lnpeer.py
electrum/lnutil.py
electrum/lnworker.py
electrum/simple_config.py
electrum/submarine_swaps.py
electrum/transaction.py
electrum/wallet.py

Todo:
- check min/max amount that we can send in a swap, fallback to normal change address
- <s>fail HTLCs if the user double spends</s>
- show warnings in ConfirmTxDialog

send tx change to lightning

---

electrum/wallet.py

The previous lower bound did not ensure that, sometimes resulting in tx rejection. Note, though, that BIP125 does not explicitly state that the new feerate must be strictly higher than the old feerate.

rbf batching: make sure new feerate > old feerate

---

electrum/gui/qt/wizard/wallet.py

- I think this fixes https://github.com/spesmilo/electrum/issues/8665
- adds missing "duplicate master key"/etc validation to WCHaveMasterKey
@accumulator, could you have a look?

some qt wizard fixes/cleanup (WCHaveMasterKey, WCHaveSeed)

---

electrum/gui/qml/components/AddressDetails.qml
electrum/gui/qml/components/Addresses.qml
electrum/gui/qml/qeaddressdetails.py
electrum/gui/qml/qeaddresslistmodel.py
electrum/gui/qml/qewallet.py
electrum/wallet.py

also fixes address list after address/key add.

qml: implement delete address for imported wallets

---

electrum/commands.py
electrum/gui/qml/components/TxDetails.qml
electrum/gui/qml/qetxdetails.py
electrum/gui/qml/qewallet.py
electrum/gui/qt/main_window.py
electrum/gui/qt/transaction_dialog.py
electrum/tests/test_wallet_vertical.py
electrum/transaction.py
electrum/wallet.py

show warning message in transaction dialog if one of my inputs have non-standard sighash.

---

electrum/gui/qml/components/ExceptionDialog.qml
electrum/gui/qml/components/NewWalletWizard.qml
electrum/gui/qml/components/OpenChannelDialog.qml
electrum/gui/qml/components/TxDetails.qml
electrum/gui/qml/components/WalletDetails.qml
electrum/gui/qml/components/WalletMainView.qml
electrum/gui/qml/components/main.qml

qml: use warning icon and error title for failure messagedialogs 

---

electrum/gui/qml/components/controls/FormattedAmount.qml
electrum/gui/qml/components/controls/HistoryItemDelegate.qml
electrum/gui/qml/qefx.py

qml: don't show fiat amount when timestamp more than a day old and historic rates are disabled

---

contrib/android/Dockerfile
contrib/android/p4a_recipes/libzbar/__init__.py
contrib/build-linux/appimage/Dockerfile
contrib/build-linux/appimage/make_appimage.sh
contrib/make_zbar.sh

see individual commit messages
(note: I've tested android/win/appimage but not mac)

build: bump zbar

---

electrum/util.py

closes https://github.com/spesmilo/electrum/issues/6961

gui: label tx sizes as "vbytes", and feerates as "sat/vbyte"

---

electrum/gui/qml/components/ConfirmTxDialog.qml
electrum/gui/qml/components/CpfpBumpFeeDialog.qml
electrum/gui/qml/components/RbfBumpFeeDialog.qml
electrum/gui/qml/components/RbfCancelDialog.qml
electrum/gui/qml/components/controls/FeePicker.qml
electrum/gui/qml/qetxfinalizer.py

Improves styling and avoids duplication of code.
Also in preparation for manual fee editing

qml: consolidate fee slider ui in various places to a single FeePicker control

---

electrum/servers_signet.json

Remove bublina Signet

---

electrum/submarine_swaps.py
electrum/wallet.py

- funding txs having only one output is not true...
- batch_rbf can combine funding txs

swaps: fix get_swap_by_funding_tx, and types/type-hints

---

org.electrum.electrum.metainfo.xml

AppStream wants a few additional elements.

Update AppStream metainfo.xml.

---

electrum/plugins/jade/jadepy/jade.py

chore: fix typos

---

electrum/plugins/bitbox02/bitbox02.py

There is some code duplication through this change, I'm open to suggestions.

Call pairing dialog when necessary, fixes #8970

---

electrum/gui/qml/components/Preferences.qml
electrum/gui/qml/qeconfig.py

qml: expose LIGHTNING_PAYMENT_BUDGET_FEE_MAX_MILLIONTHS in preferences

---

electrum/plugins/trezor/clientbase.py
electrum/plugins/trezor/qt.py
electrum/plugins/trezor/trezor.py

This enables support for the Trezor Safe 5.

trezor: Fix for trezor library version 0.13.9

---

electrum/gui/common_qt/i18n.py
electrum/gui/qml/__init__.py
electrum/gui/qt/__init__.py
electrum/gui/qt/lightning_tx_dialog.py
electrum/gui/qt/transaction_dialog.py

qt/transaction_dialog: fix translation issues

---

electrum/commands.py
tests/test_commands.py

This is most useful if the user wants to import a significant number of keys,
as every invocation of `importprivkey` results in rewriting the wallet file to disk.
The API of "importprivkey" is left unchanged for the single privkey case.

commands: extend "importprivkey" to allow importing a list of keys

---

electrum/gui/qml/qetxfinalizer.py

Show high fee warnings also for RBF/dscancel in qml gui.

qml: qetxfinalizer: use wallet.get_tx_fee_warning in all subclasses

---

.cirrus.yml
README.md
contrib/build-linux/sdist/Dockerfile
contrib/build-linux/sdist/make_sdist.sh
contrib/freeze_packages.sh
electrum/daemon.py
electrum/network.py
electrum/plugin.py
electrum/util.py
run_electrum
setup.py
tests/qt_util.py

closes https://github.com/spesmilo/electrum/issues/9239

bump min python to 3.10

---

tests/test_lnpeer.py

Adds a new test case for e2e trampoline payment, where there are multiple Trampoline Forwarders which themselves are not directly connected.
This adds a regression test for https://github.com/spesmilo/electrum/pull/9431
https://github.com/spesmilo/electrum/commit/dffdebf778327baae0502b3ec0b57092d48a24d6

tests: lnpeer: add test payment_trampoline_e2e A->T1->C>T2->E

---

electrum/gui/qt/send_tab.py

Also disables Save button when invoice has expired.

qt: show warning on expired invoice on send tab.

---

electrum/lnworker.py

Submitted as PR, as there's a small import conflict with #9542

lnworker: imports, whitespace

---

electrum/simple_config.py
tests/test_simple_config.py

ref https://github.com/spesmilo/electrum/pull/9597#discussion_r1977866311

config: raise on setting mistyped or non-existent ConfigVar

---

electrum/channel_db.py
electrum/commands.py
electrum/lnpeer.py
electrum/lnworker.py

gossip: less log lines, use command line instead

---

electrum/gui/qml/qeswaphelper.py

The swap slider / window currently throws an exception because `FeePolicy` is not passed to `make_unsigned_transaction` in `update_fee` and `_create_tx`, this fixes it.

Use FeePolicy in qeswaphelper to fix exception

---

electrum/gui/qt/main_window.py
electrum/wallet.py

alternative to https://github.com/spesmilo/electrum/pull/9630

wallet: consider "future" coins as frozen by default

---

electrum/gui/qml/qeapp.py
electrum/gui/qt/__init__.py
electrum/plugin.py
tests/test_wizard.py

Allows both internal and external plugins to be either in the form of a Zip file or a directory.

Allow all plugins to be either zip or directory based

---

electrum/plugin.py

When importing a plugin, if it raised an exception in its `__init__` file, we ignored it, and still loaded the plugin, in a potentially half-broken state. This is because maybe_load_plugin_init_method only calls exec_module_from_spec if the plugin is not already in sys.modules, but exec_module_from_spec will put the plugin into sys.modules even if it errors.
Consider this patch to test with, enable the "labels" plugin:
```patch
diff --git a/electrum/plugins/labels/__init__.py b/electrum/plugins/labels/__init__.py
index b68127df8e..0d6d95abce 100644
--- a/electrum/plugins/labels/__init__.py
+++ b/electrum/plugins/labels/__init__.py
@@ -21,3 +21,5 @@ async def pull(self: 'Commands', plugin: 'LabelsPlugin' = None, wallet=None, for
arg:bool:force:pull all labels
"""
return await …
```

plugins: better handle exceptions in `__init__`

---

electrum/submarine_swaps.py

This changes the swap nostr request event type from a type 4 dm to the event type 25582. Using an ephemeral event type is more suitable for this usecase as we don't require (and don't want) relays to store the direct messages forever. 
[NIP-01](https://github.com/nostr-protocol/nips/blob/master/01.md) defines ephemeral events as:
> for kind n such that 20000 <= n < 30000, events are ephemeral, which means they are not expected to be stored by relays.
I chose 25582 randomly as it doesn't seem to be used by anything else.
This is how [strfry](https://github.com/hoytech/strfry/blob/542552ab0f5234f808c52c21772b34f6f07bec65/strfry.conf#L29), the most common nostr relay implementation handles ephemeral events:
>   Ephemeral events older than this will be rejected …

Use ephemeral event type for nostr swap request events

---

electrum/lnworker.py

This replaces a hard coded `100_000` sats with `MIN_FUNDING_SAT` in `lnworker.suggest_funding_amount`

lnworker: use MIN_FUNDING_SAT as lower bound for channel open

---

electrum/submarine_swaps.py

Fixes race condition that caused the `assert sm.is_initialized.is_set()` in `initialize_swap_manager()` to fail because `is_initialized.set()` is called on the asyncio event loop and the assert was reached before the event was set.  
Note: https://github.com/spesmilo/electrum-aionostr/pull/9 is also required for the timeout value in `initialize_swap_manager()` to be higher than the timeout value awaited when connecting, so this PR alone doesn't completely solve the issue as the current aionostr adds +2s to the timeout val

swaps: fix race condition causing initialize_swap_manager assert to fail 

---

electrum/gui/qml/components/ConfirmTxDialog.qml
electrum/gui/qml/components/SweepDialog.qml
electrum/gui/qml/components/TxDetails.qml
electrum/gui/qml/components/WalletDetails.qml
electrum/gui/qml/components/WalletMainView.qml

qml: add ellipsis to buttons that are followed by another chance to bail

---

electrum/gui/qt/password_dialog.py
electrum/gui/qt/plugins_dialog.py
electrum/plugin.py

- Allow plugins saved as zipfiles in user data dir
- plugins are authorized with a user chosen password
- pubkey derived from password is saved with admin permissions
implements #9701

Userspace plugins:

---

electrum/lnrouter.py

If `get_shortest_path_hops()` finds a channel that is not in `my_sending_channels` but still uses our node id (`nodeA`) as starting node it will include it in the route and cause the payment to fail. Using this route will cause `pay_to_route()` to fail as we try to use a channel from our node that we have no access to (its not in our channel list).
I noticed this in form of an assertion error when trying to pay an invoice from a seed i have opened channels with in different wallet instances (same seed, different wallet).
```
26.68 | E | lnworker.LNWallet.[default_wallet] | Exception in pay_invoice: AssertionError(<ShortID: 242311x96x2>)
File "/home/user/code/electrum-fork/electrum/util.py", line 1199, in wrapper
return await func(*args, **kwargs) …
```

lightning: prevent usage of unavailable channels for payment

---

electrum/plugin.py
electrum/plugins/swapserver/__init__.py
electrum/plugins/watchtower/__init__.py
electrum/simple_config.py
tests/regtest.py
tests/test_simple_config.py

move plugin variables into sub dictionaries of user config

recursive config file

---

electrum/txbatcher.py
electrum/wallet.py

Alow user to bump fee of txbatcher transaction from GUI
fixes #9659

TxBatcher: detect if base tx has been replaced.

---

electrum/gui/qt/swap_dialog.py
electrum/submarine_swaps.py

Shows the possible swap range, or a message indicating that a swap is not possible, in the SwapDialog

swaps: show swap limits in SwapDialog

---

electrum/plugins/revealer/qt.py

there is no available documentation on what this plugin does or how it works, also the concept isn't well known. 
By adding some information in the form of a help box the user can understand the concept of what this plugin does and how it is used.

plugin: add help text to revealer plugin

---

electrum/lnworker.py

`can_pay_onchain()` has been removed in commit 840243e but suggest_swap_to_send was still calling it causing an exception when trying to pay an invoice for which there is too few outgoing liquidity to pay it via lightning.

fix: exception in suggest_swap_to_send due to missing method

---

electrum/gui/qt/transaction_dialog.py
electrum/hw_wallet/qt.py
electrum/plugins/bitbox02/qt.py
electrum/plugins/coldcard/qt.py
electrum/plugins/digitalbitbox/qt.py
electrum/plugins/jade/qt.py
electrum/plugins/keepkey/qt.py
electrum/plugins/ledger/qt.py
electrum/plugins/safe_t/qt.py
electrum/plugins/trezor/qt.py

This is motivated by https://github.com/spesmilo/electrum/pull/9589#pullrequestreview-2771395242

hardware wallets: show address on device also from tx dialog

---

electrum/gui/messages.py
electrum/gui/qt/__init__.py
electrum/gui/qt/wizard/server_connect.py
electrum/gui/qt/wizard/terms_of_use.py
electrum/simple_config.py
electrum/wizard.py

Shows the terms of use on setup in the qt gui.

qt: show terms of use as first window on setup

---

electrum/gui/text.py

Fixes a couple of issues with the text gui:
1. App crashing due to IndexError when opening the channels tab without any channels
2. App crashing when trying to pay onchain address without entering amount
3. App crashing when trying to edit Contact label due to type error
4. Implements the delete function for contacts as it is shown in the tui but was not implemented
5. uses daemon.load_wallet() instead of manually constructing the wallet, so it will get properly closed when shutting down, previously it didn't save the wallet db on close as the wallet .stop() method was not called, this is now done by the daemon.

fix: text gui exceptions and and type errors

---

electrum/gui/messages.py
electrum/gui/qt/main_window.py
electrum/lnchannel.py
electrum/lnsweep.py
electrum/lnwatcher.py
electrum/txbatcher.py
tests/regtest.py
tests/regtest/regtest.sh

warn user if closing GUI when anchor channel ctx is unconfirmed

---

electrum/gui/qml/components/TermsOfUseWizard.qml
electrum/gui/qml/components/main.qml
electrum/gui/qml/components/wizard/WCProxyConfig.qml
electrum/gui/qml/components/wizard/WCTermsOfUseRequest.qml
electrum/gui/qml/components/wizard/WCWelcome.qml
electrum/gui/qml/qeapp.py
electrum/gui/qml/qeconfig.py
electrum/gui/qml/qedaemon.py
electrum/gui/qml/qewizard.py

Adds terms of use to qml setup wizard. Flow is similar to qt. Tested on a Pixel 9, and Pixel 4a in the Emulator.

qml: add terms of use to setup wizard

---

electrum/plugins/psbt_nostr/qml.py
electrum/plugins/psbt_nostr/qml/PsbtReceiveDialog.qml
electrum/plugins/psbt_nostr/qml/main.qml

qml: offer same choices as desktop; Open, Discard, Save to wallet

Psbt nostr qml choices

---

electrum/wallet.py
tests/regtest/regtest.sh

This should make regtest extract_preimage more reliable

CLI: add preimage to invoices

---

electrum/lnchannel.py
electrum/lnworker.py
electrum/mpp_split.py
tests/test_mpp_split.py

pass number of htlc_slots_left to suggest_splits

---

electrum/address_synchronizer.py
electrum/wallet.py

- merge adb.transaction_lock and adb.lock
- take lock in more places

adb: merge `transaction_lock` and `lock`, protect more critical sections

---

electrum/address_synchronizer.py
tests/test_wallet_vertical.py

If the full tx is missing, we should force mempool/confirmed txs to be LOCAL height, however future txs should not be forced to LOCAL, they should remain FUTURE.
follow-up https://github.com/spesmilo/electrum/commit/197933debf1a31734da86edde2678c2b76987ed3

adb.get_tx_height: allow future txs to be partially signed

---

electrum/gui/qml/components/ChannelDetails.qml

qml: rm small available sending balance warning

---

contrib/deterministic-build/requirements.txt

bump aiohttp version to 3.12.9

---

electrum/plugin.py

fixes #9920
makes the plugin download use a `aiohttp.ClientSession()` constructed by `util.make_aiohttp_session()` and use a proxy if available.

fix: use make_aiohttp_session for plugin zip download

---

electrum/gui/qt/history_list.py

`do_export_history()` which is used by the qt history export function was broken as it used a method that did not exist anymore (`Abstract_Wallet.get_detailed_history()`). 
This updates `do_export_history()` to use `Abstract_wallet.get_full_history()` and also adds support for payment grouping and lightning transactions to the generated CSV file.
fixes https://github.com/spesmilo/electrum/issues/9937

fix: update do_export_history to use wallet.get_full_history

---

contrib/build-wine/pyinstaller.spec
contrib/osx/pyinstaller.spec
electrum/gui/qt/__init__.py
electrum/gui/qt/qrreader/__init__.py
electrum/gui/qt/qrreader/qtmultimedia/__init__.py

fixes https://github.com/spesmilo/electrum/issues/9949

qt gui: be more resilient against import issues with QtMultimedia

---

electrum/gui/messages.py
electrum/gui/qml/components/ReceiveDetailsDialog.qml
electrum/plugins/timelock_recovery/qt.py

fix some minor issues in the comments

chore: fix some minor issues in the comments

---

electrum/gui/qt/history_list.py

Draft because on top of #9968
Closes #9969

history: fix displayed STATUS sort order

---

electrum/address_synchronizer.py
electrum/commands.py
electrum/fee_policy.py
electrum/lnwatcher.py
electrum/plugins/watchtower/watchtower.py
electrum/submarine_swaps.py
electrum/txbatcher.py
tests/regtest.py
tests/regtest/regtest.sh

- adds a regtest test to reproduce https://github.com/spesmilo/electrum/issues/9980
- fixes https://github.com/spesmilo/electrum/issues/9980
(see individual commits)

lnwatcher: keep_watching until fees go down

---

electrum/lnwatcher.py

when a channel is redeemed, we still need to call the callback in order to set labels, accounting_addresses.
Fixes #9987

lnwatcher: add 'subscribe' parameter to add_callback

---

electrum/submarine_swaps.py

`NostrTransport.update_relays()` raises a `KeyError` when the offer of the configured swapserver (`config.SWAPSERVER_NPUB`) is not in `self._offers` even though `sm.pairs_updated` gets triggered. This happens (sometimes) because `NostrTransport.get_pairs()` called `sm.update_pairs()` before adding the received offer to `self._offers`.
Example:
```
64.70 | I | submarine_swaps.NostrTransport | connected relays: ['wss://nostr.mom', 'wss://relay.getalby.com/v1', 'wss://relay.primal.net', 'wss://nostr.einundzwanzig.space', 'wss://eu.purplerelay.com', 'wss://nos.lol', 'wss://relay.damus.io']
64.74 | I | submarine_swaps.SwapManager | updating fees SwapFees(percentage=0.5, mining_fee=1845, min_amount=20000, max_forward=1200000, max_reverse=5700000)
64.74 | E | submarine_swaps.NostrTransport | …
```

fix: NostrTransport.update_relays() KeyError

---

electrum/commands.py
tests/test_commands.py

Adds an optional `closest_htlc_expiry_height` value to the `check_hold_invoice` cli command response. This allows to see the next absolute expiry height of the pending htlcs of a payment (if `status` == `paid`). 
Note, htlcs will get failed before the actual expiry height (if block_height + 144 > htlc.cltv_abs).
Closes #10079

cli: return closest htlc expiry from check_hold_invoice

---

electrum/wallet.py

in particular, the "Cannot delete last remaining address from wallet" check should run inside the lock
- tangentially related: https://github.com/spesmilo/electrum/issues/10104#issuecomment-3151165340

wallet: more locking in delete_address

---

electrum/submarine_swaps.py

Adds logic to retry sending a direct message in
`NostrTransport.send_direct_message()` on `TimeoutError`. Handles `TimeoutError` exception more gracefully by catching it and returning `None`.

swaps: make NostrTransport.send_direct_message() more robust

---

electrum/submarine_swaps.py

I am a bit fuzzy on how this stuff works exactly -- could you review, @f321x ?

swaps: nostr: add sanity checks for replies

---

electrum/txbatcher.py
tests/test_txbatcher.py

1. Do not remove local transaction in find_base_tx.
This logic was intended to cleanup claim transactions that are never broadcast (for example, if the counterparty gets a refund) (see 1bf1de36cbbab3ef9bd06bf5009074f11f0d456d)
However, this code is too unspecific and may result in fund loss, because the transaction being removed may contain outgoing payments. For example, if the electrum server is not responsive, the tx will be seen as local and deleted. In that case, another payment will be attempted, thus paying twice.
2. Do not remove tx after try_broadcasting returns False.
The server might be lying to us. We can only remove the local tx if there is a base_tx, because the next tx we create will try to spend the same output.

txbatcher: be careful when removing local transactions

---

electrum/daemon.py
electrum/gui/qml/qedaemon.py
tests/test_daemon.py

- fix: qml gui errors when trying to open a wallet with only keystore-encryption
- fixes https://github.com/spesmilo/electrum/issues/10171
- qml gui to prompt for password on wallet open even if wallet is not storage-encrypted
- IIRC it is not the first time we had this regression. I hope by unifying the code paths like this, it won't come back again.

daemon: load_wallet: add force_check_password arg, and use it in qml

---

electrum/lnpeer.py
electrum/submarine_swaps.py

This was already implicitly checked. This diff makes the check explicit, and serves as an additional sanity-check.
- for client-forward-swaps, we have
- "cltv safety requirement: (onchain_locktime < LN_locktime),   otherwise client is vulnerable"
- server chooses onchain locktime delta = 70
https://github.com/spesmilo/electrum/blob/71255c1e735cdfcd881e045b9f2f6bc6b599f459/electrum/submarine_swaps.py#L701
- client checks that onchain locktime delta is <100
https://github.com/spesmilo/electrum/blob/71255c1e735cdfcd881e045b9f2f6bc6b599f459/electrum/submarine_swaps.py#L887
- client chooses LN locktime delta = 432
https://github.com/spesmilo/electrum/blob/71255c1e735cdfcd881e045b9f2f6bc6b599f459/electrum/submarine_swaps.py#L907
- for client-reverse-swaps, we have
- "cltv safety requirement: …

swaps: add explicit check that (onchain_locktime < LN_locktime)

---

electrum/storage.py

closes https://github.com/spesmilo/electrum/issues/8409
closes https://github.com/spesmilo/electrum/pull/8997

storage.write: make os_chmod best-effort

---

electrum/keystore.py
tests/test_wallet_vertical.py
tests/test_wizard.py

We did not have any tests for restoring from old electrum seeds in "hex format".

tests: restore from old "hex" seed

---

electrum/wallet.py
tests/test_wallet_vertical.py

fixes https://github.com/spesmilo/electrum/issues/10231

wallet: anchor reserve: handle wallet.use_change being off

---

.cirrus.yml
contrib/android/Dockerfile
contrib/android/build.sh
contrib/build-linux/appimage/Dockerfile
contrib/build-linux/appimage/build.sh
contrib/build-linux/appimage/make_type2_runtime.sh
contrib/build-linux/sdist/Dockerfile
contrib/build-linux/sdist/build.sh
contrib/build-wine/Dockerfile
contrib/build-wine/build.sh

follow-up https://github.com/spesmilo/electrum/pull/10019

ci: fix appimage build
