lib/wallet.py

I was having trouble creating or using a Trezor wallet, with this error:
```
File "/usr/local/src/electrum/gui/qt/main_window.py", line 309, in new_wallet
wallet = wizard.run('new')
File "/usr/local/src/electrum/gui/qt/installwizard.py", line 392, in run
wallet.create_main_account(password)
File "/usr/local/src/electrum/plugins/trezor.py", line 222, in create_main_account
self.create_account('Main account', None) #name, empty password
File "/usr/local/src/electrum/lib/wallet.py", line 1420, in create_account
account_id, xpub, addr = self.get_next_account(password)
File "/usr/local/src/electrum/lib/wallet.py", line 1403, in get_next_account
derivation = self.root_name + "%d'"%int(account_id)
AttributeError: 'TrezorWallet' object has no attribute …
```

Move root_name to parent class

---

gui/qt/paytoedit.py
lib/transaction.py

Seeing as 0.10 will loosen restrictions on non-standard transactions, this might be a good step towards allowing more Scripting functionality.
Todo list:
1. A method for redeeming outputs that are non-standard.
2. Perhaps the transaction dialogue should attempt to decode the hex into op codes and display them in the transaction summary?
This may be out of the focus for Electrum though... so "don't bother" also seems like a valid choice... (which is why I just left it at creating arbitrary outputs for now.)

Add arbitrary non-standard outputs

---

gui/qt/main_window.py

currently the csv output's line breaks are `\r\r\n` where the default line terminator for csv.writer is `\r\n`
and the extra `\r` is probably being inserted from writing a dict to
csv. I get around this by changing the line terminator to `\n` to output
`\r\n` which will make it compatible with most spreadsheet apps.

Fix the line terminator in csv

---

plugins/audio_modem.py

Loading the library is now done after creating the interface.
(tested with https://github.com/romanz/amodem/releases/tag/v1.7)

audio_modem: update plugin to work with latest version.

---

gui/qt/version_getter.py

http://electrum.org/version currently redirects to https://electrum.org/version, and the resulting 301 status code makes VersionGetter fail silently.
For backwards compatibility, http://electrum.org/version should serve version information directly.

Retrieve version information using HTTPS

---

gui/qt/main_window.py

blocktrail supports both BTC and tBTC, when there's no network present (which is the case for the old URL) it will redirect to the default (BTC) so the old URL will work just fine but not needing a redirect is always better ;-)

changed blocktrail baseurl to include network 'BTC' to avoid redirects

---

plugins/audio_modem.py

`send()` and `recv()` are now part of `amodem.main` module.
(tested with https://github.com/romanz/amodem/releases/tag/v1.8)

audio_modem: update plugin to work with latest amodem version.

---

plugins/trezor.py

Better version checks, used for mandatory firmware check and avoiding 'show on Trezor' feature for firmware below 1.3.0

better trezor version checks

---

plugins/trezor.py

Trezor HID transport must be closed upon releasing the wallet to prevent problem connecting with the device when opening another Trezor wallet

close Trezor USB transport on wallet close

---

.gitignore
electrum-env

Added env/ to .gitignore and added quotes around PYTHONPATH variable string to handle directories with spaces better. Also fixed script to properly pass command line arguments.

added env/ to gitignore and fixed an issue with electrum-env

---

plugins/exchange_rate.py

* Added BTCParalelo price index for Venezuelan Bolivar VEF
* Fixed all of the update_* functions on the exchange_rate.py plugin to indicate when there are SSL errors, there was a horrorous try-except-pass block that was drowning all the exceptions
* Added get_json_insecure to allow exchange rates over HTTP (I know this is horrendous, but for testing and development purposes and countries that don't have easy access to the amounts needed to issue a good SSL certificate)
Signed-off-by: John Miguel Villar Zavatti <johnvillarzavatti@gmail.com>

Fixed some issues with VEF exchanges and general drowning of exceptions

---

lib/wallet.py

I realize that console usage is 100% at-your-own-risk, but I think change_gap_limit() performs oddly enough if called with a string to warrant an assert. Specifically, calling it like so:
```python
wallet.change_gap_limit('100')
```
causes Electrum to try to create an infinite number of keys/addresses (presumably up until an out-of-memory), which continues even after a restart.

check arg type in change_gap_limit()

---

plugins/btchipwallet.py

PyUSB will be automatically used if present.

Remove useless enforced dependency of PyUSB

---

lib/bitcoin.py

Single commit version of https://github.com/spesmilo/electrum/pull/1087 . I wasn't able to reopen that pull request after I fixed the issue so creating a new one.
1. Allow wallet recovery from 64 character hex strings.
2. Allow wallet recovery from 24 word legacy seeds.
In Electrum 1.9.x, one could input 64 character hex strings and have using the method described in https://bitcointalk.org/index.php?topic=153990.0 . Specifically any procedure e.g the section titled "Custom seeds" at https://bitcoinspakistan.com/blog/electrum-seed-explained/ .
This results in a wallet that has an associated 24 word seed. This seed can be re entered into 1.9.x and the wallet successfully recovered. However in 2.x this no longer works and breaks compatibility with such wallets.
I propose this simple fix …

Let wallet recovery use 64 character hex strings and legacy 24 word seeds.

---

gui/qt/installwizard.py

I have added support for restoring BIP32 private keys (xprv) from the multisig 2of2 and 2of3 wallet restore screens. This enables an important use case where one wants to create a multisig wallet capable of signing transactions using xprv keys that they already have, which may have been generated using external programs. Further, it makes the multisig wallet restore screen consistent with the regular wallet restore, which already does accept xprv keys.

Support for restoring multisig wallets from BIP32 private keys

---

plugins/audio_modem.py
plugins/greenaddress_instant.py

Update `audio_modem` and `greenaddress_instant` plugins to use list.insert() instead of insertWidget API, after https://github.com/spesmilo/electrum/commit/66de59234345ccc4a272c2f3d40d414f074682b5 change.

plugins: fix buttons insertion

---

gui/qt/main_window.py
lib/wallet.py

Running `electrum -o` failed due to https://github.com/spesmilo/electrum/commit/e3de121be9a56c84ec80ce79a84f7ce1ae6b9b20 (missing `None` checks, when updating history).

Offline mode fixes

---

plugins/openalias.py

So in the original PR (https://github.com/spesmilo/electrum/pull/986) I said -
"One point for discussion is the timeouts I've set are quite "aggressive". Timeout for initial resolve of the address is 2 seconds, and timeout for the DNSSEC trust chain is 1 second per UDP request. I based that on my real-life example (South African ADSL + wifi, as well as 3G + wifi) and consistently had UDP pings returning from 8.8.8.8 in <600ms. That having been said, its entirely possible that this may be too aggressive as far as timeouts go, we'll have to see how the general Electrum populace responds."
Then I completely forgot to keep my eye on it:) Looks like they were too aggressive. Initial resolve timeouts stay at 2 seconds, but the resolve lifetime has changed to 4 seconds (so dnspython can retry or …

tweaked resolve and DNSSEC timeouts to be less aggressive

---

lib/account.py

Seems to have been missed during:
https://github.com/kaykurokawa/electrum/commit/a89abee9690b011031b20c39dc1d48a4b9ec1ceb
The function is not called by anything so should not have been causing issues.

get_pubkeys is called incorrectly in get_pubkey_from_xpub()

---

lib/bitcoin.py

Dust threshold should be 546, as is standard in Bitcoin Core  
https://github.com/bitcoin/bitcoin/blob/df5c246ba38c5b5bdd6192b0201d2fe8245451ca/src/primitives/transaction.h#L138

Dust threshold should be 546

---

lib/wallet.py

get_addr_received() allows the user to see the total amount of coins an address has ever received.
Use case: a merchant wants to view the total amount of coins a customer has ever sent to an address. If the merchant regularly sweeps coins from the address, the standard balance query using UTXO doesn't help.

Add wallet function get_addr_received()

---

setup.py

DragonFly and FreeBSD use same ports system and directory layout.  They should behave the same way throughout electrum, in particular in setup.py.

Setup same for FreeBSD and DragonFly

---

gui/qt/main_window.py
gui/qt/transaction_dialog.py

This should fix the following 2 exceptions:
- Unable to broadcast a signed transaction (loaded from file/text):
```
File "/home/roman/Code/Bitcoin/electrum/gui/qt/util.py", line 37, in run
self.result = self.run_task()
File "/home/roman/Code/Bitcoin/electrum/gui/qt/main_window.py", line 1150, in broadcast_thread
key = pr.get_id()
AttributeError: 'NoneType' object has no attribute 'get_id'
```
- "Broadcast" button should be hidden in offline mode (since there is no network connection to broadcast the transaction):
```
File "/home/roman/Code/Bitcoin/electrum/gui/qt/util.py", line 37, in run
self.result = self.run_task()
File "/home/roman/Code/Bitcoin/electrum/gui/qt/main_window.py", line 1151, in broadcast_thread
return …
```

Fix transaction broadcasting issues

---

gui/qt/history_widget_lite.py
lib/util.py

In particular, thousand separators ('.' or ',' or nothing) and decimal point separators are taken from the locale.
This also resolves issue 302: https://github.com/spesmilo/electrum/issues/302.

Modify format_satoshis to display amounts according to locale.

---

gui/qt/amountedit.py

Seems to suffice for expected usage.  Best I could figure out at least...

Expand default BTC / fiat amount widget width.

---

gui/qt/main_window.py

Electrum 2.x flashes a small window during startup before the main window appears.
This turns out to be the fee edit box being set to visible in create_send_tab().
Setting it to visible when the grid containing it is unparented causes QT to actually
display a window with just the edit box widget for some reason.  So defer the
call to set its visibility until the grid is parented.

Avoid ugly flash of small window during startup.

---

electrum

The goal is to be able to run local instances from arbitrary directories.
It seems that the chances of having a setup-release.py in the same directory
as an installed electrum are extremely remote: not only is the name unusual,
but the file isn't installed anyway.

Determine is_local not based on cwd but on existence of setup-release.py

---

gui/qt/__init__.py
gui/qt/main_window.py

The call to update_wallet() is redundant with earlier call to load_wallet().
Set the need_update boolean so the timer will refresh rather than
unconditionally refreshing.  This typically results in it merging with
the first network "updated" event resulting in one less refresh.
For me in online mode this results in history being calculated and shown
only twice during startup rather than four times.

Remove two redundant refreshes of history tab during startup.

---

gui/qt/main_window.py
lib/interface.py
scripts/servers

Remove some unneeded imports, a constant and a line of dead code.
Document the current external API interface.py provides.
On my system, mainline electrum frequently starts up in a permanently sychronizing state.  When run from the command line I can see that exceptions are happening with messages about broken sockets and bad file descriptors.   Electrum also frequently gets stuck whilst running, needing either a kick or a restart to have a sanely connected network again.  After looking at the code I believe these issues can be explained by racy and non-threadsafe logic in interface.py and its main client, network.py.  This sequence of pull requests will eliminate race conditions and clean up the logic to make it threadsafe.  The endpoint of these patches is working well on my system and …

First of several incremental patches tightening up interface.py.

---

lib/interface.py
lib/network.py
scripts/util.py

Removes an unnecessary Thread base-class override.  The python
documentation also strongly discourages overriding anything other
than run().

Pass the response_queue to the constructor, not start().

---

lib/interface.py

It is now unused; all necesary locking is done by the Queue objects.

Remove self.lock

---

gui/gtk.py
gui/qt/main_window.py
gui/qt/transaction_dialog.py
lib/transaction.py
lib/verifier.py
lib/wallet.py
scripts/merchant/merchant.py

This is the first step of 3 to get offline mode working.
The verifier will retain responsibility for verification, but will no longer hold the transaction sets itself.
Change requires_fee to take a wallet.
Add new function add_unverified_tx()
Move get_confirmations() to the wallet from the verifier.

Preparation for moving the set of verified and unverified txs to the wallet

---

gui/text.py

The current master branch version of the curses GUI exits on an exception when the user selects *Network* or *Settings* dialogs via `Ctrl+N` and `Ctrl+S`.
The reason is because the `self.network` object does not have the attribute `default_server` still being referred to by the **gui/text.py** code. Similarly, the code tries to access the `self.wallet.fee` attribute which, in the current master, is not assigned. `fee_per_kb` is the correct attr name.
I've updated these attrs in **gui/text.py** and tested. The curses GUI works as expected and the dialogs correctly display config settings.

gui/text.py curses GUI bug fixes

---

lib/commands.py

Found these issues while trying to create, sign, and broadcast a raw transaction. 
* createrawtransaction was using old signature for Transaction constructor
* Signwithwallet and decoderawtransaction need to call deserialize on tx before they can access inputs and outputs. (Maybe adding getInputs() and getOutputs() which deserializes if needed might be nicer)

Fix createrawtransaction and add missing deserialize() calls

---

lib/daemon.py
lib/network.py
lib/network_proxy.py

This is somewhat cleaner as the proxy's pipe and network setup
was awkwardly interleaved.  It also means network's constructor
is free to use both; currently some code is working around the
fact that the response queue doesn't exist in the constructor.

Have queues passed to the network constructor.

---

lib/network.py

Also means when switching to an already connected server our
status doesn't quickly change to connecting and back again.

Set 'connecting' status in one place.

---

lib/network.py

File "src/electrum/lib/network.py", line 411, in process_request
out['result'] = f(*params)
UnboundLocalError: local variable 'f' referenced before assignment
[Network] network error local variable 'f' referenced before assignment

Add documentation string.  Fix uninitialized f error.

---

lib/network.py

switch_to_random_interface used to do is_connected()
checks and remove interfaces when switching.  This
is redundant: interfaces are only added to self.interfaces
once in is_connected() state from process_if_notification().
When they are disconnected, a notification is also received
and process_if_notification() performs the removal.  Furthermore,
two other callers of switch_to_interface do not do explicit
is_connected() checks before calling it.

Remove interfaces in one place only

---

RELEASE-NOTES

The claim to show thousands separators has already confused
some people who didn't see it.

Tweak RELEASE-NOTES

---

lib/wallet.py

Whilst it's not a good idea to have two electrum instances
open on the same wallet, we should avoid throwing an
exception.  Also note how the old code's handling of the
exception (caused by both renaming the file almost at the
same time, rather than a non-POSIX system not supporting
the atomic rename) can lead to the wallet file being lost
enirely because os.remove(self.path) succeeds and the
rename of the temporary no-longer-existing file then fails.

Prevent race with two electrum instances on same wallet.

---

lib/network.py

Two places currently have switch-to-or-start-interface logic.
Put that common logic into switch_to_interface().

switch_to_interface() to start interface if not connected

---

gui/text.py
lib/network.py

Default to False consistently; this may change the behaviour of
network.py's get_parameters().

Put getting of auto_cycle into one place.

---

lib/simple_config.py
lib/tests/test_simple_config.py

SimpleConfig claims to handle configuration options in priority
command line, user config, system config, which makes sense.
In fact it appears it used priority command line, system config,
user config.
Also, from the priority ordering, it would seem correct that a
value should be unmodifiable if and only if it's set on the command
line.  Previously anything in the system config would be unmodifiable.
This patch fixes these and cleans the code up a bit.  I noticed this
whilst attempting to unify the 'auto_cycle' setting.
Fixup tests accordingly.

Fix SimpleConfig

---

electrum
gui/qt/installwizard.py
gui/qt/network_dialog.py
lib/network.py
lib/network_proxy.py
lib/simple_config.py
lib/tests/test_simple_config.py

User config is rewritten if appropriate.
Add tests behaviour is as expected.
Just the one rename-it reference to auto_cycle remains.

Rename auto_cycle to auto_connect in config

---

lib/simple_config.py
lib/tests/test_simple_config.py

This wasn't noticed because the test was also broken.

e20dfc unintentionally inverted portable condition

---

lib/network.py

Thomas - how about this?  It separates lagging and connected tests
which seemed to be your concern.  I'm not sure I prefer it because it
is more code and requires more care about where exactly lag can be
introduced.  Anyway I wanted your feedback.  Still testing locally.
A new function switch_stale_interface() switches servers, optionally
taking a suggestion to switch to, the previous strategy of
new_blockchain_height().  It checks the protocol of the suggestion
before switching.  The protocol might not match if the network has
just been restarted and the prior interfaces had queued a notification.
This is called from various places that check for staleness.  Socket
disconnection is exclusively checked by check_interfaces() in the
main loop.
A lagging server is checked where lag can be …

Common stale interface testing and switching

---

plugins/btchipwallet.py

Temporary fix for https://github.com/spesmilo/electrum/issues/1213
The plugin should still be adapted to threading like the trezor plugin. Once this is done the restriction can be dropped again.
But this change allows HW1 dongles with two accounts to be used with electrum, if only for the first account.

Restrict btchip to one account

---

gui/qt/main_window.py
gui/qt/paytoedit.py
lib/wallet.py

Fees should be recalculated when send_from changes.
Fees should be recalculated when editing fee preference, but
only save to storage when leaving the fee per kb widget.
No need to emit a textEdited signal; the widget does that already
(with the effect that we used to call update_fee() twice).

Fix calls to update_fee

---

gui/qt/main_window.py

Put fee_per_kb to zero rather than None when edit is blank
Changing the set of frozen addresses should update the fee

Two more fixes

---

lib/wallet.py

As discussed on #electrum yesterday.
Increase change gap limit to 6.
Choose the next unused change address, if any, otherwise pick
one at random from the gap limit.

Avoid change address reuse if possible

---

gui/gtk.py
gui/qt/main_window.py
lib/commands.py
lib/wallet.py

On my machine, with a wallet with around 500 addresses, freezing a screenful of
addresses pauses the GUI for about 5 seconds.  This brings it closer to 0.25s.
Also freezing was recently broken; this fixes it.
Speedup mainly from writing to storage only once.
Make frozen_addresses a set in memory, as sets give cleaner
code and are more efficient.
Minor change in behaviour: command line freezing used to return
False if the address isn't in the wallet OR the address was already
frozen.  Now it returns more like a success code: it returns False
only if the address isn't in the wallet regardless of frozen state.
Similarly for unfreezing.

Speed up freezing and unfreezing of many addresses

---

gui/qt/main_window.py
lib/commands.py
lib/wallet.py

Two callers of get_spendable_coins were removing frozen addrs
before calling.  Put that functionality in the function.
We shouldn't be able to send_from a frozen address.  This was
possible in the current release because logic assumed a two-element
tuple was returned when it is now three-element.  Fix that too.
Command line options listunspent and createrawtransaction currently
ignore frozen addresses.  I've preserved that behaviour.
With this patch only the wallet class refers to self.frozen_addresses;
other clients use is_frozen() now.

get_spendable_coins and frozen addrs

---

lib/network.py

interfaces we have created.
Existing code has the concept of pending servers, where a connection
thread is started but has not sent a connection notification, and
and interfaces which have received the notification.
This separation caused a couple of minor bugs, and given the cleaner
semantics of unifying the two I don't think the separation is beneficial.
The bugs:
1) When stopping the network, we only stopped the connected interface
threads, not the pending ones.  This would leave Python hanging
on exit if we don't make them daemon threads.
2) start_interface() did not check pending servers before starting
a new thread.  Some of its callers did, but not all, so it was
possible to initiate two threads to one server and "lose" one thread.
Apart form fixing the above two issues, …

Remove pending_servers, self.interfaces is now the complete set of

---

lib/interface.py
lib/network.py

This allows us to distinguish between connecting and connected
state in interface.py (used to be done in network.py but that
had other issues).
This means we don't switch to a connecting server, and get_interfaces()
does not report connecting ones.

Make interface status tri-state.

---

lib/interface.py

Set timeout and socket options on all simple sockets.  At present
some code paths can miss it, such as when the SSL certificate is
CA-signed.
Add a missing check for failure.

Fix couple of minor socket issues

---

lib/network.py

Occasionally triggered with a race at start up, typically from
the verifier requesting a merkle root.

Need an interface to process a request.

---

lib/interface.py
lib/util.py

This is a layering violation - the SocketPipe doesn't own
the socket and provides no other way to close the socket, leading
to unnecessary complexity like that in interface.py.
I looked at deamon.py and NetworkProxy - the two other users,
and they don't close the sockets explicitly, just let them be
garbage collected.

SocketPipe shouldn't close the socket.

---

.travis.yml

This should fix Travis build errors:
- protobuf module was missing.
- `import electrum` failed at `plugins` package (so it is excluded, as `gui` package).

travis.yml: add protobuf to requirements and exclude plugins

---

lib/bitcoin.py

Running `pylint --errors-only lib.bitcoin` found that `i2d_ECPrivateKey()` uses undefined constants (`_p, _Gx, _Gy, _r`). 
It seems safe to remove it (and its calling function, `GetPrivKey`), since nobody else is using it.

bitcoin: remove dead code

---

lib/blockchain.py
lib/network.py

Remove interface communication out of blockchain.py
into network.py.  network.py handles protocol requests
for headers and chunks.  blockchain.py continues to
handle their analysis and verification.
If an interface provides a header chain that doesn't
connect, it is dismissed, as per a previous TODO comment.
This removes a thread and another source of timeouts.
I see no performance issues with this when truncating the
blockchain.
Rename 'result' to 'header' for clarity.

Make the blockchain class not a thread

---

gui/qt/main_window.py
gui/qt/transaction_dialog.py

This is working towards showing transactions before asking for passwords.
I think it also means the transaction dialog now interacts properly with
plugins, whereas it didn't before.
send_tx now takes a callback instead of a label, and does not decide
on whether to broadast itself; that is left to its caller.
broadcast_transaction() takes care of adding the description of the
successfully broadcast transaction to the wallet.  Previously labels
could be added to the wallet even if the broadcast was cancelled by
the user or unsuccessful, which doesn't seem right.
Lengthen the dialog messages a little, as some window managers lose the
"Please Wait" title bar owing to window decorations if the message
is too short.

Have transaction_dialog use send_tx()

---

gui/qt/transaction_dialog.py

Resolves a long-standing bug with view-before-broadcast

Save the description to the wallet on broadcasting

---

gui/qt/transaction_dialog.py

Show change in yellow, receiving in lightgreen (as now).
Numbers are more readable with whitespace.

Distinguish receiving and change addrs in TxDialog

---

gui/qt/installwizard.py

Add scroll area for multisig wallets.  Without a scroll area, the seed text areas are too small with high N wallets.

Add seed scroll

---

gui/qt/transaction_dialog.py
plugins/audio_modem.py

This way, the Audio MODEM plugin button can be near the QR button.

transaction_dialog: allow plugins manipulate transaction sharing buttons

---

lib/commands.py
lib/interface.py

Running `python lib/interface.py` failed with:
AttributeError: 'X509' object has no attribute 'slow_parse'
After removing the lines, it runs successfully.

fix small typos at lib/interface.py and lib/commands.py

---

lib/network_proxy.py
lib/synchronizer.py
lib/wallet.py

The synchronizer's work is done from the network proxy's main loop.
A minor problem with the old synchronizer was that it considered itself
out of date if the network was out of date.  This was too generic: the
network can have pending requests unrelated to the synchronizer.  This
resulted in the synchronizer often unnecessarily flipping the wallet
between up-to-date and not-up-to-date, and causing unnecessary calls
to wallet.save_transactions().  This was observable when opening the
network dialog box: frequently just opening it would cause a wallet
status change and transaction flush, simply because the network dialog
sends a get_parameters() request.  This rework of the synchronizer does
not have that issue.

Make the synchronizer not a thread.

---

.travis.yml

Also, use `pip install .` for installing dependencies via `setup.py`.

travis: add code coverage report

---

.gitignore
.travis.yml
tox.ini

This way, any user can run the UT suite simply by using the `tox` command.
Travis will also use `tox`, so the test definition is not repeated.

travis: use Tox for test automation

---

gui/qt/amountedit.py
gui/qt/main_window.py
plugins/exchange_rate.py

It has long been a minor annoyance that this isn't the
default behaviour.  Semantics are as follows:
- Fees are calculated automatically, as usual, and shown
in black
- If the user inputs a fee, it is retained, and shown in
blue to indicate it is user-overridden
- The user can switch back to automatic fee calculation mode
in two ways: press Clear, or blank out the fee field
- User fees are also cleared by do_clear(), for instance when
the payment is sent
I have checked all usage combinations I could think of, including
the ! case, and all work in a sensible and natural fashion.
This also fixes issue #995.

Once a user inputs a fee, retain it.

---

electrum

Fix issue #1349 regarding use of --wallet with --portable on command line.

Remove --portable flag dependency on not setting wallet path via command line

---

lib/interface.py

I've tested this small change with my wildcard cert as I needed it for internal use on an electrum server.
A good example of what SubjectAltName looks like for wildcards can be seen in the wikipedia.org certificate. 
I try to make sure it can't be abused by matching sum of wildcard part and base name to full name string.

Wildcard SSL Support

---

lib/interface.py
lib/tests/test_interface.py

The existing pattern matching code:
```
val.find('*.') == 0 and name.find(val[1:]) + len(val[1:]) == len(name)
```
will return True in the following case:
```
val = '*.host.com'
name = 'blah.org'
```
since `string.find()` will return -1, `len(val[1:]) == 9` and `len(name) == 8`.

interface: fix check_host_name() pattern matching

---

lib/interface.py

After update of openssl a user reported:
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
File "/usr/local/lib/python2.7/dist-packages/electrum/interface.py", line 382, in start_tc
Debian (and possibly other distors) lately compile OpenSSL without SSLv3 support because of security considerations. Also v2 and v3 are both deprecated for SSL / TLS
Source: http://stackoverflow.com/questions/28987891/patch-pyopenssl-for-sslv3-issue
Looking at https://docs.python.org/2/library/ssl.html  - especially at the table there it would make sense to change the client code to TLSv1. On the server side SSLv23 is still good for both forward and backward compatibility.
I've tested the pull request with TLSv1 successfully on Win 7

Use ssl.PROTOCOL_TLSv1 on client side to avoid SSLv23

---

gui/qt/lite_window.py
plugins/trustedcoin.py

```
File "/media/oldhome/roman/Code/Bitcoin/electrum/plugins/trustedcoin.py", line 593, in <lambda>
b.clicked.connect(lambda b, k=k, v=v: self.on_buy(k, v, d))
File "/media/oldhome/roman/Code/Bitcoin/electrum/plugins/trustedcoin.py", line 619, in on_buy
self.window.pay_from_URI(uri)
AttributeError: 'ElectrumWindow' object has no attribute 'pay_from_URI'
```

typo fix: rename pay_from_URI() -> pay_to_URI()

---

plugins/keepkey.py

Because KeepKey doesn't have a cancel button (unlike Trezor), this needs to be done client side.  I added a "Cancel" button to the transaction dialog that prompts you to confirm requests on KeepKey.  I also made sure that when the window is canceled out or closed, the action on KeepKey is cancelled.
I had to update our python client to get this feature to work, so make sure you have the latest.

Added a "Cancel" button to transaction dialog

---

lib/tests/test_transaction.py

Fix small TypeError at:
```
@classmethod
def sweep(klass, privkeys, network, to_address, fee):
inputs = []
keypairs = {}
for privkey in privkeys:
pubkey = public_key_from_private_key(privkey)
address = address_from_private_key(privkey)
u = network.synchronous_get(('blockchain.address.listunspent',[address]))
pay_script = klass.pay_script('address', address)
for item in u:
>               item['scriptPubKey'] = pay_script
E               TypeError: list indices must be integers, not str
lib/transaction.py:540: TypeError
```

test_transaction: fix test_sweep case

---

lib/transaction.py

I have used the following command to check that no one uses the removed code:
```
git grep -E "map_file|seek_file|close_file|mmap"
```

transaction: remove unused mmap-related code

---

plugins/keepkey.py
plugins/trezor.py

Having either Trezor or KeepKey attempt to sign a partially signed transaction was breaking because both plugins were trying to parse an invalid xpub. When I fixed KeepKey's plugin, I tested it with Trezor and it started working too.  So I made the change on Trezor's plugin too.

made sure to check if x_pubkey is valid xpub before parsing it

---

gui/qt/main_window.py

```
File "/home/roman/Code/Bitcoin/electrum/gui/qt/main_window.py", line 2262, in do_process_from_text
tx = self.tx_from_text()
TypeError: tx_from_text() takes exactly 2 arguments (1 given)
```

main_window: fix typo at do_process_from_text()

---

gui/qt/main_window.py

I've seen a few people on IRC confused about when their electrum addresses expire.  I think it is a common enough misunderstanding to try to make the UI more clear.
12:41 < MarginOak> Question, with the electrum wallet even if one of the addressess expires do you get to keep your btc?
12:41 < MarginOak> or does it stay on the address?
12:41 < MarginOak> and you lose it/
12:41 < MarginOak> ?
12:45 < fireduck> MarginOak: addresses don't expire
12:46 < fireduck> Electrum generates new ones as you use them, but you keep all the old ones.  They never expire.
12:46 < MarginOak> Oh
12:46 < MarginOak> Thanks
12:46 < MarginOak> So if they have btc on them they don't expire?
12:46 < MarginOak> otherwise they do?
12:46 < fireduck> Nope, they never expire.
12:46 < MarginOak> That's funny
12:46 < …

Make verbage from requests a little more clear

---

lib/websockets.py

Also put the error message in sys.exit rather than printing. This will output it to stderr and make the exit code non-zero like it should be.

Missing sys import

---

plugins/ledger/qt.py

Added a missing import to be able to use the HW1. 
The following problem is not fixed with this:
File "/home/richi/sourcecode/electrum/lib/plugins.py", line 148, in _run_hook
r = f(*args)
File "/home/richi/sourcecode/electrum/plugins/ledger/qt.py", line 23, in load_wallet
QMessageBox.information(window, _('Error'), _("Ledger device not detected.\nContinuing in watching-only mode."), _('OK'))
NameError: global name '_' is not defined

added missing import

---

gui/qt/main_window.py

Show a message instead of a warning.

Use info message box for Pay-To-Many instructions

---

plugins/exchange_rate/exchange_rate.py

This adds Kraken exchange rates to the `exchange_rate` plugin for the following currencies: EUR, USD, CAD, GBP, JPY.

Add Kraken exchange to exchange_rate plugin

---

plugins/ledger/ledger.py

added local client variable

---

electrum
gui/kivy/nfc_scanner/scanner_android.py

https://github.com/spesmilo/electrum/blob/6ba43637f58b312e27df514fdf3ec54d430504e0/electrum#L57
has tab instead of spaces.
https://github.com/spesmilo/electrum/blob/6ba43637f58b312e27df514fdf3ec54d430504e0/gui/kivy/nfc_scanner/scanner_android.py#L118
has lone `self.`

Minor fixes - indentation and lone `self.`

---

plugins/exchange_rate/exchange_rate.py

Added two of the biggest brazilian exchangers, "Bitcontoyou" and "MercadoBitcoin", to Exchange rates plugin.

Added new exchangers to Exchange rates plugin

---

setup.py

Hello,
the new hw_wallet plugin needs to be added to setup.py installer.

Installer fix missing hw_wallet plugin

---

gui/qt/history_widget.py

Set colour of label for outgoing transactions to match the colour of the
value field (red) - closes #1393

Label colour - History Window

---

plugins/exchange_rate/exchange_rate.py

CaVirtex was recently acquired by kraken
Edit: Not sure why the travis build failed, hoping it has nothing to do with my pull req

remove cavirtex from exchange_rate.py

---

gui/stdio.py

I tried using the stdio interface to send a transaction, and it failed because the object didn't have a network attached. This should fix that.

Store the daemon's network on the stdio GUI object

---

README.rst

This commit fixes two issues in `readme.rst`:
1. Fix misspelled word - `oder` (should be `order`)
2. Fix grammatical error - `creating` (should be `create`)

readme: Fix typo and grammatical error

---

lib/tests/test_simple_config.py
lib/tests/test_transaction.py

The tests test_simple_config.py and test_transaction.py complete with errors. This PR fixes them.

fix test_simple_config and test_transaction

---

lib/wallet.py

Currently Electrum daemon runs websocket server on a configured host and
port and sends the same information to merchant payments. There is
likely that those two may be different, when websocket traffic is being
reverse proxied and sent over via different hosts.
This patch introduces two fully optional parameters,
websocket_server_announce and websocket_port_announce, which when
set, are sent to the merchant payments instead of websocket_server and
websocket_port values.

Introducing websocket_announce configuration

---

lib/wallet.py
lib/websockets.py
lib/www/index.html

Currently Electrum stores all payment requests in main requests
directory. It's not going to be efficient when we have thousands of
thousands of payment requests. This patch spreads that files across
two level of subdirectories.

Spread payment requests to subdirs

---

lib/tests/test_bitcoin.py

Fixes first failure:
lib/tests/test_bitcoin.py::Test_bitcoin::test_crypto

Fixing test_bitcoin.py::Test_bitcoin::test_crypto

---

lib/tests/test_mnemonic.py

Fixes both broken tests in test_mnemonic.py
Notes:
* prepare_seed method was removed long ago.
* custom_entropy was removed 2 weeks ago.

Fixing 2 tests in test_mnemonic.py

---

lib/tests/test_wallet.py

It seems that wallet storage now returns keys & values as **unicode**.
It also **appends** `"seed_version": 12` to the dict it creates.
Please confirm this is correct so we aren't ignoring a real error.

Fixing final test in test_wallet.py

---

gui/qt/transaction_dialog.py
lib/transaction.py

As per my issue 2051 feature request.
Add fee rate info as base_unit/kB and sat/byte in brackets after fee in details. 
Allow users to see rate used without having to manually calculate.
Tested with new tx and also in history list popup. Only shows when fee is available.

Add fee rate to transaction details dialog.

---

plugins/trezor/clientbase.py
plugins/trezor/plugin.py

Problem: Plugin doesn't work with Trezor when the firmware version is exactly the required version. 
This change fixes it work with the minimum version (it actually fixes the method 'atleast_version' to return 1 or 0 instead of -1,0 or 1) and also shows an error message in the debug log on outdated firmware.

Trezor firmware version check bugfix and log on error

---

gui/qt/seed_dialog.py

Right now checkboxes are always unchecked right after opening "Options" in seed dialog. That's confusing, as user might think that setting them doesn't work if he opens "Options" again after changing something.
This PR preserves state of checkboxes when opening/closing "Options".

Preserve checkboxes state in seed_options

---

lib/wallet.py

If you use wallet.change_gap_limit with a value below the current gap
limit, you get this exception:
```
>> wallet.change_gap_limit(1)
File "lib\wallet.py", line 1455, in change_gap_limit
elif value >= self.min_acceptable_gap():
File "lib\wallet.py", line 1479, in min_acceptable_gap
addresses = self.account.get_receiving_addresses()
AttributeError: 'Standard_Wallet' object has no attribute 'account'
>> 
```

fix AttributeError: 'Standard_Wallet' object has no attribute 'account'

---

plugins/labels/labels.py

Also removes import of aes, seems like that was forgotten in e1515743cd. It isn't used anyway.
Closes #2144

Use new LabelSync server for the plugin

---

lib/network.py

This prevents "bad" servers from sending a list of unusable servers to leave the client without a connection.

Always include default servers in the server list

---

gui/qt/__init__.py
gui/qt/network_dialog.py
lib/network.py
lib/paymentrequest.py

- `socket` doesn't have `_socketobject` any more, so we have to create that

[Python3] Make proxies work

---

.travis.yml
tox.ini

`tox-travis` makes tox only use Travis-configured Python versions when run on Travis.

[Python3] Let travis run the tests using Python3

---

electrum
lib/bitcoin.py
lib/blockchain.py
lib/commands.py
lib/network.py
lib/simple_config.py

Also update testnet servers
Add missing self. in print_error call

Add support for BU's nolnet

---

lib/commands.py

The implementation of the getunusedaddress will directly query
the wallet for the first unused address
Although it might be possible to first list all addresses, then check the balance for each of these addresses to determine the first address that has not been used, this is quite cumbersome and probably relatively slow. This convenience function resolves that.
Note that it will return false if not forced and the first unused address is beyond the gap (i.e. due to multiple existing addrequests).

Implemented getunusedaddress command

---

plugins/digitalbitbox/digitalbitbox.py

Looks like a later commit changed something and caused a bug in the Digital Bitbox plugin. This PR fixes it.
I would classify the problem as urgent as users will not be able to send coins with a Digital Bitbox when using the apps available for download on the website.
For information, the error message is `KeyError: 'pubkeys'`.
Cheers.

Digital Bitbox cannot send coins bug (due to a later upstream change)

---

lib/commands.py

The function call to `satoshis` was written as nonexistent `to_satoshis` instead, preventing paytomany command from working.

Fix 'paytomany' command

---

lib/base_wizard.py
lib/keystore.py
plugins/trezor/plugin.py

This improves Testnet support and fixes TREZOR testnet support
* Use `m/44'/1'` for Testnet
* Don't use hardcoded `addrtype` for TREZOR
* Don't use hardcoded `coin_name` for TREZOR
Ledger and Digital Bitbox have hardcoded occurences of `m/44'/0'`. I have **NOT** changed these but I strongly suggest they do.
Thanks @fivepiece for informing me of this issue
/cc @prusnak @btchip @douglasbakkum

TREZOR Testnet support

---

plugins/digitalbitbox/digitalbitbox.py

These lines https://github.com/spesmilo/electrum/blob/master/plugins/hw_wallet/qt.py#L114-L115 got broken by commit https://github.com/spesmilo/electrum/commit/fcc92c1ebdee77a4a414384f23f85d37152fbe7b
The `# If confirm is true, require the user to enter the passphrase twice` functionality was removed from https://github.com/spesmilo/electrum/blob/master/gui/qt/password_dialog.py#L194. It could be reimplemented in different ways (or dropped?), so I didn't make a PR to fix it specifically. 
The lost functionality breaks the set up process for a freshly erased Digital Bitbox https://github.com/spesmilo/electrum/blob/master/plugins/digitalbitbox/digitalbitbox.py#L108 and possibly also for a fresh Trezor https://github.com/spesmilo/electrum/blob/master/plugins/trezor/clientbase.py#L65, where …

Enter password once for initial setup of an erased device

---

lib/dnssec.py

* This adds the new KSK-2017 as a trusted anchor.
* As long as KSK-2017 is not published, the check in line 227 will fail for the first key but succeed for the second.
* When KSK-2017 is published (probably in October), it won't check for KSK-2010 any more.
Closes: #2300

Add KSK-2017 to dnssec trust anchors and accept either of the two

---

electrum.desktop

Adds the “Finance” category, which is specified as an additional category in the Desktop
Menu Specification. Also makes the GenericName a more generic as per the Desktop
Entry Specification.

Move Electrum to the Finance category

---

plugins/ledger/ledger.py

To celebrate Litecoin happy hashrate, this PR starts filling the gaps to support Segwit transactions, for initial testing.
It activates when Electrum is launched with --segwit - the final version will be able to query an additional seed version on the HW application.

Segwit and RBF support for Ledger HW

---

lib/util.py

This fixes this error:
raceback (most recent call last):
File "/usr/bin/electrum", line 98, in <module>
from electrum import bitcoin, network
File "/usr/lib/python3.6/site-packages/electrum/__init__.py", line 2, in <module>
from util import format_satoshis, print_msg, print_error, set_verbosity
File "/usr/lib/python3.6/site-packages/electrum/util.py", line 537
except socket.error, err:
Also, other exceptions in this file use the except X as Y syntax.

Fixed a syntax error with python 3.6

---

lib/commands.py

This fixes a minor typo in the help output for `--force`

fix a minor typo (beyong -> beyond)

---

.travis.yml
contrib/make_locale

This uploads updated translation strings to crowdin on every push to master.
You need to [add the API key] as a [Travis environment variable] in order for this to work.
As long as you don't merge something that prints the API key, it should be safe:
> Similarly, we do not provide these values to untrusted builds, triggered by pull requests from another repository.
[Travis environment variable]: https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings
[add the API key]: https://travis-ci.org/spesmilo/electrum/settings
Closes: #2377

Let Travis upload templates to crowdin

---

gui/qt/address_dialog.py

Before:
With this change:
Closes: #2464

Resize content of address history window

---

snap/snapcraft.yaml

This package will let you publish the latest electrum in the Ubuntu store, and from there reach many users on all the supported Ubuntu versions, and more Linux distributions in progress.

Add the packaging metadata to build the electrum snap

---

lib/plugins.py
plugins/digitalbitbox/digitalbitbox.py

This PR addresses a couple things:
- We recently published a couple firmware updates (U2F and ETH/ETC support) that required modifying the USB communication protocol to make use of the ISO 7816-4 standard. This PR allows the latest firmware to work with Electrum and is backward compatible with older firmware.
- Bugfix for signing transactions - the added `'01'` in `txin['signatures'][ii] = sig.encode('hex') + '01'`.
- Commit `91deea8` is outside of the `digitalbitbox` plugin, but it should not cause different behavior for the other plugins. This commit is required in order to make a unique ID that can distinguish different functional 'interfaces' on USB HID 'composite' devices. Composite devices have the same serial number for each interface, and some versions of the HIDAPI library do not …

Digital Bitbox update for latest firmware (v2.2.2)

---

gui/qt/main_window.py

New plugin hook `init_menubar_tools` that allows plugins to add submenu item in Tools menu.

Add plugin hook `init_menubar_tools`

---

gui/qt/main_window.py
lib/exchange_rate.py

Status bar showed price of 1 BTC regardless of which base unit (mBTC, etc) was chosen. This PR makes it show the price of the base unit.
Let me know if any style things need to be changed before merging.

Made status bar exchange rate display in terms of base unit

---

gui/qt/main_window.py

The current approach adds all tabs at the same position so the order changes depending on which tabs you enable first.
This fixes the order.

Retain tab order after toggling

---

plugins/ledger/cmdline.py

Ledger plugin cmdline module has spelling mistake in import.

fix spelling module name

---

gui/qt/installwizard.py

Since this seems to be the first page of the wizard, there is nothing to go back to. Furthermore, clicking "Back" actually takes you to the next step.
This changes the button to "Close" and closes the wizard.

Fix "Back" button in installwizard

---

gui/kivy/main_window.py
gui/kivy/uix/dialogs/installwizard.py
gui/qt/installwizard.py
gui/qt/main_window.py
gui/qt/util.py
lib/base_wizard.py
lib/commands.py

Instead of using the deprecated function `apply(f, args, kwargs)` we use the modern Python 3-compatible unpack syntax `f(*args, **kwargs)`, easing the porting effort.

Remove usages of deprecated apply() builtin

---

lib/contacts.py

Add contact validation during import and also support extracting contacts from another wallet (or any json data file with contacts).
This allows importing from either an old contacts file or another wallet file. 
Removes any items that are not contact data before updating storage. 
See issue #2649

Validate and extract contacts on import

---

lib/commands.py

With unencrypted wallet, when trying to use the console to getprivatekeys, exception is raised:
```
>> getprivatekeys("12*************************AC")
File "/home/skelet/Builds/electrum/gui/qt/main_window.py", line 1711, in <lambda>
return lambda *args: f(method, args, self.password_dialog)
File "/home/skelet/Builds/electrum/lib/commands.py", line 105, in _run
result = f(*args, **{'password':password})
UnboundLocalError: local variable 'password' referenced before assignment
```
The fix seems trivial. The case with unencrypted wallet does not seem to be handled completely. With the fix, getprivatekeys is working as expected.

Fix commands that require password with unencrypted wallet

---

plugins/trezor/plugin.py

TREZOR firmware expects signatures not to contain the trailing sighash
byte.  This fixes issue fyookball/electrum#47 which also applies to
electrum.

TREZOR: Remove sighash from input signatures

---

gui/qt/history_list.py

Fix to text alignment + small usability improvements:
+ fix: vertically align monospace columns
+ add: icon tooltip for quick check of confirmation count
+ add: double click row to access transaction details
The monospaced columns were not vertically aligned. Also added tooltip on the status icon, and quick access to details by double-clicking row (previously double clicking did nothing, except on edit column).

History list - GUI fix + small improvements

---

lib/simple_config.py

This makes sure the values are different before changing the config on disk.
---
Closes: #2719

Only save config if value changed

---

gui/qt/main_window.py

Fix minor typo in exporting labels

---

plugins/trezor/plugin.py

This fixes bug #2738 
Multisig is still not working perfectly with TREZOR.  Since the xpubkey information is destroyed when a signature is filled, the second signer will not accept the change address.  This is because TREZOR checks that the return address uses the same xpubs as all inputs.  However this is a different issue.

Set bip32 path for multisig change address

---

gui/qt/__init__.py

Issue: #2209
Fixes this error when signing with a HW wallet:
``` 
$ ./electrum
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python3: xcb_io.c:259: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Aborted (core dumped)
```
The cause is likely with the `show_message()` calls. The proper fix
would be to hunt down where QT Gui elements are touched from a wrong
thread.
The workaround is to call XInitThreads(), as the error message suggests.

fix Qt threading issue

---

lib/base_wizard.py
lib/keystore.py
lib/transaction.py
plugins/trezor/plugin.py

This adds segwit support for TREZOR in Electrum.  So far I only tested standard wallet.  
Following changes were necessary outside the TREZOR plugin.
- transaction.py: update_transaction handles segwit transactions.
- keystore.py: added a segwit parameter to bip44_derivation,
use m/49' instead of m/44' for segwit.

[TREZOR] Added Segwit support.

---

README.rst

Had problems getting Electrum to work after python3 migration.
Following commands in old README, notably ran into:
```
user@debian:~/wspace/electrum$ ./electrum 
Error: Could not import PyQt4 on Linux systems, you may try 'sudo apt-get install python3-pyqt4'
user@debian:~/wspace/electrum$ ./electrum 
qRegisterResourceData(int, str, str, str): argument 2 has unexpected type 'str'
Error: Could not find icons file.
Please run 'pyrcc4 icons.qrc -o gui/qt/icons_rc.py -py3', and reinstall Electrum
```

python 3 changes in README

---

gui/qt/address_list.py
gui/qt/main_window.py
lib/exchange_rate.py

This PR adds an optional Fiat balance column to the address view, which can be toggled in the Fiat preferences.
I also changed the alignment of the balance columns in the address view to the right, to match the history tab.

Add optional Fiat balance column to addresses view

---

lib/network.py

[Network] downloading  https://headers.electrum.org/blockchain_headers
[Network] download failed. creating file /home/wakiyamap/.electrum/blockchain_headers
I fix it.

Fix download failed blockchain headers

---

lib/transaction.py

Wasn't sure if it was better to keep the change minimal or to be consistent.
i.e. input_script() method has
```
_type = txin['type']
```
so feel free to do that instead

fix unresolved variable

---

lib/bitcoin.py
lib/network.py
lib/servers_testnet.json

This is a minimal but dirty fix. (as a follow-up of 8c5b6bdaf3077d5855b69c71830296917d132931)
Due to how imports work in Python, if `bitcoin.TESTNET == True`, in `network.py`,
```
bitcoin.DEFAULT_SERVERS != DEFAULT_SERVERS
bitcoin.DEFAULT_PORTS != DEFAULT_PORTS
```
Hence, the way Testnet functionality is implemented could use some restructuring.

fix testnet

---

lib/bitcoin.py
lib/transaction.py

While #2859 fixed the crash, it seems it wasn't logically correct.
Pay-to-pubkey outputs were incorrectly serialised, which e.g. resulted in incorrect TXIDs.

fix: p2pk output serialisation

---

gui/qt/installwizard.py

In the install wizard message, the prompt uses the word "fulfil". While this is an acceptable spelling of the word, Google ngrams indicates that it is twice as common to spell the word with two l's at the end, aka "fulfill", in modern writing. This PR proposes to use the more common spelling.
https://books.google.com/ngrams/graph?content=fulfill%2C+fulfil&year_start=1800&year_end=2000&corpus=15&smoothing=3&share=&direct_url=t1%3B%2Cfulfill%3B%2Cc0%3B.t1%3B%2Cfulfil%3B%2Cc0

Edit install wizard msg to reflect linguistic trends

---

lib/transaction.py

The lengths in the witness structure are `var_int` not pushes.
From BIP-141:
The `witness` is a serialization of all witness data of the transaction.
Each txin is associated with a witness field. A witness field starts
with a `var_int` to indicate the number of stack items for the txin. It is
followed by stack items, with each item starts with a `var_int` to
indicate the length. Witness data is NOT script.
This bug was triggered by tx
d379210d85c1346dafbfd60e3cbc5c5573e50b1f9576d39f177afb2b378f1b98

Fix parsing of witnesses

---

gui/qt/paytoedit.py

The existing code was failing with the following exception, each time I tried to use auto-complete at the "Pay to" text box:
```
File "/media/roman/data/roman/Code/Bitcoin/electrum/gui/qt/paytoedit.py", line 212, in insertCompletion
extra = completion.length() - self.c.completionPrefix().length()
AttributeError: 'str' object has no attribute 'length'
```

paytoedit: fix insertCompletion() string handling

---

lib/tests/test_mnemonic.py
lib/tests/test_transaction.py

`assertEquals` is deprecated in favor of `assertEqual`
https://bugs.python.org/issue9424
This change removes warnings such as
```
/home/user/wspace/electrum/lib/tests/test_mnemonic.py:28: DeprecationWarning: Please use assertEqual instead.
self.assertEquals(m.mnemonic_encode(i), seed)
```

replace deprecated assertEquals

---

lib/network.py

See #2899 
I send `server.version` after `blockchain.relayfee` to replicate the order of messages on a new connection.

send server.version before subscriptions

---

lib/exchange_rate.py

In Python3, `dict.iteritems()` has been removed. See https://wiki.python.org/moin/Python3.0

python3: exchange_rate.py

---

lib/currencies.json

#2881 was incomplete.
```
[FxThread] using exchange BTCe
[profiler] on_update 0.0072
[BitcoinAverage] getting fx quotes for EUR
[BitcoinAverage] received fx quotes
File "/home/user/wspace/electrum/gui/qt/main_window.py", line 2674, in on_history
update_exchanges()
File "/home/user/wspace/electrum/gui/qt/main_window.py", line 2648, in update_exchanges
exchanges = self.fx.get_exchanges_by_ccy(c, h)
File "/home/user/wspace/electrum/lib/exchange_rate.py", line 392, in get_exchanges_by_ccy
d = get_exchanges_by_ccy(h)
File "/home/user/wspace/electrum/lib/exchange_rate.py", line 370, in get_exchanges_by_ccy
klass = globals()[name]
KeyError: 'BTCe'
```

finish BTCe to WEX renaming

---

lib/daemon.py

When I start Electrum, a typical log looks like:
```
user@debian:~/wspace/electrum$ ./electrum -v
[SimpleConfig] electrum directory /home/user/.electrum
[Errno 111] Connection refused
[Plugins] registering hardware digitalbitbox: ('hardware', 'digitalbitbox', 'Digital Bitbox wallet')
[Plugins] registering hardware keepkey: ('hardware', 'keepkey', 'KeepKey wallet')
[Plugins] registering hardware ledger: ('hardware', 'ledger', 'Ledger wallet')
[Plugins] registering hardware trezor: ('hardware', 'trezor', 'TREZOR wallet')
[Plugins] registering wallet type ('2fa', 'trustedcoin')
[profiler] __init__ 0.0034
[Network] blockchains dict_keys([0])
[Network] starting network
```
The `[Errno 111] Connection refused` line is quite mysterious; this change identifies its source a bit better.

log: identify exception source in log for daemon/get_server

---

contrib/build-wine/build-electrum-git.sh
contrib/build-wine/prepare-wine.sh

- PyQt5 needs `sip`, which is not available for Python 3.4
- Python3.5 doesn't provide a single msi installer
- I changed `pywin32` to install from pypi so there are less buttons to click
- While I was at it, I updated NSIS too

Update Windows build to Python 3.5 and PyQt5

---

gui/qt/main_window.py

In the QT GUI, going into `Tools/Plugins` crashed the app for me with
```
File "site-packages\electrum-3.0-py3.5.egg\electrum_gui\qt\main_window.py", line 2830, in plugins_dialog
UnboundLocalError: local variable 'i' referenced before assignment
```
The trace is when running the windows binary for https://github.com/spesmilo/electrum/pull/2911/commits/ffdafc57b735abf76f53e3f28d665aeffb29501b from @bauerj given in https://github.com/spesmilo/electrum/pull/2916#issuecomment-331650946
The crash does not happen on master (worth looking into?), but the change I think is still warranted.

fix qt plugins crash

---

lib/tests/test_wallet_vertical.py

Tests, creating different types of wallets with corresponding keystores, and checking first addresses.
Fails on current master (088b1e6f79c33b489885638a59771a44c0608e84) due to #2932 and #2938. Works with #2936 applied.

tests: wallet-keystore integrity (seed->address)

---

gui/qt/network_dialog.py

I was playing around in the network dialog and the client crashed with
```
File "/home/user/wspace/electrum/gui/qt/network_dialog.py", line 394, in change_protocol
p = pp.keys()[0]
TypeError: 'dict_keys' object does not support indexing
Aborted
```
dict.keys() return type was changed between python 2 to python 3
See https://stackoverflow.com/questions/16819222/how-to-return-dictionary-keys-as-a-list-in-python

fix: py3 network_dialog - dict.keys()

---

gui/qt/main_window.py

…ead of "utf-8". This will cause the reader to read the files using default encoding rather then utf-8.

Fixed syntax error with utf-8 encoding argument

---

gui/qt/address_list.py
plugins/labels/labels.py

This addresses #2974 and #2975.

fix: editing labels in [QT GUI] Addresses tab for headings

---

gui/qt/main_window.py
lib/commands.py
lib/wallet.py

follow-up of e8b564c0e728e1ca15d39f48a0153c984e2acc3c
Perhaps the csv/json exports should include (or could later include) the redeem_scripts as well.

follow-up of wallet.get_private_key() -> wallet.export_private_key()

---

lib/base_wizard.py
lib/keystore.py
lib/tests/test_wallet_vertical.py

This fails on current master 031b911dce818c4c005663e770b4784234bc5590 (which clearly means it's needed :P), due to #2961. Works with #2962 applied.
Note that I obtained the constants the asserts compare against in
- test_bip39_multisig_seed_bip44_standard()
- test_bip39_multisig_seed_bip49_p2sh_segwit()
from Electrum itself, hence they might not be correct... Would be nice to get an independent confirmation. Still, even without that, these tests can be used to confirm self-consistency.

tests: wallet-keystore integrity (bip39)

---

lib/wallet.py

As the fee for sweep transactions are not set by the user (in the current code at least), it would be nice for the transactions to be replace-by-fee.

make sweep txs always RBF

---

lib/network.py
lib/simple_config.py

Not using `mode` on `mkdir()` as `chmod()` works better under Windows.

Tighten directory permissions

---

lib/wallet.py

typos...
Maybe we should consider refactoring so that txin types are referred to by variables -- so that this would have resulted in static errors (not runtime). Similar error happened before in #2938

fix: Imported_Wallet cannot spend from p2wpkh or p2wpkh-p2sh

---

gui/qt/__init__.py

Instead of creating a new context menu and setting it with setContextMenu, simply clear and modify the existing context menu.
Fixes #3022

Modify tray context menu instead of creating a new one

---

lib/transaction.py

From BIP-0141:
"A non-witness program (defined hereinafter) txin MUST be associated with an empty witness field, represented by a 0x00"
See #3031

fix: witness for non-segwit txins

---

lib/storage.py

Seems #3004 missed this.
```
File "/home/user/wspace/electrum/gui/qt/main_window.py", line 1871, in show_private_key
pk, redeem_script = self.wallet.export_private_key(address, password)
File "/home/user/wspace/electrum/lib/wallet.py", line 1461, in export_private_key
redeem_script = d['redeem_script']
KeyError: 'redeem_script'
```
Note that wallets closely following master that had already upgraded to v14 will remain in a "broken" state.

fix: storage.convert_version_14() is missing redeem_scripts

---

lib/tests/test_bitcoin.py

Tests for bitcoin.py. Added new ones, and some refactoring for existing.
new ones mainly include:
- privkey -> pubkey -> addr conversions
- xprv, xpub operations

tests: bitcoin.py

---

lib/network.py
lib/simple_config.py

```
$ ./electrum -v
File "./electrum", line 364, in <module>
config = SimpleConfig(config_options)
File "/home/user/wspace/electrum/lib/simple_config.py", line 74, in __init__
self.path = self.electrum_path()
File "/home/user/wspace/electrum/lib/simple_config.py", line 96, in electrum_path
os.chmod(path, stat.S_IRUSR | stat.S_IWUSR | stat.S_IXUSR)
NameError: name 'stat' is not defined
```

fix: missing import 'stat' in network.py and simple_config.py

---

plugins/trezor/qt_generic.py

Couldn't initialise a wiped Trezor due to this.

fix: rm unicode() calls in trezor plugin (py3)

---

contrib/build-wine/deterministic.spec
contrib/build-wine/prepare-hw.sh
contrib/build-wine/prepare-wine.sh

Building Windows binaries with hardware wallet support is not working on master currently.
This is my attempt at a fix.
- The `prepare-hw.sh` script still referred to python 2.7
- Trezor 0.7.16 requires `hidapi>=0.7.99.post20` and pip grabs `hidapi 0.7.99.post21` but I couldn't get this version to work --> set `hidapi==0.7.99.post20` explicitly
- AFAICT the migration from pyinstaller 2 to pyinstaller 3 (https://github.com/spesmilo/electrum/commit/b5338006f073b01ee5d563f47f8c5374622ee92d) broke backwards compatibility with a feature  (https://github.com/pyinstaller/pyinstaller/issues/2005) we previously relied on. I based my changes on https://github.com/anfema/pyinstaller/commit/6e9d80225f1f750a36fe8e46ad4227c0c8545c3b. Not sure if something else broke due to this referenced change in …

fix: windows build with hw wallets

---

lib/commands.py

To retain existing behaviour of release versions. -- And in any case, not sure it makes sense to base64-encode and then return that as bytes.

py3: signmessage cmd return type

---

plugins/keepkey/cmdline.py
plugins/trezor/cmdline.py

To be honest, I am unsure how to get Electrum to run the `get_pin()` method to test this, but I've tested by invoking it directly using my IDE.

fix raw_input() in trezor cmdline

---

gui/qt/__init__.py

See #3009.
This change is not really a proper fix for #3009... but I don't think these exceptions should be left unhandled and allowed to crash the whole app.

fix: [QT wallet wizard] catch exceptions: UserCancelled, GoBack

---

lib/commands.py

The commands `listunspent` and `history` were using float.
Patched to consistently return strings of Decimal objects.

Update commands: output str(Decimals), not floats

---

contrib/build-wine/prepare-wine.sh

Despite the "not so simple" look, this should be low maintenance.
Whenever the NSIS URL is updated, the committer should change the corresponding hash; and in case of a signature verification failure for the Python binaries, one should check if they added a new release-signing-key.
While all the `pip` downloads and `setuptools` downloads are still there as is, I guess the point of this PR is to reduce the attack surface.

building on wine: check hash of NSIS, and GPG sig of Python

---

gui/qt/main_window.py

follow-up 198cc9d7376768739e1233cbc67add0c5e416984
```
File "/home/user/wspace/electrum/gui/qt/main_window.py", line 2433, in on_dynfee
update_maxfee()
NameError: name 'update_maxfee' is not defined
Aborted
```

follow-up 198cc9d7376768739e1233cbc67add0c5e416984

---

lib/bitcoin.py
lib/tests/test_bitcoin.py

Main motivation is to fix the [randomly failing test](https://travis-ci.org/spesmilo/electrum/jobs/287358699)  by doing stricter checks on the padding than `pyaes`.

bitcoin.py AES: implement our own PKCS7 padding

---

gui/qt/transaction_dialog.py

@lzsaver made me aware of a color definition that doesn't use the `ColorScheme` class yet.
Related: #2957

Follow-up #2983

---

gui/qt/main_window.py
lib/plugins.py
plugins/trustedcoin/trustedcoin.py

See https://github.com/spesmilo/electrum/issues/3095#issuecomment-338525045
Introduced `BasePlugin.can_user_disable()`. TrustedCoin plugin can't be disabled by user.

Disallow disabling TrustedCoin for 2FA wallets

---

lib/tests/test_wallet_vertical.py

When I wrote the original unit test I did not realise that Electrum uses a different derivation for (multisig) hardware wallets. I think it's nicer to have the unit test mirror what Electrum does. (Though with software bip39 seeds any derivation can be specified.)

tests: have bip39 multisig wallet unit test mirror hw wallet behaviour

---

lib/bitcoin.py
lib/wallet.py

See #2857 
Now that the most widely used server implementation, ElectrumX, with [version 1.2](https://github.com/kyuupichan/electrumx/blob/1da8cb547d733fe3da9924a0d31187a6d5bb58a1/README.rst#version-12), properly separates P2PK and P2PKH scripts, we can implement a way for users to spend P2PK outputs.
In this PR, I propose enabling the `sweep` functionality to redeem these coins. Unfortunately, the WIF format for private keys gives no hint if P2PK scripts are to be used. What I do, is search for both P2PK and P2PKH scripts whenever an "old type" (pre-segwit) WIF is swept from. The `compressed` byte is assumed to be correct, the same boolean is used for both script types.
I think the fact that (in some sense) duplicate queries are sent to servers (hence e.g. increasing load/bandwidth), can …

try to sweep p2pk outputs from old type WIF privkeys

---

lib/wallet.py

I've missed this in #3125 
Only affects the transaction dialog when doing the sweep: the input type is displayed as "unknown" instead of something more meaningful.
Before / After:

fix: sweep p2pk - small display bug (unknown -> pubkey)

---

lib/wallet.py

nLockTime is currently not set when
- sweeping
- using RBF
- using CPFP
I set it analogous to https://github.com/spesmilo/electrum/blob/6f3c822867bd512e276ef63ad7b8c2af2fa40927/lib/wallet.py#L858-L860
as it's already done in case of `make_unsigned_transaction()`.

txn: set locktime to local height for RBF, CPFP, sweep

---

lib/bitcoin.py
lib/keystore.py
lib/tests/test_bitcoin.py

- normalize old seeds, see #3143
- ~~made `is_old_seed()` stricter~~. It incorrectly assumed that any permutation of (a subset with the correct size, of) words is a valid old seed (but this is false, e.g. `hurry idiot prefer sunset mention mist jaw inhale impossible kingdom rare squeeze` encodes as 33 hex characters)
edit: I've reverted the stricter check, see #3149

old seeds: normalize

---

gui/qt/address_list.py
gui/qt/main_window.py

The concept of clicking buttons to change their text is not really straight-forward and might confuse users. For example, clicking "All" doesn't show all addresses.
This changes the user interaction to use combo boxes instead:
I also added a label to the buttons.

Use combo box instead of buttons to filter address tab

---

contrib/build-wine/prepare-hw.sh

The need to do this was fixed in trezor/cython-hidapi#44 and trezor/cython-hidapi#45.

Install latest version of Trezor on Windows

---

gui/qt/network_dialog.py

Had a discussion with skace in #electrum. He said he had not realised up until that point what the list of servers in the `Overview` tab of the `Network dialog` represents. He also did not know about the fact that Electrum (using default settings) connects to 8-10 electrum servers to get headers from. He suggested that if we make the renaming in present PR, that would make it a lot more obvious.

NetworkDialog: "Node" -> "Connected node"

---

lib/wallet.py

"Addresses" should be tested for being addresses.
See #3186
Present PR does NOT fix referenced issue, as already imported garbage will need to be sanitized.
Current master only tests addresses in the wizard, when creating a new wallet:
https://github.com/spesmilo/electrum/blob/7e4e96e5eb0f15f65d45a0baba677647ddf40d04/lib/base_wizard.py#L146-L150
Not when importing into an existing wallet:
https://github.com/spesmilo/electrum/blob/7e4e96e5eb0f15f65d45a0baba677647ddf40d04/gui/qt/main_window.py#L2396-L2400

fix: import_address() for Imported_Wallet

---

contrib/build-wine/deterministic.spec
contrib/build-wine/prepare-wine.sh

See #3171
This is essentially "stolen" from https://github.com/pyinstaller/pyinstaller/issues/1566#issuecomment-279884163
With this, binaries should work on Windows 10 by default (as with 3.0.0).
On Windows 7 and 8.1, binaries **might** work by default; if they don't work, the end-user should
- try installing the KB2999226 Windows update
- try installing [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-US/download/details.aspx?id=48145)
Either of these two things should fix it. To clarify, the **end-user** has to install one of these.
Hence I would call this a "hotfix".
I've tested on Windows 10 and 7; and skace (from #electrum) tested on 8.1 - thanks for that.
No idea about earlier Windows versions.
These are the DLLs we are removing (in my dev …

 hotfix: pre-Windows10 binaries

---

lib/wallet.py

Currently when deleting an address from an Imported_Wallet, remnants are left in the wallet file.
This PR tries to do a full deletion instead.

proper address deletion for imported wallets

---

gui/text.py

It's not obvious what's going on when you're presented with this, just because it can't find the wallet file:
```
$ ./electrum --gui=text
File "./electrum", line 373, in <module>
d.init_gui(config, plugins)
File "/home/user/wspace/electrum/lib/daemon.py", line 290, in init_gui
self.gui = gui.ElectrumGui(config, self, plugins)
File "/home/user/wspace/electrum/gui/text.py", line 34, in __init__
self.wallet = Wallet(storage)
File "/home/user/wspace/electrum/lib/wallet.py", line 1819, in __new__
WalletClass = Wallet.wallet_class(wallet_type)
File "/home/user/wspace/electrum/lib/wallet.py", line 1833, in wallet_class
if multisig_type(wallet_type):
File "/home/user/wspace/electrum/lib/storage.py", line 57, in multisig_type
match = re.match('(\d+)of(\d+)', …
```

fix typo: text gui with no wallet

---

gui/qt/paytoedit.py

On high-resolution (HiRes) displays, the pixel size of a font is much
larger than the hard-coded 17 pixels, e.g. more than 40 for me. It's
better to get the line high of the current font from it's metrics and
calculate the high of the box with it.

paytoedit: Calculate height depending on font's line height

---

gui/qt/main_window.py

Note: the `@protected` decorator already checks that the password is correct.
Fixes #3234

fix: deleting a passworded wallet did not work

---

contrib/build-wine/deterministic.spec

Currently there are three Windows binaries we build: `standalone`, `setup`, and `portable`.
`standalone` and `portable` only differ in where they put the datadir, hence let's consider them identical for the purposes of this description.
The main part of the Windows build is done by PyInstaller. There are two common ways to distribute apps using PyInstaller:
- `One-File`, which packages all dependencies and the app itself into a single executable
- `One-Folder`, which packages all dependencies and an executable for the app into a folder
The `standalone` Windows binary is built using the `One-File` mode of PyInstaller.
The `setup` binary aims to be built using NSIS into a single installer FROM the folder created using the `One-Folder` mode of PyInstaller.
This intended behaviour would mean …

win binaries: build a proper setup.exe that uses local folder

---

.travis.yml
README.rst

This makes the CI build generate and upload helpful statistics about the test coverage ([like this one](https://coveralls.io/builds/14101696/source?filename=lib%2Fkeystore.py) 📊 ).
Might be useful to determine which modules still need unit tests.
If you want to merge this you will also need to login on [coveralls.io](https://coveralls.io/sign-up) and activate the repo there.

Upload coverage statistics from Travis

---

gui/qt/main_window.py

```
File "/home/user/wspace/electrum/gui/qt/main_window.py", line 2279, in export_history_dialog
self.do_export_history(self.wallet, filename, csv_button.isChecked())
File "/home/user/wspace/electrum/gui/qt/main_window.py", line 2332, in do_export_history
f.write(json.dumps(lines, indent = 4))
File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
**kw).encode(obj)
File "/usr/lib/python3.5/json/encoder.py", line 200, in encode
chunks = list(chunks)
File "/usr/lib/python3.5/json/encoder.py", line 427, in _iterencode
yield from _iterencode_list(o, _current_indent_level)
File "/usr/lib/python3.5/json/encoder.py", line 324, in _iterencode_list
yield from chunks
File "/usr/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
yield from chunks …
```

fix py3: do_export_history

---

README.rst

Sorry, I missed that in #3245.
Also a heads-up: You will need to login to [coveralls.io](https://coveralls.io/sign-up) with your Github account and activate coverage reports for electrum to link it with the Travis builds.

Follow-up #3245: Fix wrong branch name in badge

---

lib/commands.py

Avoid `RuntimeError: dictionary changed size during iteration` by converting into a list

[fix clearrequests] dictionary changed size during iteration

---

gui/qt/main_window.py
lib/transaction.py

Transaction priority is no longer used by most bitcoin nodes/miners.

remove Transaction.requires_fee()

---

electrum
gui/kivy/main_window.py
gui/qt/network_dialog.py
lib/bitcoin.py
lib/blockchain.py
lib/keystore.py
lib/network.py
lib/util.py
plugins/trezor/plugin.py

I would like to be able to undo a call of `set_testnet()` for some unit tests but this is currently not possible.

bitcoin.NetworkConstants: easier changing between testnet and mainnet

---

lib/interface.py

fixes #3253
I have **tried** to preserve the current behaviour exactly, while also allowing newer TLS than 1.1.

interface ssl: besides TLS 1.1, also allow later versions

---

gui/qt/__init__.py
gui/qt/installwizard.py
lib/daemon.py

See #3181
This PR changes the behaviour to consistently offer upgrades to the user when using the QT GUI (in all four scenarios listed in above linked issue). Users of other GUIs/CLIs/daemon should be unaffected by this change, I think, and upgrades should happen for them silently as before.

wallet storage upgrade will now happen silently whenever possible

---

lib/bitcoin.py
lib/wallet.py

When sweeping, similar to how P2PK outputs were handled in #3125, I suggest doing server lookups for both compressed and uncompressed pubkeys in case of minikeys.
see #2748
Note that this PR only affects sweeping, so e.g. imported wallets won't see and monitor outputs for both compressed and uncompressed pubkeys.

sweeping minikeys: search for both compressed and uncompressed pubkeys

---

lib/util.py

Reduces the code footprint a bit and is higher performing. I'm not super keen on the names of these, but leaving them as named for now until we can discuss.

Simplify bytes/hex conversion functions now that we're Python 3+ only.

---

plugins/keepkey/cmdline.py

`hook` decorator referenced without being imported.

Fix undefined reference error in command line KeepKey plugin.

---

gui/qt/util.py

This is a follow-up of 70d23f9e3ba0ae78840ac5cd3375685ece23dd32 and #3189
```
[DeviceMgr] scanning devices...
File "/home/user/wspace/electrum/lib/base_wizard.py", line 245, in on_hw_derivation
xpub = self.plugin.get_xpub(device_info.device.id_, derivation, xtype, self)
File "/home/user/wspace/electrum/plugins/ledger/ledger.py", line 488, in get_xpub
xpub = client.get_xpub(derivation, xtype)
File "/home/user/wspace/electrum/plugins/ledger/ledger.py", line 62, in get_xpub
raise Exception("Firmware version too old for Segwit support. Please update at https://www.ledgerwallet.com")
Exception: Firmware version too old for Segwit support. Please update at https://www.ledgerwallet.com
During handling of the above exception, another exception occurred: …
```

fix: ledger old fw segwit crash

---

gui/qt/seed_dialog.py

Fixes:
1. reach restore seed dialog in wizard
2. enter a bip39 seed
3. enable "bip39" option
4. checksum not calculated

fix: bip39 checksum sometimes not calculated

---

gui/qt/utxo_list.py

See https://github.com/spesmilo/electrum/issues/3317#issuecomment-345114444
Edit: I can add the mentioned storage version upgrade, if it's deemed to worth it.

disallow editing labels in Coins tab (QT)

---

plugins/ledger/ledger.py

fixes #3264
The crash happens at https://github.com/spesmilo/electrum/blob/219a5b02a63a9ee227cff1c83516d003736abf4b/plugins/hw_wallet/qt.py#L161
Delegating the `clear_dialog()` calls to the GUI thread (via signals) seems to fix it. I would appreciate it if someone who understands QT better would enlighten me why... :P
It took me way too long to debug this...

fix: ledger clear_dialog() threading issues

---

lib/bitcoin.py
lib/commands.py

fixes #3334
Without this PR, only one of the following three usages work.
With this PR, all three work.
```
user@debian:~/wspace/electrum$ echo '["1EmM5ASoeNYoRELRkfBKueatumrss9HBex"]' | ./electrum -w ~/.electrum/wallets/tmp5 getprivatekeys -
WARNING: ALL your private keys are secret.
Exposing a single private key can compromise your entire wallet!
In particular, DO NOT use 'redeem private key' services proposed by third parties.
Password:
File "./electrum", line 423, in <module>
result = run_offline_command(config, config_options)
File "./electrum", line 288, in run_offline_command
result = func(*args, **kwargs)
File "/home/user/wspace/electrum/lib/commands.py", line 87, in func_wrapper
return func(*args, **kwargs)
File …
```

more robust getprivatekeys() and is_segwit_address()

---

plugins/digitalbitbox/digitalbitbox.py

fixes #3339
Without PR, with traceback printed:
```
[DeviceMgr] scanning devices...
[DeviceMgr] Registering <electrum_plugins.digitalbitbox.digitalbitbox.DigitalBitbox_Client object at 0x7f9a0e9be518>
File "/home/user/wspace/electrum/plugins/digitalbitbox/digitalbitbox.py", line 368, in hid_send_plain
reply = json.loads(r)
File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytearray'
Exception caught the JSON object must be str, not 'bytearray'
```
With PR, with extra logging:
```
[DeviceMgr] scanning devices...
[DeviceMgr] Registering <electrum_plugins.digitalbitbox.digitalbitbox.DigitalBitbox_Client object at 0x7fef06e4edd8>
hid_send_plain: r= …
```

fix: py3 digitalbitbox hid_send

---

gui/qt/main_window.py

I wanted to implement showing notifications for incoming transactions but quite surprised I found out that there already is such a feature.
Apparently, the feature only worked when the transaction was received while Electrum was offline, since `ElectrumWindow.notify_transactions` was only called once from `load_wallet`.
Calling the method from the `on_network` callback makes the notification appear instantly for new transactions.

Show notifications for incoming transactions

---

lib/plugins.py
plugins/digitalbitbox/digitalbitbox.py

1. When the pairing is being forced and the user clicks 'No', the tx
was cancelled completely because the UserCancelled exception was
accidentally converted to an Exception.
2. Same with user aborting the signing process with a short touch on
the device (or a timeout).

 digitalbitbox: correctly handle user aborts

---

contrib/build-wine/build-electrum-git.sh
contrib/deterministic_requirements.txt
contrib/freeze_packages.sh
contrib/make_packages

`contrib/deterministic_requirements.txt` is a pip requirements file containing Electrum's dependencies with frozen versions. It should be generated using `contrib/freeze_packages.sh` whenever dependencies need to be updated.
`make_packages` and `build_electrum_git` will use these versions.
This should bring us one step closer to deterministic builds.

Save dependency versions in repo

---

electrum-env

Without this fix electrum-env creates a python2 virtualenv if the system default python is version 2

electrum-env creates python3 virtualenv

---

contrib/build-wine/build.sh

Passes UTC as timezone to the touch command so it doesn't depend on the local timezone.

Make build location independent

---

lib/rsakey.py

Stumbled upon this making tests

[easy] Typo breaks lib.rsakey.RSAKey.generate ?

---

gui/qt/main_window.py
gui/qt/transaction_dialog.py
lib/wallet.py

This might not be perfect as is, I haven't done very extensive testing yet (just a bit). However I wanted to get feedback regarding the approach/idea in general.
The primary motivation is #2179
Notes:
1. `Amount` is frozen and set to max. This is to avoid dealing with the user trying to sweep only "some of the coins" (where to put the change in that case?)
2. `Pay to` field is frozen and set to the single address the user entered in the sweep dialog. This is done to block the user from using the advanced functionalities of the `Pay to` field, as then she would be able to set a smaller amount directly or via pay-to-many (see previous point)
3. If the user selects `Pay to many` from the menu, the `Pay to` field will become empty and read-only. To recover she needs to use `Clear`. The `Pay …

use the send tab when sweeping (qt gui)

---

gui/qt/main_window.py

This pull request is an attempt to solve #3360 by allowing the user to select and copy the text shown in the statusBar.
This was achieved by using `QLabel's` [`TextInteractionFlag`](https://doc.qt.io/qt-5/qt.html#TextInteractionFlag-enum) property. And the label's padding was set to 0 in order to make it fit inside statusBar's height.

Selectable statusbar text

---

plugins/trustedcoin/qt.py

In response to https://github.com/spesmilo/electrum/issues/3438
- catch exception when retrieving 2FA TOS
- only allow user to continue if TOS was received

Catch exception when retrieving 2FA TOS

---

gui/qt/main_window.py
gui/qt/paytoedit.py

See https://github.com/spesmilo/electrum/issues/3477
The point of this PR is to not have Electrum try a DNSSEC resolution if the "pay to" field contains
```
mkP5Hjpke3yUwLH9piLH5QAUsLGFVe9aaP,0.2
```
(so obviously this does NOT properly deal with #3477)

fix: openalias resolution unnecessarily done for some payto

---

contrib/build-wine/build-electrum-git.sh
contrib/build-wine/build.sh
contrib/build-wine/electrum.nsi

This reduces the differences between builds of setup.exe. It's still not fully deterministic yet though.

Make setup.exe differ less

---

contrib/build-wine/electrum.nsi

This adds an "Electrum Testnet" entry to the Electrum section of the Windows start menu.
Closes: #3492

Windows Installer: Add shortcut to testnet mode

---

lib/transaction.py

`num_sig` is M
`len(txin['signatures'])` is N

fix: tx size estimation for multisig

---

gui/qt/main_window.py
lib/coinchooser.py
lib/tests/test_transaction.py
lib/transaction.py

- "privacy" is now the default coinchooser policy, and "priority" has been removed
- "privacy" prefers to spend from confirmed coins
- coinchooser choice has been hidden in QT, the same should be done in kivy
-----
One remark regarding the changed privacy policy, which actually needs detailing the changes...
Any bucket can be:
1. "confirmed" if it only contains confirmed coins; else
2. "unconfirmed" if it does not contain coins with unconfirmed parents; else
3. "unconfirmed parent"
In the current state of the PR, we try to only use buckets of type 1, and if the coins there are not enough, try to use the next type but while also selecting **all buckets of all previous types** (A).
This could be trivially changed to instead simply expand the set of allowed buckets, but do not automatically …

CoinChooser: privacy prefers confirmed and is default

---

lib/plot.py

Previously dialog with error:
need more than 0 values to unpack
was displayed and not a plot.
After this change plot is displayed without any dialog without graph of
outgoing transactions and without legend for outgoing transactions.
Fixes: #3487

Handle empty outgoing transactions for plot

---

contrib/build-wine/build-electrum-git.sh
contrib/build-wine/build.sh

This is especially useful if you want to reproduce some version while there already is a new commit in master.
We still need to figure out what to do with the icons and locale repository. Maybe we can use the timestamp from the commit of the main repository and check out the latest version on that date.

Allow to build older commits

---

lib/simple_config.py

see #3111
Electrum could only start in testnet mode if it had already started in mainnet mode before (so that it created the parent folder of the datadir already).
```
$ ./electrum -v --testnet
File "./electrum", line 360, in <module>
config = SimpleConfig(config_options)
File "/home/user/wspace/electrum/lib/simple_config.py", line 74, in __init__
self.path = self.electrum_path()
File "/home/user/wspace/electrum/lib/simple_config.py", line 95, in electrum_path
os.mkdir(path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.electrum/testnet'
```
```
$ ./electrum -v --testnet --dir=tmp
File "./electrum", line 360, in <module>
config = SimpleConfig(config_options)
File …
```

fix: testnet datadir could not be created first

---

lib/tests/test_wallet_vertical.py

- added a unit test for Yprv/Ypub (p2wsh-p2sh)
- added missing seed words for the tests where there was only an xpub
- (I could not find all the seeds, so had to change some existing wallets)
The file should now contain at least one test for all of {x,y,Y,z,Z} | {pub,prv}

tests: add missing info in vertical wallet tests

---

lib/qrscanner.py

The path to the camera device is not encoded before it gets passed to the library. This results in `zbar_processor_init` returning an error code. However, as this code is not checked, a SEGFAULT is thrown after calling further methods on `proc`.
Fixes: #3239

qrscanner: Fix segfault when using a specific camera device

---

lib/coinchooser.py
lib/transaction.py

- CoinChooser now calculates with tx weights instead of vbytes
- this removes some rounding errors
- marker and flag are now also accounted for, for segwit txns
- witness size for mixed legacy/segwit txns is now also correctly 1 weight unit for every input
@ecdsa This should make setting the feerate (more) precise.
The small deviations I had previously found are eliminated by this change.
The larger deviations were, as you guessed, due to not using dust-valued change outputs.

more precise fee calculation

---

lib/wallet.py

I don't see the reason for this override, and it's causing bugs here:
https://github.com/spesmilo/electrum/blob/4bab8b63e192078be98ebbf0e84581b2056b5dc5/gui/qt/address_list.py#L88-L93

fix: address filters for Imported_Wallet: wallet.is_used()

---

gui/kivy/uix/screens.py

```
12-24 03:23:51.092 27989 28009 I python  :    File "/data/data/org.electrum.electrum/files/app/gui/kivy/uix/ui_screens/address.kv", line 76, in <lambda>
12-24 03:23:51.094 27989 28009 I python  :      Clock.schedule_once(lambda dt: app.address_screen.update())
12-24 03:23:51.094 27989 28009 I python  :    File "./gui/kivy/uix/screens.py", line 524, in update
12-24 03:23:51.096 27989 28009 I python  :      _list = wallet.change_addresses if self.screen.show_change else wallet.receiving_addresses
12-24 03:23:51.096 27989 28009 I python  :  AttributeError: 'Imported_Wallet' object has no attribute 'change_addresses'
12-24 03:23:51.672 27989 28009 I python  : Python for android ended.
```

fix: kivy Addresses tab crash for Imported_Wallet change

---

contrib/build-wine/deterministic.spec
contrib/osx.spec
setup.py

`servers_testnet.json` is currently not included in binaries for Mac. I don't have a Mac to test but I suspect testnet might not work due to this, similar to https://github.com/spesmilo/electrum/issues/3321
Also, I think we could include `checkpoints_testnet.json` in all binaries, as otherwise there's not much point in having the file in the first place :) And the speed-up for the initial startup is significant.

include servers_testnet.json and checkpoints_testnet.json in binaries

---

gui/qt/main_window.py
lib/util.py
lib/wallet.py

This fixes some problems when using the new fee ui without a network connection (or with `--offline`).
Mostly to do with dynamic fees enabled, and not having those.
-----
For example:
```
File "/home/user/wspace/electrum/gui/qt/fee_slider.py", line 28, in moved
self.callback(self.dyn, pos, fee_rate)
File "/home/user/wspace/electrum/gui/qt/main_window.py", line 1071, in fee_cb
self.feerate_e.setAmount(fee_rate // 1000)
TypeError: unsupported operand type(s) for //: 'NoneType' and 'int'
Aborted (core dumped)
```
Or `window.size_e` not getting set.

fix fee ui: offline case

---

gui/kivy/data/java-classes/org/electrum/qr/SimpleScannerActivity.java
gui/kivy/main_window.py
gui/kivy/tools/buildozer.spec

This integrates the QR code scanner into the android app. It uses [dm77/barcodescanner](https://github.com/dm77/barcodescanner) from Maven Central, which in turn pulls the relevant parts of zxing into the project.
Pyjnius proved to be quite stubborn in that it crashed whenever a string was passed as an argument but some creative casting prevents that.
The resulting APK file is only marginally larger (<+1MB).
It doesn't look to spectacular but it works:
This depends on kivy/python-for-android#1213 and kivy/buildozer#612. If you want to test it, merge both and run `rm -rf .buildozer/android/platform/build/{build,dists}` before building.

Bundle QR scanner with Android app

---

gui/kivy/main_window.py

We're doing this in QT already.
Also, note that the user is still prompted for each individual tx:
https://github.com/spesmilo/electrum/blob/5156b60769b365522b263220dfefcca12fea4e97/gui/kivy/uix/screens.py#L266-L271

Android: make RBF on by default

---

lib/wallet.py

In python3, the `.keys()` function returns an iterator, not a list,
so to get a list that can be iterated over, use `list()` instead to
avoid modification of a list while in use.

Avoid modifying self.transactions in prepare_for_verifier

---

plugins/ledger/ledger.py

When confirming signing on Ledger it will display the SHA256 hash of the message. Electrum will now also display this allowing verification that the intendened message is being signed.

Show message hash when signing

---

lib/mnemonic.py

I am not sure if this is deliberate or not, but currently Electrum might generate shorter seeds in rare cases (fewer words).
I only noticed it when the GUI gave me `sniff slender rifle rack express anxiety ecology believe heavy accuse blue`, which is only 11 words.
Suddenly we can longer tell people that "there's no way your seed contains only 9 words", rather "it's extremely unlikely..." :)

avoid shorter seeds 'by luck'

---

lib/daemon.py

As far as I can tell, there is no need to allow this, and doing so poses severe security risks (see #3374).

Stop allowing CORS for the JSON-RPC server

---

lib/daemon.py
lib/jsonrpc.py
lib/util.py

Closes https://github.com/spesmilo/electrum/issues/3374
- Introduce `rpcuser` and `rpcpassword` config variables used to authenticate access to the JSON-RPC server
- If the variables are not set, initialise `rpcuser` to `user`, and `rpcpassword` to a random base64 string with ~128 bits of entropy
- The variables are persisted in the config file on the local filesystem. The config file has 0600 permissions.
- Uses HTTP basic access authentication

Password-protect the JSON RPC interface

---

README.rst

`./contrib/make_locale` uses `python-requests` as of [`a3ad32b`](https://github.com/spesmilo/electrum/commit/a3ad32bd91e405d918276c50d2995cd86764e518) and dropped `python-pycurl` as of [`9ee10ab`](https://github.com/spesmilo/electrum/commit/9ee10ab3e1d497a28d5783f6acd6861e9656dcd5)

Fix locale documentation

---

lib/blockchain.py

After d1b8a6fae6d44e78c8093b01321f8d430442b687, `get_target()` should always return just a target.
With this patch, synchronization from scratch should start working again.

Fix Blockchain.get_target()

---

lib/base_wizard.py
lib/keystore.py
lib/tests/test_wallet_vertical.py

This enables software bip39 seeds to use p2wpkh scripts to receive on along the derivation path described in soon-to-be bip84: https://github.com/bitcoin/bips/pull/620
~~Best not to merge until bip84 gets into draft status (above PR gets merged).~~
EDIT: bip84 is now in draft status
-----
For the time being **I've disabled this** (p2wpkh output scripts for receiving) **for hardware wallets**.
- The Trezor plugin needs some changes for it to work, but the fw might be ready. https://github.com/spesmilo/electrum/issues/3551
- also atm Trezor on master is "broken" due to merging https://github.com/spesmilo/electrum/pull/3621 too fast :)
- Ledger (Nano S) seems to work already with btchip-python 0.1.24, and latest fw
- KeepKey and dbb are not ready for this (though I haven't tested)
- KeepKey …

bip84 for sw seeds

---

plugins/trezor/plugin.py

closes https://github.com/spesmilo/electrum/issues/3551
-----
Please test with https://github.com/spesmilo/electrum/pull/3630 also merged
Note that https://github.com/spesmilo/electrum/pull/3630/commits/e218c4a305d3ba25cce0b76e138332c501bf9298 still does not allow creating a wallet with a hw device using bip84 (so comment that out to test)
Also note that you need git HEAD of python-trezor as https://github.com/spesmilo/electrum/pull/3621 broke compatibility with the latest released version.
Also note that spending from multisig with Trezor is broken on master currently (https://github.com/spesmilo/electrum/issues/3680) regardless of this PR.
----
I've tested `p2pkh` ("bip44") /`p2wpkh-p2sh` ("bip49") /`p2wpkh` ("bip84") wallets with Trezor; creating single/multi-input transactions to …

trezor plugin: native segwit

---

lib/base_wizard.py
plugins/digitalbitbox/digitalbitbox.py
plugins/keepkey/plugin.py

wizard: allow to choose derivation again if script type is not supported (instead of closing the wizard)
I think we should not allow the creation of wallets which won't properly work in any case.
This PR is specifically with https://github.com/spesmilo/electrum/pull/3630 and https://github.com/spesmilo/electrum/pull/3681 in mind, and aims to replace https://github.com/spesmilo/electrum/commit/e218c4a305d3ba25cce0b76e138332c501bf9298.
After those PRs are merged, (forgetting about multisig)
- trezor should support p2pkh, p2wpkh-p2sh, p2wpkh
- ledger (nano S, at least) should support p2pkh, p2wpkh-p2sh, p2wpkh
- dbb should support p2pkh, p2wpkh-p2sh
- keepkey should support p2pkh
-----
**Note that I have disabled creating new p2wpkh-p2sh wallets for keepkey here**, as it can NOT spend atm: …

wizard: allow to choose derivation again if script type is not supported

---

gui/qt/main_window.py

Prevents electrum from crashing when canceling a private key export. This error was caused when the window closed, but a thread continued to try to write to it.
Special thanks to @rt121212121 for helping me fix this one

Fix crash when exporting private keys

---

gui/qt/__init__.py

When I scan for hardware wallets, with --verbose log, this is what I see:
```
[WalletStorage] wallet path /home/user/.electrum/wallets/wallet_212
[WalletStorage] wallet path /home/user/.electrum/wallets/wallet_212
[WalletStorage] wallet path /home/user/.electrum/wallets/wallet_212
Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute before constructing QGuiApplication.
[Plugins] loaded ledger
[Plugins] loaded digitalbitbox
[Plugins] loaded keepkey
[Plugins] loaded trezor
[DeviceMgr] scanning devices...
[DeviceMgr] scanning devices...
[DeviceMgr] scanning devices...
[DeviceMgr] scanning devices...
```
I am unsure; shall we just do what the log line suggests? (That makes it go away.)
Would there be security-related …

QT: AA_ShareOpenGLContexts

---

gui/qt/__init__.py

If the attribute does not exist (presumably in older versions of Qt),
this change prevents the following error:
AttributeError: type object 'Qt' has no attribute 'AA_ShareOpenGLContexts'

QT: Only set if hasattr(QtCore.QCoreAplication, "AA_ShareOpenGLContexts")

---

lib/simple_config.py
lib/tests/test_simple_config.py
lib/util.py

~~Depends on https://github.com/spesmilo/electrum/pull/3731
Config version 2 removes the protocol letter from `server` in config.~~
- remove system config
- implement config upgrades
- can only meaningfully upgrade user_config (not CLI)
EDIT: config version 2 now changes the protocol to `:s` in config

Config upgrades

---

gui/qt/main_window.py

This changes the maximum number of decimal zeroes in the settings dialog when the base unit is changed. If the current value is greater than the new maximum, it will be adjusted automatically.
Closes: #1795
Closes: #2312

Change number of zero when base unit changes

---

contrib/build-wine/build.sh

@bauerj, can you have a look?
```
```
This script looks **dangerous**. If user does not have _coreutils_ or if there is another _dirname_ executable in the local bin directory - this script can remove _/build/*_ and _/dist/*_ in the root of user's filesystem.
```
here=$(nothing "$0")
echo rm $here/build/* -rf
echo rm $here/dist/* -rf
```
We have to check that _"${here}"_ is not empty at least. Also do we really need it? Can we just use _"${PWD}"_?
```
here=$PWD
test -n "$here" -a -d "$here" || exit 
```
...or simply omit it?
```
echo "Clearing $PWD/build and $PWD/dist..."
rm build/* -rf
rm dist/* -rf
prepare-wine.sh && \
prepare-pyinstaller.sh && \
prepare-hw.sh || exit 1
```
Follow-up: 5778102 (PR #3397).

Fix rm -rf

---

contrib/freeze_packages.sh

It will not create virtualenv for python3 if python2 is used by default on the system. This should fix it.

Use python3 for virtualenv

---

gui/qt/main_window.py
lib/wallet.py

`wallet.is_beyond_limit` is slow because is looks up addr indices in a list and because it copies sublists
This is a problem as this method gets called inside a for loop when opening a wallet:
https://github.com/spesmilo/electrum/blob/7ab9fa5be48cf5aefec98d94657241c73a6e280c/gui/qt/address_list.py#L109
`wallet.is_mine` is also slow. It usually does linear operations (in the number of addresses in the wallet) but sometimes even more (for Imported Wallet, it even sorts the addresses!).
This is also a problem for the same reason:
https://github.com/spesmilo/electrum/blob/7ab9fa5be48cf5aefec98d94657241c73a6e280c/lib/wallet.py#L275
-----
- make `wallet.get_address_index` faster by storing an addr->index dict, and use it
- make one fewer list copy
- make `wallet.is_mine` faster by looking up in …

Optimisations in wallet.py

---

lib/wallet.py

https://github.com/spesmilo/electrum/commit/5be78950ca31ba903b4bd0f575511eeb732e114c broke wallet.check_history AFAICT.
See here https://github.com/spesmilo/electrum/commit/5be78950ca31ba903b4bd0f575511eeb732e114c#diff-9a32635d4a93b6e41c91fec9e4001d4aL200
This PR restores the behaviour to before the above mentioned commit.

fix wallet.check_history

---

electrum
gui/qt/exception_window.py
gui/qt/main_window.py
lib/util.py

This adds an exception hook to the Qt GUI that shows an error window like this:
* Default exception handling will be delayed until the window is closed (so the application doesn't terminate for exceptions in the main window)
* Includes a button that sends a crash report to a server that eventually creates a Github issue. There will only be one Github issue per `(file, method, exception_type)` combination
Closes: #2009

Semi-automated crash reporting

---

lib/commands.py

Note: how should `getproof` be handled? We could just delete the method completely.

migrated some commands from addr to scripthash

---

contrib/build-wine/prepare-wine.sh

pypiwin32 might be going away for pywin32 at some point; and after looking into this it seems that pywin32-ctypes should be enough for our needs

Win binaries: use pywin32-ctypes instead of pypiwin32

---

electrum
gui/kivy/uix/dialogs/installwizard.py
gui/qt/installwizard.py
gui/qt/main_window.py
gui/qt/password_dialog.py
lib/base_wizard.py
lib/bitcoin.py
lib/commands.py
lib/keystore.py
lib/storage.py
lib/wallet.py
plugins/cosigner_pool/qt.py
plugins/digitalbitbox/digitalbitbox.py
plugins/greenaddress_instant/qt.py
plugins/hw_wallet/plugin.py
plugins/hw_wallet/qt.py
plugins/keepkey/plugin.py
plugins/ledger/ledger.py
plugins/trezor/plugin.py
plugins/trustedcoin/trustedcoin.py

This PR
- implements #3183: encryption of watch-only wallets
- supersedes #3297: in wizard, prompt for password for Imported_Wallet
- implements #2929: allow encrypting wallet files for hardware wallets
- but the password is unrelated to the device :(
As it doesn't really make sense to encrypt only the keystore (and not the storage) of watch-only wallets (there isn't even a keystore for imported addresses wallets), I've disabled that option for this case. I am not too happy about how this change (`force_disable_encrypt_cb`) looks in the code, so suggestions welcome.

allow encrypting watch-only wallets

---

plugins/trezor/plugin.py
plugins/trezor/qt_generic.py

Naive removal of the code to decide whether to show menu option.
And Trezor must be the first seed in the wallet.

show address on trezor for multisig

---

gui/qt/transaction_dialog.py
lib/commands.py
lib/transaction.py
lib/wallet.py

Merging the `local_tx` branch introduced the possibility of having conflicting transactions in history.
atm this PR uses a new data structure `spent_outpoints` instead of extending `pruned_txo`

conflicting transactions

---

README.rst
contrib/build-osx/README.md
contrib/build-osx/make_osx
contrib/build-osx/osx.spec
contrib/make_osx

- Updates the outdated building instructions
- Fixes the hard-coded path in the specfile
- Replaces the build script with a new one that:
- Installs a fixed Python version
- Installs the frozen dependencies that the Windows builds will use too (#3604 is merged here)
- Uses the pre-built locales and icon file
I tested it on a fresh VM, no other dependencies are necessary.
Closes: #3775

Update macOS build

---

gui/qt/main_window.py
lib/coinchooser.py

- introduce a config variable `coin_chooser_output_rounding` that enables/disables output value rounding by the coinchooser
- by default it is disabled
- expose control of config variable to qt gui
- also; changed how the rounding works if there is only one change output
- the rounding logic seems to have been written with multiple change outputs in mind; where it makes sense to allow a change output to have more-or-less precision than other outputs
- with only one change output, the ideal outcome should be to have a change output that doesn't have the most precision; with this change we aim for as much precision as the otherwise most precise output
closes https://github.com/spesmilo/electrum/issues/3255

coinchooser: make output value rounding configurable

---

lib/simple_config.py

This is trying to avoid the following example scenario:
- the server sends feerate estimates in sat/kbyte resolution
- the GUI displays feerate in sat/byte resolution
- the backend might do the calculation in sat/kbyte resolution and then be inconsistent with what the GUI displays due to rounding
-----
One concrete example:
(we assume: time-based estimates, dynamic fees)
server sends 7.5 sat/byte estimate (7500 sat/kbyte)
user moves slider to that estimate
https://github.com/spesmilo/electrum/blob/95c5815fe3c922807af06547051339b082bcb926/gui/qt/main_window.py#L1091-L1092
feerate displayed will be rounded down to 7 sat/byte
https://github.com/spesmilo/electrum/blob/95c5815fe3c922807af06547051339b082bcb926/gui/qt/main_window.py#L1414-L1424
sets `fee_estimator = None` …

fee calculation: force back-end to use integer sat/bytes

---

requirements.txt
setup.py

Some linux distros require pip to use the `--user` switch. The use case for installing dependencies in this case would be `pip3 install --user -r requirements.txt` then `sudo python3 setup.py install`.
Small change but useful for others.
Cheers!🥂

requirements.txt support for user only pip requirements

---

contrib/build-osx/osx.spec
contrib/deterministic-build/requirements-binaries.txt

As per the discussion in Electron Cash slack -- this is a PR that addresses the weirdness in PyQt5 5.10 not looking right on Mac.  Turns out libqmacstyle.dylib wasn't being picked up by PyInstaller, hence the horrible look.  This fixes that.
(NB: On Windows things should look ok as I think the Windows style is hard-compiled into Qt5 5.10 from my groking of the files, but I haven't tested this on Windows)

Fixup to get PyQt5 5.10 working ok and looking right on Mac

---

lib/bitcoin.py

Based on https://github.com/spesmilo/electrum/issues/3539, it seems some people want (or use already) separate version bytes for testnet (mostly upub; besides tpub obviously). No one had a strong opinion against this; hence to try to be compatible with other wallets/services, we too can distinguish networks.
This PR changes bip32 extended key version bytes for testnet to use `{t,u,U,v,V}|{pub,prv}`.
The constants for `u` and `v` are what [Samourai-Wallet](https://github.com/Samourai-Wallet/bitcoinj/commit/52f03cfb134728b854c3946d9f764ccb3407fb94) and [iancoleman's website](https://github.com/iancoleman/bip39/blob/fcc7d121097189600a14d5f8247735cc88a9dbb2/src/js/segwit-parameters.js#L38) uses (only `u` is defined on the latter).
I could not find constants for `U` and `V`, so I calculated …

bip32 version numbers (xpub headers): use t/u/U/v/V for testnet

---

contrib/build-wine/build-electrum-git.sh

This is a workaround for the issue described in #3871.
It will install a binary wheel of pyblake2 instead of the source package. Hopefully they will distribute the wheels themselves in the future.

Workaround for PyBlake2 build issues

---

gui/qt/main_window.py
gui/qt/util.py
lib/bitcoin.py
lib/keystore.py
lib/tests/test_bitcoin.py
lib/wallet.py

- new versions always export as `txin_type:wif` (0x80 first byte)
- we no longer import and export private keys "as-is". when exporting, everything is re-serialized as `txin_type:wif`, even minikeys
- new versions allow importing
- `txin_type:wif` (only 0x80 first byte allowed)
- `wif` -- and this format allows other first bytes; guess txin_type based on them
- provides backwards compat for our "3.0.x extended WIF"
- internally, `Imported Wallet` keystores keep storing privkeys using "3.0.x extended WIF"
Related: https://github.com/spesmilo/electrum/issues/3620, https://github.com/spesmilo/electrum/issues/3881

change WIF to "txin_type:old_wif"

---

.travis.yml

This makes Travis run the Windows build script on every commit.
This way we notice if the build fails because:
* We broke something
* An upstream package broke something
* A new Wine release broke something
It also prints the resulting hashes for the binaries which might be useful for a quick comparison.

Test Windows build using Travis

---

lib/wallet.py

fix #3949
https://github.com/spesmilo/electrum/blob/180480099926946de19e6f5db8296fc5b56683dc/lib/wallet.py#L219-L221
According to [python docs](https://docs.python.org/3.1/reference/compound_stmts.html#with) the compound `with` guarantees the order, and hence we can avoid multiple levels of indentation.

locks in wallet

---

electrum
lib/commands.py
plugins/digitalbitbox/cmdline.py
plugins/digitalbitbox/digitalbitbox.py
plugins/keepkey/cmdline.py
plugins/ledger/cmdline.py
plugins/ledger/ledger.py
plugins/trezor/cmdline.py

follow-up of https://github.com/spesmilo/electrum/pull/3346#issuecomment-349816947
-----
`create_handler` definitions are needed for CLI plugins due to
https://github.com/spesmilo/electrum/blob/264e80a7b731b15ac6ce38c90343aef70bfac751/plugins/ledger/ledger.py#L536
https://github.com/spesmilo/electrum/blob/264e80a7b731b15ac6ce38c90343aef70bfac751/plugins/digitalbitbox/digitalbitbox.py#L706
(so probably not actually needed for trezor and keepkey)
-----
```
if handler:
self.handler = handler
```
^ due to `CmdLineHandler` getting overwritten with `None`
-----
To be honest, it's really hard to track how the different handlers get assigned and used...
There are handlers for keystores and plugins and clients... :)

cli support for hw encrypted wallets

---

gui/qt/main_window.py
gui/qt/util.py

fixes https://github.com/spesmilo/electrum/issues/2968#issuecomment-337762741
Also a similar crash in the `History` tab with `Edit Description`.
And another with message decryption.
And another with message signing.

fix some crashes when the underlying QT (C/C++) object no longer exists

---

electrum-env

This adds support for Python 3.6+, which is the version I'm using on MacOS :)

Add Support for Python 3.6+ in ./electrum-env

---

gui/qt/main_window.py

fix #3965 
It's not exactly clear how an exception such as #3965 should be handled...
By the time the exception is raised, the unsigned pr is already in storage; only writing to disk fails.
So maybe we could still sign it? Anyway, in this PR we don't; and we also don't revert what has already been done.

qt save_payment_request catch exception

---

lib/wallet.py

Without this, unconfirmed and unverified txns are displayed as local in an offline client.

prepare self.unverified_tx regardless of network

---

lib/daemon.py

Currently, jsonrpc call against `daemon` with `subcommand == 'load_wallet'` returns `True` even if loading is not done, e.g. when file not existed.  I assumed the response should return `True` or `False` depending on the specified wallet actually loaded or not.  This PR makes the daemon return the result of wallet actually loaded or not.
I'm really new to making commits against the electrum code base, so please give any FB which I might be missing.

daemon returns true only if the wallet is loaded

---

gui/qt/address_list.py
gui/qt/transaction_dialog.py
gui/qt/util.py
gui/qt/utxo_list.py

I also set the formatting of the `Balance` column to be decimal-separator-aligned (both `Addresses` and `Coins` tab).

qt addresses tab: new column for type

---

gui/qt/address_list.py
gui/qt/history_list.py
gui/qt/main_window.py
gui/qt/util.py

(re visibility, not full state)
I would mainly like the address filters to be persisted but I guess why not do it for history too.

persist history and addresses toolbars (qt)

---

plugins/trezor/qt_generic.py

On Trezor model T, `bootloader_hash` is `None`, which causes tracebacks in the device dialog. This is a quick fix of the problem (otherwise Electrum seems to work perfectly with T2 out of the box), we might want to update the layout in more ways (such as displaying Trezor model :) )

Trezor model T does not provide bootloader hash

---

lib/network.py
lib/util.py
lib/wallet.py
plugins/trezor/trezor.py

As in https://github.com/spesmilo/electrum/issues/3302 but for Trezor
Tested with both p2sh-segwit and native segwit; both Trezor and also with emulator for Trezor T.
The intended usage is with the `--offline` flag; then we won't even try asking the network. Without the `--offline` flag, we ask the network but ignore the timeout (which is 30 sec!).
To play it safe, if there is a network, we ask for the parent txns; otherwise it would depend on lots of things and functionality could easily break (don't want to branch on hw wallet type; and even for a given hw wallet it is often not clear from its API whether it needs the parent txns).

trezor: segwit offline signing

---

lib/currencies.json
lib/exchange_rate.py

I fix crash the preferences dialog. https://github.com/spesmilo/electrum/pull/4007
sorry.
```
File "/home/wakiyamap/electrum/gui/qt/main_window.py", line 2909, in on_history
update_exchanges()
File "/home/wakiyamap/electrum/gui/qt/main_window.py", line 2883, in update_exchanges
exchanges = self.fx.get_exchanges_by_ccy(c, h)
File "/home/wakiyamap/electrum/lib/exchange_rate.py", line 440, in get_exchanges_by_ccy
d = get_exchanges_by_ccy(h)
File "/home/wakiyamap/electrum/lib/exchange_rate.py", line 415, in get_exchanges_by_ccy
klass = globals()[name]
KeyError: 'Bitflyer'
```

Add JPY exchange rate

---

lib/wallet.py

fix #4041 
This mutual recursion is quite expensive: 
https://github.com/spesmilo/electrum/blob/d0025491760aab9040ba31e2683adb220fd80345/lib/wallet.py#L1761
https://github.com/spesmilo/electrum/blob/d0025491760aab9040ba31e2683adb220fd80345/lib/wallet.py#L1749-L1752
-----
In one of my wallets, this reduces
```
[profiler] get_full_history 1.2266
```
to
```
[profiler] get_full_history 0.0740
```

speed-up wallet.get_full_history: cache coin_price

---

setup.py

Before, the user installation used the wrong directory
to store the application's icon resulting in the desktop
environment falling back to an ugly default icon. Now,
the correct icon is displayed in the menu.
"By default, apps should look in $HOME/.icons (for backwards
compatibility), in $XDG_DATA_DIRS/icons and in /usr/share/pixmaps
(in that order)."
https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html

setup.py: fix icon path for user installation

---

lib/wallet.py
plugins/keepkey/plugin.py
plugins/ledger/ledger.py
plugins/trezor/trezor.py

fix https://github.com/spesmilo/electrum/issues/3920
When creating transactions hw wallet APIs usually provide the option of creating the outputs either from an address or by providing a derivation. So far, we've only ever used the derivation option for addresses on the "change" branch (`.../1/addr`)
- dbb: we now send derivation info for all outputs; seems to work fine
- trezor/keepkey: we create at most one output from derivation (limitation of current fw); we prefer one on the "change" branch if both outputs from "receiving" and "change" are available
- ledger: no intended change in this PR; nano S seems not to touch the affected code paths and I don't have a hw1 to test so I tried to just keep current behaviour

trezor/keepkey/dbb: provide derivation info for all is_mine txn outputs

---

plugins/ledger/ledger.py

fix https://github.com/spesmilo/electrum/issues/4170
closes https://github.com/spesmilo/electrum/pull/3455
related: https://github.com/spesmilo/electrum/commit/e4659327a136f18fde59e4a1f60f45f3e16f22d6
It seems for the hw.1 to be able to sign a tx with a change output, it needs the derivation for the change. But sending the derivation is a good thing anyway, because then the nano S does not prompt the user for that output.
The `finalizeInputFull` method has a very convenient API but I can't see any way to send the derivation when using it; hence using `finalizeInput`.
This however wants a few more arguments: `outputAddress`, `amount`, `fees`. The first two does not really make sense for me for txns with many outputs, though perhaps that's the point: it has at most two outputs in mind; but …

ledger: send derivation for change output

---

lib/exchange_rate.py
lib/interface.py
lib/mnemonic.py
lib/network.py
lib/paymentrequest.py
lib/simple_config.py
lib/storage.py
lib/util.py
lib/wallet.py
lib/websockets.py
lib/x509.py

Related: https://github.com/spesmilo/electrum/issues/4168
Based on the [python docs](https://docs.python.org/3/library/functions.html#open), the default encoding is platform dependent.

use explicit utf-8 encoding when opening files in text mode

---

lib/daemon.py

All the jsonrpc calls against electrum daemon is affected by the
implicit parameter of wallet in the cmd_runner.  AFAIK, there is no way
to check the value of this wallet.  This can be trouble some if multiple
wallets are loaded, or load_wallet command is executed several times.
This patch makes it viewable on the `daemon status`.

daemon status shows current wallet path

---

plugins/trezor/client.py

Following https://github.com/trezor/python-trezor/pull/241.

trezor: pass transport parameter explicitly as a keyword argument

---

lib/constants.py
lib/tests/test_wallet_vertical.py

Currently testnet p2wsh-p2sh master pubkey prefix is Ups4, this changes it to Upub.

change testnet p2wsh-p2sh prefix to 0x024289ef to reflect Upub

---

lib/commands.py
lib/tests/test_commands.py

https://github.com/spesmilo/electrum/commit/a58d01ed54320e2e8eb2a495a8d9b48d8d4c4949 broke certain cases of value parsing for setconfig
Notably `electrum setconfig url_rewrite "['file:///var/www/','https://electrum.org']"` set the value to a json string, not a json array, which made it non-functional.
related: https://github.com/spesmilo/electrum/issues/4220

fix parsing values in setconfig

---

gui/kivy/Readme.md
gui/kivy/tools/buildozer.spec

This fixes https://github.com/spesmilo/electrum/issues/3517#issuecomment-363953343
It also fixes crashes relating to paying payment requests from a browser via clicking a URI (as that is startup related too).
related:
https://github.com/kivy/python-for-android/pull/1256
https://github.com/kivy/buildozer/pull/650

kivy: change activity launchMode to singleTask

---

contrib/build-osx/make_osx
contrib/build-wine/build-electrum-git.sh
gui/qt/exception_window.py

The `--dirty` flag causes `git describe` to append
`-dirty` to the version string it outputs. This is
useful to detect if a build was - intentionally or
not - created with uncommitted changes.
https://git-scm.com/docs/git-describe#git-describe---dirtyltmarkgt

contrib: detect builds with uncommitted changes

---

lib/bitcoin.py
lib/lnbase.py
lib/tests/test_lnbase.py
lib/transaction.py
plugins/digitalbitbox/digitalbitbox.py
plugins/ledger/ledger.py

Save `witness` and `scriptSig` when deserialising a txn, and use them if available when serialising it again
This is an easy temporary way to allow creation of p2wsh txns with custom witnesses.

shortcut witness serialisation

---

gui/kivy/main_window.py
gui/qt/main_window.py
lib/simple_config.py
lib/tests/test_util.py
lib/util.py
lib/wallet.py

For consistency with the inline display of sat/b in the unconfirmed list view.
See lib/wallet.py, line 1173.
https://github.com/spesmilo/electrum/blob/master/lib/wallet.py#L1173
This is particularly important when the fees/b are low and the fractional amount is a significant percentage of the total fee, e.g. between 1 and 2 sat/b.

Format the transaction window fee rate with 1 decimal place

---

lib/exchange_rate.py

As this project is currently structured, absolute
imports have the drawback that they'll load modules
from installed paths rather then from the local repo
when running unit tests. This somehow breaks the main
idea of unit tests which is being able to quickly test
newest development changes. Therefore, use a relative
import here.

exchange_rate: prefer relative imports

---

.gitmodules
contrib/build-osx/make_osx
contrib/build-wine/build-electrum-git.sh

So that deterministic builds for old versions still work.

[WIP] Track icons and locale version in submodule

---

lib/network.py
scripts/block_headers
scripts/watch_address

The old RPC call is deprecated
Port of https://github.com/fyookball/electrum/commit/fe303c97c3d737b3e6464124420609cd52b92254

Subscribe to raw headers

---

lib/interface.py
lib/network.py

- Use server.ping to ping (valid as of protocol version 1.2) rather
than server.version (deprecated as a ping)
- Ping every 5 mins rather than every 1 minute.  By default servers
don't consider a connection stale until 10 minutes of inactivity.
- Remove unused last_request member of interface
Port of https://github.com/fyookball/electrum/commit/c3f26e59db9ce6d5af6c12510f1817d2782f4928

First message on an interface is server.version

---

lib/network.py

Use blockchain.block.headers instead.  It's more flexible but
that flexibility is not used here.
Port of https://github.com/fyookball/electrum/commit/09798d6b20bb35bae745b1a74c2fac5bb24b700a

Stop using deprecated RPC blockchain.block.get_chunk

---

gui/kivy/main_window.py
gui/qt/main_window.py
gui/stdio.py
gui/text.py
lib/commands.py
lib/network.py
lib/synchronizer.py
lib/tests/test_transaction.py
lib/verifier.py
lib/wallet.py
lib/websockets.py
scripts/block_headers
scripts/get_history
scripts/watch_address

This is a continuation of #4376. The only thing changed is one commit fixing a bug in the original PR, I thought I could reopen the PR but I can't after I rebased the commits.  Ping @SomberNight, @kyuupichan.
From the original:
The goal here was to make the code base easier to understand and more decoupled. All the ElectrumX protocol mentions are now in the network module. Except for two instances in the websockets module.
Functionally almost nothing changed. The only thing which changed is that in the commands module an optional timeout parameter could be passed. That parameter has been removed in favor of simpler code.

Remove explicit send calls, part deux

---

lib/transaction.py

Causes a 1+ second lag for medium size wallets when typing the amount in the send tab.

Do not actually compute the nested p2wsh-p2sh script if just estimating size

---

gui/qt/transaction_dialog.py
lib/storage.py
lib/tests/test_transaction.py
lib/tests/test_wallet_vertical.py
lib/transaction.py
lib/util.py
lib/wallet.py
plugins/trustedcoin/trustedcoin.py

- remove "from addresses" dependency from wallet logic
- change partial txn format
- partial txns now include a header consisting of 5 fixed magic bytes and 1 byte version number
- we only parse scriptSig/witness of partial txns; no more guessing of input addresses
- this resolves the gloomy FIXME from https://github.com/spesmilo/electrum/pull/3794
- in the Qt GUI, transaction dialog, only `is_mine` input addresses are shown
- removed "`is_mine` restriction" from `wallet.spent_outpoints`
- as a result, the local transaction feature becomes more powerful: any txn that drops from the mempool will become local. this resolves https://github.com/spesmilo/electrum/issues/3595
- `wallet.spent_outpoints` is now persisted in the wallet file; there is a corresponding v17 version upgrade. wallet …

remove "from addresses"

---

gui/qt/main_window.py

Error message is not in understandable format on entering a invalid/blank public key in Encrypt/decrypt window. Please refer the bug [#64](https://github.com/Feathercoin-Foundation/electrum-ftc/issues/64) for description/steps

Added a meaningful message on invalid public key

---

gui/kivy/main_window.py
gui/kivy/uix/dialogs/crash_reporter.py
gui/kivy/uix/ui_screens/about.kv
gui/qt/exception_window.py
lib/base_crash_reporter.py

This adds crash reporting abilities to the Android APK.
To do:

[WIP] Crash reports android

---

lib/bitcoin.py
lib/tests/test_bitcoin.py

When importing minikeys, I would like to change the behaviour to derive an uncompressed public key, instead of compressed.
Before this commit https://github.com/spesmilo/electrum/commit/e8b564c0e728e1ca15d39f48a0153c984e2acc3c that first appeared in 3.0, the default was uncompressed; since then we've been deriving compressed keys.
Every so often there is a user on IRC complaining that importing does not work.
Sweeping works as then we try both compressed and uncompressed p2pkh (https://github.com/spesmilo/electrum/pull/3268).
The original Casascius coins used uncompressed public keys.
Also, @AbdussamadA emailed an active seller of physical bitcoins (Denarium Bitcoin), and was told that "uncompressed" is part of the "spec for mini private keys".
@kyuupichan also seems to agree in …

minikeys: import with uncompressed pubkey instead of compressed

---

lib/commands.py
lib/daemon.py
lib/simple_config.py

closes https://github.com/spesmilo/electrum/issues/2447#issuecomment-381360086
```
$ ./electrum getfeerate
26000
$ ./electrum getfeerate --fee_method "static" --fee_level 0.1
10000
$ ./electrum getfeerate --fee_method "static" --fee_level 0.4
50000
$ ./electrum getfeerate --fee_method "static" --fee_level 0.8
150000
$ ./electrum getfeerate --fee_method "eta" --fee_level 0.1
1081
$ ./electrum getfeerate --fee_method "eta" --fee_level 0.4
10705
$ ./electrum getfeerate --fee_method "eta" --fee_level 0.8
21190
$ ./electrum getfeerate --fee_method "mempool" --fee_level 0.1
1000
$ ./electrum getfeerate --fee_method "mempool" --fee_level 0.4
1000
$ ./electrum getfeerate --fee_method "mempool" --fee_level 0.8
20000
```

Getfeerate cmd options

---

gui/kivy/Readme.md

Add instruction to readme to manually cherry-pick https://github.com/SomberNight/python-for-android/commit/a0ef2007bc60ed642fbd8b61937995dbed0ddd24
The referenced commit disables backups, which means
- [manual adb backups](https://gist.github.com/SomberNight/295cd950ee4fb2b3768f1ae538babe7e) will not be possible
- google automatic cloud backups will not be made of the app's data
The second point is the main concern of course.
Apps need to opt-out of automatic backups, and we had not been doing that.
Luckily, we target API level 19 (4.4), which is lower than the "participation threshold" but I actually could not find during a casual search where this value is specified (I believe it is a default somewhere in python-for-android), so we should not rely on this. …

android: disable backups

---

lib/bitcoin.py

bip32 has a few extremely unlikely [edge cases](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki#private-parent-key--private-child-key) where nodes should be skipped
In existing releases of Electrum, in case the secret scalar >= curve order, we implicitly use the value modulo the curve order. However, since https://github.com/spesmilo/electrum/pull/4381, an exception will be raised and not handled.
This PR tries to implement what the spec actually expects.

handle bip32 edge cases

---

lib/verifier.py

This attempts to implement protection against the attack recently described [on the mailing list](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2018-June/016105.html).
Before merging, I would like to measure the performance impact with a relatively large wallet on mainnet.
So far, I could only measure on testnet, but blocks are mostly empty there, so merkle proofs are short.
On testnet, I synced a wallet (A) that has ~350 txns.
Irrespective of this PR, the sync took ~10 seconds.
Without the patch, the verifier spent about `19 ms` altogether in `hash_merkle_root`.
With the patch, the verifier spent about `66 ms` altogether in `hash_merkle_root`.
On testnet, I synced a wallet (B) that has ~10.9k txns.
The sync took ~3.5 minutes. (with the patch, it was about 4 seconds longer, but …

check SPV proof inner nodes not to be valid transactions

---

gui/kivy/uix/screens.py
gui/kivy/uix/ui_screens/history.kv

The reduces memory consumption a lot. One wallet's RES memory usage went from 218 MB to 123 MB. The wallet is actually rather small, some wallets can't even be opened without this patch.

kivy: use RecycleView in history

---

plugins/trezor/qt.py

python-trezor 0.10.0 and up doesn't provide a list of supported coins,
and newer Trezor firmwares will not send it. This doesn't seem to be actually used anywhere, so I just removed the field entirely.

trezor: drop list of supported coins

---

gui/qt/transaction_dialog.py
lib/coinchooser.py
lib/tests/test_wallet_vertical.py
lib/transaction.py
lib/wallet.py

fixes https://github.com/spesmilo/electrum/issues/3738
fixes https://github.com/spesmilo/electrum/issues/2897
fixes https://github.com/spesmilo/electrum/issues/3918
- if any inputs have `address` txin_type, serialize the txn in segwit format
- make sure the partial txns contain `value` for all these inputs
- put `OP_INVALIDOPCODE` + `OP_0` + `push_script(fd_extended_pubkey)` into the `scriptSig`
- I meant `OP_0` as an internal version number but it could be left out I guess
- the `address` txin_type, unlike before, now deliberately has a distinct serialization hence, and the type is also kept as `address` when deserialized. the idea is that the offline signing wallet can fill in the data for the txin after deserializing the txn
- this is currently done in …

change partial txn serialization format for imported addresses txins

---

electrum
lib/plugins.py

`electrum_plugins` is imported in the `electrum` script
without being used - I assume it's done to make PyInstaller
find that package. But this can be achieved by avoiding
the usage of `__import__()` when importing `electrum_plugins`
where it's effectively used.

electrum: cleanup plugin imports

---

lib/constants.py
lib/keystore.py

The BIP44 coin type is conceptually a per-network parameter, e.g. developers who are porting Electrum to an altcoin will usually need to change the BIP44 coin type in the same way that they change the address prefixes.  Therefore I think it makes sense to have the BIP44 coin type in the net constants, rather than burying it in the keystore logic.

Move BIP44 coin type to net constants.

---

contrib/requirements/requirements.txt
gui/qt/__init__.py
gui/qt/main_window.py
gui/qt/util.py

qdarkstyle is now a new dependency - note that it is only for qt and qt is not strictly a dependency, but it is pure python and relatively small

option to set a dark theme for Qt

---

lib/jsonrpc.py

Problem:
When Electrum is started in daemon mode it calls an authenticate method for every incoming request. However, when a POST request from another domain is conducted, the actual POST request is always preceded by an OPTIONS request (Cross-Origin Resource Sharing; CORS, see https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). This OPTIONS request should/can not contain any credential information. Thus, in the current state the Electrum daemon is not accessible from other domains.
Fix:
Circumvent the authentication method when the request method is "OPTIONS".

Daemon: Fix preflight CORS request handling

---

gui/qt/console.py

This adds a warning about malicious code to the console window. It should help prevent users from executing code they found online.
This warning is certainly hard to miss:
Clicking the message indeed hides it:
Related: #3678

Add a warning about harmful code to the console

---

gui/qt/installwizard.py
lib/base_wizard.py
lib/bitcoin.py
lib/keystore.py
lib/tests/test_bitcoin.py

- extend derivation dialog to also let user select script type
- enable segwit multisig for bip39/hw wallets
The default paths for segwit multisig are as described in https://github.com/spesmilo/electrum/issues/4352#issuecomment-398028047 , i.e.
```
m / purpose' / coin_type' / account' / script_type' / change / address_index
```
where `purpose = 48`, `account = 0`, and
`script_type = 1` for p2wsh-p2sh multisig, and
`script_type = 2` for p2wsh multisig
This supersedes https://github.com/spesmilo/electrum/pull/4464 and https://github.com/spesmilo/electrum/pull/4443

wizard: extend derivation dialog to also let user select script type

---

lib/bitcoin.py
lib/crypto.py
lib/ecc.py

python3.7 is out now
It has a faster hmac implementation when the data fits in RAM: https://docs.python.org/3.7/library/hmac.html#hmac.digest
I've measured about ~20% faster seed bruteforcing with this

fast hmac on python 3.7+

---

contrib/build-osx/make_osx
contrib/build-wine/build-electrum-git.sh

Clean PyInstaller cache and remove temporary files before building.
Starting totally from a clean environment when building a new binary / release is always a good idea IMO. It doesn't add much to the build time.
See the PyInstaller documentation here: https://pythonhosted.org/PyInstaller/usage.html

Pyinstaller: Clean cache before building

---

lib/paymentrequest.py

Hi guys,
I stumbled across this bug in the PaymentRequest class when developing Electron Cash on iOS and I figured I'd push the fix to you guys upstream.
I don't think any of your code calls this function (but my code does -- which is how I triggered it).
PaymentRequest's self.raw is a bytes object in some code paths (perhaps all code paths, actually).. but the \_\_str\_\_ function was returning it unchanged.  This causes an exception from the python runtime.

Fix a bug in PaymentRequest __str__() function

---

lib/network.py

(second attempt, now trying to handle internal failure within dnspython)
trying to fix https://github.com/spesmilo/electrum/issues/4483
I could not reproduce the problem described in https://github.com/spesmilo/electrum/issues/4483 on a real Windows machine or VM, only in Wine.
This PR now works on Wine.
see original issue https://github.com/spesmilo/electrum/issues/4421 and PR https://github.com/spesmilo/electrum/pull/4422

socket.getaddrinfo on win32: do our own dns resolution

---

lib/simple_config.py

https://github.com/spesmilo/electrum/commit/1635c149bd7399beb346a6a91466e988746aaf43 changed the config key for the base unit preference on kivy
this PR upgrades the config so the setting will not get reset (from a user perspective)
related: https://github.com/spesmilo/electrum/issues/4491

follow-up re #4491, do config upgrade to keep base unit settings on kivy

---

gui/qt/transaction_dialog.py
lib/wallet.py
plugins/trustedcoin/trustedcoin.py

resolves https://github.com/spesmilo/electrum/issues/3844
Billing addresses are persisted in the wallet file.
When receiving a new billing index from TrustedCoin, which is a counter from 0 up, we generate all missing billing addresses up to that index (to cover the case of restoring from seed).
This information is used to colour the output addresses in the Qt tx dialog; and also to make sure when RBF bumping a transaction the billing output is not decreased.
Note that when restoring from seed and disabling 2fa, i.e. keeping two xprvs in the wallet, TrustedCoin is not contacted for billing info, and hence the billing addresses will not be calculated, and e.g. the colouring will not work.

colour 2fa billing outputs in Qt tx dialog

---

lib/currencies.json

Adding the options to be able to select BitcoinVenezuela.com fiat exchange rates in the Preferences. Certificate validation error has been fixed.

Show fiat options from api.bitcoinvenezuela.com

---

tox.ini

I'm not sure why the actual test files are included in the coverage, I can't think of a good reason why. They kind of inflate the actual coverage of the core libs.
Unfortunately this reduces your reported coverage from 56% to 46%

Remove test files from coverage

---

README.rst
contrib/make_locale

The current download URL was returning a 404, I've updated it to what seems to be the functioning URL format. Additionally, Crowdin provides a "% localized" badge, which adds a bit extra information.
Fixes #4559

localization: fix download link + badge

---

electrum/plugins/keepkey/keepkey.py
electrum/plugins/trezor/trezor.py

Attempt to spend coinbase output results in error:
a bytes-like object is required, not 'str'
Note: I have not tested this with Bitcoin since obtaining coinbase outputs is not easy even on Bitcoin testnet. Originally I have found, tested and fixed this problem in Zcoin fork of Electrum and just backporting this fix back to upstream.

Trezor: fix spending coinbase outputs

---

electrum/network.py

If there is already a fork at height h, and the branch we are on reorganises, we detect the reorg but will be left in a weird state, with a 50% chance.
This gets resolved, but only when the next block comes (on top of the new chain).
With this PR, it gets resolved when we detect the reorg (one block sooner).
related: https://github.com/spesmilo/electrum/commit/d5d5e8af5c77760e8e20a5565388b9acc337279b
-----
On master, if we get into the weird state, depends on whether the binary search of block headers find the checkpoint from the left or from the right.
<details>
<summary>master, from left</summary>
```
[Network] notified of header 2328 3b5b8df46ec29ca1a25ec820e9ad72229cb0f7a136c57a088ca7d10a861f7518
[Network] got header 2327 106448c2efc98c088c5cc1a270be98d45339aa58e631624b50124d2e4ff23cf8 …
```

network: handle reorg (sooner) in case of multiple forks at given height

---

electrum/address_synchronizer.py
electrum/gui/kivy/uix/screens.py
electrum/gui/qt/history_list.py
electrum/gui/stdio.py
electrum/gui/text.py
electrum/storage.py
electrum/util.py
electrum/verifier.py
electrum/wallet.py

- wallet file changed for `verified_tx3`
from: `block_height, block_timestamp, tx_pos`
to: `block_height, block_timestamp, tx_pos, block_hash`
- when reorging, verifier compares block hashes instead of block timestamps
- also, previously if there was a reorg and a txn was mined at the same height in both sides of the fork, we would convert that txn to local; which would only get fixed after app restart

verifier: better handle reorgs (and storage upgrade)

---

electrum/address_synchronizer.py
electrum/coinchooser.py
electrum/commands.py
electrum/gui/kivy/main_window.py
electrum/gui/kivy/uix/dialogs/__init__.py
electrum/gui/kivy/uix/screens.py
electrum/gui/qt/main_window.py
electrum/gui/qt/paytoedit.py
electrum/gui/stdio.py
electrum/gui/text.py
electrum/paymentrequest.py
electrum/plugins/digitalbitbox/digitalbitbox.py
electrum/plugins/hw_wallet/plugin.py
electrum/plugins/keepkey/keepkey.py
electrum/plugins/ledger/ledger.py
electrum/plugins/safe_t/safe_t.py
electrum/plugins/trezor/trezor.py
electrum/plugins/trustedcoin/trustedcoin.py
electrum/tests/test_wallet_vertical.py
electrum/transaction.py
electrum/wallet.py

related: https://github.com/spesmilo/electrum/issues/4570
I think it's nicer for us too not to have 3-tuples everywhere;
a data class might have been even better so that it can't be unpacked (in case we introduce a new field).
Also, I think it's better than dicts.

transaction: introduce TxOutput namedtuple

---

electrum/ecc_fast.py

This patch fixes next error on win64:
```ctypes.ArgumentError: argument 1: <class 'OverflowError'>: int too long to convert```
When trying to make signature or sweep master key to new wallet.

fix ecc_fast.py for win64

---

setup.py

Rotonen suggested on IRC that it would be nice to be able to just pip install from github and have a working installation with GUI; something like:
```
pip install -Ue git+https://github.com/spesmilo/electrum.git@3.2.2#egg=electrum[fast,gui]
```
For this,
- a `gui` extra is added that contains pyqt5
- we try to build the `icons_rc.py` file if it's not present and if pyqt5 is installed

setup.py: add 'gui' extra. potentially build Qt icons files

---

electrum/tests/test_bitcoin.py

This bug is triggered if `ecc_fast._libsecp256k1` and/or `crypto.AES` are not present.
Before, if the first test would have raised an exception it would have been implicitly caught by returning from the `finally` block and hence this effectively masks the test's outcome. Now, the exception is properly propagated causing the test to fail if an exception is raised.
The effect of the `return` statement in a `finally` block can be observed using the following snippet.
```py
def foo():
try:
raise Exception()
finally:
return
try:
foo()
except:
print("Exception?")
else:
print("No exception!!!")
```
Contributed by FDF.

test_bitcoin: fix decorators for running tests twice

---

contrib/build-osx/make_osx
contrib/build-wine/build-electrum-git.sh

`git describe` fails if no tag can be found, leading to the whole build script to fail. This is not always desired. To prevent `git describe` from failing in this case the `--always` flag can be passed which causes a short commit hash to be output when a tag is not present.
Contributed by FDF.

contrib: remove git describe workaround

---

contrib/build-osx/make_osx

After you guys upgraded to the new building scheme for macOS (which we ported over to our code) -- the Info.plist for macOS became spartan and bare.  One of the thing's it's missing is support for bitcoin: (or bitcoincash: in our case) URI types.
This adds that.
~Also I noticed your build system insists on Homebrew.. when it also works with either MacPorts or Homebrew - so I added supporting that too.~
~I personally use MacPorts and consider it pretty awesome so I try to add support for it to any project.  Since it's 0 cost for you guys to support it (it provides identical tools really) -- here it is, acknowledged as being a viable way to build.~
Tested and works on my macOS system.

Backport from Electron Cash (macOS) -- fix missing URI types

---

contrib/build-wine/build-electrum-git.sh

https://github.com/spesmilo/electrum-locale/commit/27e36687f4b0fbd126628bdde80758b63ade7347 should be reverted after this has been merged.

 build-wine: avoid untracked changes in submodule 

---

contrib/build-osx/make_osx
contrib/build-wine/prepare-wine.sh

PyInstaller 3.4 highlights from [changelog](https://pyinstaller.readthedocs.io/en/v3.4/CHANGES.html):
* patch for deterministic builds by electrum
* improved support for Qt5-based applications
* added support for Python 3.7
Contributed by FDF.

 contrib: bump pyinstaller to 3.4

---

contrib/build-wine/build-electrum-git.sh

`$i` already contains `locale/`.

build-wine: fix locale path

---

electrum/rsakey.py

The function `numBits` has two `return` statements.  
The second one will, of course, never get called.
This PR removes the second return `statement`.
```
def numBits(n):
if n==0:
return 0
s = "%x" % n
return ((len(s)-1)*4) + \
{'0':0, '1':1, '2':2, '3':2,
'4':3, '5':3, '6':3, '7':3,
'8':4, '9':4, 'a':4, 'b':4,
'c':4, 'd':4, 'e':4, 'f':4,
}[s[0]]
return int(math.floor(math.log(n, 2))+1)
```

Remove unreachable return statement

---

electrum/gui/qt/main_window.py

Refresh Qt GUI tabs when user presses `F5` key.

qt: refresh gui with "F5"

---

electrum/address_synchronizer.py
electrum/commands.py
electrum/interface.py
electrum/network.py
electrum/synchronizer.py
electrum/util.py
electrum/verifier.py
electrum/websockets.py
run_electrum

- instead of the wallet subscribing to `default_server_changed`, now the `Synchronizer` and `Verifier` do it themselves. they are now long-lived, as previously, and not recreated every time the server changes
- fix CLI notify cmd
- fix merchant websockets

restructure synchronizer

---

electrum/blockchain.py
electrum/gui/kivy/main_window.py
electrum/gui/qt/network_dialog.py
electrum/interface.py
electrum/network.py
electrum/verifier.py

If auto_connect is enabled, allow jumping between forks too.
(Previously auto_connect was only switching between servers on a given fork, not across forks)
If there is a preferred fork set, jump to that (and stay);
if there isn't, always jump to the longest fork.

network: auto-switch servers to preferred fork (or longest chain)

---

contrib/build-wine/docker/Dockerfile

The following error occurred at build time.
`E: Version '1:2.17.1-1ubuntu0.1' for 'git' was not found`
It seems that git has updated.
https://packages.ubuntu.com/en/bionic/git

build-wine: update git version

---

electrum/gui/kivy/main_window.py
electrum/gui/kivy/uix/ui_screens/network.kv
electrum/network.py
setup.py

closes #4826 
note: the min python version was deliberately bumped to 3.6.1 as [default args for NamedTuple need it](https://docs.python.org/3/library/typing.html#typing.NamedTuple)
I don't think any Linux distribution is on 3.6.0 specifically

implement oneserver option for kivy

---

electrum/gui/qt/history_list.py

This was a pet peeve of mine that we fixed on Electron Cash.
Basically, the TxDialog window never gets the 'label' when a user double-clicks a tx in the History List.  They see the historical tx, but no "Description:" field, even if a label is defined for the tx.
This PR fixes that.
See screenshots:

Show description (label) in TxDialog screen when opened from History

---

electrum/gui/kivy/Readme.md
electrum/gui/kivy/data/java-classes/org/electrum/qr/SimpleScannerActivity.java
electrum/gui/kivy/tools/buildozer.spec
electrum/util.py

Build Android APK using Google Android NDK and new p4a toolchain (https://github.com/kivy/python-for-android/pull/1412).
(wishlist: make a dockerfile for this mess...)
fixes https://github.com/spesmilo/electrum/issues/4728

android: build apk using new python3 p4a toolchain

---

electrum/exchange_rate.py
electrum/gui/qt/history_list.py
electrum/tests/test_wallet.py
electrum/util.py
electrum/wallet.py

previously, when you submitted a fiat value with thousands separator, it would get misinterpreted.
also, previously, when you manually typed the default fiat value, it would remain blue.

qt history view custom fiat input fixes

---

electrum/gui/qt/__init__.py
electrum/gui/qt/util.py
electrum/i18n.py

Default language is english and settings menu is not available until you create first wallet. For not english speaking users it very hard to accomplish.
It would be better to use system language at first start.
My commit is applied to qt interface. I'm not sure where to set default language for kivy interface.

use system language by default

---

contrib/build-osx/base.sh
contrib/build-osx/make_osx

As per a Slack conversation with @SomberNight , I am adding code signing capability to the macOS build scripts in `contrib/build-osx`.
Note that this capability is completely optional.  It is enabled by passing a "codesigning identity" as the first arg to the `make-osx` script, eg:
---
If no arg is specified it does warn the user that codesigning is disabled, but proceeds anyway.
And at the end it warns again:
---
The changes are minimal and I think will help going forward.
Note that this PR is a prerequisite for a PR I plan on submitting this week which will enable QR scanning on macOS by compiling a tiny Objective-C app at build time.   I made that using native macOS libs to do QR.  
(The helper app will be bundled with the final build .app and both need to be signed for the webcam to …

[macOS] Added optional code signing capability to the OSX build scripts.

---

electrum/crypto.py
electrum/keystore.py
electrum/plugins/digitalbitbox/digitalbitbox.py
electrum/tests/test_bitcoin.py

Currently, when keystore encryption is enabled, the symmetric key used to encrypt the seed/private keys is `sha256d(password)`. (If storage encryption is also enabled, then the whole wallet file is encrypted again, there the key derivation uses PBKDF2 with 1024 iterations of sha512)
This PR introduces versioning for the keystore encryption, and the existing behaviour becomes version 1.
Version 2 uses PBKDF2 with 50k iterations of hmac-sha256 with a random 16 byte salt.
Newly created wallets will use version 2 automatically; and for existing wallets, if they change the password, they will get upgraded to version 2.
see: https://github.com/spesmilo/electrum/issues/3147

keystore: stronger pbkdf for encryption

---

electrum/gui/qt/utxo_list.py

This is a follow-up to #4775.  It turns out the UTXOList (Coins tab) has the same issue as the history screen did before #4775.
You right-click on a coin which has a label, pick "Details" and the resulting Tx Dialog lacks a tx description.
Can be useful to have it there.
---
Here is a sample screenshot of what's new with this change.

UI: Make Coins Tab -> Details TX Dialog show TX Description (label)

---

electrum/plugins/digitalbitbox/digitalbitbox.py

Entropy required to be 64 bytes.
Fixes #4902

bitbox: fix seed command

---

contrib/build-wine/deterministic.spec
contrib/osx/osx.spec

When bumping pyinstaller to 3.4, binary sizes had increased drastically.
The main reason seems to be that pyinstaller is pulling in "all" of qt.
based on Electron-Cash/Electron-Cash@4b0996959420dfca3d53f178d86205616d8c568b
closes https://github.com/spesmilo/electrum/issues/4815
closes https://github.com/spesmilo/electrum/issues/4834

win/mac build: strip parts of pyqt5 from binaries to reduce size

---

electrum/gui/kivy/main_window.py
electrum/gui/kivy/uix/screens.py
electrum/gui/qt/address_list.py
electrum/gui/qt/main_window.py
electrum/gui/qt/request_list.py
electrum/util.py
electrum/wallet.py

It looks like there might be malware out there which modifies wallet files of users, injecting foreign bitcoin addresses in hope of the user receiving coins there [0]
This is intended as naive defense against that.
- try to re-derive (from xpub) the first 10 addresses of the wallet, plus 10 additional random ones on every wallet-open (only if libsecp256k1 is available as otherwise it would be too slow)
- try to re-derive address (from xpub) in following cases
- address shown in `Receive` tab
- address to sweep to
- user right-click copies address in `Addresses` tab
- "change" addresses used in newly created transactions
The idea is that now the malware author needs to also change the xpub saved in the wallet to pass these checks; as well as changing most of the addresses stored in the …

wallet: try detecting internal address corruption

---

electrum/crypto.py
electrum/tests/test_bitcoin.py

This reverts the KDF change from #4838.
Making the KDF expensive is blocked on #4909.
Deferred for now.

keystore: revert KDF change

---

contrib/osx/README.md
contrib/osx/make_osx

use old xcode to build qr scanner on El Capitan

mac: build qr scanner using old xcode

---

electrum/lnchan.py
electrum/lnsweep.py

follow up 7084f63ea2be17b4128d1ccbb86002f18766869a "lnchannel: store pre-signed sweep transactions after each new commitment"

lnsweep: use dicts consistently

---

electrum/plugins/ledger/ledger.py

Use the correct transaction version when signing using a ledger hardware wallet.
By default, transactions created by electrum are currently version `1`, which is also the default transaction version assumed by `startUntrustedTransaction`.
However, when signing a version `2` transaction with a ledger device, the correct version should be passed through in order to obtain a valid signature for the transaction.

Fix ledger transaction version

---

contrib/build-wine/docker/Dockerfile

Fixes for docker
```E: Version '2.2.4-1ubuntu1.1' for 'gnupg2' was not found```
```E: Version '2.2.4-1ubuntu1.1' for 'dirmngr' was not found```

[Docker] fix gnupg2 and dirmngr

---

electrum/commands.py
electrum/verifier.py

The `--skipmerklecheck` optional flag makes Electrum tolerate invalid merkle proofs from the server. This is useful for building Electrum servers that need a minimum amount of storage, though of course users should only enable it if they completely trust the connected server.
This is primarily motivated so that Electrum Personal Server can be compatible with pruning. Users who have a pruned full node would enable `--skipmerklecheck`. Also it would make it much easier to create a "no history" mode where the rpc call `scantxoutset` (https://github.com/chris-belcher/electrum-personal-server/issues/27) is used to find a wallet balance without needing a long rescan.
The way this works is based on an IRC conversation with ghost43 who suggested this method, saying it's a little bit hacky but is …

Add flag --skipmerklecheck

---

contrib/osx/make_osx
contrib/osx/osx.spec

This was pulled from Electron Cash #1110.
This addresses #4994 .
Verified to fix the problem.  Release version (note the dynamic requirements fail.. PID 598 is the subprocess that actually contains the Python interpreter):
```
528: satisfies its Designated Requirement
calin@CalinMBP2016 ~/tmp/ec/electrum $ ps -eafw | grep Electrum
501   597     1   0 11:02AM ??         0:00.95 /Applications/Electrum.app/Contents/MacOS/Electrum
501   598   597   0 11:02AM ??         0:01.98 /Applications/Electrum.app/Contents/MacOS/Electrum
calin@CalinMBP2016 ~/tmp/ec/electrum $ codesign -vvv 597 598
597: dynamically valid
597: valid on disk
597: satisfies its Designated Requirement
598: code identity has been invalidated
```
App built against this PR (and code signed using my developer key):
``` …
```

[MacOS] Fixed code signing on macos to code sign *all* embedded binaries

---

electrum/gui/qt/utxo_list.py

This PR slightly cleans up UTXOList and makes it more straightforward to subclass.
My primary motivation for this PR is that Namecoin's Electrum fork implements a subclass of UTXOList for displaying name outputs (and I've already been bitten once due to that subclass duplicating too much upstream code), but I tend to think this PR makes the original code cleaner and easier to read as well.

Refactor UTXOList headers into class attribute

---

electrum/daemon.py

If there is a error in a CLI command, it is hard to debug because JSONRPC-Pelix will remove the traceback and just forward `str(exception)`. This works around this limitation by embedding the traceback in the exception message.

daemon: forward TypeError trace to client

---

electrum/tests/test_wallet_vertical.py
electrum/transaction.py
electrum/wallet.py

Bitcoin Core has been creating transactions with version=2 by default for 2 years now (since 0.14).
see https://github.com/bitcoin/bitcoin/pull/7562
We should try to blend in.

transaction: change default version to 2

---

contrib/make_tgz

~~The release tarballs should contain the compiled Qt icons file.
The need for this was previously not articulated anywhere AFAICT.~~
Also, occasionally some garbage files from the build machine get included into the tarball (https://github.com/spesmilo/electrum/issues/5033#issuecomment-457930965 and https://github.com/spesmilo/electrum/issues/4424), so dry-run a `git clean` and show the user the results.
related: https://github.com/spesmilo/electrum/issues/5030

contrib/make_tgz: small improvements

---

.travis.yml
contrib/build-linux/appimage/Dockerfile
contrib/build-linux/appimage/README.md
contrib/build-linux/appimage/apprun.sh
contrib/build-linux/appimage/build.sh
contrib/build-wine/prepare-wine.sh
contrib/build_tools_util.sh
contrib/osx/base.sh

One-file executable for Linux x86_64
on top of obvious dependencies, includes:
- libsecp256k1
- PyCryptodomex
- zbar
- hidapi/libusb (+hw wallet libraries)
- note that users will still need to set udev rules themselves
The binary is not reproducible for now; haven't really spent time on that. (but I suspect it might be difficult)
closes https://github.com/spesmilo/electrum/issues/4054
closes https://github.com/spesmilo/electrum/issues/4343
@bauerj

binaries for Linux: AppImage

---

electrum/interface.py
electrum/network.py

network.debug and interface.debug were removed during the asyncio-aiorpcx network-rewrite.
note that msg ids are per session
example:
```
[i][testnet.qtornado.com] <-- ('blockchain.transaction.broadcast', ['02000000000103e765267e94c7fae4316fba0b5dd99b0680f3f9086e6ec227db75220143a1305c0000000000fdffffff7e5b33b952ee177973eee1763eaa113557c2dc07a050e2d8b28a06649ab6ebab0000000000fdffffff92cc9dfe88bc742c7c12e5f4f79a42c15d8562bf3b1e5fc42f2cf012951fdadd0300000000fdffffff03a086010000000000160014337d48cf02b91b8e6914f3c2b9c9dea549e46812a0860100000000001600146aec431285e8872b0974b0c5778ef50274cc5e6ea64e070000000000160014f735528beef7f8c4f4adfc3028014a2cb6bf496302483045022100e2aa1664f15fe78935747415a9cdefc318d8eaf702ea98ed31e1fda780cbf29f02207c407c70b9781d80388c58628533aaf52cc2e3fbb0bf276a50001f5c2abdd17 …
```

network: reintroduce network.debug

---

electrum/plugins/keepkey/keepkey.py
electrum/plugins/safe_t/safe_t.py
electrum/plugins/trezor/qt.py
electrum/plugins/trezor/trezor.py

Newer Trezor firmwares [introduced a "seedless" mode](https://blog.trezor.io/firmware-updates-2-0-9-and-1-7-1-developed-by-the-community-for-the-community-c4b965741ca3).
This is an option during device initialisation. When enabled, the user will never be shown the seed words, and the device even stores this fact; i.e. the user will have "proof" the mnemonic was never shown. Apparently the main use case in mind is redundant multisig setups.
There are now multiple "advanced" options when initialising a Trezor, so I hid some of them behind an "expert" button.
Also did some clean-up.
-----
<details>
<summary>default screen</summary>
</details>
<details>
<summary>in case of previously selecting `Let the device generate a completely new seed randomly`, after revealing expert settings</summary> …

Trezor: implement "seedless" mode

---

electrum/address_synchronizer.py
electrum/commands.py
electrum/gui/qt/address_list.py
electrum/gui/qt/main_window.py
electrum/gui/qt/util.py
electrum/gui/qt/utxo_list.py
electrum/wallet.py

Implements new feature where users can freeze individual UTXOs.
This is orthogonal to addresses being frozen, and for the wallet to automatically select a coin to spend, the coin must be unfrozen both ways.
somewhat based on https://github.com/Electron-Cash/Electron-Cash/pull/891
Not clear how to make UI intuitive; for now I've opted to use foreground colour for UTXO frozenness, and background colour for address frozenness.
related: https://github.com/spesmilo/electrum/issues/5061

Freeze individual UTXOs

---

electrum/gui/qt/main_window.py

When copying text of message to sign from rich text editors, there is rich formating copied together with text and confusions possible during verify process. This patch disables `acceptRichText` on QTextEdit field for message.

fix sign message not accept rich text

---

electrum/currencies.json
electrum/exchange_rate.py

The bylls cad/BTC rate has become one of the dr facto Bitcoin price indexes do to its stability (not an order-book) and trustworthiness (5+ years running).
It queries the Bull Bitcoin (Bylls) servers in Canada, we do not log requests.
I'm not a dev, actually trying to learn python while doing this. Your patience and feedback is appreciated!
Unfortunately still too much of a job to test this myself. Just good old copy pasta.
Thanks !

Add Bylls BTC/CAD rates 

---

electrum/util.py

removed blocktrail.com, blockr.io, biteasy.com ( this explorers no longer works)
added btc.bitaps.com (mainnet explorer) tbtc.bitaps.com (testnet explorer + coin faucet)

update bitcoin explorer options

---

electrum/base_wizard.py
electrum/bitcoin.py
electrum/gui/kivy/uix/dialogs/installwizard.py
electrum/gui/qt/main_window.py
electrum/gui/qt/seed_dialog.py
electrum/keystore.py
electrum/plugins/ledger/ledger.py
electrum/tests/test_bitcoin.py
electrum/transaction.py
electrum/wallet.py

- disallow importing/sweeping segwit scripts with uncompressed pubkey
- show error in Qt GUI to user as tooltip on button
fixes https://github.com/spesmilo/electrum/issues/4638

 sweep/import key: disallow uncompressed segwit

---

electrum/address_synchronizer.py
electrum/gui/kivy/main_window.py
electrum/gui/qt/main_window.py
electrum/synchronizer.py

This is another take on https://github.com/spesmilo/electrum/pull/5312 and https://github.com/spesmilo/electrum/pull/5316
Similar to https://github.com/spesmilo/electrum/pull/5316
Now `req_answered` and `req_sent` are per-wallet, and they also reset when reaching the `up_to_date` state.
Only requests done by the Synchronizer are counted (so e.g. Verifier is not counted).

synchronizer: show progress in GUI (take 3) (req_answered/req_sent)

---

electrum/commands.py
electrum/interface.py
electrum/logging.py
electrum/network.py
electrum/plugin.py
electrum/util.py
electrum/wallet.py

for example, `-V ni` will whitelist the `Network` and `Interface` classes (`-Vni` and `-V=ni` also works)
`-V ^ni` will blacklist those instead
This is introduced in addition to the existing `-v` syntax.

logging: '-V' cli option can blacklist/whitelist classes with short names

---

README.rst

The README.md docs for creating binaries didn't mention the AppImage; this PR fixes that.

Add AppImage to "Creating Binaries" in README.md

---

electrum/servers.json

Port and hostname changed, since the other port is heavily ddos'ed. The original port is still open but errors on subscription requests.
Note that this server was only added in December to default list and changed from self-signed to letsencrypt certificate two months later, so it doesn't help much in disabling old clients.

Update Johoe's server address

---

electrum-env

On BSDs. `bash` is not located in `/bin` but in `/usr/local/bin`. This is the platform-agnostic fix.

Fix electrum-env on FreeBSD

---

electrum/gui/qt/qrcodewidget.py

Fix as in: https://stackoverflow.com/questions/41118431/qt-5-7-drawrect-with-big-stroke-width-drawing-cut-out-corners
QR Code without fix:

qt gui: fix qrcodewidget pen for retina display

---

.travis.yml
electrum/logging.py
electrum/plugins/ledger/qt.py
electrum/wallet.py

Also the __sudo:__ tag is now deprecated in Travis CI.
Identity is not the same thing as equality in Python:
$ python
```python
>>> platform = "andr"
>>> platform += "oid"
>>> platform == "android"
True
>>> platform is "android"
False
```

Travis CI: Use flake8 to find Python syntax errors and undefined names

---

electrum/tests/test_lnchannel.py

This makes the code more resilient in case additional members are added to TxOutput later.

Use NamedTuple notation for TxOutput in test_lnchannel

---

electrum/lnaddr.py

Fixes https://github.com/spesmilo/electrum/issues/5581

lnaddr: Pull in Bech32 and Base58 prefixes from constants

---

electrum/tests/test_blockchain.py

The function `Blockchain.verify_header` was previously not covered by tests at all.  Even removing all the tests in it would still make the unit tests pass.  This change adds tests for this important (!) function.

Unit tests for Blockchain.verify_header

---

electrum/tests/regtest/regtest.sh

I fix this error.
``(standard_in) 1: syntax error``
https://travis-ci.org/spesmilo/electrum/jobs/577905117#L481

Fix travis error

---

electrum/servers.json

Remove electrumx.ml because of phishing
It's already listed in https://electrum.org/electrum-server-blacklist.json

Remove electrumx.ml because of phishing

---

.gitignore
electrum/wallet.py

This pull request fixes `onchain_history` command.
When building summary, it encountered the following error:
```
File "daemons/btc.py", line 240, in xpub_func
result = await result
File "/home/alex/envs/bitcart/lib/python3.6/site-packages/electrum/commands.py", line 605, in onchain_history
return json_encode(self.wallet.get_detailed_history(**kwargs))
File "/home/alex/envs/bitcart/lib/python3.6/site-packages/electrum/util.py", line 394, in <lambda>
return lambda *args, **kw_args: do_profile(args, kw_args)
File "/home/alex/envs/bitcart/lib/python3.6/site-packages/electrum/util.py", line 390, in do_profile
o = func(*args, **kw_args)
File "/home/alex/envs/bitcart/lib/python3.6/site-packages/electrum/wallet.py", line 591, in get_detailed_history
b, v = …
```

Fix for onchain_history summary building

---

electrum/plugins/digitalbitbox/digitalbitbox.py

Make sure that a pubkey is only appended to the checkpub array if it corresponds to a change address. Signing will fail otherwise, if a non-change pubkey is sent as part of the checkpub list to the Digital BitBox.

Digital BitBox: Fix sending to self

---

electrum/commands.py

Fixes https://github.com/spesmilo/electrum/issues/5430

Add from_coins arg to payto/paytomany

---

electrum/gui/qt/history_list.py

Resolves #5762 
Although looking at the code, it looks like this was intentionally disabled so maybe you don't want this. We can continue discussion in the related issue.

Show outgoing Lightning payments with red description

---

electrum/commands.py

`_mktx` wasn't properly passing the `wallet` argument to `_resolver`; this caused errors when it was called with non-`None` values for `domain_addr`.  This PR fixes that.

Fix missing wallet argument to _resolver

---

electrum/gui/kivy/main.kv
electrum/gui/kivy/uix/dialogs/__init__.py
electrum/gui/kivy/uix/dialogs/tx_dialog.py

- Created a kivy component BackgroundTopLabel, which allows custom background colors
- Transferred the logic for color coding from the qt version, which gives identical color coding of output addresses in the kivy gui
Closes: #5750

Color-Code Addresses in Kivy UI

---

electrum/address_synchronizer.py
electrum/gui/kivy/main_window.py
electrum/gui/kivy/uix/screens.py
electrum/gui/qt/invoice_list.py
electrum/gui/qt/main_window.py
electrum/gui/qt/transaction_dialog.py
electrum/json_db.py
electrum/wallet.py

- no more passing around "invoice" in GUIs, invoice "paid" detection is now handled by wallet logic
- a tx can now pay for multiple invoices
- an invoice can now be paid by multiple txs (through partial payments)
- new data structure in storage: prevouts_by_scripthash
- type: scripthash -> set of (outpoint, value)
- also, storage upgrade to build this for existing wallets
Note that this is regarding "outgoing" invoices;
"incoming" ones are currently called "receive requests" (in the code) and they are handled differently.

wallet: better (outgoing) invoice "paid" detection

---

electrum/tests/test_lnpeer.py

Since this method was removed, there is no reason to mock it.

Tests: Remove on_channels_updated

---

electrum/base_wizard.py
electrum/bip32.py
electrum/keystore.py
run_electrum

- keystore: cache `derive_pubkey`
- keystore: cache `BIP32Node.from_xkey(self.xpub)`
- This results in significant performance improvements for keystore.can_sign() and wallet._add_txinout_derivation_info()

wallet perf: significant speedup for make_unsigned_transaction and rel.

---

contrib/requirements/requirements.txt

In regards to issue #5753, the error just popped up for me. This PR fixes the error

Aiohttp must be lower than 4.0.0

---

electrum/gui/qt/confirm_tx_dialog.py
electrum/gui/qt/util.py

A variant of `WaitingDialog` that runs the task in the GUI thread, blocking the GUI.
It is probably a code smell to actually use this, as operations should not block the GUI... still it provides a middle-ground between blocking the GUI without giving user-feedback and having to refactor existing code (to avoid blocking).

Qt: introduce BlockingWaitingDialog

---

.gitignore
run_electrum

Python 3.8 changed where DLLs are searched for.
see https://docs.python.org/3/whatsnew/3.8.html#bpo-36085-whatsnew
This potentially affects our binaries when we start shipping python 3.8+, however that is not being addressed here. This commit simply addresses the usecase of running from source, on Windows, using python 3.8.
On older Python, a user could build/obtain DLLs and place them anywhere on the system %PATH%, however this no longer works with py3.8, as %PATH% is no longer checked.
With py3.8, instead, we now check if there is a folder named '.dlls' in the top-level project directory, and if so, register that as an additional search path.
A user who wants to run Electrum from source on Windows using python 3.8 or later, with their custom DLLs, should manually create the '.dlls' …

windows: when running from source, with py3.8+, load DLLs from '.dlls'

---

electrum/address_synchronizer.py
electrum/gui/qt/transaction_dialog.py
electrum/json_db.py
electrum/lnworker.py
electrum/wallet.py

- So far we have required local txns to be complete. This requirement is now loosened such that it is sufficient for a tx to have a txid to be saved as a "local" tx into the wallet.
- In the wallet file, re the "transactions" dictionary,
- complete txns are serialised as a hex string (no change); while partial txns are serialised as a base64 PSBT string
- the key, as before, is the txid; so there can be only one tx saved for a given txid
- partial txns with same txid overwrite each other (latest wins), however a complete tx cannot be overwritten
- In second commit, see the main motivation for this: save LN funding txns as local automatically
- these are partial for watching-only wallets/multisig/etc. The user will now have time to conveniently get the funding tx signed and then broadcast …

wallet: allow saving partial tx as local (if it has a txid)

---

electrum/util.py

Very minor change which adds support for loading mynode.local when the user selects "View on block explorer" option on a transaction or address.
User can select "mynode.local" entry in the "Online Block Explorer" in the preferences window to enable this.
Tested and working fine on addresses or transactions being selected without issue.
This only works when the user has a mynode installation on their network (website here: http://www.mynodebtc.com/ ) and have turned on the electrum server option. If this has not been done, then the mynode.local domain will not resolve and loading will fail.
This allows users to run electrum on their own node, but also interface with a friendly block explorer which is hosted locally.
Only appears in mainnet as testnet isn't really supported by mynode …

Add block explorer support for mynode.local

---

.travis.yml

It seems that the version of python that runs electrumx is 3.7 or higher.
https://github.com/kyuupichan/electrumx

Fix travis regtest

---

contrib/build-linux/appimage/Dockerfile

https://travis-ci.org/spesmilo/electrum/jobs/640576201
``E: Version '1:1.2.8.dfsg-2ubuntu4.1' for 'zlib1g-dev' was not found``
Now version is `1:1.2.8.dfsg-2ubuntu4.3`
https://packages.ubuntu.com/xenial/zlib1g-dev

Fix travis appimage

---

electrum/gui/kivy/main.kv
electrum/gui/kivy/uix/dialogs/addresses.py
electrum/gui/kivy/uix/dialogs/tx_dialog.py
electrum/gui/kivy/util.py

I added coloring (green, yellow, blue) to the AddressPopup dialog in Kivy to be consistent with coloring done in the tx_dialog.
The necessary coloring function was moved into a new file electrum/gui/kivy/util.py
Open Issues:
- The colored background in AddressPopup is significantly larger than the address text. In the tx_dialog the colored background is only as large as the address text.
- In a future PR the 2 coloring format functions (1. electrum/gui/kivy/util.py  and 2. electrum/gui/qt/util.py) could be perhaps united.

Kivy: Adding address coloring to AddressPopup (Address Details)

---

contrib/build-linux/appimage/Dockerfile

https://travis-ci.org/spesmilo/electrum/jobs/647090064
E: Version '229-4ubuntu21.23' for 'libudev-dev' was not found
Now version is 229-4ubuntu21.27
https://packages.ubuntu.com/xenial/libudev-dev

appimage: update libudev-dev

---

electrum/commands.py
electrum/simple_config.py

By default, Electrum saves the last opened wallet's path as well as
recently opened wallets.
This can be damaging to plausible deniability.
Now it's possible to run Electrum with `--forgetconfig` to not
write to the config at all, which includes the wallet paths.

Add command line option to forget config on exit.
